// Generated by CIRCT unknown git version
module bsg_unconcentrate_static_7(	// file.cleaned.mlir:2:3
  input  [2:0] i,	// file.cleaned.mlir:2:44
  output [2:0] o	// file.cleaned.mlir:2:57
);

  assign o = i;	// file.cleaned.mlir:3:5
endmodule

