// Generated by CIRCT unknown git version
module alu_imem_addr_width_p10(	// file.cleaned.mlir:2:3
  input  [31:0] rs1_i,	// file.cleaned.mlir:2:41
                rs2_i,	// file.cleaned.mlir:2:58
                pc_plus4_i,	// file.cleaned.mlir:2:75
                op_i,	// file.cleaned.mlir:2:97
  output [31:0] result_o,	// file.cleaned.mlir:2:114
  output [9:0]  jalr_addr_o,	// file.cleaned.mlir:2:134
  output        jump_now_o	// file.cleaned.mlir:2:157
);

  wire        _GEN;	// file.cleaned.mlir:309:12
  wire        _GEN_0;	// file.cleaned.mlir:308:12
  wire        _GEN_1;	// file.cleaned.mlir:307:12
  wire        _GEN_2;	// file.cleaned.mlir:303:12
  wire        N214;	// file.cleaned.mlir:302:12
  wire        N206;	// file.cleaned.mlir:301:12
  wire        N201;	// file.cleaned.mlir:300:12
  wire        N188;	// file.cleaned.mlir:299:12
  wire        N178;	// file.cleaned.mlir:298:12
  wire        N170;	// file.cleaned.mlir:297:12
  wire        _op_i_25;	// file.cleaned.mlir:295:12
  wire        N156;	// file.cleaned.mlir:294:12
  wire        N155;	// file.cleaned.mlir:292:12
  wire        N146;	// file.cleaned.mlir:291:12
  wire        N140;	// file.cleaned.mlir:290:12
  wire        _op_i_27;	// file.cleaned.mlir:288:12
  wire        _op_i_29;	// file.cleaned.mlir:286:12
  wire        N122;	// file.cleaned.mlir:285:12
  wire        N120;	// file.cleaned.mlir:283:12
  wire [31:0] _GEN_3;	// file.cleaned.mlir:281:12
  wire [31:0] _GEN_4;	// file.cleaned.mlir:280:12
  wire [31:0] _GEN_5;	// file.cleaned.mlir:279:12
  wire        _GEN_6;	// file.cleaned.mlir:278:12
  wire        _GEN_7;	// file.cleaned.mlir:276:12
  wire        _GEN_8;	// file.cleaned.mlir:274:12
  wire        _GEN_9;	// file.cleaned.mlir:272:12
  wire        _GEN_10;	// file.cleaned.mlir:270:12
  wire        _GEN_11;	// file.cleaned.mlir:268:12
  wire        _GEN_12;	// file.cleaned.mlir:266:12
  wire        _GEN_13;	// file.cleaned.mlir:264:12
  wire        _GEN_14;	// file.cleaned.mlir:262:12
  wire        _GEN_15;	// file.cleaned.mlir:260:12
  wire        _GEN_16;	// file.cleaned.mlir:258:12
  wire        _GEN_17;	// file.cleaned.mlir:256:12
  wire        _GEN_18;	// file.cleaned.mlir:254:12
  wire        _GEN_19;	// file.cleaned.mlir:252:12
  wire        _GEN_20;	// file.cleaned.mlir:250:12
  wire        _GEN_21;	// file.cleaned.mlir:248:12
  wire        _GEN_22;	// file.cleaned.mlir:246:12
  wire        _GEN_23;	// file.cleaned.mlir:244:12
  wire        _GEN_24;	// file.cleaned.mlir:242:12
  wire        _GEN_25;	// file.cleaned.mlir:240:12
  wire        _GEN_26;	// file.cleaned.mlir:238:12
  wire        _GEN_27;	// file.cleaned.mlir:236:12
  wire        _GEN_28;	// file.cleaned.mlir:234:12
  wire        _GEN_29;	// file.cleaned.mlir:232:12
  wire        _GEN_30;	// file.cleaned.mlir:230:12
  wire        _GEN_31;	// file.cleaned.mlir:228:12
  wire        _GEN_32;	// file.cleaned.mlir:226:12
  wire        _GEN_33;	// file.cleaned.mlir:224:12
  wire        _GEN_34;	// file.cleaned.mlir:222:12
  wire        _GEN_35;	// file.cleaned.mlir:220:12
  wire        _GEN_36;	// file.cleaned.mlir:218:12
  wire        _GEN_37;	// file.cleaned.mlir:216:12
  wire        N38;	// file.cleaned.mlir:214:12
  wire        N334;	// file.cleaned.mlir:209:12
  wire        N335;	// file.cleaned.mlir:208:12
  wire        N324;	// file.cleaned.mlir:204:12
  wire        N325;	// file.cleaned.mlir:203:12
  wire        is_imm_op;	// file.cleaned.mlir:202:12
  wire        sign_ex_or_zero;	// file.cleaned.mlir:194:12
  wire        sub_not_add;	// file.cleaned.mlir:192:12
  wire [4:0]  sh_amount;	// file.cleaned.mlir:170:12
  wire [31:0] adder_input;	// file.cleaned.mlir:166:12
  wire        _op_i_31;	// file.cleaned.mlir:158:12
  wire        _GEN_38;	// file.cleaned.mlir:157:12
  wire        _GEN_39;	// file.cleaned.mlir:156:12
  wire        _GEN_40;	// file.cleaned.mlir:155:12
  wire        _GEN_41;	// file.cleaned.mlir:154:12
  wire        _GEN_42;	// file.cleaned.mlir:153:12
  wire        _GEN_43;	// file.cleaned.mlir:152:12
  wire        _GEN_44;	// file.cleaned.mlir:151:12
  wire        _GEN_45;	// file.cleaned.mlir:150:12
  wire        _GEN_46;	// file.cleaned.mlir:149:12
  wire        _GEN_47;	// file.cleaned.mlir:148:12
  wire        N311;	// file.cleaned.mlir:137:12
  wire        N307;	// file.cleaned.mlir:135:12
  wire        N304;	// file.cleaned.mlir:132:12
  wire        N301;	// file.cleaned.mlir:129:12
  wire        N295;	// file.cleaned.mlir:128:12
  wire        N226;	// file.cleaned.mlir:123:11
  wire        _op_i_3;	// file.cleaned.mlir:122:11
  wire        _op_i_6;	// file.cleaned.mlir:119:11
  wire        N193;	// file.cleaned.mlir:106:11
  wire        N185;	// file.cleaned.mlir:102:11
  wire        N179;	// file.cleaned.mlir:100:11
  wire        _op_i_12;	// file.cleaned.mlir:99:11
  wire        N175;	// file.cleaned.mlir:97:11
  wire        N167;	// file.cleaned.mlir:94:11
  wire        _op_i_14;	// file.cleaned.mlir:89:11
  wire        N152;	// file.cleaned.mlir:85:11
  wire        N150;	// file.cleaned.mlir:84:11
  wire        N147;	// file.cleaned.mlir:83:11
  wire [32:0] _GEN_48 = $signed($signed({sign_ex_or_zero, rs1_i}) >>> sh_amount);	// file.cleaned.mlir:55:11, :57:11, :170:12, :194:12
  wire        N106 = ~_op_i_6 & op_i[5];	// file.cleaned.mlir:61:11, :62:11, :119:11, :210:12
  wire        N107 = op_i[4] & ~_op_i_3;	// file.cleaned.mlir:63:11, :64:11, :122:11, :282:12
  wire        N110 = op_i[2] & op_i[1] & op_i[0];	// file.cleaned.mlir:65:11, :66:11, :67:11, :68:11
  wire        N112 = ~_op_i_6 & ~(op_i[5]);	// file.cleaned.mlir:61:11, :70:11, :119:11, :210:12, :211:12
  wire        N125 = ~_op_i_31 & N122;	// file.cleaned.mlir:74:11, :158:12, :284:12, :285:12
  wire        N128 = op_i[13] & ~_op_i_12;	// file.cleaned.mlir:76:11, :77:11, :99:11, :305:12
  assign N147 = ~_op_i_12 & ~_op_i_6;	// file.cleaned.mlir:83:11, :99:11, :119:11, :210:12, :305:12
  assign N150 = op_i[1] & op_i[0];	// file.cleaned.mlir:66:11, :67:11, :84:11
  assign N152 = ~(op_i[5]) & op_i[4] & ~_op_i_3 & ~(op_i[2]);	// file.cleaned.mlir:61:11, :63:11, :65:11, :85:11, :122:11, :211:12, :212:12, :282:12
  wire        N158 = ~_op_i_29 & N155;	// file.cleaned.mlir:87:11, :286:12, :287:12, :292:12
  wire        N159 = ~_op_i_27 & N156;	// file.cleaned.mlir:88:11, :288:12, :289:12, :294:12
  assign _op_i_14 = op_i[14];	// file.cleaned.mlir:89:11
  wire        N162 = N125 & N158;	// file.cleaned.mlir:74:11, :87:11, :90:11
  wire        N163 = N159 & ~_op_i_25 & _op_i_14;	// file.cleaned.mlir:88:11, :89:11, :91:11, :295:12, :296:12
  wire        N165 = N107 & N295;	// file.cleaned.mlir:64:11, :92:11, :128:12
  wire        N166 = N162 & N163;	// file.cleaned.mlir:90:11, :91:11, :93:11
  assign N167 = ~(op_i[13]) & ~_op_i_12 & N106 & N165;	// file.cleaned.mlir:62:11, :76:11, :92:11, :94:11, :99:11, :304:12, :305:12
  assign N175 = N128 & N106 & N165;	// file.cleaned.mlir:62:11, :77:11, :92:11, :97:11
  assign _op_i_12 = op_i[12];	// file.cleaned.mlir:99:11
  assign N179 = _op_i_12 & ~_op_i_6;	// file.cleaned.mlir:99:11, :100:11, :119:11, :210:12
  assign N185 = op_i[13] & _op_i_12 & N106 & N165;	// file.cleaned.mlir:62:11, :76:11, :92:11, :99:11, :102:11
  wire        N190 = ~(op_i[13]) & _op_i_12;	// file.cleaned.mlir:76:11, :99:11, :104:11, :304:12
  wire        N191 = N159 & ~_op_i_25 & ~_op_i_14;	// file.cleaned.mlir:88:11, :89:11, :105:11, :295:12, :296:12, :306:12
  assign N193 = N162 & N191;	// file.cleaned.mlir:90:11, :105:11, :106:11
  wire        N194 = N190 & N112 & N165;	// file.cleaned.mlir:70:11, :92:11, :104:11, :107:11
  wire        N198 = N190 & N106 & N165;	// file.cleaned.mlir:62:11, :92:11, :104:11, :109:11
  wire        N208 = ~_op_i_31 & op_i[30] & N158;	// file.cleaned.mlir:87:11, :113:11, :114:11, :158:12, :284:12
  wire        N209 = N208 & N163;	// file.cleaned.mlir:91:11, :114:11, :115:11
  wire        N217 = N208 & N191 & N167 & op_i[0];	// file.cleaned.mlir:67:11, :94:11, :105:11, :114:11, :118:11
  assign _op_i_6 = op_i[6];	// file.cleaned.mlir:119:11
  wire        N225 = _op_i_6 & op_i[5];	// file.cleaned.mlir:61:11, :119:11, :121:11
  assign _op_i_3 = op_i[3];	// file.cleaned.mlir:122:11
  assign N226 = ~(op_i[4]) & _op_i_3;	// file.cleaned.mlir:63:11, :122:11, :123:11, :205:12
  wire        _GEN_49 = rs1_i == rs2_i;	// file.cleaned.mlir:125:11
  wire        _GEN_50 = rs1_i < rs2_i;	// file.cleaned.mlir:126:11
  wire        _GEN_51 = $signed(rs1_i) < $signed(rs2_i);	// file.cleaned.mlir:127:11
  assign N295 = ~(op_i[2]) & op_i[1];	// file.cleaned.mlir:65:11, :66:11, :128:12, :212:12
  assign N301 = ~_op_i_14 & ~(op_i[13]);	// file.cleaned.mlir:76:11, :89:11, :129:12, :304:12, :306:12
  assign N304 = _op_i_14 & ~(op_i[13]);	// file.cleaned.mlir:76:11, :89:11, :132:12, :304:12
  assign N307 = _op_i_14 & op_i[13];	// file.cleaned.mlir:76:11, :89:11, :135:12
  assign N311 = ~_op_i_14 & op_i[13];	// file.cleaned.mlir:76:11, :89:11, :137:12, :306:12
  wire [31:0] _GEN_52 = {op_i[31:12], 12'h0};	// file.cleaned.mlir:6:15, :138:12, :139:12
  wire [33:0] _GEN_53 =
    {1'h0, rs1_i[31], rs1_i} + {1'h0, adder_input[31], adder_input}
    + {33'h0, sub_not_add};	// file.cleaned.mlir:14:15, :26:14, :141:12, :142:12, :143:12, :144:12, :145:12, :146:12, :166:12, :192:12
  assign _GEN_47 = _GEN_53[2];	// file.cleaned.mlir:146:12, :148:12
  assign _GEN_46 = _GEN_53[3];	// file.cleaned.mlir:146:12, :149:12
  assign _GEN_45 = _GEN_53[4];	// file.cleaned.mlir:146:12, :150:12
  assign _GEN_44 = _GEN_53[5];	// file.cleaned.mlir:146:12, :151:12
  assign _GEN_43 = _GEN_53[6];	// file.cleaned.mlir:146:12, :152:12
  assign _GEN_42 = _GEN_53[7];	// file.cleaned.mlir:146:12, :153:12
  assign _GEN_41 = _GEN_53[8];	// file.cleaned.mlir:146:12, :154:12
  assign _GEN_40 = _GEN_53[9];	// file.cleaned.mlir:146:12, :155:12
  assign _GEN_39 = _GEN_53[10];	// file.cleaned.mlir:146:12, :156:12
  assign _GEN_38 = _GEN_53[11];	// file.cleaned.mlir:146:12, :157:12
  assign _op_i_31 = op_i[31];	// file.cleaned.mlir:158:12
  wire [31:0] _GEN_54 =
    is_imm_op ? {{20{_op_i_31}}, op_i[31:20]} : ~is_imm_op ? rs2_i : 32'h0;	// file.cleaned.mlir:4:15, :158:12, :159:12, :160:12, :161:12, :162:12, :163:12, :202:12, :213:12
  assign adder_input =
    sub_not_add
      ? {_GEN_37,
         _GEN_36,
         _GEN_35,
         _GEN_34,
         _GEN_33,
         _GEN_32,
         _GEN_31,
         _GEN_30,
         _GEN_29,
         _GEN_28,
         _GEN_27,
         _GEN_26,
         _GEN_25,
         _GEN_24,
         _GEN_23,
         _GEN_22,
         _GEN_21,
         _GEN_20,
         _GEN_19,
         _GEN_18,
         _GEN_17,
         _GEN_16,
         _GEN_15,
         _GEN_14,
         _GEN_13,
         _GEN_12,
         _GEN_11,
         _GEN_10,
         _GEN_9,
         _GEN_8,
         _GEN_7,
         _GEN_6}
      : N38 ? _GEN_54 : 32'h0;	// file.cleaned.mlir:4:15, :163:12, :164:12, :165:12, :166:12, :192:12, :214:12, :216:12, :218:12, :220:12, :222:12, :224:12, :226:12, :228:12, :230:12, :232:12, :234:12, :236:12, :238:12, :240:12, :242:12, :244:12, :246:12, :248:12, :250:12, :252:12, :254:12, :256:12, :258:12, :260:12, :262:12, :264:12, :266:12, :268:12, :270:12, :272:12, :274:12, :276:12, :278:12
  assign sh_amount = is_imm_op ? op_i[24:20] : ~is_imm_op ? rs2_i[4:0] : 5'h0;	// file.cleaned.mlir:7:14, :167:12, :168:12, :169:12, :170:12, :202:12, :213:12
  assign sub_not_add = ~N120 & (N140 | N146 | N217);	// file.cleaned.mlir:118:11, :190:12, :191:12, :192:12, :283:12, :290:12, :291:12
  assign sign_ex_or_zero = ~N206 & N214 & rs1_i[31];	// file.cleaned.mlir:141:12, :193:12, :194:12, :301:12, :302:12
  assign is_imm_op = N325 | N335;	// file.cleaned.mlir:202:12, :203:12, :208:12
  assign N325 = ~N324;	// file.cleaned.mlir:203:12, :204:12
  assign N324 =
    _op_i_6 | op_i[5] | ~(op_i[4]) | _op_i_3 | op_i[2] | ~(op_i[1]) | ~(op_i[0]);	// file.cleaned.mlir:61:11, :63:11, :65:11, :66:11, :67:11, :119:11, :122:11, :204:12, :205:12, :206:12, :207:12
  assign N335 = ~N334;	// file.cleaned.mlir:208:12, :209:12
  assign N334 =
    ~_op_i_6 | ~(op_i[5]) | op_i[4] | _op_i_3 | ~(op_i[2]) | ~(op_i[1]) | ~(op_i[0]);	// file.cleaned.mlir:61:11, :63:11, :65:11, :66:11, :67:11, :119:11, :122:11, :206:12, :207:12, :209:12, :210:12, :211:12, :212:12
  assign N38 = ~sub_not_add;	// file.cleaned.mlir:192:12, :214:12
  assign _GEN_37 = ~(_GEN_54[31]);	// file.cleaned.mlir:163:12, :215:12, :216:12
  assign _GEN_36 = ~(_GEN_54[30]);	// file.cleaned.mlir:163:12, :217:12, :218:12
  assign _GEN_35 = ~(_GEN_54[29]);	// file.cleaned.mlir:163:12, :219:12, :220:12
  assign _GEN_34 = ~(_GEN_54[28]);	// file.cleaned.mlir:163:12, :221:12, :222:12
  assign _GEN_33 = ~(_GEN_54[27]);	// file.cleaned.mlir:163:12, :223:12, :224:12
  assign _GEN_32 = ~(_GEN_54[26]);	// file.cleaned.mlir:163:12, :225:12, :226:12
  assign _GEN_31 = ~(_GEN_54[25]);	// file.cleaned.mlir:163:12, :227:12, :228:12
  assign _GEN_30 = ~(_GEN_54[24]);	// file.cleaned.mlir:163:12, :229:12, :230:12
  assign _GEN_29 = ~(_GEN_54[23]);	// file.cleaned.mlir:163:12, :231:12, :232:12
  assign _GEN_28 = ~(_GEN_54[22]);	// file.cleaned.mlir:163:12, :233:12, :234:12
  assign _GEN_27 = ~(_GEN_54[21]);	// file.cleaned.mlir:163:12, :235:12, :236:12
  assign _GEN_26 = ~(_GEN_54[20]);	// file.cleaned.mlir:163:12, :237:12, :238:12
  assign _GEN_25 = ~(_GEN_54[19]);	// file.cleaned.mlir:163:12, :239:12, :240:12
  assign _GEN_24 = ~(_GEN_54[18]);	// file.cleaned.mlir:163:12, :241:12, :242:12
  assign _GEN_23 = ~(_GEN_54[17]);	// file.cleaned.mlir:163:12, :243:12, :244:12
  assign _GEN_22 = ~(_GEN_54[16]);	// file.cleaned.mlir:163:12, :245:12, :246:12
  assign _GEN_21 = ~(_GEN_54[15]);	// file.cleaned.mlir:163:12, :247:12, :248:12
  assign _GEN_20 = ~(_GEN_54[14]);	// file.cleaned.mlir:163:12, :249:12, :250:12
  assign _GEN_19 = ~(_GEN_54[13]);	// file.cleaned.mlir:163:12, :251:12, :252:12
  assign _GEN_18 = ~(_GEN_54[12]);	// file.cleaned.mlir:163:12, :253:12, :254:12
  assign _GEN_17 = ~(_GEN_54[11]);	// file.cleaned.mlir:163:12, :255:12, :256:12
  assign _GEN_16 = ~(_GEN_54[10]);	// file.cleaned.mlir:163:12, :257:12, :258:12
  assign _GEN_15 = ~(_GEN_54[9]);	// file.cleaned.mlir:163:12, :259:12, :260:12
  assign _GEN_14 = ~(_GEN_54[8]);	// file.cleaned.mlir:163:12, :261:12, :262:12
  assign _GEN_13 = ~(_GEN_54[7]);	// file.cleaned.mlir:163:12, :263:12, :264:12
  assign _GEN_12 = ~(_GEN_54[6]);	// file.cleaned.mlir:163:12, :265:12, :266:12
  assign _GEN_11 = ~(_GEN_54[5]);	// file.cleaned.mlir:163:12, :267:12, :268:12
  assign _GEN_10 = ~(_GEN_54[4]);	// file.cleaned.mlir:163:12, :269:12, :270:12
  assign _GEN_9 = ~(_GEN_54[3]);	// file.cleaned.mlir:163:12, :271:12, :272:12
  assign _GEN_8 = ~(_GEN_54[2]);	// file.cleaned.mlir:163:12, :273:12, :274:12
  assign _GEN_7 = ~(_GEN_54[1]);	// file.cleaned.mlir:163:12, :275:12, :276:12
  assign _GEN_6 = ~(_GEN_54[0]);	// file.cleaned.mlir:163:12, :277:12, :278:12
  assign _GEN_5 = rs1_i ^ _GEN_54;	// file.cleaned.mlir:163:12, :279:12
  assign _GEN_4 = rs1_i & _GEN_54;	// file.cleaned.mlir:163:12, :280:12
  assign _GEN_3 = rs1_i | _GEN_54;	// file.cleaned.mlir:163:12, :281:12
  assign N120 = N301 & N147 & N152 & N150 | N193 & N167 & op_i[0];	// file.cleaned.mlir:67:11, :72:11, :73:11, :83:11, :84:11, :85:11, :94:11, :106:11, :129:12, :283:12
  assign N122 = ~(op_i[30]);	// file.cleaned.mlir:113:11, :285:12
  assign _op_i_29 = op_i[29];	// file.cleaned.mlir:286:12
  assign _op_i_27 = op_i[27];	// file.cleaned.mlir:288:12
  assign N140 = N311 & N147 & N152 & N150 | N193 & N175 & op_i[0];	// file.cleaned.mlir:67:11, :79:11, :80:11, :83:11, :84:11, :85:11, :97:11, :106:11, :137:12, :290:12
  assign N146 = N311 & N179 & N152 & N150 | N193 & N185 & op_i[0];	// file.cleaned.mlir:67:11, :81:11, :82:11, :84:11, :85:11, :100:11, :102:11, :106:11, :137:12, :291:12
  assign N155 = ~(op_i[28]);	// file.cleaned.mlir:75:11, :292:12
  assign N156 = ~(op_i[26]);	// file.cleaned.mlir:293:12, :294:12
  assign _op_i_25 = op_i[25];	// file.cleaned.mlir:295:12
  assign N170 = N304 & N147 & N152 & N150 | N166 & N167 & op_i[0];	// file.cleaned.mlir:67:11, :83:11, :84:11, :85:11, :86:11, :93:11, :94:11, :95:11, :132:12, :297:12
  assign N178 = N307 & N147 & N152 & N150 | N166 & N175 & op_i[0];	// file.cleaned.mlir:67:11, :83:11, :84:11, :85:11, :93:11, :96:11, :97:11, :98:11, :135:12, :298:12
  assign N188 = N307 & N179 & N152 & N150 | N166 & N185 & op_i[0];	// file.cleaned.mlir:67:11, :84:11, :85:11, :93:11, :100:11, :101:11, :102:11, :103:11, :135:12, :299:12
  assign N201 = N193 & N194 & op_i[0] | N193 & N198 & op_i[0];	// file.cleaned.mlir:67:11, :106:11, :107:11, :108:11, :109:11, :110:11, :300:12
  assign N206 = N166 & N194 & op_i[0] | N166 & N198 & op_i[0];	// file.cleaned.mlir:67:11, :93:11, :107:11, :109:11, :111:11, :112:11, :301:12
  assign N214 = N209 & N194 & op_i[0] | N209 & N198 & op_i[0];	// file.cleaned.mlir:67:11, :107:11, :109:11, :115:11, :116:11, :117:11, :302:12
  assign _GEN_2 = ~(_GEN_53[33]);	// file.cleaned.mlir:146:12, :147:12, :303:12
  assign _GEN_1 = ~_GEN_49;	// file.cleaned.mlir:125:11, :307:12
  assign _GEN_0 = ~_GEN_51;	// file.cleaned.mlir:127:11, :308:12
  assign _GEN = ~_GEN_50;	// file.cleaned.mlir:126:11, :309:12
  assign result_o =
    N106 & N107 & N110
      ? _GEN_52
      : N112 & N107 & N110
          ? _GEN_52 + pc_plus4_i - 32'h4
          : N120
              ? _GEN_53[31:0]
              : N125 & ~_op_i_29 & op_i[28] & ~_op_i_27 & ~_op_i_14 & N128 & N106 & N226
                & N110
                  ? rs1_i
                  : N140
                      ? {31'h0, _GEN_53[32]}
                      : N146
                          ? {31'h0, _GEN_2}
                          : N170
                              ? _GEN_5
                              : N178
                                  ? _GEN_3
                                  : N188
                                      ? _GEN_4
                                      : N201
                                          ? rs1_i << sh_amount
                                          : N206 | N214
                                              ? _GEN_48[31:0]
                                              : N217
                                                  ? _GEN_53[31:0]
                                                  : N301 & ~_op_i_12 & _op_i_6 & op_i[5]
                                                    & ~(op_i[4]) & ~_op_i_3 & op_i[2]
                                                    & N150 | N225 & N226 & N110
                                                      ? pc_plus4_i
                                                      : 32'h0;	// file.cleaned.mlir:3:15, :4:15, :57:11, :58:11, :60:11, :61:11, :62:11, :63:11, :64:11, :65:11, :68:11, :69:11, :70:11, :71:11, :74:11, :75:11, :77:11, :78:11, :84:11, :89:11, :99:11, :118:11, :119:11, :120:11, :121:11, :122:11, :123:11, :124:11, :129:12, :139:12, :140:12, :146:12, :170:12, :171:12, :172:12, :173:12, :174:12, :175:12, :176:12, :177:12, :178:12, :179:12, :180:12, :181:12, :182:12, :183:12, :184:12, :185:12, :186:12, :187:12, :188:12, :189:12, :205:12, :279:12, :280:12, :281:12, :282:12, :283:12, :286:12, :287:12, :288:12, :289:12, :290:12, :291:12, :297:12, :298:12, :299:12, :300:12, :301:12, :302:12, :303:12, :305:12, :306:12, :310:5
  assign jalr_addr_o =
    {_GEN_38, 9'h0}
    | ({1'h0, _GEN_39, 8'h0}
       | ({2'h0, _GEN_40, 7'h0}
          | ({3'h0, _GEN_41, 6'h0}
             | ({4'h0, _GEN_42, 5'h0}
                | ({5'h0, _GEN_43, 4'h0}
                   | ({6'h0, _GEN_44, 3'h0}
                      | ({7'h0, _GEN_45, 2'h0} | ({8'h0, _GEN_46, 1'h0} | {9'h0, _GEN_47})
                         & 10'h3FB) & 10'h3F7) & 10'h3EF) & 10'h3DF) & 10'h3BF) & 10'h37F)
       & 10'h2FF) & 10'h1FF;	// file.cleaned.mlir:7:14, :8:14, :9:14, :10:14, :11:14, :12:14, :13:14, :17:17, :18:18, :19:18, :20:17, :21:17, :22:17, :23:16, :24:16, :26:14, :27:14, :28:10, :29:10, :30:10, :31:10, :32:10, :33:10, :34:10, :35:10, :36:10, :37:10, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :148:12, :149:12, :150:12, :151:12, :152:12, :153:12, :154:12, :155:12, :156:12, :157:12, :310:5
  assign jump_now_o =
    N225 & ~(op_i[4]) & ~_op_i_3 & N295
    & (N301 & ~_op_i_12
         ? _GEN_49
         : N301 & _op_i_12
             ? _GEN_1
             : N304 & ~_op_i_12
                 ? _GEN_51
                 : N304 & _op_i_12
                     ? _GEN_0
                     : N307 & ~_op_i_12 ? _GEN_50 : N307 & _op_i_12 & _GEN);	// file.cleaned.mlir:63:11, :99:11, :121:11, :122:11, :125:11, :126:11, :127:11, :128:12, :129:12, :130:12, :131:12, :132:12, :133:12, :134:12, :135:12, :136:12, :195:12, :196:12, :197:12, :198:12, :199:12, :200:12, :201:12, :205:12, :282:12, :305:12, :307:12, :308:12, :309:12, :310:5
endmodule

