// Generated by CIRCT e2b32a42e
module carry_lookahead_generator(	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:2:3
  input        carry_in,	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:2:43
  input  [7:0] generate_in,	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:2:62
               propagate_in,	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:2:84
  output [7:0] carry,	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:2:108
  output       group_generate,	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:2:124
               group_propagate	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:2:149
);

  wire        _GEN_71_26;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:390:12
  wire        _GEN_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:384:12
  wire        _propagate_in_7;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:382:12
  wire        _GEN_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:381:12
  wire        _GEN_3;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:379:12
  wire        _GEN_4;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:377:12
  wire        _GEN_5;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:375:12
  wire        _GEN_6;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:373:12
  wire        _GEN_7;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:371:12
  wire        _GEN_8;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:369:12
  wire        _GEN_9;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:367:12
  wire        _GEN_10;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:365:12
  wire        _GEN_11;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:363:12
  wire        _GEN_12;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:361:12
  wire        _GEN_13;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:359:12
  wire        _generate_in_7;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:357:12
  wire        _GEN_14;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:356:12
  wire        _GEN_17;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:353:12
  wire        _propagate_in_6;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:351:12
  wire        _GEN_18;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:350:12
  wire        _GEN_19;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:348:12
  wire        _GEN_20;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:346:12
  wire        _GEN_21;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:344:12
  wire        _GEN_22;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:342:12
  wire        _GEN_23;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:340:12
  wire        _GEN_24;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:338:12
  wire        _GEN_25;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:336:12
  wire        _GEN_26;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:334:12
  wire        _GEN_27;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:332:12
  wire        _generate_in_6;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:330:12
  wire        _GEN_28;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:329:12
  wire        _GEN_31;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:325:12
  wire        _propagate_in_5;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:323:12
  wire        _GEN_32;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:322:12
  wire        _GEN_33;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:320:12
  wire        _GEN_34;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:318:12
  wire        _GEN_35;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:316:12
  wire        _GEN_36;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:314:12
  wire        _GEN_37;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:312:12
  wire        _GEN_38;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:310:12
  wire        _GEN_39;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:308:12
  wire        _generate_in_5;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:306:12
  wire        _GEN_40;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:305:12
  wire        _GEN_43;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:301:12
  wire        _propagate_in_4;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:299:12
  wire        _GEN_44;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:298:12
  wire        _GEN_45;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:296:12
  wire        _GEN_46;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:294:12
  wire        _GEN_47;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:292:12
  wire        _GEN_48;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:290:12
  wire        _GEN_49;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:288:12
  wire        _generate_in_4;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:286:12
  wire        _GEN_50;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:285:12
  wire        _GEN_53;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:281:12
  wire        _propagate_in_3;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:279:12
  wire        _GEN_54;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:278:12
  wire        _GEN_55;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:276:12
  wire        _GEN_56;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:274:12
  wire        _GEN_57;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:272:12
  wire        _generate_in_3;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:270:12
  wire        _GEN_58;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:269:12
  wire        _GEN_61;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:265:12
  wire        _propagate_in_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:263:12
  wire        _GEN_62;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:262:12
  wire        _GEN_63;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:260:12
  wire        _generate_in_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:258:12
  wire        _GEN_64;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:257:12
  wire        _GEN_67;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:253:12
  wire        _propagate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:251:12
  wire        _generate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:250:12
  wire        _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:249:12
  wire [33:0] _GEN_71 =
    {_propagate_in_7, 33'h0}
    | {1'h0,
       {_GEN_3, 32'h0}
         | {1'h0,
            {_GEN_5, 31'h0}
              | {1'h0,
                 {_GEN_7, 30'h0}
                   | {1'h0,
                      {_GEN_9, 29'h0}
                        | {1'h0,
                           {_GEN_11, 28'h0}
                             | {1'h0,
                                {_GEN_13, 27'h0}
                                  | {1'h0,
                                     {_GEN_14, 26'h0}
                                       | {1'h0,
                                          {_propagate_in_6, 25'h0}
                                            | {1'h0,
                                               {_GEN_19, 24'h0}
                                                 | {1'h0,
                                                    {_GEN_21, 23'h0}
                                                      | {1'h0,
                                                         {_GEN_23, 22'h0}
                                                           | {1'h0,
                                                              {_GEN_25, 21'h0}
                                                                | {1'h0,
                                                                   {_GEN_27, 20'h0}
                                                                     | {1'h0,
                                                                        {_GEN_28, 19'h0}
                                                                          | {1'h0,
                                                                             {_propagate_in_5,
                                                                              18'h0}
                                                                               | {1'h0,
                                                                                  {_GEN_33,
                                                                                   17'h0}
                                                                                    | {1'h0,
                                                                                       {_GEN_35,
                                                                                        16'h0}
                                                                                         | {1'h0,
                                                                                            {_GEN_37,
                                                                                             15'h0}
                                                                                              | {1'h0,
                                                                                                 {_GEN_39,
                                                                                                  14'h0}
                                                                                                   | {1'h0,
                                                                                                      {_GEN_40,
                                                                                                       13'h0}
                                                                                                        | {1'h0,
                                                                                                           {_propagate_in_4,
                                                                                                            12'h0}
                                                                                                             | {1'h0,
                                                                                                                {_GEN_45,
                                                                                                                 11'h0}
                                                                                                                  | {1'h0,
                                                                                                                     {_GEN_47,
                                                                                                                      10'h0}
                                                                                                                       | {1'h0,
                                                                                                                          {_GEN_49,
                                                                                                                           9'h0}
                                                                                                                            | {1'h0,
                                                                                                                               {_GEN_50,
                                                                                                                                8'h0}
                                                                                                                                 | {1'h0,
                                                                                                                                    {_propagate_in_3,
                                                                                                                                     7'h0}
                                                                                                                                      | {1'h0,
                                                                                                                                         {_GEN_55,
                                                                                                                                          6'h0}
                                                                                                                                           | {1'h0,
                                                                                                                                              {_GEN_57,
                                                                                                                                               5'h0}
                                                                                                                                                | {1'h0,
                                                                                                                                                   {_GEN_58,
                                                                                                                                                    4'h0}
                                                                                                                                                     | {1'h0,
                                                                                                                                                        {_propagate_in_2,
                                                                                                                                                         3'h0}
                                                                                                                                                          | {1'h0,
                                                                                                                                                             {_GEN_63,
                                                                                                                                                              2'h0}
                                                                                                                                                               | {1'h0,
                                                                                                                                                                  {_GEN_64,
                                                                                                                                                                   1'h0}
                                                                                                                                                                    | {1'h0,
                                                                                                                                                                       _propagate_in_1}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}};	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:10:15, :11:15, :12:15, :13:15, :14:15, :15:15, :16:15, :17:15, :18:15, :19:15, :20:15, :21:15, :22:15, :23:15, :24:15, :25:15, :26:15, :27:14, :28:15, :29:14, :30:15, :31:14, :32:15, :33:14, :34:15, :35:14, :36:15, :37:14, :38:15, :39:14, :40:15, :41:14, :43:14, :45:10, :46:10, :47:10, :48:10, :49:10, :50:10, :51:10, :52:10, :53:10, :54:10, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :65:11, :66:11, :67:11, :68:11, :69:11, :70:11, :71:11, :72:11, :73:11, :74:11, :75:11, :76:11, :77:11, :78:11, :79:11, :80:11, :81:11, :82:11, :83:11, :84:11, :85:11, :86:11, :87:11, :88:11, :89:11, :90:11, :91:11, :92:11, :93:11, :94:11, :95:11, :96:11, :97:11, :98:11, :99:11, :100:11, :101:11, :102:11, :103:11, :104:11, :105:11, :106:11, :107:11, :108:11, :109:11, :110:11, :111:11, :112:11, :113:11, :114:11, :115:11, :116:11, :117:11, :118:11, :119:11, :120:11, :121:11, :122:11, :123:11, :124:11, :125:11, :126:11, :127:11, :128:11, :129:11, :130:11, :131:11, :132:11, :133:11, :134:11, :135:11, :136:11, :137:11, :138:11, :139:11, :140:11, :141:11, :142:11, :143:11, :251:12, :257:12, :260:12, :263:12, :269:12, :272:12, :276:12, :279:12, :285:12, :288:12, :292:12, :296:12, :299:12, :305:12, :308:12, :312:12, :316:12, :320:12, :323:12, :329:12, :332:12, :336:12, :340:12, :344:12, :348:12, :351:12, :356:12, :359:12, :363:12, :367:12, :371:12, :375:12, :379:12, :382:12
  wire [35:0] _GEN_72 =
    {_GEN_1, 35'h0}
    | {1'h0,
       {_GEN_2, 34'h0}
         | {1'h0,
            {_GEN_4, 33'h0}
              | {1'h0,
                 {_GEN_6, 32'h0}
                   | {1'h0,
                      {_GEN_8, 31'h0}
                        | {1'h0,
                           {_GEN_10, 30'h0}
                             | {1'h0,
                                {_GEN_12, 29'h0}
                                  | {1'h0,
                                     {_generate_in_7, 28'h0}
                                       | {1'h0,
                                          {_GEN_17, 27'h0}
                                            | {1'h0,
                                               {_GEN_18, 26'h0}
                                                 | {1'h0,
                                                    {_GEN_20, 25'h0}
                                                      | {1'h0,
                                                         {_GEN_22, 24'h0}
                                                           | {1'h0,
                                                              {_GEN_24, 23'h0}
                                                                | {1'h0,
                                                                   {_GEN_26, 22'h0}
                                                                     | {1'h0,
                                                                        {_generate_in_6,
                                                                         21'h0}
                                                                          | {1'h0,
                                                                             {_GEN_31,
                                                                              20'h0}
                                                                               | {1'h0,
                                                                                  {_GEN_32,
                                                                                   19'h0}
                                                                                    | {1'h0,
                                                                                       {_GEN_34,
                                                                                        18'h0}
                                                                                         | {1'h0,
                                                                                            {_GEN_36,
                                                                                             17'h0}
                                                                                              | {1'h0,
                                                                                                 {_GEN_38,
                                                                                                  16'h0}
                                                                                                   | {1'h0,
                                                                                                      {_generate_in_5,
                                                                                                       15'h0}
                                                                                                        | {1'h0,
                                                                                                           {_GEN_43,
                                                                                                            14'h0}
                                                                                                             | {1'h0,
                                                                                                                {_GEN_44,
                                                                                                                 13'h0}
                                                                                                                  | {1'h0,
                                                                                                                     {_GEN_46,
                                                                                                                      12'h0}
                                                                                                                       | {1'h0,
                                                                                                                          {_GEN_48,
                                                                                                                           11'h0}
                                                                                                                            | {1'h0,
                                                                                                                               {_generate_in_4,
                                                                                                                                10'h0}
                                                                                                                                 | {1'h0,
                                                                                                                                    {_GEN_53,
                                                                                                                                     9'h0}
                                                                                                                                      | {1'h0,
                                                                                                                                         {_GEN_54,
                                                                                                                                          8'h0}
                                                                                                                                           | {1'h0,
                                                                                                                                              {_GEN_56,
                                                                                                                                               7'h0}
                                                                                                                                                | {1'h0,
                                                                                                                                                   {_generate_in_3,
                                                                                                                                                    6'h0}
                                                                                                                                                     | {1'h0,
                                                                                                                                                        {_GEN_61,
                                                                                                                                                         5'h0}
                                                                                                                                                          | {1'h0,
                                                                                                                                                             {_GEN_62,
                                                                                                                                                              4'h0}
                                                                                                                                                               | {1'h0,
                                                                                                                                                                  {_generate_in_2,
                                                                                                                                                                   3'h0}
                                                                                                                                                                    | {1'h0,
                                                                                                                                                                       {_GEN_67,
                                                                                                                                                                        2'h0}
                                                                                                                                                                         | {1'h0,
                                                                                                                                                                            {_generate_in_1,
                                                                                                                                                                             1'h0}
                                                                                                                                                                              | {1'h0,
                                                                                                                                                                                 _generate_in_0}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}};	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:10:15, :11:15, :12:15, :13:15, :14:15, :15:15, :16:15, :17:15, :18:15, :19:15, :20:15, :21:15, :22:15, :23:15, :24:15, :25:15, :26:15, :27:14, :28:15, :29:14, :30:15, :31:14, :32:15, :33:14, :34:15, :35:14, :36:15, :37:14, :38:15, :39:14, :40:15, :41:14, :42:15, :43:14, :44:15, :144:11, :145:12, :146:12, :147:12, :148:12, :149:12, :150:12, :151:12, :152:12, :153:12, :154:12, :155:12, :156:12, :157:12, :158:12, :159:12, :160:12, :161:12, :162:12, :163:12, :164:12, :165:12, :166:12, :167:12, :168:12, :169:12, :170:12, :171:12, :172:12, :173:12, :174:12, :175:12, :176:12, :177:12, :178:12, :179:12, :180:12, :181:12, :182:12, :183:12, :184:12, :185:12, :186:12, :187:12, :188:12, :189:12, :190:12, :191:12, :192:12, :193:12, :194:12, :195:12, :196:12, :197:12, :198:12, :199:12, :200:12, :201:12, :202:12, :203:12, :204:12, :205:12, :206:12, :207:12, :208:12, :209:12, :210:12, :211:12, :212:12, :213:12, :214:12, :215:12, :216:12, :217:12, :218:12, :219:12, :220:12, :221:12, :222:12, :223:12, :224:12, :225:12, :226:12, :227:12, :228:12, :229:12, :230:12, :231:12, :232:12, :233:12, :234:12, :235:12, :236:12, :237:12, :238:12, :239:12, :240:12, :241:12, :242:12, :243:12, :244:12, :245:12, :246:12, :247:12, :248:12, :249:12, :250:12, :253:12, :258:12, :262:12, :265:12, :270:12, :274:12, :278:12, :281:12, :286:12, :290:12, :294:12, :298:12, :301:12, :306:12, :310:12, :314:12, :318:12, :322:12, :325:12, :330:12, :334:12, :338:12, :342:12, :346:12, :350:12, :353:12, :357:12, :361:12, :365:12, :369:12, :373:12, :377:12, :381:12, :384:12
  assign _generate_in_0 = generate_in[0];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:249:12
  assign _generate_in_1 = generate_in[1];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:250:12
  assign _propagate_in_1 = propagate_in[1];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:251:12
  assign _GEN_67 = _GEN_71[0] & _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :249:12, :252:12, :253:12
  assign _GEN_64 = &(propagate_in[2:0]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:256:12, :257:12
  assign _generate_in_2 = generate_in[2];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:258:12
  assign _GEN_63 = &(propagate_in[2:1]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:259:12, :260:12
  assign _GEN_62 = _GEN_71[2] & _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :249:12, :261:12, :262:12
  assign _propagate_in_2 = propagate_in[2];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:263:12
  assign _GEN_61 = _GEN_71[3] & _generate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :250:12, :264:12, :265:12
  assign _GEN_58 = &(propagate_in[3:0]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:268:12, :269:12
  assign _generate_in_3 = generate_in[3];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:270:12
  assign _GEN_57 = &(propagate_in[3:1]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:271:12, :272:12
  assign _GEN_56 = _GEN_71[5] & _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :249:12, :273:12, :274:12
  assign _GEN_55 = &(propagate_in[3:2]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:275:12, :276:12
  assign _GEN_54 = _GEN_71[6] & _generate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :250:12, :277:12, :278:12
  assign _propagate_in_3 = propagate_in[3];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:279:12
  assign _GEN_53 = _GEN_71[7] & _generate_in_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :258:12, :280:12, :281:12
  assign _GEN_50 = &(propagate_in[4:0]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:284:12, :285:12
  assign _generate_in_4 = generate_in[4];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:286:12
  assign _GEN_49 = &(propagate_in[4:1]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:287:12, :288:12
  assign _GEN_48 = _GEN_71[9] & _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :249:12, :289:12, :290:12
  assign _GEN_47 = &(propagate_in[4:2]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:291:12, :292:12
  assign _GEN_46 = _GEN_71[10] & _generate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :250:12, :293:12, :294:12
  assign _GEN_45 = &(propagate_in[4:3]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:295:12, :296:12
  assign _GEN_44 = _GEN_71[11] & _generate_in_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :258:12, :297:12, :298:12
  assign _propagate_in_4 = propagate_in[4];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:299:12
  assign _GEN_43 = _GEN_71[12] & _generate_in_3;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :270:12, :300:12, :301:12
  assign _GEN_40 = &(propagate_in[5:0]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:304:12, :305:12
  assign _generate_in_5 = generate_in[5];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:306:12
  assign _GEN_39 = &(propagate_in[5:1]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:307:12, :308:12
  assign _GEN_38 = _GEN_71[14] & _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :249:12, :309:12, :310:12
  assign _GEN_37 = &(propagate_in[5:2]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:311:12, :312:12
  assign _GEN_36 = _GEN_71[15] & _generate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :250:12, :313:12, :314:12
  assign _GEN_35 = &(propagate_in[5:3]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:315:12, :316:12
  assign _GEN_34 = _GEN_71[16] & _generate_in_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :258:12, :317:12, :318:12
  assign _GEN_33 = &(propagate_in[5:4]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:319:12, :320:12
  assign _GEN_32 = _GEN_71[17] & _generate_in_3;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :270:12, :321:12, :322:12
  assign _propagate_in_5 = propagate_in[5];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:323:12
  assign _GEN_31 = _GEN_71[18] & _generate_in_4;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :286:12, :324:12, :325:12
  assign _GEN_28 = &(propagate_in[6:0]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:328:12, :329:12
  assign _generate_in_6 = generate_in[6];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:330:12
  assign _GEN_27 = &(propagate_in[6:1]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:331:12, :332:12
  assign _GEN_26 = _GEN_71[20] & _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :249:12, :333:12, :334:12
  assign _GEN_25 = &(propagate_in[6:2]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:335:12, :336:12
  assign _GEN_24 = _GEN_71[21] & _generate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :250:12, :337:12, :338:12
  assign _GEN_23 = &(propagate_in[6:3]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:339:12, :340:12
  assign _GEN_22 = _GEN_71[22] & _generate_in_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :258:12, :341:12, :342:12
  assign _GEN_21 = &(propagate_in[6:4]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:343:12, :344:12
  assign _GEN_20 = _GEN_71[23] & _generate_in_3;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :270:12, :345:12, :346:12
  assign _GEN_19 = &(propagate_in[6:5]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:347:12, :348:12
  assign _GEN_18 = _GEN_71[24] & _generate_in_4;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :286:12, :349:12, :350:12
  assign _propagate_in_6 = propagate_in[6];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:351:12
  assign _GEN_17 = _GEN_71[25] & _generate_in_5;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :306:12, :352:12, :353:12
  assign _GEN_14 = &propagate_in;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:356:12
  assign _generate_in_7 = generate_in[7];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:357:12
  assign _GEN_13 = &(propagate_in[7:1]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:358:12, :359:12
  assign _GEN_12 = _GEN_71[27] & _generate_in_0;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :249:12, :360:12, :361:12
  assign _GEN_11 = &(propagate_in[7:2]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:362:12, :363:12
  assign _GEN_10 = _GEN_71[28] & _generate_in_1;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :250:12, :364:12, :365:12
  assign _GEN_9 = &(propagate_in[7:3]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:366:12, :367:12
  assign _GEN_8 = _GEN_71[29] & _generate_in_2;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :258:12, :368:12, :369:12
  assign _GEN_7 = &(propagate_in[7:4]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:370:12, :371:12
  assign _GEN_6 = _GEN_71[30] & _generate_in_3;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :270:12, :372:12, :373:12
  assign _GEN_5 = &(propagate_in[7:5]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:374:12, :375:12
  assign _GEN_4 = _GEN_71[31] & _generate_in_4;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :286:12, :376:12, :377:12
  assign _GEN_3 = &(propagate_in[7:6]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:378:12, :379:12
  assign _GEN_2 = _GEN_71[32] & _generate_in_5;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :306:12, :380:12, :381:12
  assign _propagate_in_7 = propagate_in[7];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:382:12
  assign _GEN_1 = _GEN_71[33] & _generate_in_6;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :330:12, :383:12, :384:12
  assign _GEN_71_26 = _GEN_71[26];	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:143:11, :390:12
  assign carry =
    {_GEN_71_26 & carry_in,
     |(_GEN_72[27:21]),
     |(_GEN_72[20:15]),
     |(_GEN_72[14:10]),
     |(_GEN_72[9:6]),
     |(_GEN_72[5:3]),
     |(_GEN_72[2:1]),
     _GEN_72[0]};	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:248:12, :254:12, :255:12, :266:12, :267:12, :282:12, :283:12, :302:12, :303:12, :326:12, :327:12, :354:12, :355:12, :385:12, :388:12, :389:12, :390:12, :391:5
  assign group_generate = |(_GEN_72[35:28]);	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:248:12, :386:12, :387:12, :391:5
  assign group_propagate = _GEN_71_26;	// 2993_DDLM_lab_05_src_13_carry_lookahead_adder_unwind_common_carry_lookahead_generator.v.cleaned.mlir:390:12, :391:5
endmodule

