// Generated by CIRCT unknown git version
module add32(	// file.cleaned.mlir:2:3
  input  [31:0] a,	// file.cleaned.mlir:2:23
                b,	// file.cleaned.mlir:2:36
  output [31:0] s	// file.cleaned.mlir:2:50
);

  assign s = a + b;	// file.cleaned.mlir:3:10, :4:5
endmodule

