// Generated by CIRCT unknown git version
module multip_adder(	// file.cleaned.mlir:2:3
  input  [7:0]  in_a,	// file.cleaned.mlir:2:30
                in_b,	// file.cleaned.mlir:2:45
  input  [15:0] in_c,	// file.cleaned.mlir:2:60
  output [15:0] product	// file.cleaned.mlir:2:77
);

  assign product = in_c + {{8{in_a[7]}}, in_a} * {{8{in_b[7]}}, in_b};	// file.cleaned.mlir:3:10, :4:10, :5:10, :6:10, :7:10, :8:10, :9:10, :10:10, :11:5
endmodule

