// Generated by CIRCT unknown git version
module Arbiter_3(	// file.cleaned.mlir:2:3
  input          io_in_1_valid,	// file.cleaned.mlir:2:27
  input  [3:0]   io_in_1_bits_way_en,	// file.cleaned.mlir:2:51
  input  [11:0]  io_in_1_bits_addr,	// file.cleaned.mlir:2:81
  input  [1:0]   io_in_1_bits_wmask,	// file.cleaned.mlir:2:110
  input  [127:0] io_in_1_bits_data,	// file.cleaned.mlir:2:139
  input          io_in_0_valid,	// file.cleaned.mlir:2:169
  input  [3:0]   io_in_0_bits_way_en,	// file.cleaned.mlir:2:193
  input  [11:0]  io_in_0_bits_addr,	// file.cleaned.mlir:2:223
  input  [1:0]   io_in_0_bits_wmask,	// file.cleaned.mlir:2:252
  input  [127:0] io_in_0_bits_data,	// file.cleaned.mlir:2:281
  input          io_out_ready,	// file.cleaned.mlir:2:311
  output         io_in_1_ready,	// file.cleaned.mlir:2:335
                 io_in_0_ready,	// file.cleaned.mlir:2:359
                 io_out_valid,	// file.cleaned.mlir:2:383
  output [3:0]   io_out_bits_way_en,	// file.cleaned.mlir:2:406
  output [11:0]  io_out_bits_addr,	// file.cleaned.mlir:2:435
  output [1:0]   io_out_bits_wmask,	// file.cleaned.mlir:2:463
  output [127:0] io_out_bits_data,	// file.cleaned.mlir:2:491
  output         io_chosen	// file.cleaned.mlir:2:520
);

  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// file.cleaned.mlir:8:10, :18:11, :19:5
  assign io_in_0_ready = io_out_ready;	// file.cleaned.mlir:19:5
  assign io_out_valid = ~io_in_0_valid ? io_in_1_valid : io_in_0_valid;	// file.cleaned.mlir:8:10, :17:10, :19:5
  assign io_out_bits_way_en =
    ~io_in_0_valid ? io_in_1_bits_way_en : io_in_0_valid ? io_in_0_bits_way_en : 4'h0;	// file.cleaned.mlir:3:14, :8:10, :15:10, :16:10, :19:5
  assign io_out_bits_addr =
    ~io_in_0_valid ? io_in_1_bits_addr : io_in_0_valid ? io_in_0_bits_addr : 12'h0;	// file.cleaned.mlir:4:15, :8:10, :13:10, :14:10, :19:5
  assign io_out_bits_wmask =
    ~io_in_0_valid ? io_in_1_bits_wmask : io_in_0_valid ? io_in_0_bits_wmask : 2'h0;	// file.cleaned.mlir:5:14, :8:10, :11:10, :12:10, :19:5
  assign io_out_bits_data =
    ~io_in_0_valid ? io_in_1_bits_data : io_in_0_valid ? io_in_0_bits_data : 128'h0;	// file.cleaned.mlir:6:16, :8:10, :9:10, :10:10, :19:5
  assign io_chosen = ~io_in_0_valid;	// file.cleaned.mlir:8:10, :19:5
endmodule

