// Generated by CIRCT unknown git version
module rom_prio(	// file.cleaned.mlir:2:3
  input  [7:0] address,	// file.cleaned.mlir:2:26
  input        clock,	// file.cleaned.mlir:2:44
  input  [3:0] data,	// file.cleaned.mlir:2:60
  input        wren,	// file.cleaned.mlir:2:75
  output [3:0] q	// file.cleaned.mlir:2:91
);

  assign q = 4'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

