// Generated by CIRCT unknown git version
module bsg_expand_bitmask_in_width_p2_expand_p4(	// file.cleaned.mlir:2:3
  input  [1:0] i,	// file.cleaned.mlir:2:58
  output [7:0] o	// file.cleaned.mlir:2:71
);

  wire o_3_;	// file.cleaned.mlir:38:11
  wire o_7_;	// file.cleaned.mlir:37:11
  assign o_7_ = i[1];	// file.cleaned.mlir:37:11
  assign o_3_ = i[0];	// file.cleaned.mlir:38:11
  assign o =
    {o_7_, 7'h0}
    | ({1'h0, o_7_, 6'h0}
       | ({2'h0, o_7_, 5'h0}
          | ({3'h0, o_7_, 4'h0}
             | ({4'h0, o_3_, 3'h0}
                | ({5'h0, o_3_, 2'h0} | ({6'h0, o_3_, 1'h0} | {7'h0, o_3_}) & 8'hFB)
                & 8'hF7) & 8'hEF) & 8'hDF) & 8'hBF) & 8'h7F;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:16, :10:16, :11:16, :12:16, :13:15, :14:15, :15:14, :16:10, :17:10, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:5
endmodule

