// Generated by CIRCT unknown git version
module bsg_unconcentrate_static_05(	// file.cleaned.mlir:2:3
  input  [1:0] i,	// file.cleaned.mlir:2:45
  output [4:0] o	// file.cleaned.mlir:2:58
);

  wire o_0_;	// file.cleaned.mlir:11:10
  wire o_2_;	// file.cleaned.mlir:10:10
  assign o_2_ = i[1];	// file.cleaned.mlir:10:10
  assign o_0_ = i[0];	// file.cleaned.mlir:11:10
  assign o = ({2'h0, o_2_, 2'h0} | {4'h0, o_0_}) & 5'h7;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:10, :7:10, :8:10, :9:10, :10:10, :11:10, :12:5
endmodule

