// Generated by CIRCT unknown git version
module bsg_unconcentrate_static_09(	// file.cleaned.mlir:2:3
  input  [1:0] i,	// file.cleaned.mlir:2:45
  output [4:0] o	// file.cleaned.mlir:2:58
);

  wire o_0_;	// file.cleaned.mlir:12:10
  wire o_3_;	// file.cleaned.mlir:11:10
  assign o_3_ = i[1];	// file.cleaned.mlir:11:10
  assign o_0_ = i[0];	// file.cleaned.mlir:12:10
  assign o = ({1'h0, o_3_, 3'h0} | {4'h0, o_0_}) & 5'hF;	// file.cleaned.mlir:3:14, :4:14, :5:15, :6:14, :7:10, :8:10, :9:10, :10:10, :11:10, :12:10, :13:5
endmodule

