// Generated by CIRCT unknown git version
module lzc_00000003(	// file.cleaned.mlir:2:3
  input  [2:0] in_i,	// file.cleaned.mlir:2:30
  output [1:0] cnt_o,	// file.cleaned.mlir:2:46
  output       empty_o	// file.cleaned.mlir:2:62
);

  wire       _GEN;	// file.cleaned.mlir:19:11
  wire       _GEN_0;	// file.cleaned.mlir:17:11
  wire       _GEN_1;	// file.cleaned.mlir:15:11
  wire       _GEN_2;	// file.cleaned.mlir:13:10
  wire       _GEN_3;	// file.cleaned.mlir:12:10
  wire [1:0] _GEN_4 = {_GEN, 1'h0} | {1'h0, _GEN_0};	// file.cleaned.mlir:4:14, :8:10, :9:10, :10:10, :17:11, :19:11
  assign _GEN_3 = ~(_GEN_4[1]);	// file.cleaned.mlir:10:10, :11:10, :12:10
  assign _GEN_2 = _GEN_4[1] & _GEN_1;	// file.cleaned.mlir:10:10, :11:10, :13:10, :15:11
  assign _GEN_1 = ~(in_i[0]);	// file.cleaned.mlir:14:10, :15:11
  assign _GEN_0 = _GEN_4[1] | in_i[2];	// file.cleaned.mlir:10:10, :11:10, :16:11, :17:11
  assign _GEN = in_i[0] | in_i[1];	// file.cleaned.mlir:14:10, :18:11, :19:11
  assign cnt_o = {_GEN_3, 1'h0} | {1'h0, _GEN_2};	// file.cleaned.mlir:4:14, :5:10, :6:10, :7:10, :12:10, :13:10, :22:5
  assign empty_o = ~(_GEN_4[0]);	// file.cleaned.mlir:10:10, :20:11, :21:11, :22:5
endmodule

