// Generated by CIRCT unknown git version
module bsg_mux_segmented_segments_p8_segment_width_p8(	// file.cleaned.mlir:2:3
  input  [63:0] data0_i,	// file.cleaned.mlir:2:64
                data1_i,	// file.cleaned.mlir:2:83
  input  [7:0]  sel_i,	// file.cleaned.mlir:2:102
  output [63:0] data_o	// file.cleaned.mlir:2:119
);

  wire       _GEN;	// file.cleaned.mlir:85:11
  wire       _GEN_0;	// file.cleaned.mlir:84:11
  wire       _GEN_1;	// file.cleaned.mlir:83:11
  wire       _GEN_2;	// file.cleaned.mlir:82:11
  wire       _GEN_3;	// file.cleaned.mlir:81:11
  wire       _GEN_4;	// file.cleaned.mlir:80:11
  wire       _GEN_5;	// file.cleaned.mlir:79:11
  wire       _GEN_6;	// file.cleaned.mlir:78:11
  wire       N7;	// file.cleaned.mlir:77:11
  wire [7:0] _GEN_7;	// file.cleaned.mlir:76:11
  wire       N6;	// file.cleaned.mlir:72:11
  wire [7:0] _GEN_8;	// file.cleaned.mlir:71:11
  wire       N5;	// file.cleaned.mlir:67:11
  wire [7:0] _GEN_9;	// file.cleaned.mlir:66:11
  wire       N4;	// file.cleaned.mlir:62:11
  wire [7:0] _GEN_10;	// file.cleaned.mlir:61:11
  wire       N3;	// file.cleaned.mlir:57:11
  wire [7:0] _GEN_11;	// file.cleaned.mlir:56:11
  wire       N2;	// file.cleaned.mlir:52:11
  wire [7:0] _GEN_12;	// file.cleaned.mlir:51:11
  wire       N1;	// file.cleaned.mlir:47:11
  wire [7:0] _GEN_13;	// file.cleaned.mlir:46:11
  wire       N0;	// file.cleaned.mlir:42:11
  wire [7:0] _GEN_14;	// file.cleaned.mlir:41:11
  assign _GEN_14 = N0 ? data1_i[7:0] : _GEN_6 ? data0_i[7:0] : 8'h0;	// file.cleaned.mlir:8:14, :38:11, :39:11, :40:11, :41:11, :42:11, :78:11
  assign N0 = sel_i[0];	// file.cleaned.mlir:42:11
  assign _GEN_13 = N1 ? data1_i[15:8] : _GEN_5 ? data0_i[15:8] : 8'h0;	// file.cleaned.mlir:8:14, :43:11, :44:11, :45:11, :46:11, :47:11, :79:11
  assign N1 = sel_i[1];	// file.cleaned.mlir:47:11
  assign _GEN_12 = N2 ? data1_i[23:16] : _GEN_4 ? data0_i[23:16] : 8'h0;	// file.cleaned.mlir:8:14, :48:11, :49:11, :50:11, :51:11, :52:11, :80:11
  assign N2 = sel_i[2];	// file.cleaned.mlir:52:11
  assign _GEN_11 = N3 ? data1_i[31:24] : _GEN_3 ? data0_i[31:24] : 8'h0;	// file.cleaned.mlir:8:14, :53:11, :54:11, :55:11, :56:11, :57:11, :81:11
  assign N3 = sel_i[3];	// file.cleaned.mlir:57:11
  assign _GEN_10 = N4 ? data1_i[39:32] : _GEN_2 ? data0_i[39:32] : 8'h0;	// file.cleaned.mlir:8:14, :58:11, :59:11, :60:11, :61:11, :62:11, :82:11
  assign N4 = sel_i[4];	// file.cleaned.mlir:62:11
  assign _GEN_9 = N5 ? data1_i[47:40] : _GEN_1 ? data0_i[47:40] : 8'h0;	// file.cleaned.mlir:8:14, :63:11, :64:11, :65:11, :66:11, :67:11, :83:11
  assign N5 = sel_i[5];	// file.cleaned.mlir:67:11
  assign _GEN_8 = N6 ? data1_i[55:48] : _GEN_0 ? data0_i[55:48] : 8'h0;	// file.cleaned.mlir:8:14, :68:11, :69:11, :70:11, :71:11, :72:11, :84:11
  assign N6 = sel_i[6];	// file.cleaned.mlir:72:11
  assign _GEN_7 = N7 ? data1_i[63:56] : _GEN ? data0_i[63:56] : 8'h0;	// file.cleaned.mlir:8:14, :73:11, :74:11, :75:11, :76:11, :77:11, :85:11
  assign N7 = sel_i[7];	// file.cleaned.mlir:77:11
  assign _GEN_6 = ~N0;	// file.cleaned.mlir:42:11, :78:11
  assign _GEN_5 = ~N1;	// file.cleaned.mlir:47:11, :79:11
  assign _GEN_4 = ~N2;	// file.cleaned.mlir:52:11, :80:11
  assign _GEN_3 = ~N3;	// file.cleaned.mlir:57:11, :81:11
  assign _GEN_2 = ~N4;	// file.cleaned.mlir:62:11, :82:11
  assign _GEN_1 = ~N5;	// file.cleaned.mlir:67:11, :83:11
  assign _GEN_0 = ~N6;	// file.cleaned.mlir:72:11, :84:11
  assign _GEN = ~N7;	// file.cleaned.mlir:77:11, :85:11
  assign data_o =
    {_GEN_7, 56'h0}
    | ({8'h0, _GEN_8, 48'h0}
       | ({16'h0, _GEN_9, 40'h0}
          | ({24'h0, _GEN_10, 32'h0}
             | ({32'h0, _GEN_11, 24'h0}
                | ({40'h0, _GEN_12, 16'h0} | ({48'h0, _GEN_13, 8'h0} | {56'h0, _GEN_14})
                   & 64'hFFFFFFFFFF00FFFF) & 64'hFFFFFFFF00FFFFFF) & 64'hFFFFFF00FFFFFFFF)
          & 64'hFFFF00FFFFFFFFFF) & 64'hFF00FFFFFFFFFFFF) & 64'hFFFFFFFFFFFFFF;	// file.cleaned.mlir:3:15, :4:15, :5:15, :6:15, :7:15, :8:14, :10:31, :11:32, :12:30, :13:28, :14:25, :15:23, :16:15, :17:10, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :41:11, :46:11, :51:11, :56:11, :61:11, :66:11, :71:11, :76:11, :86:5
endmodule

