// Generated by CIRCT unknown git version
module bp_be_dcache_lru_encode_ways_p8(	// file.cleaned.mlir:2:3
  input  [6:0] lru_i,	// file.cleaned.mlir:2:49
  output [2:0] way_id_o	// file.cleaned.mlir:2:66
);

  wire N26;	// file.cleaned.mlir:39:11
  wire N20;	// file.cleaned.mlir:37:11
  wire N15;	// file.cleaned.mlir:36:11
  wire N9;	// file.cleaned.mlir:34:11
  wire _lru_i_2;	// file.cleaned.mlir:21:11
  wire _lru_i_0;	// file.cleaned.mlir:17:10
  assign _lru_i_0 = lru_i[0];	// file.cleaned.mlir:17:10
  assign _lru_i_2 = lru_i[2];	// file.cleaned.mlir:21:11
  assign N9 = ~(lru_i[1]);	// file.cleaned.mlir:13:10, :34:11
  assign N15 = ~(lru_i[4]);	// file.cleaned.mlir:15:10, :36:11
  assign N20 = ~(lru_i[5]);	// file.cleaned.mlir:19:10, :37:11
  assign N26 = ~(lru_i[6]);	// file.cleaned.mlir:23:11, :39:11
  assign way_id_o =
    lru_i[3] | lru_i[1] | _lru_i_0
      ? (lru_i[3] & N9 & ~_lru_i_0
           ? 3'h1
           : N15 & lru_i[1] & ~_lru_i_0
               ? 3'h2
               : lru_i[4] & lru_i[1] & ~_lru_i_0
                   ? 3'h3
                   : N20 & ~_lru_i_2 & _lru_i_0
                       ? 3'h4
                       : lru_i[5] & ~_lru_i_2 & _lru_i_0
                           ? 3'h5
                           : N26 & _lru_i_2 & _lru_i_0
                               ? 3'h6
                               : {3{lru_i[6] & _lru_i_2 & _lru_i_0}})
      : 3'h0;	// file.cleaned.mlir:3:15, :4:15, :5:15, :6:14, :7:14, :8:14, :9:14, :11:10, :12:10, :13:10, :14:10, :15:10, :16:10, :17:10, :18:10, :19:10, :20:10, :21:11, :22:11, :23:11, :24:11, :25:11, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:5
endmodule

