// Generated by CIRCT unknown git version
module bsg_mux_width_p16_els_p4(	// file.cleaned.mlir:2:3
  input  [63:0] data_i,	// file.cleaned.mlir:2:42
  input  [1:0]  sel_i,	// file.cleaned.mlir:2:60
  output [15:0] data_o	// file.cleaned.mlir:2:77
);

  wire _GEN;	// file.cleaned.mlir:213:12
  wire _GEN_0;	// file.cleaned.mlir:212:12
  wire N2;	// file.cleaned.mlir:211:12
  wire _GEN_1;	// file.cleaned.mlir:206:12
  wire _GEN_2;	// file.cleaned.mlir:198:12
  wire _GEN_3;	// file.cleaned.mlir:190:12
  wire _GEN_4;	// file.cleaned.mlir:182:12
  wire _GEN_5;	// file.cleaned.mlir:174:12
  wire _GEN_6;	// file.cleaned.mlir:166:12
  wire _GEN_7;	// file.cleaned.mlir:158:12
  wire _GEN_8;	// file.cleaned.mlir:150:12
  wire _GEN_9;	// file.cleaned.mlir:142:12
  wire _GEN_10;	// file.cleaned.mlir:134:12
  wire _GEN_11;	// file.cleaned.mlir:126:11
  wire _GEN_12;	// file.cleaned.mlir:118:11
  wire _GEN_13;	// file.cleaned.mlir:110:11
  wire _GEN_14;	// file.cleaned.mlir:102:11
  wire _GEN_15;	// file.cleaned.mlir:94:11
  wire _GEN_16;	// file.cleaned.mlir:86:11
  assign _GEN_16 =
    N2 ? data_i[15] : _GEN ? data_i[31] : _GEN_0 ? data_i[47] : (&sel_i) & data_i[63];	// file.cleaned.mlir:79:11, :80:11, :81:11, :82:11, :83:11, :84:11, :85:11, :86:11, :211:12, :212:12, :213:12, :214:12
  assign _GEN_15 =
    N2 ? data_i[14] : _GEN ? data_i[30] : _GEN_0 ? data_i[46] : (&sel_i) & data_i[62];	// file.cleaned.mlir:87:11, :88:11, :89:11, :90:11, :91:11, :92:11, :93:11, :94:11, :211:12, :212:12, :213:12, :214:12
  assign _GEN_14 =
    N2 ? data_i[13] : _GEN ? data_i[29] : _GEN_0 ? data_i[45] : (&sel_i) & data_i[61];	// file.cleaned.mlir:95:11, :96:11, :97:11, :98:11, :99:11, :100:11, :101:11, :102:11, :211:12, :212:12, :213:12, :214:12
  assign _GEN_13 =
    N2 ? data_i[12] : _GEN ? data_i[28] : _GEN_0 ? data_i[44] : (&sel_i) & data_i[60];	// file.cleaned.mlir:103:11, :104:11, :105:11, :106:11, :107:11, :108:11, :109:11, :110:11, :211:12, :212:12, :213:12, :214:12
  assign _GEN_12 =
    N2 ? data_i[11] : _GEN ? data_i[27] : _GEN_0 ? data_i[43] : (&sel_i) & data_i[59];	// file.cleaned.mlir:111:11, :112:11, :113:11, :114:11, :115:11, :116:11, :117:11, :118:11, :211:12, :212:12, :213:12, :214:12
  assign _GEN_11 =
    N2 ? data_i[10] : _GEN ? data_i[26] : _GEN_0 ? data_i[42] : (&sel_i) & data_i[58];	// file.cleaned.mlir:119:11, :120:11, :121:11, :122:11, :123:11, :124:11, :125:11, :126:11, :211:12, :212:12, :213:12, :214:12
  assign _GEN_10 =
    N2 ? data_i[9] : _GEN ? data_i[25] : _GEN_0 ? data_i[41] : (&sel_i) & data_i[57];	// file.cleaned.mlir:127:11, :128:11, :129:11, :130:11, :131:11, :132:11, :133:11, :134:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_9 =
    N2 ? data_i[8] : _GEN ? data_i[24] : _GEN_0 ? data_i[40] : (&sel_i) & data_i[56];	// file.cleaned.mlir:135:12, :136:12, :137:12, :138:12, :139:12, :140:12, :141:12, :142:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_8 =
    N2 ? data_i[7] : _GEN ? data_i[23] : _GEN_0 ? data_i[39] : (&sel_i) & data_i[55];	// file.cleaned.mlir:143:12, :144:12, :145:12, :146:12, :147:12, :148:12, :149:12, :150:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_7 =
    N2 ? data_i[6] : _GEN ? data_i[22] : _GEN_0 ? data_i[38] : (&sel_i) & data_i[54];	// file.cleaned.mlir:151:12, :152:12, :153:12, :154:12, :155:12, :156:12, :157:12, :158:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_6 =
    N2 ? data_i[5] : _GEN ? data_i[21] : _GEN_0 ? data_i[37] : (&sel_i) & data_i[53];	// file.cleaned.mlir:159:12, :160:12, :161:12, :162:12, :163:12, :164:12, :165:12, :166:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_5 =
    N2 ? data_i[4] : _GEN ? data_i[20] : _GEN_0 ? data_i[36] : (&sel_i) & data_i[52];	// file.cleaned.mlir:167:12, :168:12, :169:12, :170:12, :171:12, :172:12, :173:12, :174:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_4 =
    N2 ? data_i[3] : _GEN ? data_i[19] : _GEN_0 ? data_i[35] : (&sel_i) & data_i[51];	// file.cleaned.mlir:175:12, :176:12, :177:12, :178:12, :179:12, :180:12, :181:12, :182:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_3 =
    N2 ? data_i[2] : _GEN ? data_i[18] : _GEN_0 ? data_i[34] : (&sel_i) & data_i[50];	// file.cleaned.mlir:183:12, :184:12, :185:12, :186:12, :187:12, :188:12, :189:12, :190:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_2 =
    N2 ? data_i[1] : _GEN ? data_i[17] : _GEN_0 ? data_i[33] : (&sel_i) & data_i[49];	// file.cleaned.mlir:191:12, :192:12, :193:12, :194:12, :195:12, :196:12, :197:12, :198:12, :211:12, :212:12, :213:12, :214:12
  assign _GEN_1 =
    N2 ? data_i[0] : _GEN ? data_i[16] : _GEN_0 ? data_i[32] : (&sel_i) & data_i[48];	// file.cleaned.mlir:199:12, :200:12, :201:12, :202:12, :203:12, :204:12, :205:12, :206:12, :211:12, :212:12, :213:12, :214:12
  assign N2 = ~(sel_i[0]) & ~(sel_i[1]);	// file.cleaned.mlir:207:12, :208:12, :209:12, :210:12, :211:12
  assign _GEN_0 = ~(sel_i[0]) & sel_i[1];	// file.cleaned.mlir:207:12, :208:12, :209:12, :212:12
  assign _GEN = sel_i[0] & ~(sel_i[1]);	// file.cleaned.mlir:207:12, :209:12, :210:12, :213:12
  assign data_o =
    {_GEN_16, 15'h0}
    | ({1'h0, _GEN_15, 14'h0}
       | ({2'h0, _GEN_14, 13'h0}
          | ({3'h0, _GEN_13, 12'h0}
             | ({4'h0, _GEN_12, 11'h0}
                | ({5'h0, _GEN_11, 10'h0}
                   | ({6'h0, _GEN_10, 9'h0}
                      | ({7'h0, _GEN_9, 8'h0}
                         | ({8'h0, _GEN_8, 7'h0}
                            | ({9'h0, _GEN_7, 6'h0}
                               | ({10'h0, _GEN_6, 5'h0}
                                  | ({11'h0, _GEN_5, 4'h0}
                                     | ({12'h0, _GEN_4, 3'h0}
                                        | ({13'h0, _GEN_3, 2'h0}
                                           | ({14'h0, _GEN_2, 1'h0} | {15'h0, _GEN_1})
                                           & 16'hFFFB) & 16'hFFF7) & 16'hFFEF) & 16'hFFDF)
                               & 16'hFFBF) & 16'hFF7F) & 16'hFEFF) & 16'hFDFF) & 16'hFBFF)
                & 16'hF7FF) & 16'hEFFF) & 16'hDFFF) & 16'hBFFF) & 16'h7FFF;	// file.cleaned.mlir:4:14, :5:14, :6:14, :7:14, :8:15, :9:14, :10:15, :11:14, :12:15, :13:14, :14:15, :15:14, :16:15, :17:14, :19:19, :20:20, :21:19, :22:19, :23:19, :24:19, :25:18, :26:18, :27:18, :28:17, :29:17, :30:17, :31:16, :32:16, :33:15, :34:10, :35:10, :36:10, :37:10, :38:10, :39:10, :40:10, :41:10, :42:10, :43:10, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :65:11, :66:11, :67:11, :68:11, :69:11, :70:11, :71:11, :72:11, :73:11, :74:11, :75:11, :76:11, :77:11, :78:11, :86:11, :94:11, :102:11, :110:11, :118:11, :126:11, :134:12, :142:12, :150:12, :158:12, :166:12, :174:12, :182:12, :190:12, :198:12, :206:12, :215:5
endmodule

