// Generated by CIRCT unknown git version
module bsg_encode_one_hot_width_p1(	// file.cleaned.mlir:2:3
  input  i,	// file.cleaned.mlir:2:45
  output addr_o,	// file.cleaned.mlir:2:58
         v_o	// file.cleaned.mlir:2:75
);

  assign addr_o = 1'h0;	// file.cleaned.mlir:3:14, :4:5
  assign v_o = i;	// file.cleaned.mlir:4:5
endmodule

