// Generated by CIRCT unknown git version
module Arbiter_1(	// file.cleaned.mlir:2:3
  input         io_in_1_valid,	// file.cleaned.mlir:2:27
  input  [5:0]  io_in_1_bits_idx,	// file.cleaned.mlir:2:51
  input  [3:0]  io_in_1_bits_way_en,	// file.cleaned.mlir:2:78
  input  [19:0] io_in_1_bits_data_tag,	// file.cleaned.mlir:2:108
  input  [1:0]  io_in_1_bits_data_coh_state,	// file.cleaned.mlir:2:141
  input         io_in_0_valid,	// file.cleaned.mlir:2:179
  input  [5:0]  io_in_0_bits_idx,	// file.cleaned.mlir:2:203
  input  [3:0]  io_in_0_bits_way_en,	// file.cleaned.mlir:2:230
  input  [19:0] io_in_0_bits_data_tag,	// file.cleaned.mlir:2:260
  input  [1:0]  io_in_0_bits_data_coh_state,	// file.cleaned.mlir:2:293
  input         io_out_ready,	// file.cleaned.mlir:2:331
  output        io_in_1_ready,	// file.cleaned.mlir:2:355
                io_in_0_ready,	// file.cleaned.mlir:2:379
                io_out_valid,	// file.cleaned.mlir:2:403
  output [5:0]  io_out_bits_idx,	// file.cleaned.mlir:2:426
  output [3:0]  io_out_bits_way_en,	// file.cleaned.mlir:2:452
  output [19:0] io_out_bits_data_tag,	// file.cleaned.mlir:2:481
  output [1:0]  io_out_bits_data_coh_state,	// file.cleaned.mlir:2:513
  output        io_chosen	// file.cleaned.mlir:2:550
);

  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// file.cleaned.mlir:8:10, :18:11, :19:5
  assign io_in_0_ready = io_out_ready;	// file.cleaned.mlir:19:5
  assign io_out_valid = ~io_in_0_valid ? io_in_1_valid : io_in_0_valid;	// file.cleaned.mlir:8:10, :17:10, :19:5
  assign io_out_bits_idx =
    ~io_in_0_valid ? io_in_1_bits_idx : io_in_0_valid ? io_in_0_bits_idx : 6'h0;	// file.cleaned.mlir:3:14, :8:10, :15:10, :16:10, :19:5
  assign io_out_bits_way_en =
    ~io_in_0_valid ? io_in_1_bits_way_en : io_in_0_valid ? io_in_0_bits_way_en : 4'h0;	// file.cleaned.mlir:4:14, :8:10, :13:10, :14:10, :19:5
  assign io_out_bits_data_tag =
    ~io_in_0_valid
      ? io_in_1_bits_data_tag
      : io_in_0_valid ? io_in_0_bits_data_tag : 20'h0;	// file.cleaned.mlir:5:15, :8:10, :11:10, :12:10, :19:5
  assign io_out_bits_data_coh_state =
    ~io_in_0_valid
      ? io_in_1_bits_data_coh_state
      : io_in_0_valid ? io_in_0_bits_data_coh_state : 2'h0;	// file.cleaned.mlir:6:14, :8:10, :9:10, :10:10, :19:5
  assign io_chosen = ~io_in_0_valid;	// file.cleaned.mlir:8:10, :19:5
endmodule

