// Generated by CIRCT unknown git version
module Arbiter(	// file.cleaned.mlir:2:3
  input         clock,	// file.cleaned.mlir:2:25
                reset,	// file.cleaned.mlir:2:41
                io_fifo_valid,	// file.cleaned.mlir:2:57
  input  [15:0] io_fifo_data,	// file.cleaned.mlir:2:81
  input         io_pe0_ready,	// file.cleaned.mlir:2:105
                io_pe1_ready,	// file.cleaned.mlir:2:128
  output        io_fifo_ready,	// file.cleaned.mlir:2:152
                io_pe0_valid,	// file.cleaned.mlir:2:176
  output [15:0] io_pe0_data,	// file.cleaned.mlir:2:199
  output        io_pe1_valid,	// file.cleaned.mlir:2:222
  output [15:0] io_pe1_data	// file.cleaned.mlir:2:245
);

  assign io_fifo_ready = io_pe0_ready | io_pe1_ready;	// file.cleaned.mlir:4:10, :8:5
  assign io_pe0_valid = io_fifo_valid & io_pe0_ready;	// file.cleaned.mlir:5:10, :8:5
  assign io_pe0_data = io_fifo_data;	// file.cleaned.mlir:8:5
  assign io_pe1_valid = io_fifo_valid & io_pe1_ready & ~io_pe0_ready;	// file.cleaned.mlir:6:10, :7:10, :8:5
  assign io_pe1_data = io_fifo_data;	// file.cleaned.mlir:8:5
endmodule

