// Generated by CIRCT unknown git version
module fifo_in_samples(	// file.cleaned.mlir:2:3
  input         wr_clk_i,	// file.cleaned.mlir:2:33
                rd_clk_i,	// file.cleaned.mlir:2:52
                rst_i,	// file.cleaned.mlir:2:71
                rp_rst_i,	// file.cleaned.mlir:2:87
                wr_en_i,	// file.cleaned.mlir:2:106
                rd_en_i,	// file.cleaned.mlir:2:124
  input  [15:0] wr_data_i,	// file.cleaned.mlir:2:142
  output        full_o,	// file.cleaned.mlir:2:164
                empty_o,	// file.cleaned.mlir:2:181
                almost_empty_o,	// file.cleaned.mlir:2:199
  output [15:0] rd_data_o	// file.cleaned.mlir:2:224
);

  assign full_o = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign empty_o = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign almost_empty_o = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign rd_data_o = 16'h0;	// file.cleaned.mlir:4:15, :5:5
endmodule

