// Generated by CIRCT unknown git version
module S1(	// file.cleaned.mlir:2:3
  input  [4:0] S,	// file.cleaned.mlir:2:20
  output       Y	// file.cleaned.mlir:2:33
);

  wire SYNTHESIZED_WIRE_4;	// file.cleaned.mlir:13:10
  wire SYNTHESIZED_WIRE_3;	// file.cleaned.mlir:11:10
  wire SYNTHESIZED_WIRE_0;	// file.cleaned.mlir:9:10
  wire SYNTHESIZED_WIRE_2;	// file.cleaned.mlir:7:10
  assign SYNTHESIZED_WIRE_2 = ~(S[4]);	// file.cleaned.mlir:6:10, :7:10
  assign SYNTHESIZED_WIRE_0 = ~(S[3]);	// file.cleaned.mlir:8:10, :9:10
  assign SYNTHESIZED_WIRE_3 = ~(S[2]);	// file.cleaned.mlir:10:10, :11:10
  assign SYNTHESIZED_WIRE_4 = ~(S[1]);	// file.cleaned.mlir:12:10, :13:10
  assign Y =
    SYNTHESIZED_WIRE_0 & SYNTHESIZED_WIRE_2 & SYNTHESIZED_WIRE_3 & SYNTHESIZED_WIRE_4
    & S[0];	// file.cleaned.mlir:4:10, :5:10, :7:10, :9:10, :11:10, :13:10, :14:5
endmodule

