// Generated by CIRCT unknown git version
module absolute_value(	// file.cleaned.mlir:2:3
  input  [31:0] data_in,	// file.cleaned.mlir:2:32
  output [31:0] data_out	// file.cleaned.mlir:2:52
);

  wire [31:0] data_sign_ext = {32{data_in[31]}};	// file.cleaned.mlir:3:10, :4:10
  assign data_out = (data_in ^ data_sign_ext) - data_sign_ext;	// file.cleaned.mlir:4:10, :5:10, :6:10, :7:5
endmodule

