// Generated by CIRCT unknown git version
module adder_sat_8(	// file.cleaned.mlir:2:3
  input  [7:0] a,	// file.cleaned.mlir:2:29
               b,	// file.cleaned.mlir:2:41
  output [7:0] c	// file.cleaned.mlir:2:54
);

  wire [8:0] _GEN = {1'h0, a} + {b[7], b};	// file.cleaned.mlir:5:14, :6:10, :7:10, :8:10, :9:10
  assign c = _GEN[8] ? (b[7] ? 8'h0 : 8'hFF) : _GEN[7:0];	// file.cleaned.mlir:3:15, :4:14, :7:10, :9:10, :10:10, :11:10, :12:10, :13:10, :14:5
endmodule

