// Generated by CIRCT unknown git version
module rgb2y(	// file.cleaned.mlir:2:3
  input  [5:0] r,	// file.cleaned.mlir:2:23
               g,	// file.cleaned.mlir:2:35
               b,	// file.cleaned.mlir:2:47
  output [7:0] y	// file.cleaned.mlir:2:60
);

  wire [13:0] acc = {8'h0, r} * 14'h4D + {8'h0, g} * 14'h96 + {8'h0, b} * 14'h1D;	// file.cleaned.mlir:3:16, :4:17, :5:16, :6:14, :7:10, :8:10, :9:10, :10:10, :11:10, :12:10, :13:10
  assign y = acc[13:6];	// file.cleaned.mlir:13:10, :14:10, :15:5
endmodule

