// Generated by CIRCT unknown git version
module pcie_pipe_misc_v6(	// file.cleaned.mlir:2:3
  input        pipe_tx_rcvr_det_i,	// file.cleaned.mlir:2:35
               pipe_tx_reset_i,	// file.cleaned.mlir:2:64
               pipe_tx_rate_i,	// file.cleaned.mlir:2:90
               pipe_tx_deemph_i,	// file.cleaned.mlir:2:115
  input  [2:0] pipe_tx_margin_i,	// file.cleaned.mlir:2:142
  input        pipe_tx_swing_i,	// file.cleaned.mlir:2:169
               pipe_clk,	// file.cleaned.mlir:2:195
               rst_n,	// file.cleaned.mlir:2:214
  output       pipe_tx_rcvr_det_o,	// file.cleaned.mlir:2:231
               pipe_tx_reset_o,	// file.cleaned.mlir:2:260
               pipe_tx_rate_o,	// file.cleaned.mlir:2:286
               pipe_tx_deemph_o,	// file.cleaned.mlir:2:311
  output [2:0] pipe_tx_margin_o,	// file.cleaned.mlir:2:338
  output       pipe_tx_swing_o	// file.cleaned.mlir:2:365
);

  assign pipe_tx_rcvr_det_o = pipe_tx_rcvr_det_i;	// file.cleaned.mlir:3:5
  assign pipe_tx_reset_o = pipe_tx_reset_i;	// file.cleaned.mlir:3:5
  assign pipe_tx_rate_o = pipe_tx_rate_i;	// file.cleaned.mlir:3:5
  assign pipe_tx_deemph_o = pipe_tx_deemph_i;	// file.cleaned.mlir:3:5
  assign pipe_tx_margin_o = pipe_tx_margin_i;	// file.cleaned.mlir:3:5
  assign pipe_tx_swing_o = pipe_tx_swing_i;	// file.cleaned.mlir:3:5
endmodule

