// Generated by CIRCT unknown git version
module Multiplier(	// file.cleaned.mlir:2:3
  input  [7:0]  in1,	// file.cleaned.mlir:2:28
                in2,	// file.cleaned.mlir:2:42
  output [15:0] result	// file.cleaned.mlir:2:57
);

  assign result = {8'h0, in1} * {8'h0, in2};	// file.cleaned.mlir:3:14, :4:10, :5:10, :6:10, :7:5
endmodule

