// Generated by CIRCT unknown git version
module cmsdk_apb_slave_mux(	// file.cleaned.mlir:2:3
  input  [3:0]  DECODE4BIT,	// file.cleaned.mlir:2:37
  input         PSEL,	// file.cleaned.mlir:2:58
                PREADY0,	// file.cleaned.mlir:2:73
  input  [31:0] PRDATA0,	// file.cleaned.mlir:2:91
  input         PSLVERR0,	// file.cleaned.mlir:2:110
                PREADY1,	// file.cleaned.mlir:2:129
  input  [31:0] PRDATA1,	// file.cleaned.mlir:2:147
  input         PSLVERR1,	// file.cleaned.mlir:2:166
                PREADY2,	// file.cleaned.mlir:2:185
  input  [31:0] PRDATA2,	// file.cleaned.mlir:2:203
  input         PSLVERR2,	// file.cleaned.mlir:2:222
                PREADY3,	// file.cleaned.mlir:2:241
  input  [31:0] PRDATA3,	// file.cleaned.mlir:2:259
  input         PSLVERR3,	// file.cleaned.mlir:2:278
                PREADY4,	// file.cleaned.mlir:2:297
  input  [31:0] PRDATA4,	// file.cleaned.mlir:2:315
  input         PSLVERR4,	// file.cleaned.mlir:2:334
                PREADY5,	// file.cleaned.mlir:2:353
  input  [31:0] PRDATA5,	// file.cleaned.mlir:2:371
  input         PSLVERR5,	// file.cleaned.mlir:2:390
                PREADY6,	// file.cleaned.mlir:2:409
  input  [31:0] PRDATA6,	// file.cleaned.mlir:2:427
  input         PSLVERR6,	// file.cleaned.mlir:2:446
                PREADY7,	// file.cleaned.mlir:2:465
  input  [31:0] PRDATA7,	// file.cleaned.mlir:2:483
  input         PSLVERR7,	// file.cleaned.mlir:2:502
                PREADY8,	// file.cleaned.mlir:2:521
  input  [31:0] PRDATA8,	// file.cleaned.mlir:2:539
  input         PSLVERR8,	// file.cleaned.mlir:2:558
                PREADY9,	// file.cleaned.mlir:2:577
  input  [31:0] PRDATA9,	// file.cleaned.mlir:2:595
  input         PSLVERR9,	// file.cleaned.mlir:2:614
                PREADY10,	// file.cleaned.mlir:2:633
  input  [31:0] PRDATA10,	// file.cleaned.mlir:2:652
  input         PSLVERR10,	// file.cleaned.mlir:2:672
                PREADY11,	// file.cleaned.mlir:2:692
  input  [31:0] PRDATA11,	// file.cleaned.mlir:2:711
  input         PSLVERR11,	// file.cleaned.mlir:2:731
                PREADY12,	// file.cleaned.mlir:2:751
  input  [31:0] PRDATA12,	// file.cleaned.mlir:2:770
  input         PSLVERR12,	// file.cleaned.mlir:2:790
                PREADY13,	// file.cleaned.mlir:2:810
  input  [31:0] PRDATA13,	// file.cleaned.mlir:2:829
  input         PSLVERR13,	// file.cleaned.mlir:2:849
                PREADY14,	// file.cleaned.mlir:2:869
  input  [31:0] PRDATA14,	// file.cleaned.mlir:2:888
  input         PSLVERR14,	// file.cleaned.mlir:2:908
                PREADY15,	// file.cleaned.mlir:2:928
  input  [31:0] PRDATA15,	// file.cleaned.mlir:2:947
  input         PSLVERR15,	// file.cleaned.mlir:2:967
  output        PSEL0,	// file.cleaned.mlir:2:988
                PSEL1,	// file.cleaned.mlir:2:1004
                PSEL2,	// file.cleaned.mlir:2:1020
                PSEL3,	// file.cleaned.mlir:2:1036
                PSEL4,	// file.cleaned.mlir:2:1052
                PSEL5,	// file.cleaned.mlir:2:1068
                PSEL6,	// file.cleaned.mlir:2:1084
                PSEL7,	// file.cleaned.mlir:2:1100
                PSEL8,	// file.cleaned.mlir:2:1116
                PSEL9,	// file.cleaned.mlir:2:1132
                PSEL10,	// file.cleaned.mlir:2:1148
                PSEL11,	// file.cleaned.mlir:2:1165
                PSEL12,	// file.cleaned.mlir:2:1182
                PSEL13,	// file.cleaned.mlir:2:1199
                PSEL14,	// file.cleaned.mlir:2:1216
                PSEL15,	// file.cleaned.mlir:2:1233
                PREADY,	// file.cleaned.mlir:2:1250
  output [31:0] PRDATA,	// file.cleaned.mlir:2:1267
  output        PSLVERR	// file.cleaned.mlir:2:1285
);

  wire _GEN = DECODE4BIT == 4'hE;	// file.cleaned.mlir:18:15, :21:10
  wire _GEN_0 = DECODE4BIT == 4'hD;	// file.cleaned.mlir:17:15, :22:10
  wire _GEN_1 = DECODE4BIT == 4'hC;	// file.cleaned.mlir:16:15, :23:10
  wire _GEN_2 = DECODE4BIT == 4'hB;	// file.cleaned.mlir:15:15, :24:10
  wire _GEN_3 = DECODE4BIT == 4'hA;	// file.cleaned.mlir:14:15, :25:10
  wire _GEN_4 = DECODE4BIT == 4'h9;	// file.cleaned.mlir:13:15, :26:10
  wire _GEN_5 = DECODE4BIT == 4'h8;	// file.cleaned.mlir:12:15, :27:10
  wire _GEN_6 = DECODE4BIT == 4'h7;	// file.cleaned.mlir:11:14, :28:10
  wire _GEN_7 = DECODE4BIT == 4'h6;	// file.cleaned.mlir:10:14, :29:10
  wire _GEN_8 = DECODE4BIT == 4'h5;	// file.cleaned.mlir:9:14, :30:11
  wire _GEN_9 = DECODE4BIT == 4'h4;	// file.cleaned.mlir:8:14, :31:11
  wire _GEN_10 = DECODE4BIT == 4'h3;	// file.cleaned.mlir:7:14, :32:11
  wire _GEN_11 = DECODE4BIT == 4'h2;	// file.cleaned.mlir:6:14, :33:11
  wire _GEN_12 = DECODE4BIT == 4'h1;	// file.cleaned.mlir:5:14, :34:11
  wire _GEN_13 = DECODE4BIT == 4'h0;	// file.cleaned.mlir:4:14, :35:11
  wire _GEN_14 = PSEL & _GEN_13;	// file.cleaned.mlir:35:11, :36:11
  wire _GEN_15 = PSEL & _GEN_12;	// file.cleaned.mlir:34:11, :37:11
  wire _GEN_16 = PSEL & _GEN_11;	// file.cleaned.mlir:33:11, :38:11
  wire _GEN_17 = PSEL & _GEN_10;	// file.cleaned.mlir:32:11, :39:11
  wire _GEN_18 = PSEL & _GEN_9;	// file.cleaned.mlir:31:11, :40:11
  wire _GEN_19 = PSEL & _GEN_8;	// file.cleaned.mlir:30:11, :41:11
  wire _GEN_20 = PSEL & _GEN_7;	// file.cleaned.mlir:29:10, :42:11
  wire _GEN_21 = PSEL & _GEN_6;	// file.cleaned.mlir:28:10, :43:11
  wire _GEN_22 = PSEL & _GEN_5;	// file.cleaned.mlir:27:10, :44:11
  wire _GEN_23 = PSEL & _GEN_4;	// file.cleaned.mlir:26:10, :45:11
  wire _GEN_24 = PSEL & _GEN_3;	// file.cleaned.mlir:25:10, :46:11
  wire _GEN_25 = PSEL & _GEN_2;	// file.cleaned.mlir:24:10, :47:11
  wire _GEN_26 = PSEL & _GEN_1;	// file.cleaned.mlir:23:10, :48:11
  wire _GEN_27 = PSEL & _GEN_0;	// file.cleaned.mlir:22:10, :49:11
  wire _GEN_28 = PSEL & _GEN;	// file.cleaned.mlir:21:10, :50:11
  wire _GEN_29 = PSEL & (&DECODE4BIT);	// file.cleaned.mlir:20:10, :51:11
  assign PSEL0 = _GEN_14;	// file.cleaned.mlir:36:11, :120:5
  assign PSEL1 = _GEN_15;	// file.cleaned.mlir:37:11, :120:5
  assign PSEL2 = _GEN_16;	// file.cleaned.mlir:38:11, :120:5
  assign PSEL3 = _GEN_17;	// file.cleaned.mlir:39:11, :120:5
  assign PSEL4 = _GEN_18;	// file.cleaned.mlir:40:11, :120:5
  assign PSEL5 = _GEN_19;	// file.cleaned.mlir:41:11, :120:5
  assign PSEL6 = _GEN_20;	// file.cleaned.mlir:42:11, :120:5
  assign PSEL7 = _GEN_21;	// file.cleaned.mlir:43:11, :120:5
  assign PSEL8 = _GEN_22;	// file.cleaned.mlir:44:11, :120:5
  assign PSEL9 = _GEN_23;	// file.cleaned.mlir:45:11, :120:5
  assign PSEL10 = _GEN_24;	// file.cleaned.mlir:46:11, :120:5
  assign PSEL11 = _GEN_25;	// file.cleaned.mlir:47:11, :120:5
  assign PSEL12 = _GEN_26;	// file.cleaned.mlir:48:11, :120:5
  assign PSEL13 = _GEN_27;	// file.cleaned.mlir:49:11, :120:5
  assign PSEL14 = _GEN_28;	// file.cleaned.mlir:50:11, :120:5
  assign PSEL15 = _GEN_29;	// file.cleaned.mlir:51:11, :120:5
  assign PREADY =
    ~PSEL | _GEN_13 & PREADY0 | _GEN_12 & PREADY1 | _GEN_11 & PREADY2 | _GEN_10 & PREADY3
    | _GEN_9 & PREADY4 | _GEN_8 & PREADY5 | _GEN_7 & PREADY6 | _GEN_6 & PREADY7 | _GEN_5
    & PREADY8 | _GEN_4 & PREADY9 | _GEN_3 & PREADY10 | _GEN_2 & PREADY11 | _GEN_1
    & PREADY12 | _GEN_0 & PREADY13 | _GEN & PREADY14 | (&DECODE4BIT) & PREADY15;	// file.cleaned.mlir:20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:10, :29:10, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :65:11, :66:11, :67:11, :68:11, :69:11, :120:5
  assign PRDATA =
    {32{_GEN_14}} & PRDATA0 | {32{_GEN_15}} & PRDATA1 | {32{_GEN_16}} & PRDATA2
    | {32{_GEN_17}} & PRDATA3 | {32{_GEN_18}} & PRDATA4 | {32{_GEN_19}} & PRDATA5
    | {32{_GEN_20}} & PRDATA6 | {32{_GEN_21}} & PRDATA7 | {32{_GEN_22}} & PRDATA8
    | {32{_GEN_23}} & PRDATA9 | {32{_GEN_24}} & PRDATA10 | {32{_GEN_25}} & PRDATA11
    | {32{_GEN_26}} & PRDATA12 | {32{_GEN_27}} & PRDATA13 | {32{_GEN_28}} & PRDATA14
    | {32{_GEN_29}} & PRDATA15;	// file.cleaned.mlir:36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :87:11, :88:11, :89:11, :90:11, :91:11, :92:11, :93:11, :94:11, :95:11, :96:11, :97:11, :98:11, :99:11, :100:11, :101:11, :102:11, :103:11, :104:11, :105:11, :106:11, :107:11, :108:11, :109:11, :110:11, :111:11, :112:11, :113:11, :114:11, :115:11, :116:11, :117:11, :118:11, :119:11, :120:5
  assign PSLVERR =
    _GEN_14 & PSLVERR0 | _GEN_15 & PSLVERR1 | _GEN_16 & PSLVERR2 | _GEN_17 & PSLVERR3
    | _GEN_18 & PSLVERR4 | _GEN_19 & PSLVERR5 | _GEN_20 & PSLVERR6 | _GEN_21 & PSLVERR7
    | _GEN_22 & PSLVERR8 | _GEN_23 & PSLVERR9 | _GEN_24 & PSLVERR10 | _GEN_25 & PSLVERR11
    | _GEN_26 & PSLVERR12 | _GEN_27 & PSLVERR13 | _GEN_28 & PSLVERR14 | _GEN_29
    & PSLVERR15;	// file.cleaned.mlir:36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :70:11, :71:11, :72:11, :73:11, :74:11, :75:11, :76:11, :77:11, :78:11, :79:11, :80:11, :81:11, :82:11, :83:11, :84:11, :85:11, :86:11, :120:5
endmodule

