// Generated by CIRCT unknown git version
module dut(	// file.cleaned.mlir:2:3
  input        clk,	// file.cleaned.mlir:2:21
  input  [7:0] a,	// file.cleaned.mlir:2:35
  output [7:0] b	// file.cleaned.mlir:2:48
);

  assign b = a;	// file.cleaned.mlir:3:5
endmodule

