// Generated by CIRCT unknown git version
module dut(	// file.cleaned.mlir:2:3
  input  [2:0] a,	// file.cleaned.mlir:2:21
  output [2:0] o	// file.cleaned.mlir:2:34
);

  assign o = {a[1:0], 1'h0};	// file.cleaned.mlir:3:14, :4:10, :5:10, :6:5
endmodule

