// Generated by CIRCT unknown git version
module AHBlite_Decoder(	// file.cleaned.mlir:2:3
  input  [31:0] HADDR,	// file.cleaned.mlir:2:33
  output        P0_HSEL,	// file.cleaned.mlir:2:51
                P1_HSEL,	// file.cleaned.mlir:2:69
                P2_HSEL,	// file.cleaned.mlir:2:87
                P3_HSEL	// file.cleaned.mlir:2:105
);

  assign P0_HSEL = 1'h0;	// file.cleaned.mlir:3:14, :4:5
  assign P1_HSEL = 1'h0;	// file.cleaned.mlir:3:14, :4:5
  assign P2_HSEL = 1'h0;	// file.cleaned.mlir:3:14, :4:5
  assign P3_HSEL = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

