// Generated by CIRCT unknown git version
module circuit(	// file.cleaned.mlir:2:3
  input  a,	// file.cleaned.mlir:2:25
         b,	// file.cleaned.mlir:2:37
         c,	// file.cleaned.mlir:2:49
  output x	// file.cleaned.mlir:2:62
);

  assign x = ~(a & b) | c;	// file.cleaned.mlir:4:10, :5:10, :6:10, :7:5
endmodule

