// Generated by CIRCT unknown git version
module three_bit_comparator(	// file.cleaned.mlir:2:3
  input  [2:0] A,	// file.cleaned.mlir:2:38
               B,	// file.cleaned.mlir:2:50
  output       GT,	// file.cleaned.mlir:2:63
               LT,	// file.cleaned.mlir:2:76
               EQ	// file.cleaned.mlir:2:89
);

  wire _GEN = ~(B[2]) & ~(B[1]);	// file.cleaned.mlir:4:10, :5:10, :6:10, :7:10, :8:10
  wire _GEN_0 = B[2] & B[1];	// file.cleaned.mlir:4:10, :6:10, :30:11
  assign GT =
    _GEN & ~(B[0]) & A[0] | _GEN & A[1] | ~(B[2]) & A[2] | ~(B[2]) & ~(B[0]) & A[1] & A[0]
    | ~(B[1]) & ~(B[0]) & A[2] & A[0] | ~(B[1]) & A[2] & A[1] | ~(B[0]) & A[2] & A[1]
    & A[0];	// file.cleaned.mlir:4:10, :5:10, :6:10, :7:10, :8:10, :9:10, :10:10, :11:10, :12:10, :13:10, :14:11, :15:11, :16:11, :17:11, :18:11, :19:11, :20:11, :21:11, :38:5
  assign LT =
    B[0] & ~(A[2]) & ~(A[1]) & ~(A[0]) | B[1] & ~(A[2]) & ~(A[1]) | B[1] & B[0] & ~(A[2])
    & ~(A[0]) | B[2] & ~(A[2]) | B[2] & B[0] & ~(A[1]) & ~(A[0]) | _GEN_0 & ~(A[1])
    | _GEN_0 & B[0] & ~(A[0]);	// file.cleaned.mlir:4:10, :6:10, :9:10, :11:10, :13:10, :15:11, :22:11, :23:11, :24:11, :25:11, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :38:5
  assign EQ = (A[0] ^ ~(B[0])) & (A[1] ^ ~(B[1])) & (A[2] ^ ~(B[2]));	// file.cleaned.mlir:4:10, :6:10, :9:10, :11:10, :13:10, :15:11, :34:11, :35:11, :36:11, :37:11, :38:5
endmodule

