// Generated by CIRCT unknown git version
module Anti_jitter(	// file.cleaned.mlir:2:3
  input        clk,	// file.cleaned.mlir:2:29
  input  [3:0] button,	// file.cleaned.mlir:2:43
  input  [7:0] SW,	// file.cleaned.mlir:2:60
  output [3:0] button_out,	// file.cleaned.mlir:2:74
               button_pulse,	// file.cleaned.mlir:2:95
  output [7:0] SW_OK,	// file.cleaned.mlir:2:118
  output       rst	// file.cleaned.mlir:2:134
);

  assign button_out = 4'h0;	// file.cleaned.mlir:3:14, :6:5
  assign button_pulse = 4'h0;	// file.cleaned.mlir:3:14, :6:5
  assign SW_OK = 8'h0;	// file.cleaned.mlir:4:14, :6:5
  assign rst = 1'h0;	// file.cleaned.mlir:5:14, :6:5
endmodule

