// Generated by CIRCT unknown git version
module altera_dpram(	// file.cleaned.mlir:2:3
  input  [11:0] address_a,	// file.cleaned.mlir:2:30
                address_b,	// file.cleaned.mlir:2:51
  input         clock_a,	// file.cleaned.mlir:2:72
                clock_b,	// file.cleaned.mlir:2:90
  input  [31:0] data_a,	// file.cleaned.mlir:2:108
                data_b,	// file.cleaned.mlir:2:126
  input         wren_a,	// file.cleaned.mlir:2:144
                wren_b,	// file.cleaned.mlir:2:161
  output [31:0] q_a,	// file.cleaned.mlir:2:179
                q_b	// file.cleaned.mlir:2:194
);

  assign q_a = 32'h0;	// file.cleaned.mlir:3:15, :4:5
  assign q_b = 32'h0;	// file.cleaned.mlir:3:15, :4:5
endmodule

