// Generated by CIRCT unknown git version
module transmission_gate_oneway(	// file.cleaned.mlir:2:3
  input  b,	// file.cleaned.mlir:2:42
         c,	// file.cleaned.mlir:2:54
  output a	// file.cleaned.mlir:2:67
);

  assign a = c & b;	// file.cleaned.mlir:3:10, :4:5
endmodule

