// Generated by CIRCT unknown git version
module riscv_ram32(	// file.cleaned.mlir:2:3
  input  [7:0]  address,	// file.cleaned.mlir:2:29
  input  [3:0]  byteena,	// file.cleaned.mlir:2:47
  input         clock,	// file.cleaned.mlir:2:65
  input  [31:0] data,	// file.cleaned.mlir:2:81
  input         rden,	// file.cleaned.mlir:2:97
                wren,	// file.cleaned.mlir:2:112
  output [31:0] q	// file.cleaned.mlir:2:128
);

  assign q = 32'h0;	// file.cleaned.mlir:3:15, :4:5
endmodule

