// Generated by CIRCT unknown git version
module top_module(	// file.cleaned.mlir:2:3
  input  [31:0] a,	// file.cleaned.mlir:2:28
                b,	// file.cleaned.mlir:2:41
  output [31:0] sum	// file.cleaned.mlir:2:55
);

  wire [15:0] _GEN;	// file.cleaned.mlir:16:10
  wire [15:0] _num01_sum;	// file.cleaned.mlir:15:31
  wire [15:0] _num0_sum;	// file.cleaned.mlir:14:29
  wire [15:0] _adder_sum;	// file.cleaned.mlir:11:31
  wire        _adder_cout;	// file.cleaned.mlir:11:31
  assign _GEN = _adder_cout ? _num01_sum : _num0_sum;	// file.cleaned.mlir:11:31, :14:29, :15:31, :16:10
  add16 adder (	// file.cleaned.mlir:11:31
    .a    (a[15:0]),	// file.cleaned.mlir:9:10
    .b    (b[15:0]),	// file.cleaned.mlir:10:10
    .cin  (1'h0),	// file.cleaned.mlir:4:14
    .sum  (_adder_sum),
    .cout (_adder_cout)
  );	// file.cleaned.mlir:11:31
  add16 num0 (	// file.cleaned.mlir:14:29
    .a    (a[31:16]),	// file.cleaned.mlir:12:10
    .b    (b[31:16]),	// file.cleaned.mlir:13:10
    .cin  (1'h0),	// file.cleaned.mlir:4:14
    .sum  (_num0_sum),
    .cout (/* unused */)
  );	// file.cleaned.mlir:14:29
  add16 num01 (	// file.cleaned.mlir:15:31
    .a    (a[31:16]),	// file.cleaned.mlir:12:10
    .b    (b[31:16]),	// file.cleaned.mlir:13:10
    .cin  (1'h1),	// file.cleaned.mlir:3:13
    .sum  (_num01_sum),
    .cout (/* unused */)
  );	// file.cleaned.mlir:15:31
  assign sum = {_GEN, 16'h0} | {16'h0, _adder_sum};	// file.cleaned.mlir:5:15, :6:10, :7:10, :8:10, :11:31, :16:10, :17:5
endmodule

module add16(	// file.cleaned.mlir:19:3
  input  [15:0] a,	// file.cleaned.mlir:19:31
                b,	// file.cleaned.mlir:19:44
  input         cin,	// file.cleaned.mlir:19:57
  output [15:0] sum,	// file.cleaned.mlir:19:72
  output        cout	// file.cleaned.mlir:19:87
);

  assign sum = 16'h0;	// file.cleaned.mlir:20:15, :22:5
  assign cout = 1'h0;	// file.cleaned.mlir:21:14, :22:5
endmodule

