// Generated by CIRCT unknown git version
module add12se_54E(	// file.cleaned.mlir:2:3
  input  [11:0] A,	// file.cleaned.mlir:2:29
                B,	// file.cleaned.mlir:2:42
  output [12:0] O	// file.cleaned.mlir:2:56
);

  wire sig_103;	// file.cleaned.mlir:114:11
  wire sig_102;	// file.cleaned.mlir:113:11
  wire sig_101;	// file.cleaned.mlir:112:11
  wire sig_100;	// file.cleaned.mlir:111:11
  wire sig_99;	// file.cleaned.mlir:110:11
  wire sig_98;	// file.cleaned.mlir:109:11
  wire sig_97;	// file.cleaned.mlir:108:11
  wire sig_57;	// file.cleaned.mlir:90:11
  wire _A_5;	// file.cleaned.mlir:88:11
  wire sig_38;	// file.cleaned.mlir:70:11
  wire _B_5;	// file.cleaned.mlir:63:11
  assign _B_5 = B[5];	// file.cleaned.mlir:63:11
  wire sig_37 = A[6] ^ B[6];	// file.cleaned.mlir:64:11, :65:11, :67:11
  assign sig_38 = A[7] & B[7];	// file.cleaned.mlir:68:11, :69:11, :70:11
  wire sig_39 = A[7] ^ B[7];	// file.cleaned.mlir:68:11, :69:11, :71:11
  wire sig_41 = A[8] ^ B[8];	// file.cleaned.mlir:72:11, :73:11, :75:11
  wire sig_42 = A[9] & B[9];	// file.cleaned.mlir:76:11, :77:11, :78:11
  wire sig_43 = A[9] ^ B[9];	// file.cleaned.mlir:76:11, :77:11, :79:11
  wire sig_45 = A[10] ^ B[10];	// file.cleaned.mlir:80:11, :81:11, :83:11
  wire sig_48 = A[11] ^ B[11];	// file.cleaned.mlir:84:11, :85:11, :87:11
  assign _A_5 = A[5];	// file.cleaned.mlir:88:11
  assign sig_57 = A[6] & B[6] | sig_37 & _A_5;	// file.cleaned.mlir:64:11, :65:11, :66:11, :67:11, :88:11, :89:11, :90:11
  wire sig_59 = sig_41 & sig_39;	// file.cleaned.mlir:71:11, :75:11, :92:11
  wire sig_60 = A[8] & B[8] | sig_41 & sig_38;	// file.cleaned.mlir:70:11, :72:11, :73:11, :74:11, :75:11, :91:11, :93:11
  wire sig_62 = sig_45 & sig_43;	// file.cleaned.mlir:79:11, :83:11, :95:11
  wire sig_75 =
    A[10] & B[10] | sig_45 & sig_42 | sig_62 & sig_60 | sig_62 & sig_59 & sig_57;	// file.cleaned.mlir:78:11, :80:11, :81:11, :82:11, :83:11, :90:11, :92:11, :93:11, :94:11, :95:11, :96:11, :97:11, :98:11
  wire sig_79 = sig_60 | sig_59 & sig_57;	// file.cleaned.mlir:90:11, :92:11, :93:11, :99:11, :100:11
  assign sig_97 = sig_37 ^ _A_5;	// file.cleaned.mlir:67:11, :88:11, :108:11
  assign sig_98 = sig_39 ^ sig_57;	// file.cleaned.mlir:71:11, :90:11, :109:11
  assign sig_99 = sig_41 ^ (sig_38 | sig_39 & sig_57);	// file.cleaned.mlir:70:11, :71:11, :75:11, :90:11, :101:11, :102:11, :110:11
  assign sig_100 = sig_43 ^ sig_79;	// file.cleaned.mlir:79:11, :100:11, :111:11
  assign sig_101 = sig_45 ^ (sig_42 | sig_43 & sig_79);	// file.cleaned.mlir:78:11, :79:11, :83:11, :100:11, :103:11, :104:11, :112:11
  assign sig_102 = sig_48 ^ sig_75;	// file.cleaned.mlir:87:11, :98:11, :113:11
  assign sig_103 = sig_48 ^ (A[11] & B[11] | sig_48 & sig_75);	// file.cleaned.mlir:84:11, :85:11, :86:11, :87:11, :98:11, :105:11, :106:11, :114:11
  assign O =
    {sig_103, 12'h0}
    | ({1'h0, sig_102, 11'h0}
       | ({2'h0, sig_101, 10'h0}
          | ({3'h0, sig_100, 9'h0}
             | ({4'h0, sig_99, 8'h0}
                | ({5'h0, sig_98, 7'h0}
                   | ({6'h0, sig_97, 6'h0}
                      | ({7'h0, _B_5, 5'h0}
                         | ({8'h0, ~_A_5, 4'h0}
                            | ({9'h0, ~_A_5, 3'h0}
                               | ({10'h0, sig_57, 2'h0}
                                  | ({11'h0, ~_A_5, 1'h0} | {12'h0, sig_38}) & 13'h1FFB)
                               & 13'h1FF7) & 13'h1FEF) & 13'h1FDF) & 13'h1FBF) & 13'h1F7F)
                & 13'h1EFF) & 13'h1DFF) & 13'h1BFF) & 13'h17FF) & 13'hFFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:15, :11:14, :12:15, :13:14, :15:18, :16:19, :17:19, :18:18, :19:18, :20:18, :21:17, :22:17, :23:17, :24:16, :25:16, :26:15, :27:10, :28:10, :29:10, :30:10, :31:10, :32:10, :33:10, :34:10, :35:10, :36:10, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :70:11, :88:11, :90:11, :107:11, :108:11, :109:11, :110:11, :111:11, :112:11, :113:11, :114:11, :115:5
endmodule

