// Generated by CIRCT unknown git version
module add12u_0FY(	// file.cleaned.mlir:2:3
  input  [11:0] A,	// file.cleaned.mlir:2:28
                B,	// file.cleaned.mlir:2:41
  output [12:0] O	// file.cleaned.mlir:2:55
);

  wire        _GEN;	// file.cleaned.mlir:98:11
  wire        _GEN_0;	// file.cleaned.mlir:97:11
  wire        _B_5;	// file.cleaned.mlir:96:11
  wire        _B_6;	// file.cleaned.mlir:95:11
  wire        _GEN_1;	// file.cleaned.mlir:94:11
  wire        _GEN_2;	// file.cleaned.mlir:93:11
  wire        _GEN_3;	// file.cleaned.mlir:86:11
  wire        _GEN_4;	// file.cleaned.mlir:79:11
  wire        _B_9;	// file.cleaned.mlir:75:11
  wire        _GEN_5;	// file.cleaned.mlir:72:11
  wire        _GEN_6;	// file.cleaned.mlir:65:11
  wire        _A_5;	// file.cleaned.mlir:58:11
  wire [12:0] _GEN_7 =
    {_GEN_1, 12'h0}
    | ({1'h0, _GEN_2, 11'h0}
       | ({2'h0, _GEN_3, 10'h0}
          | ({3'h0, _GEN, 9'h0}
             | ({4'h0, _GEN_5, 8'h0}
                | ({5'h0, _GEN_0, 7'h0}
                   | ({6'h0, _B_5, 6'h0}
                      | ({7'h0, _A_5, 5'h0}
                         | ({8'h0, _B_6, 4'h0}
                            | ({9'h0, _GEN_4, 3'h0}
                               | ({10'h0, _B_9, 2'h0} | {12'h0, _GEN_6}) & 13'h1FF7)
                            & 13'h1FEF) & 13'h1FDF) & 13'h1FBF) & 13'h1F7F) & 13'h1EFF)
             & 13'h1DFF) & 13'h1BFF) & 13'h17FF) & 13'hFFF;	// file.cleaned.mlir:3:14, :4:15, :5:14, :6:14, :7:14, :8:14, :9:14, :10:14, :11:14, :12:15, :13:14, :14:18, :15:19, :16:19, :17:18, :18:18, :19:18, :20:17, :21:17, :22:17, :23:16, :24:15, :25:10, :26:10, :27:10, :28:10, :29:10, :30:10, :31:10, :32:10, :33:10, :34:10, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :65:11, :72:11, :75:11, :79:11, :86:11, :93:11, :94:11, :95:11, :96:11, :97:11, :98:11
  assign _A_5 = A[5];	// file.cleaned.mlir:58:11
  wire        sig_56 = A[7] ^ B[7];	// file.cleaned.mlir:59:11, :60:11, :61:11
  assign _GEN_6 = sig_56 ^ A[6];	// file.cleaned.mlir:61:11, :63:11, :65:11
  wire        sig_60 = A[7] & B[7] | sig_56 & A[6];	// file.cleaned.mlir:59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :66:11
  wire        sig_61 = A[8] ^ B[8];	// file.cleaned.mlir:67:11, :68:11, :69:11
  assign _GEN_5 = sig_61 ^ sig_60;	// file.cleaned.mlir:66:11, :69:11, :72:11
  wire        sig_65 = A[8] & B[8] | sig_61 & sig_60;	// file.cleaned.mlir:66:11, :67:11, :68:11, :69:11, :70:11, :71:11, :73:11
  assign _B_9 = B[9];	// file.cleaned.mlir:75:11
  wire        sig_66 = A[9] ^ _B_9;	// file.cleaned.mlir:74:11, :75:11, :76:11
  assign _GEN_4 = sig_66 ^ sig_65;	// file.cleaned.mlir:73:11, :76:11, :79:11
  wire        sig_70 = A[9] & _B_9 | sig_66 & sig_65;	// file.cleaned.mlir:73:11, :74:11, :75:11, :76:11, :77:11, :78:11, :80:11
  wire        sig_71 = A[10] ^ B[10];	// file.cleaned.mlir:81:11, :82:11, :83:11
  assign _GEN_3 = sig_71 ^ sig_70;	// file.cleaned.mlir:80:11, :83:11, :86:11
  wire        sig_75 = A[10] & B[10] | sig_71 & sig_70;	// file.cleaned.mlir:80:11, :81:11, :82:11, :83:11, :84:11, :85:11, :87:11
  wire        sig_76 = A[11] ^ B[11];	// file.cleaned.mlir:88:11, :89:11, :90:11
  assign _GEN_2 = sig_76 ^ sig_75;	// file.cleaned.mlir:87:11, :90:11, :93:11
  assign _GEN_1 = A[11] & B[11] | sig_76 & sig_75;	// file.cleaned.mlir:87:11, :88:11, :89:11, :90:11, :91:11, :92:11, :94:11
  assign _B_6 = B[6];	// file.cleaned.mlir:95:11
  assign _B_5 = B[5];	// file.cleaned.mlir:96:11
  assign _GEN_0 = _GEN_7[0];	// file.cleaned.mlir:57:11, :97:11
  assign _GEN = _GEN_7[3];	// file.cleaned.mlir:57:11, :98:11
  assign O = _GEN_7;	// file.cleaned.mlir:57:11, :99:5
endmodule

