// Generated by CIRCT unknown git version
module add8se_8XS(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:28
               B,	// file.cleaned.mlir:2:40
  output [8:0] O	// file.cleaned.mlir:2:53
);

  wire _A_1;	// file.cleaned.mlir:43:11
  wire _B_3;	// file.cleaned.mlir:42:11
  wire _A_5;	// file.cleaned.mlir:41:11
  wire _B_6;	// file.cleaned.mlir:40:11
  wire _A_6;	// file.cleaned.mlir:39:11
  wire _A_7;	// file.cleaned.mlir:38:11
  assign _A_7 = A[7];	// file.cleaned.mlir:38:11
  assign _A_6 = A[6];	// file.cleaned.mlir:39:11
  assign _B_6 = B[6];	// file.cleaned.mlir:40:11
  assign _A_5 = A[5];	// file.cleaned.mlir:41:11
  assign _B_3 = B[3];	// file.cleaned.mlir:42:11
  assign _A_1 = A[1];	// file.cleaned.mlir:43:11
  assign O =
    {_A_7, 8'h0}
    | ({1'h0, _A_7, 7'h0}
       | ({2'h0, _A_6, 6'h0}
          | ({3'h0, _B_6, 5'h0}
             | ({4'h0, _A_5, 4'h0}
                | ({5'h0, _B_3, 3'h0} | ({6'h0, _A_5, 2'h0} | {7'h0, _A_1, 1'h0})
                   & 9'h1F7) & 9'h1EF) & 9'h1DF) & 9'h1BF) & 9'h17F) & 9'hFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:16, :10:17, :11:16, :12:16, :13:16, :14:15, :15:14, :16:14, :17:10, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:5
endmodule

