// Generated by CIRCT unknown git version
module add8se_7A2(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:28
               B,	// file.cleaned.mlir:2:40
  output [8:0] O	// file.cleaned.mlir:2:53
);

  wire sig_54;	// file.cleaned.mlir:95:11
  wire sig_51;	// file.cleaned.mlir:93:11
  wire sig_46;	// file.cleaned.mlir:86:11
  wire sig_41;	// file.cleaned.mlir:79:11
  wire sig_36;	// file.cleaned.mlir:72:11
  wire sig_31;	// file.cleaned.mlir:65:11
  wire sig_26;	// file.cleaned.mlir:58:11
  wire sig_21;	// file.cleaned.mlir:51:11
  wire sig_16;	// file.cleaned.mlir:44:11
  assign sig_16 = A[0] ^ B[0];	// file.cleaned.mlir:42:11, :43:11, :44:11
  wire sig_17 = A[0] & B[0];	// file.cleaned.mlir:42:11, :43:11, :45:11
  wire sig_18 = A[1] ^ B[1];	// file.cleaned.mlir:46:11, :47:11, :48:11
  assign sig_21 = sig_18 ^ sig_17;	// file.cleaned.mlir:45:11, :48:11, :51:11
  wire sig_22 = A[1] & B[1] | sig_18 & sig_17;	// file.cleaned.mlir:45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :52:11
  wire sig_23 = A[2] ^ B[2];	// file.cleaned.mlir:53:11, :54:11, :55:11
  assign sig_26 = sig_23 ^ sig_22;	// file.cleaned.mlir:52:11, :55:11, :58:11
  wire sig_27 = A[2] & B[2] | sig_23 & sig_22;	// file.cleaned.mlir:52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :59:11
  wire sig_28 = A[3] ^ B[3];	// file.cleaned.mlir:60:11, :61:11, :62:11
  assign sig_31 = sig_28 ^ sig_27;	// file.cleaned.mlir:59:11, :62:11, :65:11
  wire sig_32 = A[3] & B[3] | sig_28 & sig_27;	// file.cleaned.mlir:59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :66:11
  wire sig_33 = A[4] ^ B[4];	// file.cleaned.mlir:67:11, :68:11, :69:11
  assign sig_36 = sig_33 ^ sig_32;	// file.cleaned.mlir:66:11, :69:11, :72:11
  wire sig_37 = A[4] & B[4] | sig_33 & sig_32;	// file.cleaned.mlir:66:11, :67:11, :68:11, :69:11, :70:11, :71:11, :73:11
  wire sig_38 = A[5] ^ B[5];	// file.cleaned.mlir:74:11, :75:11, :76:11
  assign sig_41 = sig_38 ^ sig_37;	// file.cleaned.mlir:73:11, :76:11, :79:11
  wire sig_42 = A[5] & B[5] | sig_38 & sig_37;	// file.cleaned.mlir:73:11, :74:11, :75:11, :76:11, :77:11, :78:11, :80:11
  wire sig_43 = A[6] ^ B[6];	// file.cleaned.mlir:81:11, :82:11, :83:11
  assign sig_46 = sig_43 ^ sig_42;	// file.cleaned.mlir:80:11, :83:11, :86:11
  wire sig_47 = A[6] & B[6] | sig_43 & sig_42;	// file.cleaned.mlir:80:11, :81:11, :82:11, :83:11, :84:11, :85:11, :87:11
  wire sig_48 = A[7] ^ B[7];	// file.cleaned.mlir:88:11, :89:11, :90:11
  assign sig_51 = sig_48 ^ sig_47;	// file.cleaned.mlir:87:11, :90:11, :93:11
  assign sig_54 = sig_48 ^ (A[7] & B[7] | sig_48 & sig_47);	// file.cleaned.mlir:87:11, :88:11, :89:11, :90:11, :91:11, :92:11, :94:11, :95:11
  assign O =
    {sig_54, 8'h0}
    | ({1'h0, sig_51, 7'h0}
       | ({2'h0, sig_46, 6'h0}
          | ({3'h0, sig_41, 5'h0}
             | ({4'h0, sig_36, 4'h0}
                | ({5'h0, sig_31, 3'h0}
                   | ({6'h0, sig_26, 2'h0} | ({7'h0, sig_21, 1'h0} | {8'h0, sig_16})
                      & 9'h1FB) & 9'h1F7) & 9'h1EF) & 9'h1DF) & 9'h1BF) & 9'h17F) & 9'hFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:16, :11:17, :12:16, :13:16, :14:16, :15:15, :16:15, :17:14, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :44:11, :51:11, :58:11, :65:11, :72:11, :79:11, :86:11, :93:11, :95:11, :96:5
endmodule

