// Generated by CIRCT unknown git version
module add8se_8YC(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:28
               B,	// file.cleaned.mlir:2:40
  output [8:0] O	// file.cleaned.mlir:2:53
);

  wire sig_84;	// file.cleaned.mlir:116:11
  wire sig_83;	// file.cleaned.mlir:115:11
  wire sig_82;	// file.cleaned.mlir:114:11
  wire sig_81;	// file.cleaned.mlir:113:11
  wire sig_80;	// file.cleaned.mlir:112:11
  wire sig_79;	// file.cleaned.mlir:111:11
  wire sig_78;	// file.cleaned.mlir:110:11
  wire sig_77;	// file.cleaned.mlir:109:11
  wire sig_17;	// file.cleaned.mlir:46:11
  wire sig_16 = A[0] & B[0];	// file.cleaned.mlir:43:11, :44:11, :45:11
  assign sig_17 = ~sig_16;	// file.cleaned.mlir:45:11, :46:11
  wire sig_18 = A[1] & B[1];	// file.cleaned.mlir:47:11, :48:11, :49:11
  wire sig_19 = A[1] ^ B[1];	// file.cleaned.mlir:47:11, :48:11, :50:11
  wire sig_20 = A[2] & B[2];	// file.cleaned.mlir:51:11, :52:11, :53:11
  wire sig_21 = A[2] ^ B[2];	// file.cleaned.mlir:51:11, :52:11, :54:11
  wire sig_22 = A[3] & B[3];	// file.cleaned.mlir:55:11, :56:11, :57:11
  wire sig_23 = A[3] ^ B[3];	// file.cleaned.mlir:55:11, :56:11, :58:11
  wire sig_24 = A[4] & B[4];	// file.cleaned.mlir:59:11, :60:11, :61:11
  wire sig_25 = A[4] ^ B[4];	// file.cleaned.mlir:59:11, :60:11, :62:11
  wire sig_26 = A[5] & B[5];	// file.cleaned.mlir:63:11, :64:11, :65:11
  wire sig_27 = A[5] ^ B[5];	// file.cleaned.mlir:63:11, :64:11, :66:11
  wire sig_28 = A[6] & B[6];	// file.cleaned.mlir:67:11, :68:11, :69:11
  wire sig_29 = A[6] ^ B[6];	// file.cleaned.mlir:67:11, :68:11, :70:11
  wire sig_32 = A[7] ^ B[7];	// file.cleaned.mlir:71:11, :72:11, :74:11
  wire sig_34 = sig_18 | sig_19 & sig_16;	// file.cleaned.mlir:45:11, :49:11, :50:11, :75:11, :76:11
  wire sig_36 = sig_21 & sig_19;	// file.cleaned.mlir:50:11, :54:11, :78:11
  wire sig_37 = sig_20 | sig_21 & sig_18;	// file.cleaned.mlir:49:11, :53:11, :54:11, :77:11, :79:11
  wire sig_39 = sig_23 & sig_21;	// file.cleaned.mlir:54:11, :58:11, :81:11
  wire sig_40 = sig_22 | sig_23 & sig_20;	// file.cleaned.mlir:53:11, :57:11, :58:11, :80:11, :82:11
  wire sig_42 = sig_25 & sig_23;	// file.cleaned.mlir:58:11, :62:11, :84:11
  wire sig_43 = sig_24 | sig_25 & sig_22;	// file.cleaned.mlir:57:11, :61:11, :62:11, :83:11, :85:11
  wire sig_45 = sig_27 & sig_25;	// file.cleaned.mlir:62:11, :66:11, :87:11
  wire sig_46 = sig_26 | sig_27 & sig_24;	// file.cleaned.mlir:61:11, :65:11, :66:11, :86:11, :88:11
  wire sig_48 = sig_29 & sig_27;	// file.cleaned.mlir:66:11, :70:11, :90:11
  wire sig_51 = sig_32 & sig_29;	// file.cleaned.mlir:70:11, :74:11, :92:11
  wire sig_54 = sig_37 | sig_36 & sig_16;	// file.cleaned.mlir:45:11, :78:11, :79:11, :93:11, :94:11
  wire sig_56 = sig_40 | sig_39 & sig_34;	// file.cleaned.mlir:76:11, :81:11, :82:11, :95:11, :96:11
  assign sig_77 = sig_19 ^ sig_16;	// file.cleaned.mlir:45:11, :50:11, :109:11
  assign sig_78 = sig_21 ^ sig_34;	// file.cleaned.mlir:54:11, :76:11, :110:11
  assign sig_79 = sig_23 ^ sig_54;	// file.cleaned.mlir:58:11, :94:11, :111:11
  assign sig_80 = sig_25 ^ sig_56;	// file.cleaned.mlir:62:11, :96:11, :112:11
  assign sig_81 = sig_27 ^ (sig_43 | sig_42 & sig_37 | sig_42 & sig_36 & sig_16);	// file.cleaned.mlir:45:11, :66:11, :78:11, :79:11, :84:11, :85:11, :97:11, :101:11, :102:11, :113:11
  assign sig_82 = sig_29 ^ (sig_46 | sig_45 & sig_40 | sig_45 & sig_39 & sig_34);	// file.cleaned.mlir:70:11, :76:11, :81:11, :82:11, :87:11, :88:11, :98:11, :103:11, :104:11, :114:11
  assign sig_83 =
    sig_32 ^ (sig_28 | sig_29 & sig_26 | sig_48 & sig_43 | sig_48 & sig_42 & sig_54);	// file.cleaned.mlir:65:11, :69:11, :70:11, :74:11, :84:11, :85:11, :89:11, :90:11, :94:11, :99:11, :105:11, :106:11, :115:11
  assign sig_84 =
    sig_32 ^ (A[7] & B[7] | sig_32 & sig_28 | sig_51 & sig_46 | sig_51 & sig_45 & sig_56);	// file.cleaned.mlir:69:11, :71:11, :72:11, :73:11, :74:11, :87:11, :88:11, :91:11, :92:11, :96:11, :100:11, :107:11, :108:11, :116:11
  assign O =
    {sig_84, 8'h0}
    | ({1'h0, sig_83, 7'h0}
       | ({2'h0, sig_82, 6'h0}
          | ({3'h0, sig_81, 5'h0}
             | ({4'h0, sig_80, 4'h0}
                | ({5'h0, sig_79, 3'h0}
                   | ({6'h0, sig_78, 2'h0} | ({7'h0, sig_77, 1'h0} | {8'h0, sig_17})
                      & 9'h1FB) & 9'h1F7) & 9'h1EF) & 9'h1DF) & 9'h1BF) & 9'h17F) & 9'hFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :11:16, :12:17, :13:16, :14:16, :15:16, :16:15, :17:15, :18:14, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:10, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :46:11, :109:11, :110:11, :111:11, :112:11, :113:11, :114:11, :115:11, :116:11, :117:5
endmodule

