// Generated by CIRCT unknown git version
module add8se_7J7(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:28
               B,	// file.cleaned.mlir:2:40
  output [8:0] O	// file.cleaned.mlir:2:53
);

  wire sig_66;	// file.cleaned.mlir:83:11
  wire sig_65;	// file.cleaned.mlir:82:11
  wire sig_64;	// file.cleaned.mlir:81:11
  wire sig_63;	// file.cleaned.mlir:80:11
  wire sig_62;	// file.cleaned.mlir:79:11
  wire sig_59;	// file.cleaned.mlir:78:11
  wire sig_52;	// file.cleaned.mlir:73:11
  wire sig_23;	// file.cleaned.mlir:50:11
  wire sig_22 = A[3] & B[3];	// file.cleaned.mlir:47:11, :48:11, :49:11
  assign sig_23 = A[3] ^ B[3];	// file.cleaned.mlir:47:11, :48:11, :50:11
  wire sig_25 = A[4] ^ B[4];	// file.cleaned.mlir:51:11, :52:11, :54:11
  wire sig_26 = A[5] & B[5];	// file.cleaned.mlir:55:11, :56:11, :57:11
  wire sig_27 = A[5] ^ B[5];	// file.cleaned.mlir:55:11, :56:11, :58:11
  wire sig_29 = A[6] ^ B[6];	// file.cleaned.mlir:59:11, :60:11, :62:11
  wire sig_32 = A[7] ^ B[7];	// file.cleaned.mlir:63:11, :64:11, :66:11
  wire sig_38 = A[4] & B[4] | sig_25 & sig_22;	// file.cleaned.mlir:49:11, :51:11, :52:11, :53:11, :54:11, :67:11, :68:11
  wire sig_48 = A[6] & B[6] | sig_29 & sig_27 & sig_38 | sig_29 & sig_26;	// file.cleaned.mlir:57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :68:11, :69:11, :70:11, :71:11
  assign sig_52 = B[2] | A[2];	// file.cleaned.mlir:43:11, :72:11, :73:11
  assign sig_59 = B[1] & ~(B[2]) ^ B[2];	// file.cleaned.mlir:43:11, :44:11, :45:11, :46:11, :78:11
  assign sig_62 = sig_25 ^ sig_22;	// file.cleaned.mlir:49:11, :54:11, :79:11
  assign sig_63 = sig_27 ^ sig_38;	// file.cleaned.mlir:58:11, :68:11, :80:11
  assign sig_64 = sig_29 ^ (sig_26 | sig_27 & sig_38);	// file.cleaned.mlir:57:11, :58:11, :62:11, :68:11, :74:11, :75:11, :81:11
  assign sig_65 = sig_32 ^ sig_48;	// file.cleaned.mlir:66:11, :71:11, :82:11
  assign sig_66 = sig_32 ^ (A[7] & B[7] | sig_32 & sig_48);	// file.cleaned.mlir:63:11, :64:11, :65:11, :66:11, :71:11, :76:11, :77:11, :83:11
  assign O =
    {sig_66, 8'h0}
    | ({1'h0, sig_65, 7'h0}
       | ({2'h0, sig_64, 6'h0}
          | ({3'h0, sig_63, 5'h0}
             | ({4'h0, sig_62, 4'h0}
                | ({5'h0, sig_23, 3'h0}
                   | ({6'h0, sig_52, 2'h0} | ({7'h0, sig_59, 1'h0} | {8'h0, sig_52})
                      & 9'h1FB) & 9'h1F7) & 9'h1EF) & 9'h1DF) & 9'h1BF) & 9'h17F) & 9'hFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :11:16, :12:17, :13:16, :14:16, :15:16, :16:15, :17:15, :18:14, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:10, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :50:11, :73:11, :78:11, :79:11, :80:11, :81:11, :82:11, :83:11, :84:5
endmodule

