// Generated by CIRCT unknown git version
module add8se_8UN(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:28
               B,	// file.cleaned.mlir:2:40
  output [8:0] O	// file.cleaned.mlir:2:53
);

  wire _A_4;	// file.cleaned.mlir:54:11
  wire _B_6;	// file.cleaned.mlir:53:11
  wire sig_54;	// file.cleaned.mlir:52:11
  wire sig_51;	// file.cleaned.mlir:50:11
  wire sig_46;	// file.cleaned.mlir:44:11
  assign sig_46 = ~(A[6]);	// file.cleaned.mlir:43:11, :44:11
  wire sig_53 = A[7] ^ B[7];	// file.cleaned.mlir:45:11, :46:11, :47:11
  assign sig_51 = sig_53 ^ A[6];	// file.cleaned.mlir:43:11, :47:11, :50:11
  assign sig_54 = sig_53 ^ (A[7] & B[7] | sig_53 & A[6]);	// file.cleaned.mlir:43:11, :45:11, :46:11, :47:11, :48:11, :49:11, :51:11, :52:11
  assign _B_6 = B[6];	// file.cleaned.mlir:53:11
  assign _A_4 = A[4];	// file.cleaned.mlir:54:11
  assign O =
    {sig_54, 8'h0}
    | ({1'h0, sig_51, 7'h0}
       | ({2'h0, sig_46, 6'h0}
          | ({3'h0, _B_6, 5'h0}
             | ({4'h0, _B_6, 4'h0}
                | ({5'h0, _A_4, 3'h0}
                   | ({6'h0, _B_6, 2'h0} | ({7'h0, sig_51, 1'h0} | {8'h0, sig_54})
                      & 9'h1FB) & 9'h1F7) & 9'h1EF) & 9'h1DF) & 9'h1BF) & 9'h17F) & 9'hFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :11:16, :12:17, :13:16, :14:16, :15:16, :16:15, :17:15, :18:14, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:10, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :44:11, :50:11, :52:11, :53:11, :54:11, :55:5
endmodule

