// Generated by CIRCT unknown git version
module add8s_6H2(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:27
               B,	// file.cleaned.mlir:2:39
  output [7:0] O	// file.cleaned.mlir:2:52
);

  wire _A_3;	// file.cleaned.mlir:62:11
  wire _B_3;	// file.cleaned.mlir:61:11
  wire sig_61;	// file.cleaned.mlir:60:11
  wire sig_60;	// file.cleaned.mlir:59:11
  wire sig_59;	// file.cleaned.mlir:58:11
  wire sig_25;	// file.cleaned.mlir:42:11
  assign sig_25 = A[4] ^ B[4];	// file.cleaned.mlir:39:11, :40:11, :42:11
  wire sig_26 = A[5] & B[5];	// file.cleaned.mlir:43:11, :44:11, :45:11
  wire sig_27 = A[5] ^ B[5];	// file.cleaned.mlir:43:11, :44:11, :46:11
  wire sig_29 = A[6] ^ B[6];	// file.cleaned.mlir:47:11, :48:11, :50:11
  wire sig_46 = A[4] & B[4] | sig_25 & B[7] & A[7];	// file.cleaned.mlir:37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :51:11, :52:11
  assign sig_59 = sig_27 ^ sig_46;	// file.cleaned.mlir:46:11, :52:11, :58:11
  assign sig_60 = sig_29 ^ (sig_26 | sig_27 & sig_46);	// file.cleaned.mlir:45:11, :46:11, :50:11, :52:11, :56:11, :57:11, :59:11
  assign sig_61 =
    A[7] ^ B[7] ^ (A[6] & B[6] | sig_29 & sig_26 | sig_29 & sig_27 & sig_46);	// file.cleaned.mlir:37:11, :38:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :52:11, :53:11, :54:11, :55:11, :60:11
  assign _B_3 = B[3];	// file.cleaned.mlir:61:11
  assign _A_3 = A[3];	// file.cleaned.mlir:62:11
  assign O =
    {sig_61, 7'h0}
    | ({1'h0, sig_60, 6'h0}
       | ({2'h0, sig_59, 5'h0}
          | ({3'h0, sig_25, 4'h0}
             | ({4'h0, _B_3, 3'h0}
                | ({5'h0, _A_3, 2'h0} | ({6'h0, _A_3, 1'h0} | {7'h0, _A_3}) & 8'hFB)
                & 8'hF7) & 8'hEF) & 8'hDF) & 8'hBF) & 8'h7F;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:16, :10:16, :11:16, :12:16, :13:15, :14:15, :15:14, :16:10, :17:10, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :42:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:5
endmodule

