// Generated by CIRCT unknown git version
module add8s_701(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:27
               B,	// file.cleaned.mlir:2:39
  output [7:0] O	// file.cleaned.mlir:2:52
);

  wire _A_0;	// file.cleaned.mlir:46:11
  wire _A_5;	// file.cleaned.mlir:45:11
  wire sig_60;	// file.cleaned.mlir:44:11
  wire _GEN;	// file.cleaned.mlir:41:11
  wire sig_33 = B[7] & A[7];	// file.cleaned.mlir:38:11, :39:11, :40:11
  assign _GEN = sig_33 | B[6] ^ ~(A[6]);	// file.cleaned.mlir:34:11, :35:11, :36:11, :40:11, :41:11
  assign sig_60 = (A[6] & B[6] | sig_33) ^ A[7] ^ B[7];	// file.cleaned.mlir:34:11, :35:11, :37:11, :38:11, :39:11, :40:11, :43:11, :44:11
  assign _A_5 = A[5];	// file.cleaned.mlir:45:11
  assign _A_0 = A[0];	// file.cleaned.mlir:46:11
  assign O =
    {sig_60, 7'h0}
    | ({1'h0, ~_GEN, 6'h0}
       | ({2'h0, _A_5, 5'h0}
          | ({3'h0, _A_0, 4'h0}
             | ({4'h0, ~_GEN, 3'h0} | ({6'h0, _A_0, 1'h0} | {7'h0, ~_GEN}) & 8'hF3)
             & 8'hEF) & 8'hDF) & 8'hBF) & 8'h7F;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:16, :8:14, :9:14, :11:16, :12:16, :13:16, :14:16, :15:14, :16:10, :17:10, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :41:11, :42:11, :44:11, :45:11, :46:11, :47:5
endmodule

