// Generated by CIRCT unknown git version
module add8s_6UN(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:27
               B,	// file.cleaned.mlir:2:39
  output [7:0] O	// file.cleaned.mlir:2:52
);

  wire _A_1;	// file.cleaned.mlir:81:11
  wire _B_1;	// file.cleaned.mlir:80:11
  wire sig_64;	// file.cleaned.mlir:79:11
  wire sig_63;	// file.cleaned.mlir:78:11
  wire sig_62;	// file.cleaned.mlir:77:11
  wire sig_61;	// file.cleaned.mlir:76:11
  wire sig_60;	// file.cleaned.mlir:75:11
  wire sig_22 = A[3] & B[3];	// file.cleaned.mlir:43:11, :44:11, :45:11
  wire sig_23 = A[3] ^ B[3];	// file.cleaned.mlir:43:11, :44:11, :46:11
  wire sig_25 = A[4] ^ B[4];	// file.cleaned.mlir:47:11, :48:11, :50:11
  wire sig_26 = A[5] & B[5];	// file.cleaned.mlir:51:11, :52:11, :53:11
  wire sig_27 = A[5] ^ B[5];	// file.cleaned.mlir:51:11, :52:11, :54:11
  wire sig_29 = A[6] ^ B[6];	// file.cleaned.mlir:55:11, :56:11, :58:11
  wire sig_36 = A[4] & B[4] | sig_25 & sig_22;	// file.cleaned.mlir:45:11, :47:11, :48:11, :49:11, :50:11, :60:11, :61:11
  wire sig_38 = sig_29 & sig_27;	// file.cleaned.mlir:54:11, :58:11, :63:11
  wire sig_43 = A[2] & B[2] | (A[2] | B[2]) & A[7] & B[7];	// file.cleaned.mlir:37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :59:11, :64:11
  wire sig_52 = sig_25 & sig_23 & sig_43;	// file.cleaned.mlir:46:11, :50:11, :64:11, :69:11
  assign sig_60 = sig_23 ^ sig_43;	// file.cleaned.mlir:46:11, :64:11, :75:11
  assign sig_61 = sig_25 ^ (sig_22 | sig_23 & sig_43);	// file.cleaned.mlir:45:11, :46:11, :50:11, :64:11, :67:11, :68:11, :76:11
  assign sig_62 = sig_27 ^ (sig_36 | sig_52);	// file.cleaned.mlir:54:11, :61:11, :69:11, :70:11, :77:11
  assign sig_63 = sig_29 ^ (sig_26 | sig_27 & sig_36 | sig_27 & sig_52);	// file.cleaned.mlir:53:11, :54:11, :58:11, :61:11, :65:11, :69:11, :71:11, :72:11, :78:11
  assign sig_64 =
    A[7] ^ B[7] ^ (A[6] & B[6] | sig_29 & sig_26 | sig_38 & sig_36 | sig_38 & sig_52);	// file.cleaned.mlir:37:11, :38:11, :53:11, :55:11, :56:11, :57:11, :58:11, :61:11, :62:11, :63:11, :66:11, :69:11, :73:11, :74:11, :79:11
  assign _B_1 = B[1];	// file.cleaned.mlir:80:11
  assign _A_1 = A[1];	// file.cleaned.mlir:81:11
  assign O =
    {sig_64, 7'h0}
    | ({1'h0, sig_63, 6'h0}
       | ({2'h0, sig_62, 5'h0}
          | ({3'h0, sig_61, 4'h0}
             | ({4'h0, sig_60, 3'h0}
                | ({5'h0, _B_1, 2'h0} | ({6'h0, _A_1, 1'h0} | {7'h0, sig_63}) & 8'hFB)
                & 8'hF7) & 8'hEF) & 8'hDF) & 8'hBF) & 8'h7F;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:16, :10:16, :11:16, :12:16, :13:15, :14:15, :15:14, :16:10, :17:10, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :75:11, :76:11, :77:11, :78:11, :79:11, :80:11, :81:11, :82:5
endmodule

