// Generated by CIRCT unknown git version
module add8u_2XT(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:27
               B,	// file.cleaned.mlir:2:39
  output [8:0] O	// file.cleaned.mlir:2:52
);

  wire n_213;	// file.cleaned.mlir:69:11
  wire n_211;	// file.cleaned.mlir:68:11
  wire n_209;	// file.cleaned.mlir:67:11
  wire n_193;	// file.cleaned.mlir:66:11
  wire n_11;	// file.cleaned.mlir:47:11
  wire n_5;	// file.cleaned.mlir:44:11
  wire n_4;	// file.cleaned.mlir:43:11
  wire n_0;	// file.cleaned.mlir:42:11
  assign n_0 = A[0];	// file.cleaned.mlir:42:11
  assign n_4 = A[4];	// file.cleaned.mlir:43:11
  assign n_5 = A[5];	// file.cleaned.mlir:44:11
  assign n_11 = B[3];	// file.cleaned.mlir:47:11
  wire n_37 = A[7] | B[7];	// file.cleaned.mlir:46:11, :51:11, :52:11
  wire n_38 = n_5 ^ B[5];	// file.cleaned.mlir:44:11, :49:11, :53:11
  wire n_40 = n_5 & B[5];	// file.cleaned.mlir:44:11, :49:11, :54:11
  wire n_42 = A[6] ^ B[6];	// file.cleaned.mlir:45:11, :50:11, :55:11
  wire n_44 = A[6] & B[6];	// file.cleaned.mlir:45:11, :50:11, :56:11
  wire n_116 = n_38 & B[4];	// file.cleaned.mlir:48:11, :53:11, :58:11
  wire n_144 = n_42 & n_116;	// file.cleaned.mlir:55:11, :58:11, :60:11
  wire n_147 = n_42 & n_40;	// file.cleaned.mlir:54:11, :55:11, :61:11
  assign n_193 = A[7] & B[7] | n_37 & n_44 | n_37 & n_147 | n_37 & n_144;	// file.cleaned.mlir:46:11, :51:11, :52:11, :56:11, :57:11, :60:11, :61:11, :63:11, :64:11, :65:11, :66:11
  assign n_209 = n_38 ^ B[4];	// file.cleaned.mlir:48:11, :53:11, :67:11
  assign n_211 = n_42 ^ (n_40 | n_116);	// file.cleaned.mlir:54:11, :55:11, :58:11, :59:11, :68:11
  assign n_213 = A[7] ^ B[7] ^ (n_44 | n_147 | n_144);	// file.cleaned.mlir:46:11, :51:11, :56:11, :60:11, :61:11, :62:11, :69:11
  assign O =
    {n_193, 8'h0}
    | ({1'h0, n_213, 7'h0}
       | ({2'h0, n_211, 6'h0}
          | ({3'h0, n_209, 5'h0}
             | ({4'h0, n_4, 4'h0}
                | ({5'h0, n_11, 3'h0}
                   | ({6'h0, n_5, 2'h0} | ({7'h0, n_5, 1'h0} | {8'h0, n_0}) & 9'h1FB)
                   & 9'h1F7) & 9'h1EF) & 9'h1DF) & 9'h1BF) & 9'h17F) & 9'hFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:16, :11:17, :12:16, :13:16, :14:16, :15:15, :16:15, :17:14, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :47:11, :66:11, :67:11, :68:11, :69:11, :70:5
endmodule

