// Generated by CIRCT unknown git version
module add8u_4T8(	// file.cleaned.mlir:2:3
  input  [7:0] A,	// file.cleaned.mlir:2:27
               B,	// file.cleaned.mlir:2:39
  output [8:0] O	// file.cleaned.mlir:2:52
);

  wire n_212;	// file.cleaned.mlir:94:11
  wire n_204;	// file.cleaned.mlir:92:11
  wire n_200;	// file.cleaned.mlir:91:11
  wire n_196;	// file.cleaned.mlir:90:11
  wire n_192;	// file.cleaned.mlir:89:11
  wire n_189;	// file.cleaned.mlir:88:11
  wire n_185;	// file.cleaned.mlir:87:11
  wire n_23;	// file.cleaned.mlir:58:11
  wire n_0;	// file.cleaned.mlir:42:11
  assign n_0 = A[0];	// file.cleaned.mlir:42:11
  assign n_23 = A[1] ^ B[1];	// file.cleaned.mlir:43:11, :50:11, :58:11
  wire n_27 = A[1] & B[1];	// file.cleaned.mlir:43:11, :50:11, :59:11
  wire n_31 = B[2] ^ A[2];	// file.cleaned.mlir:44:11, :51:11, :60:11
  wire n_39 = A[3] ^ B[3];	// file.cleaned.mlir:45:11, :52:11, :62:11
  wire n_42 = A[3] & B[3];	// file.cleaned.mlir:45:11, :52:11, :63:11
  wire n_46 = A[4] ^ B[4];	// file.cleaned.mlir:46:11, :53:11, :64:11
  wire n_54 = A[5] ^ B[5];	// file.cleaned.mlir:47:11, :54:11, :66:11
  wire n_58 = B[5] & A[5];	// file.cleaned.mlir:47:11, :54:11, :67:11
  wire n_62 = A[6] ^ B[6];	// file.cleaned.mlir:48:11, :55:11, :68:11
  wire n_69 = A[7] ^ B[7];	// file.cleaned.mlir:49:11, :56:11, :70:11
  wire n_85 = A[2] & B[2] | n_31 & n_27;	// file.cleaned.mlir:44:11, :51:11, :59:11, :60:11, :61:11, :72:11, :73:11
  wire n_96 = A[4] & B[4] | n_46 & n_42;	// file.cleaned.mlir:46:11, :53:11, :63:11, :64:11, :65:11, :74:11, :75:11
  wire n_104 = n_62 & n_54;	// file.cleaned.mlir:66:11, :68:11, :77:11
  wire n_119 = n_46 & n_39 & n_85;	// file.cleaned.mlir:62:11, :64:11, :73:11, :78:11
  wire n_127 = n_96 | n_119;	// file.cleaned.mlir:75:11, :78:11, :79:11
  wire n_154 = A[6] & B[6] | n_62 & n_58 | n_104 & n_96 | n_104 & n_119;	// file.cleaned.mlir:48:11, :55:11, :67:11, :68:11, :69:11, :75:11, :76:11, :77:11, :78:11, :80:11, :81:11, :82:11
  assign n_185 = n_31 ^ n_27;	// file.cleaned.mlir:59:11, :60:11, :87:11
  assign n_189 = n_39 ^ n_85;	// file.cleaned.mlir:62:11, :73:11, :88:11
  assign n_192 = n_46 ^ (n_42 | (A[3] | B[3]) & n_85);	// file.cleaned.mlir:45:11, :52:11, :57:11, :63:11, :64:11, :73:11, :83:11, :84:11, :89:11
  assign n_196 = n_54 ^ n_127;	// file.cleaned.mlir:66:11, :79:11, :90:11
  assign n_200 = n_62 ^ (n_58 | n_54 & n_127);	// file.cleaned.mlir:66:11, :67:11, :68:11, :79:11, :85:11, :86:11, :91:11
  assign n_204 = n_69 ^ n_154;	// file.cleaned.mlir:70:11, :82:11, :92:11
  assign n_212 = A[7] & B[7] | n_69 & n_154;	// file.cleaned.mlir:49:11, :56:11, :70:11, :71:11, :82:11, :93:11, :94:11
  assign O =
    {n_212, 8'h0}
    | ({1'h0, n_204, 7'h0}
       | ({2'h0, n_200, 6'h0}
          | ({3'h0, n_196, 5'h0}
             | ({4'h0, n_192, 4'h0}
                | ({5'h0, n_189, 3'h0}
                   | ({6'h0, n_185, 2'h0} | ({7'h0, n_23, 1'h0} | {8'h0, n_0}) & 9'h1FB)
                   & 9'h1F7) & 9'h1EF) & 9'h1DF) & 9'h1BF) & 9'h17F) & 9'hFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:16, :11:17, :12:16, :13:16, :14:16, :15:15, :16:15, :17:14, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :58:11, :87:11, :88:11, :89:11, :90:11, :91:11, :92:11, :94:11, :95:5
endmodule

