// Generated by CIRCT unknown git version
module add9se_080(	// file.cleaned.mlir:2:3
  input  [8:0] A,	// file.cleaned.mlir:2:28
               B,	// file.cleaned.mlir:2:40
  output [9:0] O	// file.cleaned.mlir:2:53
);

  wire sig_61;	// file.cleaned.mlir:52:11
  wire sig_58;	// file.cleaned.mlir:50:11
  wire sig_53;	// file.cleaned.mlir:43:11
  wire sig_45 = A[6] | B[6];	// file.cleaned.mlir:35:11, :36:11, :37:11
  wire sig_50 = A[7] ^ B[7];	// file.cleaned.mlir:38:11, :39:11, :40:11
  assign sig_53 = sig_50 ^ sig_45;	// file.cleaned.mlir:37:11, :40:11, :43:11
  wire sig_54 = A[7] & B[7] | sig_50 & sig_45;	// file.cleaned.mlir:37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :44:11
  wire sig_55 = A[8] ^ B[8];	// file.cleaned.mlir:45:11, :46:11, :47:11
  assign sig_58 = sig_55 ^ sig_54;	// file.cleaned.mlir:44:11, :47:11, :50:11
  assign sig_61 = sig_55 ^ (A[8] & B[8] | sig_55 & sig_54);	// file.cleaned.mlir:44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :51:11, :52:11
  assign O =
    {sig_61, 9'h0}
    | ({1'h0, sig_58, 8'h0}
       | ({2'h0, sig_53, 7'h0}
          | ({4'h0, sig_53, 5'h0}
             | ({6'h0, sig_58, 3'h0} | ({7'h0, sig_61, 2'h0} | {8'h0, sig_58, 1'h0})
                & 10'h3F7) & 10'h3CF) & 10'h33F) & 10'h2FF) & 10'h1FF;	// file.cleaned.mlir:3:14, :4:18, :5:14, :6:14, :7:17, :8:14, :9:14, :10:14, :11:14, :12:17, :13:18, :14:16, :15:14, :16:14, :17:10, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :43:11, :50:11, :52:11, :53:5
endmodule

