// Generated by CIRCT unknown git version
module mul12u_2DU(	// file.cleaned.mlir:2:3
  input  [11:0] A,	// file.cleaned.mlir:2:28
                B,	// file.cleaned.mlir:2:41
  output [23:0] O	// file.cleaned.mlir:2:55
);

  wire _U40643_YS;	// file.cleaned.mlir:124:30
  wire _U40643_YC;	// file.cleaned.mlir:124:30
  wire _U40642_YS;	// file.cleaned.mlir:123:30
  wire _U40642_YC;	// file.cleaned.mlir:123:30
  wire _U40641_YS;	// file.cleaned.mlir:122:30
  wire _U40641_YC;	// file.cleaned.mlir:122:30
  wire _U40640_YS;	// file.cleaned.mlir:121:30
  wire _U40640_YC;	// file.cleaned.mlir:121:30
  wire _U40639_YS;	// file.cleaned.mlir:120:30
  wire _U40639_YC;	// file.cleaned.mlir:120:30
  wire _U40638_YS;	// file.cleaned.mlir:119:30
  wire _U40638_YC;	// file.cleaned.mlir:119:30
  wire _U40637_YS;	// file.cleaned.mlir:118:30
  wire _U40637_YC;	// file.cleaned.mlir:118:30
  wire _U40636_YS;	// file.cleaned.mlir:117:30
  wire _U40636_YC;	// file.cleaned.mlir:117:30
  wire _U40635_YS;	// file.cleaned.mlir:116:30
  wire _U40635_YC;	// file.cleaned.mlir:116:30
  wire _U40631_YS;	// file.cleaned.mlir:114:30
  wire _U40631_YC;	// file.cleaned.mlir:114:30
  wire _U40630_YS;	// file.cleaned.mlir:112:30
  wire _U40630_YC;	// file.cleaned.mlir:112:30
  wire _U40629_YS;	// file.cleaned.mlir:110:30
  wire _U40629_YC;	// file.cleaned.mlir:110:30
  wire _U40628_YS;	// file.cleaned.mlir:108:30
  wire _U40628_YC;	// file.cleaned.mlir:108:30
  wire _U40627_YS;	// file.cleaned.mlir:106:30
  wire _U40627_YC;	// file.cleaned.mlir:106:30
  wire _U40626_YS;	// file.cleaned.mlir:104:30
  wire _U40626_YC;	// file.cleaned.mlir:104:30
  wire _U40625_YS;	// file.cleaned.mlir:102:30
  wire _U40625_YC;	// file.cleaned.mlir:102:30
  wire _U40624_YS;	// file.cleaned.mlir:100:30
  wire _U40624_YC;	// file.cleaned.mlir:100:30
  wire _U40623_YS;	// file.cleaned.mlir:98:30
  wire _U40623_YC;	// file.cleaned.mlir:98:30
  wire _U40619_YS;	// file.cleaned.mlir:93:30
  wire _U40619_YC;	// file.cleaned.mlir:93:30
  wire _U40618_YS;	// file.cleaned.mlir:91:30
  wire _U40618_YC;	// file.cleaned.mlir:91:30
  wire _U40617_YS;	// file.cleaned.mlir:89:30
  wire _U40617_YC;	// file.cleaned.mlir:89:30
  wire _U40616_YS;	// file.cleaned.mlir:87:30
  wire _U40616_YC;	// file.cleaned.mlir:87:30
  wire _U40615_YS;	// file.cleaned.mlir:85:30
  wire _U40615_YC;	// file.cleaned.mlir:85:30
  wire _U40614_YS;	// file.cleaned.mlir:83:30
  wire _U40614_YC;	// file.cleaned.mlir:83:30
  wire _U40613_YS;	// file.cleaned.mlir:81:30
  wire _U40613_YC;	// file.cleaned.mlir:81:30
  wire _U40612_YS;	// file.cleaned.mlir:79:30
  wire _U40612_YC;	// file.cleaned.mlir:79:30
  wire _U40607_YS;	// file.cleaned.mlir:74:30
  wire _U40607_YC;	// file.cleaned.mlir:74:30
  wire _U40606_YS;	// file.cleaned.mlir:72:30
  wire _U40606_YC;	// file.cleaned.mlir:72:30
  wire _U40605_YS;	// file.cleaned.mlir:70:30
  wire _U40605_YC;	// file.cleaned.mlir:70:30
  wire _U40604_YS;	// file.cleaned.mlir:68:30
  wire _U40604_YC;	// file.cleaned.mlir:68:30
  wire _U40603_YS;	// file.cleaned.mlir:66:30
  wire _U40603_YC;	// file.cleaned.mlir:66:30
  wire _U40602_YS;	// file.cleaned.mlir:64:30
  wire _U40602_YC;	// file.cleaned.mlir:64:30
  wire _U40601_YS;	// file.cleaned.mlir:62:30
  wire _U40601_YC;	// file.cleaned.mlir:62:30
  wire _U40595_YS;	// file.cleaned.mlir:57:30
  wire _U40595_YC;	// file.cleaned.mlir:57:30
  wire _U40594_YS;	// file.cleaned.mlir:55:30
  wire _U40594_YC;	// file.cleaned.mlir:55:30
  wire _U40593_YS;	// file.cleaned.mlir:53:30
  wire _U40593_YC;	// file.cleaned.mlir:53:30
  wire _U40592_YS;	// file.cleaned.mlir:51:30
  wire _U40592_YC;	// file.cleaned.mlir:51:30
  wire _U40591_YS;	// file.cleaned.mlir:49:30
  wire _U40591_YC;	// file.cleaned.mlir:49:30
  wire _U40590_YS;	// file.cleaned.mlir:47:30
  wire _U40590_YC;	// file.cleaned.mlir:47:30
  wire _U40583_YS;	// file.cleaned.mlir:42:30
  wire _U40583_YC;	// file.cleaned.mlir:42:30
  wire _U40582_YS;	// file.cleaned.mlir:40:30
  wire _U40582_YC;	// file.cleaned.mlir:40:30
  wire _U40581_YS;	// file.cleaned.mlir:38:30
  wire _U40581_YC;	// file.cleaned.mlir:38:30
  wire _U40580_YS;	// file.cleaned.mlir:36:30
  wire _U40580_YC;	// file.cleaned.mlir:36:30
  wire _U40579_YS;	// file.cleaned.mlir:34:30
  wire _U40579_YC;	// file.cleaned.mlir:34:30
  wire _U40571_YS;	// file.cleaned.mlir:29:30
  wire _U40571_YC;	// file.cleaned.mlir:29:30
  wire _U40570_YS;	// file.cleaned.mlir:27:30
  wire _U40570_YC;	// file.cleaned.mlir:27:30
  wire _U40569_YS;	// file.cleaned.mlir:25:30
  wire _U40569_YC;	// file.cleaned.mlir:25:30
  wire _U40568_YS;	// file.cleaned.mlir:23:30
  wire _U40568_YC;	// file.cleaned.mlir:23:30
  wire _U40559_YS;	// file.cleaned.mlir:18:30
  wire _U40559_YC;	// file.cleaned.mlir:18:30
  wire _U40558_YS;	// file.cleaned.mlir:16:30
  wire _U40558_YC;	// file.cleaned.mlir:16:30
  wire _U40557_YS;	// file.cleaned.mlir:14:30
  wire _U40557_YC;	// file.cleaned.mlir:14:30
  PDKGENHAX1 U40557 (	// file.cleaned.mlir:14:30
    .A  (A[4] & B[9]),	// file.cleaned.mlir:4:10, :5:10, :6:10
    .B  (A[5] & B[8]),	// file.cleaned.mlir:11:10, :12:10, :13:10
    .YS (_U40557_YS),
    .YC (_U40557_YC)
  );	// file.cleaned.mlir:14:30
  PDKGENHAX1 U40558 (	// file.cleaned.mlir:16:30
    .A  (A[4] & B[10]),	// file.cleaned.mlir:4:10, :7:10, :8:10
    .B  (A[5] & B[9]),	// file.cleaned.mlir:5:10, :11:10, :15:11
    .YS (_U40558_YS),
    .YC (_U40558_YC)
  );	// file.cleaned.mlir:16:30
  PDKGENHAX1 U40559 (	// file.cleaned.mlir:18:30
    .A  (A[4] & B[11]),	// file.cleaned.mlir:4:10, :9:10, :10:10
    .B  (A[5] & B[10]),	// file.cleaned.mlir:7:10, :11:10, :17:11
    .YS (_U40559_YS),
    .YC (_U40559_YC)
  );	// file.cleaned.mlir:18:30
  PDKGENHAX1 U40568 (	// file.cleaned.mlir:23:30
    .A  (_U40557_YS),	// file.cleaned.mlir:14:30
    .B  (A[6] & B[7]),	// file.cleaned.mlir:20:11, :21:11, :22:11
    .YS (_U40568_YS),
    .YC (_U40568_YC)
  );	// file.cleaned.mlir:23:30
  PDKGENFAX1 U40569 (	// file.cleaned.mlir:25:30
    .A  (_U40558_YS),	// file.cleaned.mlir:16:30
    .B  (_U40557_YC),	// file.cleaned.mlir:14:30
    .C  (A[6] & B[8]),	// file.cleaned.mlir:12:10, :20:11, :24:11
    .YS (_U40569_YS),
    .YC (_U40569_YC)
  );	// file.cleaned.mlir:25:30
  PDKGENFAX1 U40570 (	// file.cleaned.mlir:27:30
    .A  (_U40559_YS),	// file.cleaned.mlir:18:30
    .B  (_U40558_YC),	// file.cleaned.mlir:16:30
    .C  (A[6] & B[9]),	// file.cleaned.mlir:5:10, :20:11, :26:11
    .YS (_U40570_YS),
    .YC (_U40570_YC)
  );	// file.cleaned.mlir:27:30
  PDKGENFAX1 U40571 (	// file.cleaned.mlir:29:30
    .A  (A[5] & B[11]),	// file.cleaned.mlir:9:10, :11:10, :19:11
    .B  (_U40559_YC),	// file.cleaned.mlir:18:30
    .C  (A[6] & B[10]),	// file.cleaned.mlir:7:10, :20:11, :28:11
    .YS (_U40571_YS),
    .YC (_U40571_YC)
  );	// file.cleaned.mlir:29:30
  PDKGENHAX1 U40579 (	// file.cleaned.mlir:34:30
    .A  (_U40568_YS),	// file.cleaned.mlir:23:30
    .B  (A[7] & B[6]),	// file.cleaned.mlir:31:11, :32:11, :33:11
    .YS (_U40579_YS),
    .YC (_U40579_YC)
  );	// file.cleaned.mlir:34:30
  PDKGENFAX1 U40580 (	// file.cleaned.mlir:36:30
    .A  (_U40569_YS),	// file.cleaned.mlir:25:30
    .B  (_U40568_YC),	// file.cleaned.mlir:23:30
    .C  (A[7] & B[7]),	// file.cleaned.mlir:21:11, :31:11, :35:11
    .YS (_U40580_YS),
    .YC (_U40580_YC)
  );	// file.cleaned.mlir:36:30
  PDKGENFAX1 U40581 (	// file.cleaned.mlir:38:30
    .A  (_U40570_YS),	// file.cleaned.mlir:27:30
    .B  (_U40569_YC),	// file.cleaned.mlir:25:30
    .C  (A[7] & B[8]),	// file.cleaned.mlir:12:10, :31:11, :37:11
    .YS (_U40581_YS),
    .YC (_U40581_YC)
  );	// file.cleaned.mlir:38:30
  PDKGENFAX1 U40582 (	// file.cleaned.mlir:40:30
    .A  (_U40571_YS),	// file.cleaned.mlir:29:30
    .B  (_U40570_YC),	// file.cleaned.mlir:27:30
    .C  (A[7] & B[9]),	// file.cleaned.mlir:5:10, :31:11, :39:11
    .YS (_U40582_YS),
    .YC (_U40582_YC)
  );	// file.cleaned.mlir:40:30
  PDKGENFAX1 U40583 (	// file.cleaned.mlir:42:30
    .A  (A[6] & B[11]),	// file.cleaned.mlir:9:10, :20:11, :30:11
    .B  (_U40571_YC),	// file.cleaned.mlir:29:30
    .C  (A[7] & B[10]),	// file.cleaned.mlir:7:10, :31:11, :41:11
    .YS (_U40583_YS),
    .YC (_U40583_YC)
  );	// file.cleaned.mlir:42:30
  PDKGENHAX1 U40590 (	// file.cleaned.mlir:47:30
    .A  (_U40579_YS),	// file.cleaned.mlir:34:30
    .B  (A[8] & B[5]),	// file.cleaned.mlir:44:11, :45:11, :46:11
    .YS (_U40590_YS),
    .YC (_U40590_YC)
  );	// file.cleaned.mlir:47:30
  PDKGENFAX1 U40591 (	// file.cleaned.mlir:49:30
    .A  (_U40580_YS),	// file.cleaned.mlir:36:30
    .B  (_U40579_YC),	// file.cleaned.mlir:34:30
    .C  (A[8] & B[6]),	// file.cleaned.mlir:32:11, :44:11, :48:11
    .YS (_U40591_YS),
    .YC (_U40591_YC)
  );	// file.cleaned.mlir:49:30
  PDKGENFAX1 U40592 (	// file.cleaned.mlir:51:30
    .A  (_U40581_YS),	// file.cleaned.mlir:38:30
    .B  (_U40580_YC),	// file.cleaned.mlir:36:30
    .C  (A[8] & B[7]),	// file.cleaned.mlir:21:11, :44:11, :50:11
    .YS (_U40592_YS),
    .YC (_U40592_YC)
  );	// file.cleaned.mlir:51:30
  PDKGENFAX1 U40593 (	// file.cleaned.mlir:53:30
    .A  (_U40582_YS),	// file.cleaned.mlir:40:30
    .B  (_U40581_YC),	// file.cleaned.mlir:38:30
    .C  (A[8] & B[8]),	// file.cleaned.mlir:12:10, :44:11, :52:11
    .YS (_U40593_YS),
    .YC (_U40593_YC)
  );	// file.cleaned.mlir:53:30
  PDKGENFAX1 U40594 (	// file.cleaned.mlir:55:30
    .A  (_U40583_YS),	// file.cleaned.mlir:42:30
    .B  (_U40582_YC),	// file.cleaned.mlir:40:30
    .C  (A[8] & B[9]),	// file.cleaned.mlir:5:10, :44:11, :54:11
    .YS (_U40594_YS),
    .YC (_U40594_YC)
  );	// file.cleaned.mlir:55:30
  PDKGENFAX1 U40595 (	// file.cleaned.mlir:57:30
    .A  (A[7] & B[11]),	// file.cleaned.mlir:9:10, :31:11, :43:11
    .B  (_U40583_YC),	// file.cleaned.mlir:42:30
    .C  (A[8] & B[10]),	// file.cleaned.mlir:7:10, :44:11, :56:11
    .YS (_U40595_YS),
    .YC (_U40595_YC)
  );	// file.cleaned.mlir:57:30
  PDKGENHAX1 U40601 (	// file.cleaned.mlir:62:30
    .A  (_U40590_YS),	// file.cleaned.mlir:47:30
    .B  (A[9] & B[4]),	// file.cleaned.mlir:59:11, :60:11, :61:11
    .YS (_U40601_YS),
    .YC (_U40601_YC)
  );	// file.cleaned.mlir:62:30
  PDKGENFAX1 U40602 (	// file.cleaned.mlir:64:30
    .A  (_U40591_YS),	// file.cleaned.mlir:49:30
    .B  (_U40590_YC),	// file.cleaned.mlir:47:30
    .C  (A[9] & B[5]),	// file.cleaned.mlir:45:11, :59:11, :63:11
    .YS (_U40602_YS),
    .YC (_U40602_YC)
  );	// file.cleaned.mlir:64:30
  PDKGENFAX1 U40603 (	// file.cleaned.mlir:66:30
    .A  (_U40592_YS),	// file.cleaned.mlir:51:30
    .B  (_U40591_YC),	// file.cleaned.mlir:49:30
    .C  (A[9] & B[6]),	// file.cleaned.mlir:32:11, :59:11, :65:11
    .YS (_U40603_YS),
    .YC (_U40603_YC)
  );	// file.cleaned.mlir:66:30
  PDKGENFAX1 U40604 (	// file.cleaned.mlir:68:30
    .A  (_U40593_YS),	// file.cleaned.mlir:53:30
    .B  (_U40592_YC),	// file.cleaned.mlir:51:30
    .C  (A[9] & B[7]),	// file.cleaned.mlir:21:11, :59:11, :67:11
    .YS (_U40604_YS),
    .YC (_U40604_YC)
  );	// file.cleaned.mlir:68:30
  PDKGENFAX1 U40605 (	// file.cleaned.mlir:70:30
    .A  (_U40594_YS),	// file.cleaned.mlir:55:30
    .B  (_U40593_YC),	// file.cleaned.mlir:53:30
    .C  (A[9] & B[8]),	// file.cleaned.mlir:12:10, :59:11, :69:11
    .YS (_U40605_YS),
    .YC (_U40605_YC)
  );	// file.cleaned.mlir:70:30
  PDKGENFAX1 U40606 (	// file.cleaned.mlir:72:30
    .A  (_U40595_YS),	// file.cleaned.mlir:57:30
    .B  (_U40594_YC),	// file.cleaned.mlir:55:30
    .C  (A[9] & B[9]),	// file.cleaned.mlir:5:10, :59:11, :71:11
    .YS (_U40606_YS),
    .YC (_U40606_YC)
  );	// file.cleaned.mlir:72:30
  PDKGENFAX1 U40607 (	// file.cleaned.mlir:74:30
    .A  (A[8] & B[11]),	// file.cleaned.mlir:9:10, :44:11, :58:11
    .B  (_U40595_YC),	// file.cleaned.mlir:57:30
    .C  (A[9] & B[10]),	// file.cleaned.mlir:7:10, :59:11, :73:11
    .YS (_U40607_YS),
    .YC (_U40607_YC)
  );	// file.cleaned.mlir:74:30
  PDKGENHAX1 U40612 (	// file.cleaned.mlir:79:30
    .A  (_U40601_YS),	// file.cleaned.mlir:62:30
    .B  (A[10] & B[3]),	// file.cleaned.mlir:76:11, :77:11, :78:11
    .YS (_U40612_YS),
    .YC (_U40612_YC)
  );	// file.cleaned.mlir:79:30
  PDKGENFAX1 U40613 (	// file.cleaned.mlir:81:30
    .A  (_U40602_YS),	// file.cleaned.mlir:64:30
    .B  (_U40601_YC),	// file.cleaned.mlir:62:30
    .C  (A[10] & B[4]),	// file.cleaned.mlir:60:11, :76:11, :80:11
    .YS (_U40613_YS),
    .YC (_U40613_YC)
  );	// file.cleaned.mlir:81:30
  PDKGENFAX1 U40614 (	// file.cleaned.mlir:83:30
    .A  (_U40603_YS),	// file.cleaned.mlir:66:30
    .B  (_U40602_YC),	// file.cleaned.mlir:64:30
    .C  (A[10] & B[5]),	// file.cleaned.mlir:45:11, :76:11, :82:11
    .YS (_U40614_YS),
    .YC (_U40614_YC)
  );	// file.cleaned.mlir:83:30
  PDKGENFAX1 U40615 (	// file.cleaned.mlir:85:30
    .A  (_U40604_YS),	// file.cleaned.mlir:68:30
    .B  (_U40603_YC),	// file.cleaned.mlir:66:30
    .C  (A[10] & B[6]),	// file.cleaned.mlir:32:11, :76:11, :84:11
    .YS (_U40615_YS),
    .YC (_U40615_YC)
  );	// file.cleaned.mlir:85:30
  PDKGENFAX1 U40616 (	// file.cleaned.mlir:87:30
    .A  (_U40605_YS),	// file.cleaned.mlir:70:30
    .B  (_U40604_YC),	// file.cleaned.mlir:68:30
    .C  (A[10] & B[7]),	// file.cleaned.mlir:21:11, :76:11, :86:11
    .YS (_U40616_YS),
    .YC (_U40616_YC)
  );	// file.cleaned.mlir:87:30
  PDKGENFAX1 U40617 (	// file.cleaned.mlir:89:30
    .A  (_U40606_YS),	// file.cleaned.mlir:72:30
    .B  (_U40605_YC),	// file.cleaned.mlir:70:30
    .C  (A[10] & B[8]),	// file.cleaned.mlir:12:10, :76:11, :88:11
    .YS (_U40617_YS),
    .YC (_U40617_YC)
  );	// file.cleaned.mlir:89:30
  PDKGENFAX1 U40618 (	// file.cleaned.mlir:91:30
    .A  (_U40607_YS),	// file.cleaned.mlir:74:30
    .B  (_U40606_YC),	// file.cleaned.mlir:72:30
    .C  (A[10] & B[9]),	// file.cleaned.mlir:5:10, :76:11, :90:11
    .YS (_U40618_YS),
    .YC (_U40618_YC)
  );	// file.cleaned.mlir:91:30
  PDKGENFAX1 U40619 (	// file.cleaned.mlir:93:30
    .A  (A[9] & B[11]),	// file.cleaned.mlir:9:10, :59:11, :75:11
    .B  (_U40607_YC),	// file.cleaned.mlir:74:30
    .C  (A[10] & B[10]),	// file.cleaned.mlir:7:10, :76:11, :92:11
    .YS (_U40619_YS),
    .YC (_U40619_YC)
  );	// file.cleaned.mlir:93:30
  PDKGENHAX1 U40623 (	// file.cleaned.mlir:98:30
    .A  (_U40612_YS),	// file.cleaned.mlir:79:30
    .B  (A[11] & B[2]),	// file.cleaned.mlir:95:11, :96:11, :97:11
    .YS (_U40623_YS),
    .YC (_U40623_YC)
  );	// file.cleaned.mlir:98:30
  PDKGENFAX1 U40624 (	// file.cleaned.mlir:100:30
    .A  (_U40613_YS),	// file.cleaned.mlir:81:30
    .B  (_U40612_YC),	// file.cleaned.mlir:79:30
    .C  (A[11] & B[3]),	// file.cleaned.mlir:77:11, :95:11, :99:11
    .YS (_U40624_YS),
    .YC (_U40624_YC)
  );	// file.cleaned.mlir:100:30
  PDKGENFAX1 U40625 (	// file.cleaned.mlir:102:30
    .A  (_U40614_YS),	// file.cleaned.mlir:83:30
    .B  (_U40613_YC),	// file.cleaned.mlir:81:30
    .C  (A[11] & B[4]),	// file.cleaned.mlir:60:11, :95:11, :101:11
    .YS (_U40625_YS),
    .YC (_U40625_YC)
  );	// file.cleaned.mlir:102:30
  PDKGENFAX1 U40626 (	// file.cleaned.mlir:104:30
    .A  (_U40615_YS),	// file.cleaned.mlir:85:30
    .B  (_U40614_YC),	// file.cleaned.mlir:83:30
    .C  (A[11] & B[5]),	// file.cleaned.mlir:45:11, :95:11, :103:11
    .YS (_U40626_YS),
    .YC (_U40626_YC)
  );	// file.cleaned.mlir:104:30
  PDKGENFAX1 U40627 (	// file.cleaned.mlir:106:30
    .A  (_U40616_YS),	// file.cleaned.mlir:87:30
    .B  (_U40615_YC),	// file.cleaned.mlir:85:30
    .C  (A[11] & B[6]),	// file.cleaned.mlir:32:11, :95:11, :105:11
    .YS (_U40627_YS),
    .YC (_U40627_YC)
  );	// file.cleaned.mlir:106:30
  PDKGENFAX1 U40628 (	// file.cleaned.mlir:108:30
    .A  (_U40617_YS),	// file.cleaned.mlir:89:30
    .B  (_U40616_YC),	// file.cleaned.mlir:87:30
    .C  (A[11] & B[7]),	// file.cleaned.mlir:21:11, :95:11, :107:11
    .YS (_U40628_YS),
    .YC (_U40628_YC)
  );	// file.cleaned.mlir:108:30
  PDKGENFAX1 U40629 (	// file.cleaned.mlir:110:30
    .A  (_U40618_YS),	// file.cleaned.mlir:91:30
    .B  (_U40617_YC),	// file.cleaned.mlir:89:30
    .C  (A[11] & B[8]),	// file.cleaned.mlir:12:10, :95:11, :109:11
    .YS (_U40629_YS),
    .YC (_U40629_YC)
  );	// file.cleaned.mlir:110:30
  PDKGENFAX1 U40630 (	// file.cleaned.mlir:112:30
    .A  (_U40619_YS),	// file.cleaned.mlir:93:30
    .B  (_U40618_YC),	// file.cleaned.mlir:91:30
    .C  (A[11] & B[9]),	// file.cleaned.mlir:5:10, :95:11, :111:11
    .YS (_U40630_YS),
    .YC (_U40630_YC)
  );	// file.cleaned.mlir:112:30
  PDKGENFAX1 U40631 (	// file.cleaned.mlir:114:30
    .A  (A[10] & B[11]),	// file.cleaned.mlir:9:10, :76:11, :94:11
    .B  (_U40619_YC),	// file.cleaned.mlir:93:30
    .C  (A[11] & B[10]),	// file.cleaned.mlir:7:10, :95:11, :113:11
    .YS (_U40631_YS),
    .YC (_U40631_YC)
  );	// file.cleaned.mlir:114:30
  PDKGENHAX1 U40635 (	// file.cleaned.mlir:116:30
    .A  (_U40624_YS),	// file.cleaned.mlir:100:30
    .B  (_U40623_YC),	// file.cleaned.mlir:98:30
    .YS (_U40635_YS),
    .YC (_U40635_YC)
  );	// file.cleaned.mlir:116:30
  PDKGENFAX1 U40636 (	// file.cleaned.mlir:117:30
    .A  (_U40625_YS),	// file.cleaned.mlir:102:30
    .B  (_U40635_YC),	// file.cleaned.mlir:116:30
    .C  (_U40624_YC),	// file.cleaned.mlir:100:30
    .YS (_U40636_YS),
    .YC (_U40636_YC)
  );	// file.cleaned.mlir:117:30
  PDKGENFAX1 U40637 (	// file.cleaned.mlir:118:30
    .A  (_U40626_YS),	// file.cleaned.mlir:104:30
    .B  (_U40636_YC),	// file.cleaned.mlir:117:30
    .C  (_U40625_YC),	// file.cleaned.mlir:102:30
    .YS (_U40637_YS),
    .YC (_U40637_YC)
  );	// file.cleaned.mlir:118:30
  PDKGENFAX1 U40638 (	// file.cleaned.mlir:119:30
    .A  (_U40627_YS),	// file.cleaned.mlir:106:30
    .B  (_U40637_YC),	// file.cleaned.mlir:118:30
    .C  (_U40626_YC),	// file.cleaned.mlir:104:30
    .YS (_U40638_YS),
    .YC (_U40638_YC)
  );	// file.cleaned.mlir:119:30
  PDKGENFAX1 U40639 (	// file.cleaned.mlir:120:30
    .A  (_U40628_YS),	// file.cleaned.mlir:108:30
    .B  (_U40638_YC),	// file.cleaned.mlir:119:30
    .C  (_U40627_YC),	// file.cleaned.mlir:106:30
    .YS (_U40639_YS),
    .YC (_U40639_YC)
  );	// file.cleaned.mlir:120:30
  PDKGENFAX1 U40640 (	// file.cleaned.mlir:121:30
    .A  (_U40629_YS),	// file.cleaned.mlir:110:30
    .B  (_U40639_YC),	// file.cleaned.mlir:120:30
    .C  (_U40628_YC),	// file.cleaned.mlir:108:30
    .YS (_U40640_YS),
    .YC (_U40640_YC)
  );	// file.cleaned.mlir:121:30
  PDKGENFAX1 U40641 (	// file.cleaned.mlir:122:30
    .A  (_U40630_YS),	// file.cleaned.mlir:112:30
    .B  (_U40640_YC),	// file.cleaned.mlir:121:30
    .C  (_U40629_YC),	// file.cleaned.mlir:110:30
    .YS (_U40641_YS),
    .YC (_U40641_YC)
  );	// file.cleaned.mlir:122:30
  PDKGENFAX1 U40642 (	// file.cleaned.mlir:123:30
    .A  (_U40631_YS),	// file.cleaned.mlir:114:30
    .B  (_U40641_YC),	// file.cleaned.mlir:122:30
    .C  (_U40630_YC),	// file.cleaned.mlir:112:30
    .YS (_U40642_YS),
    .YC (_U40642_YC)
  );	// file.cleaned.mlir:123:30
  PDKGENFAX1 U40643 (	// file.cleaned.mlir:124:30
    .A  (A[11] & B[11]),	// file.cleaned.mlir:9:10, :95:11, :115:11
    .B  (_U40642_YC),	// file.cleaned.mlir:123:30
    .C  (_U40631_YC),	// file.cleaned.mlir:114:30
    .YS (_U40643_YS),
    .YC (_U40643_YC)
  );	// file.cleaned.mlir:124:30
  assign O =
    {_U40643_YC,
     _U40643_YS,
     _U40642_YS,
     _U40641_YS,
     _U40640_YS,
     _U40639_YS,
     _U40638_YS,
     _U40637_YS,
     _U40636_YS,
     _U40635_YS,
     _U40623_YS,
     13'h0};	// file.cleaned.mlir:3:15, :98:30, :116:30, :117:30, :118:30, :119:30, :120:30, :121:30, :122:30, :123:30, :124:30, :125:11, :126:5
endmodule

module PDKGENHAX1(	// file.cleaned.mlir:128:3
  input  A,	// file.cleaned.mlir:128:36
         B,	// file.cleaned.mlir:128:48
  output YS,	// file.cleaned.mlir:128:61
         YC	// file.cleaned.mlir:128:74
);

  assign YS = A ^ B;	// file.cleaned.mlir:129:10, :131:5
  assign YC = A & B;	// file.cleaned.mlir:130:10, :131:5
endmodule

module PDKGENFAX1(	// file.cleaned.mlir:133:3
  input  A,	// file.cleaned.mlir:133:36
         B,	// file.cleaned.mlir:133:48
         C,	// file.cleaned.mlir:133:60
  output YS,	// file.cleaned.mlir:133:73
         YC	// file.cleaned.mlir:133:86
);

  assign YS = A ^ B ^ C;	// file.cleaned.mlir:134:10, :139:5
  assign YC = A & B | B & C | A & C;	// file.cleaned.mlir:135:10, :136:10, :137:10, :138:10, :139:5
endmodule

