// Generated by CIRCT unknown git version
module mul12u_2CS(	// file.cleaned.mlir:2:3
  input  [11:0] A,	// file.cleaned.mlir:2:28
                B,	// file.cleaned.mlir:2:41
  output [23:0] O	// file.cleaned.mlir:2:55
);

  wire _U16931_YS;	// file.cleaned.mlir:90:30
  wire _U16931_YC;	// file.cleaned.mlir:90:30
  wire _U16930_YS;	// file.cleaned.mlir:89:30
  wire _U16930_YC;	// file.cleaned.mlir:89:30
  wire _U16929_YS;	// file.cleaned.mlir:88:30
  wire _U16929_YC;	// file.cleaned.mlir:88:30
  wire _U16928_YS;	// file.cleaned.mlir:87:30
  wire _U16928_YC;	// file.cleaned.mlir:87:30
  wire _U16927_YS;	// file.cleaned.mlir:86:30
  wire _U16927_YC;	// file.cleaned.mlir:86:30
  wire _U16926_YS;	// file.cleaned.mlir:85:30
  wire _U16926_YC;	// file.cleaned.mlir:85:30
  wire _U16925_YS;	// file.cleaned.mlir:84:30
  wire _U16925_YC;	// file.cleaned.mlir:84:30
  wire _U16919_YS;	// file.cleaned.mlir:82:30
  wire _U16919_YC;	// file.cleaned.mlir:82:30
  wire _U16918_YS;	// file.cleaned.mlir:80:30
  wire _U16918_YC;	// file.cleaned.mlir:80:30
  wire _U16917_YS;	// file.cleaned.mlir:78:30
  wire _U16917_YC;	// file.cleaned.mlir:78:30
  wire _U16916_YS;	// file.cleaned.mlir:76:30
  wire _U16916_YC;	// file.cleaned.mlir:76:30
  wire _U16915_YS;	// file.cleaned.mlir:74:30
  wire _U16915_YC;	// file.cleaned.mlir:74:30
  wire _U16914_YS;	// file.cleaned.mlir:72:30
  wire _U16914_YC;	// file.cleaned.mlir:72:30
  wire _U16913_YS;	// file.cleaned.mlir:70:30
  wire _U16913_YC;	// file.cleaned.mlir:70:30
  wire _U16907_YS;	// file.cleaned.mlir:65:30
  wire _U16907_YC;	// file.cleaned.mlir:65:30
  wire _U16906_YS;	// file.cleaned.mlir:63:30
  wire _U16906_YC;	// file.cleaned.mlir:63:30
  wire _U16905_YS;	// file.cleaned.mlir:61:30
  wire _U16905_YC;	// file.cleaned.mlir:61:30
  wire _U16904_YS;	// file.cleaned.mlir:59:30
  wire _U16904_YC;	// file.cleaned.mlir:59:30
  wire _U16903_YS;	// file.cleaned.mlir:57:30
  wire _U16903_YC;	// file.cleaned.mlir:57:30
  wire _U16902_YS;	// file.cleaned.mlir:55:30
  wire _U16902_YC;	// file.cleaned.mlir:55:30
  wire _U16895_YS;	// file.cleaned.mlir:50:30
  wire _U16895_YC;	// file.cleaned.mlir:50:30
  wire _U16894_YS;	// file.cleaned.mlir:48:30
  wire _U16894_YC;	// file.cleaned.mlir:48:30
  wire _U16893_YS;	// file.cleaned.mlir:46:30
  wire _U16893_YC;	// file.cleaned.mlir:46:30
  wire _U16892_YS;	// file.cleaned.mlir:44:30
  wire _U16892_YC;	// file.cleaned.mlir:44:30
  wire _U16891_YS;	// file.cleaned.mlir:42:30
  wire _U16891_YC;	// file.cleaned.mlir:42:30
  wire _U16883_YS;	// file.cleaned.mlir:37:30
  wire _U16883_YC;	// file.cleaned.mlir:37:30
  wire _U16882_YS;	// file.cleaned.mlir:35:30
  wire _U16882_YC;	// file.cleaned.mlir:35:30
  wire _U16881_YS;	// file.cleaned.mlir:33:30
  wire _U16881_YC;	// file.cleaned.mlir:33:30
  wire _U16880_YS;	// file.cleaned.mlir:31:30
  wire _U16880_YC;	// file.cleaned.mlir:31:30
  wire _U16871_YS;	// file.cleaned.mlir:26:30
  wire _U16871_YC;	// file.cleaned.mlir:26:30
  wire _U16870_YS;	// file.cleaned.mlir:24:30
  wire _U16870_YC;	// file.cleaned.mlir:24:30
  wire _U16869_YS;	// file.cleaned.mlir:22:30
  wire _U16869_YC;	// file.cleaned.mlir:22:30
  wire _U16859_YS;	// file.cleaned.mlir:17:30
  wire _U16859_YC;	// file.cleaned.mlir:17:30
  wire _U16858_YS;	// file.cleaned.mlir:15:30
  wire _U16858_YC;	// file.cleaned.mlir:15:30
  wire _U16847_YS;	// file.cleaned.mlir:10:30
  wire _U16847_YC;	// file.cleaned.mlir:10:30
  PDKGENHAX1 U16847 (	// file.cleaned.mlir:10:30
    .A  (A[4] & B[11]),	// file.cleaned.mlir:4:10, :5:10, :6:10
    .B  (A[5] & B[10]),	// file.cleaned.mlir:7:10, :8:10, :9:10
    .YS (_U16847_YS),
    .YC (_U16847_YC)
  );	// file.cleaned.mlir:10:30
  PDKGENHAX1 U16858 (	// file.cleaned.mlir:15:30
    .A  (_U16847_YS),	// file.cleaned.mlir:10:30
    .B  (A[6] & B[9]),	// file.cleaned.mlir:12:10, :13:10, :14:10
    .YS (_U16858_YS),
    .YC (_U16858_YC)
  );	// file.cleaned.mlir:15:30
  PDKGENFAX1 U16859 (	// file.cleaned.mlir:17:30
    .A  (A[5] & B[11]),	// file.cleaned.mlir:5:10, :7:10, :11:10
    .B  (_U16847_YC),	// file.cleaned.mlir:10:30
    .C  (A[6] & B[10]),	// file.cleaned.mlir:8:10, :12:10, :16:11
    .YS (_U16859_YS),
    .YC (_U16859_YC)
  );	// file.cleaned.mlir:17:30
  PDKGENHAX1 U16869 (	// file.cleaned.mlir:22:30
    .A  (_U16858_YS),	// file.cleaned.mlir:15:30
    .B  (A[7] & B[8]),	// file.cleaned.mlir:19:11, :20:11, :21:11
    .YS (_U16869_YS),
    .YC (_U16869_YC)
  );	// file.cleaned.mlir:22:30
  PDKGENFAX1 U16870 (	// file.cleaned.mlir:24:30
    .A  (_U16859_YS),	// file.cleaned.mlir:17:30
    .B  (_U16858_YC),	// file.cleaned.mlir:15:30
    .C  (A[7] & B[9]),	// file.cleaned.mlir:13:10, :19:11, :23:11
    .YS (_U16870_YS),
    .YC (_U16870_YC)
  );	// file.cleaned.mlir:24:30
  PDKGENFAX1 U16871 (	// file.cleaned.mlir:26:30
    .A  (A[6] & B[11]),	// file.cleaned.mlir:5:10, :12:10, :18:11
    .B  (_U16859_YC),	// file.cleaned.mlir:17:30
    .C  (A[7] & B[10]),	// file.cleaned.mlir:8:10, :19:11, :25:11
    .YS (_U16871_YS),
    .YC (_U16871_YC)
  );	// file.cleaned.mlir:26:30
  PDKGENHAX1 U16880 (	// file.cleaned.mlir:31:30
    .A  (_U16869_YS),	// file.cleaned.mlir:22:30
    .B  (A[8] & B[7]),	// file.cleaned.mlir:28:11, :29:11, :30:11
    .YS (_U16880_YS),
    .YC (_U16880_YC)
  );	// file.cleaned.mlir:31:30
  PDKGENFAX1 U16881 (	// file.cleaned.mlir:33:30
    .A  (_U16870_YS),	// file.cleaned.mlir:24:30
    .B  (_U16869_YC),	// file.cleaned.mlir:22:30
    .C  (A[8] & B[8]),	// file.cleaned.mlir:20:11, :28:11, :32:11
    .YS (_U16881_YS),
    .YC (_U16881_YC)
  );	// file.cleaned.mlir:33:30
  PDKGENFAX1 U16882 (	// file.cleaned.mlir:35:30
    .A  (_U16871_YS),	// file.cleaned.mlir:26:30
    .B  (_U16870_YC),	// file.cleaned.mlir:24:30
    .C  (A[8] & B[9]),	// file.cleaned.mlir:13:10, :28:11, :34:11
    .YS (_U16882_YS),
    .YC (_U16882_YC)
  );	// file.cleaned.mlir:35:30
  PDKGENFAX1 U16883 (	// file.cleaned.mlir:37:30
    .A  (A[7] & B[11]),	// file.cleaned.mlir:5:10, :19:11, :27:11
    .B  (_U16871_YC),	// file.cleaned.mlir:26:30
    .C  (A[8] & B[10]),	// file.cleaned.mlir:8:10, :28:11, :36:11
    .YS (_U16883_YS),
    .YC (_U16883_YC)
  );	// file.cleaned.mlir:37:30
  PDKGENHAX1 U16891 (	// file.cleaned.mlir:42:30
    .A  (_U16880_YS),	// file.cleaned.mlir:31:30
    .B  (A[9] & B[6]),	// file.cleaned.mlir:39:11, :40:11, :41:11
    .YS (_U16891_YS),
    .YC (_U16891_YC)
  );	// file.cleaned.mlir:42:30
  PDKGENFAX1 U16892 (	// file.cleaned.mlir:44:30
    .A  (_U16881_YS),	// file.cleaned.mlir:33:30
    .B  (_U16880_YC),	// file.cleaned.mlir:31:30
    .C  (A[9] & B[7]),	// file.cleaned.mlir:29:11, :39:11, :43:11
    .YS (_U16892_YS),
    .YC (_U16892_YC)
  );	// file.cleaned.mlir:44:30
  PDKGENFAX1 U16893 (	// file.cleaned.mlir:46:30
    .A  (_U16882_YS),	// file.cleaned.mlir:35:30
    .B  (_U16881_YC),	// file.cleaned.mlir:33:30
    .C  (A[9] & B[8]),	// file.cleaned.mlir:20:11, :39:11, :45:11
    .YS (_U16893_YS),
    .YC (_U16893_YC)
  );	// file.cleaned.mlir:46:30
  PDKGENFAX1 U16894 (	// file.cleaned.mlir:48:30
    .A  (_U16883_YS),	// file.cleaned.mlir:37:30
    .B  (_U16882_YC),	// file.cleaned.mlir:35:30
    .C  (A[9] & B[9]),	// file.cleaned.mlir:13:10, :39:11, :47:11
    .YS (_U16894_YS),
    .YC (_U16894_YC)
  );	// file.cleaned.mlir:48:30
  PDKGENFAX1 U16895 (	// file.cleaned.mlir:50:30
    .A  (A[8] & B[11]),	// file.cleaned.mlir:5:10, :28:11, :38:11
    .B  (_U16883_YC),	// file.cleaned.mlir:37:30
    .C  (A[9] & B[10]),	// file.cleaned.mlir:8:10, :39:11, :49:11
    .YS (_U16895_YS),
    .YC (_U16895_YC)
  );	// file.cleaned.mlir:50:30
  PDKGENHAX1 U16902 (	// file.cleaned.mlir:55:30
    .A  (_U16891_YS),	// file.cleaned.mlir:42:30
    .B  (A[10] & B[5]),	// file.cleaned.mlir:52:11, :53:11, :54:11
    .YS (_U16902_YS),
    .YC (_U16902_YC)
  );	// file.cleaned.mlir:55:30
  PDKGENFAX1 U16903 (	// file.cleaned.mlir:57:30
    .A  (_U16892_YS),	// file.cleaned.mlir:44:30
    .B  (_U16891_YC),	// file.cleaned.mlir:42:30
    .C  (A[10] & B[6]),	// file.cleaned.mlir:40:11, :52:11, :56:11
    .YS (_U16903_YS),
    .YC (_U16903_YC)
  );	// file.cleaned.mlir:57:30
  PDKGENFAX1 U16904 (	// file.cleaned.mlir:59:30
    .A  (_U16893_YS),	// file.cleaned.mlir:46:30
    .B  (_U16892_YC),	// file.cleaned.mlir:44:30
    .C  (A[10] & B[7]),	// file.cleaned.mlir:29:11, :52:11, :58:11
    .YS (_U16904_YS),
    .YC (_U16904_YC)
  );	// file.cleaned.mlir:59:30
  PDKGENFAX1 U16905 (	// file.cleaned.mlir:61:30
    .A  (_U16894_YS),	// file.cleaned.mlir:48:30
    .B  (_U16893_YC),	// file.cleaned.mlir:46:30
    .C  (A[10] & B[8]),	// file.cleaned.mlir:20:11, :52:11, :60:11
    .YS (_U16905_YS),
    .YC (_U16905_YC)
  );	// file.cleaned.mlir:61:30
  PDKGENFAX1 U16906 (	// file.cleaned.mlir:63:30
    .A  (_U16895_YS),	// file.cleaned.mlir:50:30
    .B  (_U16894_YC),	// file.cleaned.mlir:48:30
    .C  (A[10] & B[9]),	// file.cleaned.mlir:13:10, :52:11, :62:11
    .YS (_U16906_YS),
    .YC (_U16906_YC)
  );	// file.cleaned.mlir:63:30
  PDKGENFAX1 U16907 (	// file.cleaned.mlir:65:30
    .A  (A[9] & B[11]),	// file.cleaned.mlir:5:10, :39:11, :51:11
    .B  (_U16895_YC),	// file.cleaned.mlir:50:30
    .C  (A[10] & B[10]),	// file.cleaned.mlir:8:10, :52:11, :64:11
    .YS (_U16907_YS),
    .YC (_U16907_YC)
  );	// file.cleaned.mlir:65:30
  PDKGENHAX1 U16913 (	// file.cleaned.mlir:70:30
    .A  (_U16902_YS),	// file.cleaned.mlir:55:30
    .B  (A[11] & B[4]),	// file.cleaned.mlir:67:11, :68:11, :69:11
    .YS (_U16913_YS),
    .YC (_U16913_YC)
  );	// file.cleaned.mlir:70:30
  PDKGENFAX1 U16914 (	// file.cleaned.mlir:72:30
    .A  (_U16903_YS),	// file.cleaned.mlir:57:30
    .B  (_U16902_YC),	// file.cleaned.mlir:55:30
    .C  (A[11] & B[5]),	// file.cleaned.mlir:53:11, :67:11, :71:11
    .YS (_U16914_YS),
    .YC (_U16914_YC)
  );	// file.cleaned.mlir:72:30
  PDKGENFAX1 U16915 (	// file.cleaned.mlir:74:30
    .A  (_U16904_YS),	// file.cleaned.mlir:59:30
    .B  (_U16903_YC),	// file.cleaned.mlir:57:30
    .C  (A[11] & B[6]),	// file.cleaned.mlir:40:11, :67:11, :73:11
    .YS (_U16915_YS),
    .YC (_U16915_YC)
  );	// file.cleaned.mlir:74:30
  PDKGENFAX1 U16916 (	// file.cleaned.mlir:76:30
    .A  (_U16905_YS),	// file.cleaned.mlir:61:30
    .B  (_U16904_YC),	// file.cleaned.mlir:59:30
    .C  (A[11] & B[7]),	// file.cleaned.mlir:29:11, :67:11, :75:11
    .YS (_U16916_YS),
    .YC (_U16916_YC)
  );	// file.cleaned.mlir:76:30
  PDKGENFAX1 U16917 (	// file.cleaned.mlir:78:30
    .A  (_U16906_YS),	// file.cleaned.mlir:63:30
    .B  (_U16905_YC),	// file.cleaned.mlir:61:30
    .C  (A[11] & B[8]),	// file.cleaned.mlir:20:11, :67:11, :77:11
    .YS (_U16917_YS),
    .YC (_U16917_YC)
  );	// file.cleaned.mlir:78:30
  PDKGENFAX1 U16918 (	// file.cleaned.mlir:80:30
    .A  (_U16907_YS),	// file.cleaned.mlir:65:30
    .B  (_U16906_YC),	// file.cleaned.mlir:63:30
    .C  (A[11] & B[9]),	// file.cleaned.mlir:13:10, :67:11, :79:11
    .YS (_U16918_YS),
    .YC (_U16918_YC)
  );	// file.cleaned.mlir:80:30
  PDKGENFAX1 U16919 (	// file.cleaned.mlir:82:30
    .A  (A[10] & B[11]),	// file.cleaned.mlir:5:10, :52:11, :66:11
    .B  (_U16907_YC),	// file.cleaned.mlir:65:30
    .C  (A[11] & B[10]),	// file.cleaned.mlir:8:10, :67:11, :81:11
    .YS (_U16919_YS),
    .YC (_U16919_YC)
  );	// file.cleaned.mlir:82:30
  PDKGENHAX1 U16925 (	// file.cleaned.mlir:84:30
    .A  (_U16914_YS),	// file.cleaned.mlir:72:30
    .B  (_U16913_YC),	// file.cleaned.mlir:70:30
    .YS (_U16925_YS),
    .YC (_U16925_YC)
  );	// file.cleaned.mlir:84:30
  PDKGENFAX1 U16926 (	// file.cleaned.mlir:85:30
    .A  (_U16915_YS),	// file.cleaned.mlir:74:30
    .B  (_U16925_YC),	// file.cleaned.mlir:84:30
    .C  (_U16914_YC),	// file.cleaned.mlir:72:30
    .YS (_U16926_YS),
    .YC (_U16926_YC)
  );	// file.cleaned.mlir:85:30
  PDKGENFAX1 U16927 (	// file.cleaned.mlir:86:30
    .A  (_U16916_YS),	// file.cleaned.mlir:76:30
    .B  (_U16926_YC),	// file.cleaned.mlir:85:30
    .C  (_U16915_YC),	// file.cleaned.mlir:74:30
    .YS (_U16927_YS),
    .YC (_U16927_YC)
  );	// file.cleaned.mlir:86:30
  PDKGENFAX1 U16928 (	// file.cleaned.mlir:87:30
    .A  (_U16917_YS),	// file.cleaned.mlir:78:30
    .B  (_U16927_YC),	// file.cleaned.mlir:86:30
    .C  (_U16916_YC),	// file.cleaned.mlir:76:30
    .YS (_U16928_YS),
    .YC (_U16928_YC)
  );	// file.cleaned.mlir:87:30
  PDKGENFAX1 U16929 (	// file.cleaned.mlir:88:30
    .A  (_U16918_YS),	// file.cleaned.mlir:80:30
    .B  (_U16928_YC),	// file.cleaned.mlir:87:30
    .C  (_U16917_YC),	// file.cleaned.mlir:78:30
    .YS (_U16929_YS),
    .YC (_U16929_YC)
  );	// file.cleaned.mlir:88:30
  PDKGENFAX1 U16930 (	// file.cleaned.mlir:89:30
    .A  (_U16919_YS),	// file.cleaned.mlir:82:30
    .B  (_U16929_YC),	// file.cleaned.mlir:88:30
    .C  (_U16918_YC),	// file.cleaned.mlir:80:30
    .YS (_U16930_YS),
    .YC (_U16930_YC)
  );	// file.cleaned.mlir:89:30
  PDKGENFAX1 U16931 (	// file.cleaned.mlir:90:30
    .A  (A[11] & B[11]),	// file.cleaned.mlir:5:10, :67:11, :83:11
    .B  (_U16930_YC),	// file.cleaned.mlir:89:30
    .C  (_U16919_YC),	// file.cleaned.mlir:82:30
    .YS (_U16931_YS),
    .YC (_U16931_YC)
  );	// file.cleaned.mlir:90:30
  assign O =
    {_U16931_YC,
     _U16931_YS,
     _U16930_YS,
     _U16929_YS,
     _U16928_YS,
     _U16927_YS,
     _U16926_YS,
     _U16925_YS,
     _U16913_YS,
     15'h0};	// file.cleaned.mlir:3:15, :70:30, :84:30, :85:30, :86:30, :87:30, :88:30, :89:30, :90:30, :91:11, :92:5
endmodule

module PDKGENHAX1(	// file.cleaned.mlir:94:3
  input  A,	// file.cleaned.mlir:94:36
         B,	// file.cleaned.mlir:94:48
  output YS,	// file.cleaned.mlir:94:61
         YC	// file.cleaned.mlir:94:74
);

  assign YS = A ^ B;	// file.cleaned.mlir:95:10, :97:5
  assign YC = A & B;	// file.cleaned.mlir:96:10, :97:5
endmodule

module PDKGENFAX1(	// file.cleaned.mlir:99:3
  input  A,	// file.cleaned.mlir:99:36
         B,	// file.cleaned.mlir:99:48
         C,	// file.cleaned.mlir:99:60
  output YS,	// file.cleaned.mlir:99:73
         YC	// file.cleaned.mlir:99:86
);

  assign YS = A ^ B ^ C;	// file.cleaned.mlir:100:10, :105:5
  assign YC = A & B | B & C | A & C;	// file.cleaned.mlir:101:10, :102:10, :103:10, :104:10, :105:5
endmodule

