// Generated by CIRCT unknown git version
module mul16s_HEB(	// file.cleaned.mlir:2:3
  input  [15:0] A,	// file.cleaned.mlir:2:28
                B,	// file.cleaned.mlir:2:41
  output [31:0] Z	// file.cleaned.mlir:2:55
);

  assign Z = {{16{A[15]}}, A} * {{16{B[15]}}, B};	// file.cleaned.mlir:3:10, :4:10, :5:10, :6:10, :7:10, :8:10, :9:10, :10:5
endmodule

