// Generated by CIRCT unknown git version
module mul7u_06J(	// file.cleaned.mlir:2:3
  input  [6:0]  A,	// file.cleaned.mlir:2:27
                B,	// file.cleaned.mlir:2:39
  output [13:0] O	// file.cleaned.mlir:2:52
);

  wire        _GEN;	// file.cleaned.mlir:230:12
  wire        _GEN_0;	// file.cleaned.mlir:229:12
  wire        _GEN_1;	// file.cleaned.mlir:225:12
  wire        _GEN_2;	// file.cleaned.mlir:220:12
  wire        _GEN_3;	// file.cleaned.mlir:219:12
  wire        _GEN_4;	// file.cleaned.mlir:214:12
  wire        _GEN_5;	// file.cleaned.mlir:209:12
  wire        _GEN_6;	// file.cleaned.mlir:204:12
  wire        _GEN_7;	// file.cleaned.mlir:199:12
  wire        _GEN_8;	// file.cleaned.mlir:176:12
  wire        _GEN_9;	// file.cleaned.mlir:165:12
  wire        _GEN_10;	// file.cleaned.mlir:159:12
  wire        _GEN_11;	// file.cleaned.mlir:135:12
  wire        _GEN_12;	// file.cleaned.mlir:113:11
  wire [13:0] _GEN_13 =
    {_GEN, 13'h0}
    | ({1'h0, _GEN_0, 12'h0}
       | ({2'h0, _GEN_1, 11'h0}
          | ({3'h0, _GEN_3, 10'h0}
             | ({4'h0, _GEN_4, 9'h0}
                | ({5'h0, _GEN_5, 8'h0}
                   | ({6'h0, _GEN_6, 7'h0}
                      | ({7'h0, _GEN_7, 6'h0}
                         | ({8'h0, _GEN_10, 5'h0}
                            | ({9'h0, _GEN_11, 4'h0}
                               | ({10'h0, _GEN_8, 3'h0}
                                  | ({11'h0, _GEN_12, 2'h0}
                                     | ({12'h0, _GEN_9, 1'h0} | {13'h0, _GEN_2})
                                     & 14'h3FFB) & 14'h3FF7) & 14'h3FEF) & 14'h3FDF)
                         & 14'h3FBF) & 14'h3F7F) & 14'h3EFF) & 14'h3DFF) & 14'h3BFF)
          & 14'h37FF) & 14'h2FFF) & 14'h1FFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:15, :10:14, :11:15, :12:14, :13:15, :14:14, :15:18, :16:19, :17:19, :18:19, :19:18, :20:18, :21:18, :22:17, :23:17, :24:17, :25:16, :26:16, :27:15, :28:10, :29:10, :30:10, :31:10, :32:10, :33:10, :34:10, :35:10, :36:10, :37:10, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :65:11, :66:11, :113:11, :135:12, :159:12, :165:12, :176:12, :199:12, :204:12, :209:12, :214:12, :219:12, :220:12, :225:12, :229:12, :230:12
  wire        sig_56 = B[1] & A[5] & A[6];	// file.cleaned.mlir:67:11, :68:11, :70:11, :71:11
  wire        sig_55 = sig_56 ^ A[6] & B[1];	// file.cleaned.mlir:67:11, :68:11, :69:11, :71:11, :72:11
  wire        sig_84 = B[0] & A[4];	// file.cleaned.mlir:79:11, :81:11, :83:11
  wire        sig_85 = B[2] & A[4] | B[0] & (A[5] ^ A[5] ^ A[3] & B[2]);	// file.cleaned.mlir:70:11, :73:11, :74:11, :75:11, :78:11, :79:11, :80:11, :81:11, :82:11, :84:11
  wire        sig_86 = sig_55 | A[5] & B[2];	// file.cleaned.mlir:70:11, :72:11, :74:11, :76:11, :85:11
  wire        sig_89 = sig_86 ^ sig_85;	// file.cleaned.mlir:84:11, :85:11, :88:11
  wire        sig_90 = sig_55 & A[5] ^ sig_86 & sig_85;	// file.cleaned.mlir:70:11, :72:11, :84:11, :85:11, :86:11, :87:11, :89:11
  wire        sig_94 = sig_56 ^ A[6] & B[2] ^ sig_90;	// file.cleaned.mlir:67:11, :71:11, :74:11, :77:11, :89:11, :92:11
  wire        sig_95 = sig_56 & B[2] | A[6] & sig_90;	// file.cleaned.mlir:67:11, :71:11, :74:11, :89:11, :90:11, :91:11, :93:11
  wire        sig_99 = A[2] & B[3];	// file.cleaned.mlir:94:11, :95:11, :96:11
  wire        sig_100 = A[4] & B[3];	// file.cleaned.mlir:79:11, :95:11, :97:11
  wire        sig_101 = A[5] & B[3];	// file.cleaned.mlir:70:11, :95:11, :98:11
  wire        sig_114 = A[3] & B[3];	// file.cleaned.mlir:73:11, :95:11, :100:11
  wire        sig_115 = sig_84 ^ sig_99;	// file.cleaned.mlir:83:11, :96:11, :101:11
  wire        sig_118 = sig_115 ^ sig_114;	// file.cleaned.mlir:100:11, :101:11, :104:11
  wire        sig_119 = sig_84 & sig_99 ^ sig_115 & sig_114;	// file.cleaned.mlir:83:11, :96:11, :100:11, :101:11, :102:11, :103:11, :105:11
  wire        sig_120 = sig_89 ^ sig_100;	// file.cleaned.mlir:88:11, :97:11, :106:11
  wire        sig_123 = sig_120 ^ sig_119;	// file.cleaned.mlir:105:11, :106:11, :109:11
  wire        sig_124 = sig_89 & sig_100 ^ sig_120 & sig_119;	// file.cleaned.mlir:88:11, :97:11, :105:11, :106:11, :107:11, :108:11, :110:11
  wire        sig_125 = sig_94 ^ sig_101;	// file.cleaned.mlir:92:11, :98:11, :111:11
  assign _GEN_12 = sig_125 & sig_124;	// file.cleaned.mlir:110:11, :111:11, :113:11
  wire        sig_128 = sig_125 ^ sig_124;	// file.cleaned.mlir:110:11, :111:11, :114:11
  wire        sig_129 = sig_94 & sig_101 | _GEN_13[2];	// file.cleaned.mlir:66:11, :92:11, :98:11, :112:11, :115:11, :116:11
  wire        sig_133 = sig_95 ^ A[6] & B[3] ^ sig_129;	// file.cleaned.mlir:67:11, :93:11, :95:11, :99:11, :116:11, :119:11
  wire        sig_134 = sig_95 & B[3] | A[6] & sig_129;	// file.cleaned.mlir:67:11, :93:11, :95:11, :116:11, :117:11, :118:11, :120:11
  wire        sig_137 = A[2] & B[4];	// file.cleaned.mlir:94:11, :121:11, :122:11
  wire        sig_138 = A[3] & B[4];	// file.cleaned.mlir:73:11, :121:11, :123:11
  wire        sig_139 = A[4] & B[4];	// file.cleaned.mlir:79:11, :121:11, :124:11
  wire        sig_140 = A[5] & B[4];	// file.cleaned.mlir:70:11, :121:11, :125:11
  wire        sig_148 = B[4] & A[1];	// file.cleaned.mlir:121:11, :127:11, :128:12
  wire        sig_149 = sig_118 ^ sig_137;	// file.cleaned.mlir:104:11, :122:11, :129:12
  wire        sig_152 = sig_149 ^ sig_148;	// file.cleaned.mlir:128:12, :129:12, :132:12
  wire        sig_153 = sig_118 & sig_137 ^ sig_149 & sig_148;	// file.cleaned.mlir:104:11, :122:11, :128:12, :129:12, :130:12, :131:12, :133:12
  wire        sig_154 = sig_123 ^ sig_138;	// file.cleaned.mlir:109:11, :123:11, :134:12
  assign _GEN_11 = sig_123 & sig_138;	// file.cleaned.mlir:109:11, :123:11, :135:12
  wire        sig_157 = sig_154 ^ sig_153;	// file.cleaned.mlir:133:12, :134:12, :137:12
  wire        sig_158 = _GEN_13[4] | sig_154 & sig_153;	// file.cleaned.mlir:66:11, :133:12, :134:12, :136:12, :138:12, :139:12
  wire        sig_159 = sig_128 ^ sig_139;	// file.cleaned.mlir:114:11, :124:11, :140:12
  wire        sig_162 = sig_159 ^ sig_158;	// file.cleaned.mlir:139:12, :140:12, :143:12
  wire        sig_163 = sig_128 & sig_139 ^ sig_159 & sig_158;	// file.cleaned.mlir:114:11, :124:11, :139:12, :140:12, :141:12, :142:12, :144:12
  wire        sig_164 = sig_133 ^ sig_140;	// file.cleaned.mlir:119:11, :125:11, :145:12
  wire        sig_167 = sig_164 ^ sig_163;	// file.cleaned.mlir:144:12, :145:12, :148:12
  wire        sig_168 = sig_133 & sig_140 | sig_164 & sig_163;	// file.cleaned.mlir:119:11, :125:11, :144:12, :145:12, :146:12, :147:12, :149:12
  wire        sig_172 = sig_134 ^ A[6] & B[4] ^ sig_168;	// file.cleaned.mlir:67:11, :120:11, :121:11, :126:11, :149:12, :152:12
  wire        sig_173 = sig_134 & B[4] | A[6] & sig_168;	// file.cleaned.mlir:67:11, :120:11, :121:11, :149:12, :150:12, :151:12, :153:12
  wire        sig_176 = A[2] & B[5];	// file.cleaned.mlir:94:11, :154:12, :156:12
  wire        sig_177 = A[3] & B[5];	// file.cleaned.mlir:73:11, :154:12, :157:12
  wire        sig_178 = A[4] & B[5];	// file.cleaned.mlir:79:11, :154:12, :158:12
  assign _GEN_10 = A[5] & B[5];	// file.cleaned.mlir:70:11, :154:12, :159:12
  wire        sig_186 = sig_152 ^ A[1] & B[5];	// file.cleaned.mlir:127:11, :132:12, :154:12, :155:12, :161:12
  wire        sig_187 = sig_152 & A[1] & B[5];	// file.cleaned.mlir:127:11, :132:12, :154:12, :162:12
  wire        sig_188 = sig_157 ^ sig_176;	// file.cleaned.mlir:137:12, :156:12, :163:12
  assign _GEN_9 = sig_188 & sig_187;	// file.cleaned.mlir:162:12, :163:12, :165:12
  wire        sig_191 = sig_188 ^ sig_187;	// file.cleaned.mlir:162:12, :163:12, :166:12
  wire        sig_192 = sig_157 & sig_176 ^ _GEN_13[1];	// file.cleaned.mlir:66:11, :137:12, :156:12, :164:12, :167:12, :168:12
  wire        sig_193 = sig_162 ^ sig_177;	// file.cleaned.mlir:143:12, :157:12, :169:12
  wire        sig_196 = sig_193 ^ sig_192;	// file.cleaned.mlir:168:12, :169:12, :172:12
  wire        sig_197 = sig_162 & sig_177 | sig_193 & sig_192;	// file.cleaned.mlir:143:12, :157:12, :168:12, :169:12, :170:12, :171:12, :173:12
  wire        sig_198 = sig_167 ^ sig_178;	// file.cleaned.mlir:148:12, :158:12, :174:12
  assign _GEN_8 = sig_198 & sig_197;	// file.cleaned.mlir:173:12, :174:12, :176:12
  wire        sig_201 = sig_198 ^ sig_197;	// file.cleaned.mlir:173:12, :174:12, :177:12
  wire        sig_202 = sig_167 & sig_178 | _GEN_13[3];	// file.cleaned.mlir:66:11, :148:12, :158:12, :175:12, :178:12, :179:12
  wire        sig_203 = sig_172 ^ _GEN_13[5];	// file.cleaned.mlir:66:11, :152:12, :180:12, :181:12
  wire        sig_206 = sig_203 ^ sig_202;	// file.cleaned.mlir:179:12, :181:12, :184:12
  wire        sig_207 = sig_172 & _GEN_13[5] ^ sig_203 & sig_202;	// file.cleaned.mlir:66:11, :152:12, :179:12, :180:12, :181:12, :182:12, :183:12, :185:12
  wire        sig_211 = sig_173 ^ A[6] & B[5] ^ sig_207;	// file.cleaned.mlir:67:11, :153:12, :154:12, :160:12, :185:12, :188:12
  wire        sig_212 = sig_173 & B[5] | A[6] & sig_207;	// file.cleaned.mlir:67:11, :153:12, :154:12, :185:12, :186:12, :187:12, :189:12
  wire        sig_213 = A[0] & B[6];	// file.cleaned.mlir:190:12, :191:12, :192:12
  wire        sig_214 = A[1] & B[6];	// file.cleaned.mlir:127:11, :191:12, :193:12
  wire        sig_215 = A[2] & B[6];	// file.cleaned.mlir:94:11, :191:12, :194:12
  wire        sig_216 = A[3] & B[6];	// file.cleaned.mlir:73:11, :191:12, :195:12
  wire        sig_217 = A[4] & B[6];	// file.cleaned.mlir:79:11, :191:12, :196:12
  wire        sig_218 = A[5] & B[6];	// file.cleaned.mlir:70:11, :191:12, :197:12
  assign _GEN_7 = sig_186 ^ sig_213;	// file.cleaned.mlir:161:12, :192:12, :199:12
  wire        sig_221 = sig_186 & sig_213;	// file.cleaned.mlir:161:12, :192:12, :200:12
  wire        sig_222 = sig_191 ^ sig_214;	// file.cleaned.mlir:166:12, :193:12, :201:12
  assign _GEN_6 = sig_222 ^ sig_221;	// file.cleaned.mlir:200:12, :201:12, :204:12
  wire        sig_226 = sig_191 & sig_214 ^ sig_222 & sig_221;	// file.cleaned.mlir:166:12, :193:12, :200:12, :201:12, :202:12, :203:12, :205:12
  wire        sig_227 = sig_196 ^ sig_215;	// file.cleaned.mlir:172:12, :194:12, :206:12
  assign _GEN_5 = sig_227 ^ sig_226;	// file.cleaned.mlir:205:12, :206:12, :209:12
  wire        sig_231 = sig_196 & sig_215 ^ sig_227 & sig_226;	// file.cleaned.mlir:172:12, :194:12, :205:12, :206:12, :207:12, :208:12, :210:12
  wire        sig_232 = sig_201 ^ sig_216;	// file.cleaned.mlir:177:12, :195:12, :211:12
  assign _GEN_4 = sig_232 ^ sig_231;	// file.cleaned.mlir:210:12, :211:12, :214:12
  wire        sig_236 = sig_201 & sig_216 | sig_232 & sig_231;	// file.cleaned.mlir:177:12, :195:12, :210:12, :211:12, :212:12, :213:12, :215:12
  wire        sig_237 = sig_206 ^ sig_217;	// file.cleaned.mlir:184:12, :196:12, :216:12
  assign _GEN_3 = sig_237 ^ sig_236;	// file.cleaned.mlir:215:12, :216:12, :219:12
  assign _GEN_2 = sig_206 & sig_217 ^ sig_237 & sig_236;	// file.cleaned.mlir:184:12, :196:12, :215:12, :216:12, :217:12, :218:12, :220:12
  wire        sig_242 = sig_211 ^ sig_218;	// file.cleaned.mlir:188:12, :197:12, :221:12
  assign _GEN_1 = sig_242 ^ _GEN_13[0];	// file.cleaned.mlir:66:11, :221:12, :223:12, :225:12
  wire        sig_246 = sig_211 & sig_218 | sig_242 & _GEN_13[0];	// file.cleaned.mlir:66:11, :188:12, :197:12, :221:12, :222:12, :223:12, :224:12, :226:12
  assign _GEN_0 = sig_212 ^ A[6] & B[6] ^ sig_246;	// file.cleaned.mlir:67:11, :189:12, :191:12, :198:12, :226:12, :229:12
  assign _GEN = sig_212 & B[6] | A[6] & sig_246;	// file.cleaned.mlir:67:11, :189:12, :191:12, :226:12, :227:12, :228:12, :230:12
  assign O = _GEN_13;	// file.cleaned.mlir:66:11, :231:5
endmodule

