// Generated by CIRCT unknown git version
module mul8x4u_4Z7(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:29
  input  [3:0]  B,	// file.cleaned.mlir:2:41
  output [11:0] O	// file.cleaned.mlir:2:54
);

  wire sig_151;	// file.cleaned.mlir:74:11
  wire sig_150;	// file.cleaned.mlir:73:11
  wire sig_145;	// file.cleaned.mlir:70:11
  wire sig_112;	// file.cleaned.mlir:64:11
  wire sig_104;	// file.cleaned.mlir:61:11
  wire sig_97;	// file.cleaned.mlir:60:11
  wire sig_69;	// file.cleaned.mlir:59:11
  wire sig_27;	// file.cleaned.mlir:55:11
  assign sig_27 = A[7] & B[1];	// file.cleaned.mlir:53:11, :54:11, :55:11
  wire sig_68 = A[6] & B[2];	// file.cleaned.mlir:56:11, :57:11, :58:11
  assign sig_69 = A[7] & B[2];	// file.cleaned.mlir:53:11, :57:11, :59:11
  assign sig_97 = sig_27 ^ sig_68;	// file.cleaned.mlir:55:11, :58:11, :60:11
  assign sig_104 = sig_27 & sig_68;	// file.cleaned.mlir:55:11, :58:11, :61:11
  assign sig_112 = A[5] & B[3];	// file.cleaned.mlir:62:11, :63:11, :64:11
  wire sig_113 = A[6] & B[3];	// file.cleaned.mlir:56:11, :63:11, :65:11
  wire sig_114 = A[7] & B[3];	// file.cleaned.mlir:53:11, :63:11, :66:11
  wire sig_141 = sig_113 | sig_112;	// file.cleaned.mlir:64:11, :65:11, :67:11
  wire sig_142 = sig_69 | sig_113;	// file.cleaned.mlir:59:11, :65:11, :68:11
  wire sig_144 = sig_142 & sig_141;	// file.cleaned.mlir:67:11, :68:11, :69:11
  assign sig_145 = sig_142 ^ sig_141;	// file.cleaned.mlir:67:11, :68:11, :70:11
  assign sig_150 = sig_104 ^ sig_114 ^ sig_144;	// file.cleaned.mlir:61:11, :66:11, :69:11, :73:11
  assign sig_151 = sig_104 & sig_114 | A[7] & sig_144;	// file.cleaned.mlir:53:11, :61:11, :66:11, :69:11, :71:11, :72:11, :74:11
  assign O =
    {sig_151, 11'h0}
    | ({1'h0, sig_150, 10'h0}
       | ({2'h0, sig_145, 9'h0}
          | ({3'h0, sig_97, 8'h0}
             | ({4'h0, sig_69, 7'h0}
                | ({5'h0, sig_97, 6'h0}
                   | ({6'h0, sig_69, 5'h0}
                      | ({7'h0, sig_112, 4'h0}
                         | ({8'h0, sig_151, 3'h0}
                            | ({9'h0, sig_27, 2'h0} | {10'h0, sig_104, 1'h0}) & 12'hFF7)
                         & 12'hFEF) & 12'hFDF) & 12'hFBF) & 12'hF7F) & 12'hEFF) & 12'hDFF)
       & 12'hBFF) & 12'h7FF;	// file.cleaned.mlir:3:15, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:14, :11:14, :12:18, :13:19, :14:18, :15:18, :16:18, :17:17, :18:17, :19:17, :20:16, :21:15, :22:14, :23:10, :24:10, :25:10, :26:10, :27:10, :28:10, :29:10, :30:10, :31:10, :32:10, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :55:11, :59:11, :60:11, :61:11, :64:11, :70:11, :73:11, :74:11, :75:5
endmodule

