// Generated by CIRCT unknown git version
module mul8x4u_2UU(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:29
  input  [3:0]  B,	// file.cleaned.mlir:2:41
  output [11:0] O	// file.cleaned.mlir:2:54
);

  wire sig_151;	// file.cleaned.mlir:206:12
  wire sig_150;	// file.cleaned.mlir:205:12
  wire sig_145;	// file.cleaned.mlir:200:12
  wire sig_140;	// file.cleaned.mlir:195:12
  wire sig_135;	// file.cleaned.mlir:190:12
  wire sig_130;	// file.cleaned.mlir:185:12
  wire sig_125;	// file.cleaned.mlir:180:12
  wire sig_120;	// file.cleaned.mlir:175:12
  wire sig_116;	// file.cleaned.mlir:171:12
  wire sig_71;	// file.cleaned.mlir:125:12
  wire sig_29;	// file.cleaned.mlir:84:11
  wire sig_12;	// file.cleaned.mlir:59:11
  assign sig_12 = A[0] & B[0];	// file.cleaned.mlir:57:11, :58:11, :59:11
  wire sig_13 = A[1] & B[0];	// file.cleaned.mlir:58:11, :60:11, :61:11
  wire sig_14 = A[2] & B[0];	// file.cleaned.mlir:58:11, :62:11, :63:11
  wire sig_15 = A[3] & B[0];	// file.cleaned.mlir:58:11, :64:11, :65:11
  wire sig_16 = A[4] & B[0];	// file.cleaned.mlir:58:11, :66:11, :67:11
  wire sig_17 = A[5] & B[0];	// file.cleaned.mlir:58:11, :68:11, :69:11
  wire sig_18 = A[6] & B[0];	// file.cleaned.mlir:58:11, :70:11, :71:11
  wire sig_19 = A[7] & B[0];	// file.cleaned.mlir:58:11, :72:11, :73:11
  wire sig_20 = A[0] & B[1];	// file.cleaned.mlir:57:11, :74:11, :75:11
  wire sig_21 = A[1] & B[1];	// file.cleaned.mlir:60:11, :74:11, :76:11
  wire sig_22 = A[2] & B[1];	// file.cleaned.mlir:62:11, :74:11, :77:11
  wire sig_23 = A[3] & B[1];	// file.cleaned.mlir:64:11, :74:11, :78:11
  wire sig_24 = A[4] & B[1];	// file.cleaned.mlir:66:11, :74:11, :79:11
  wire sig_25 = A[5] & B[1];	// file.cleaned.mlir:68:11, :74:11, :80:11
  wire sig_26 = A[6] & B[1];	// file.cleaned.mlir:70:11, :74:11, :81:11
  wire sig_27 = A[7] & B[1];	// file.cleaned.mlir:72:11, :74:11, :82:11
  wire sig_28 = sig_13 & sig_20;	// file.cleaned.mlir:61:11, :75:11, :83:11
  assign sig_29 = sig_13 ^ sig_20;	// file.cleaned.mlir:61:11, :75:11, :84:11
  wire sig_33 = sig_14 ^ sig_21 ^ sig_28;	// file.cleaned.mlir:63:11, :76:11, :83:11, :86:11
  wire sig_34 = sig_14 & sig_21 | sig_28;	// file.cleaned.mlir:63:11, :76:11, :83:11, :85:11, :87:11
  wire sig_35 = sig_15 ^ sig_22;	// file.cleaned.mlir:65:11, :77:11, :88:11
  wire sig_38 = sig_35 ^ sig_34;	// file.cleaned.mlir:87:11, :88:11, :91:11
  wire sig_39 = sig_15 & sig_22 | sig_35 & sig_34;	// file.cleaned.mlir:65:11, :77:11, :87:11, :88:11, :89:11, :90:11, :92:11
  wire sig_40 = sig_16 ^ sig_23;	// file.cleaned.mlir:67:11, :78:11, :93:11
  wire sig_43 = sig_40 ^ sig_39;	// file.cleaned.mlir:92:11, :93:11, :96:11
  wire sig_44 = sig_16 & sig_23 | sig_40 & sig_39;	// file.cleaned.mlir:67:11, :78:11, :92:11, :93:11, :94:11, :95:11, :97:11
  wire sig_45 = sig_17 ^ sig_24;	// file.cleaned.mlir:69:11, :79:11, :98:11
  wire sig_48 = sig_45 ^ sig_44;	// file.cleaned.mlir:97:11, :98:11, :101:11
  wire sig_49 = sig_17 & sig_24 | sig_45 & sig_44;	// file.cleaned.mlir:69:11, :79:11, :97:11, :98:11, :99:11, :100:11, :102:11
  wire sig_50 = sig_18 ^ sig_25;	// file.cleaned.mlir:71:11, :80:11, :103:11
  wire sig_53 = sig_50 ^ sig_49;	// file.cleaned.mlir:102:11, :103:11, :106:11
  wire sig_54 = sig_18 & sig_25 | sig_50 & sig_49;	// file.cleaned.mlir:71:11, :80:11, :102:11, :103:11, :104:11, :105:11, :107:11
  wire sig_55 = sig_19 ^ sig_26;	// file.cleaned.mlir:73:11, :81:11, :108:11
  wire sig_58 = sig_55 ^ sig_54;	// file.cleaned.mlir:107:11, :108:11, :111:11
  wire sig_59 = sig_19 & sig_26 | sig_55 & sig_54;	// file.cleaned.mlir:73:11, :81:11, :107:11, :108:11, :109:11, :110:11, :112:11
  wire sig_60 = sig_59 & sig_27;	// file.cleaned.mlir:82:11, :112:11, :113:11
  wire sig_61 = sig_59 ^ sig_27;	// file.cleaned.mlir:82:11, :112:11, :114:11
  wire sig_62 = A[0] & B[2];	// file.cleaned.mlir:57:11, :115:11, :116:11
  wire sig_63 = A[1] & B[2];	// file.cleaned.mlir:60:11, :115:11, :117:11
  wire sig_64 = A[2] & B[2];	// file.cleaned.mlir:62:11, :115:11, :118:11
  wire sig_65 = A[3] & B[2];	// file.cleaned.mlir:64:11, :115:11, :119:11
  wire sig_66 = A[4] & B[2];	// file.cleaned.mlir:66:11, :115:11, :120:11
  wire sig_67 = A[5] & B[2];	// file.cleaned.mlir:68:11, :115:11, :121:11
  wire sig_68 = A[6] & B[2];	// file.cleaned.mlir:70:11, :115:11, :122:11
  wire sig_69 = A[7] & B[2];	// file.cleaned.mlir:72:11, :115:11, :123:11
  wire sig_70 = sig_33 & sig_62;	// file.cleaned.mlir:86:11, :116:11, :124:12
  assign sig_71 = sig_33 ^ sig_62;	// file.cleaned.mlir:86:11, :116:11, :125:12
  wire sig_72 = sig_38 ^ sig_63;	// file.cleaned.mlir:91:11, :117:11, :126:12
  wire sig_75 = sig_72 ^ sig_70;	// file.cleaned.mlir:124:12, :126:12, :129:12
  wire sig_76 = sig_38 & sig_63 | sig_72 & sig_70;	// file.cleaned.mlir:91:11, :117:11, :124:12, :126:12, :127:12, :128:12, :130:12
  wire sig_77 = sig_43 ^ sig_64;	// file.cleaned.mlir:96:11, :118:11, :131:12
  wire sig_80 = sig_77 ^ sig_76;	// file.cleaned.mlir:130:12, :131:12, :134:12
  wire sig_81 = sig_43 & sig_64 | sig_77 & sig_76;	// file.cleaned.mlir:96:11, :118:11, :130:12, :131:12, :132:12, :133:12, :135:12
  wire sig_82 = sig_48 ^ sig_65;	// file.cleaned.mlir:101:11, :119:11, :136:12
  wire sig_85 = sig_82 ^ sig_81;	// file.cleaned.mlir:135:12, :136:12, :139:12
  wire sig_86 = sig_48 & sig_65 | sig_82 & sig_81;	// file.cleaned.mlir:101:11, :119:11, :135:12, :136:12, :137:12, :138:12, :140:12
  wire sig_87 = sig_53 ^ sig_66;	// file.cleaned.mlir:106:11, :120:11, :141:12
  wire sig_90 = sig_87 ^ sig_86;	// file.cleaned.mlir:140:12, :141:12, :144:12
  wire sig_91 = sig_53 & sig_66 | sig_87 & sig_86;	// file.cleaned.mlir:106:11, :120:11, :140:12, :141:12, :142:12, :143:12, :145:12
  wire sig_92 = sig_58 ^ sig_67;	// file.cleaned.mlir:111:11, :121:11, :146:12
  wire sig_95 = sig_92 ^ sig_91;	// file.cleaned.mlir:145:12, :146:12, :149:12
  wire sig_96 = sig_58 & sig_67 | sig_92 & sig_91;	// file.cleaned.mlir:111:11, :121:11, :145:12, :146:12, :147:12, :148:12, :150:12
  wire sig_97 = sig_61 ^ sig_68;	// file.cleaned.mlir:114:11, :122:11, :151:12
  wire sig_100 = sig_97 ^ sig_96;	// file.cleaned.mlir:150:12, :151:12, :154:12
  wire sig_101 = sig_61 & sig_68 | sig_97 & sig_96;	// file.cleaned.mlir:114:11, :122:11, :150:12, :151:12, :152:12, :153:12, :155:12
  wire sig_102 = sig_60 ^ sig_69;	// file.cleaned.mlir:113:11, :123:11, :156:12
  wire sig_105 = sig_102 ^ sig_101;	// file.cleaned.mlir:155:12, :156:12, :159:12
  wire sig_106 = sig_60 & sig_69 | sig_102 & sig_101;	// file.cleaned.mlir:113:11, :123:11, :155:12, :156:12, :157:12, :158:12, :160:12
  wire sig_107 = A[0] & B[3];	// file.cleaned.mlir:57:11, :161:12, :162:12
  wire sig_108 = A[1] & B[3];	// file.cleaned.mlir:60:11, :161:12, :163:12
  wire sig_109 = A[2] & B[3];	// file.cleaned.mlir:62:11, :161:12, :164:12
  wire sig_110 = A[3] & B[3];	// file.cleaned.mlir:64:11, :161:12, :165:12
  wire sig_111 = A[4] & B[3];	// file.cleaned.mlir:66:11, :161:12, :166:12
  wire sig_112 = A[5] & B[3];	// file.cleaned.mlir:68:11, :161:12, :167:12
  wire sig_113 = A[6] & B[3];	// file.cleaned.mlir:70:11, :161:12, :168:12
  wire sig_114 = A[7] & B[3];	// file.cleaned.mlir:72:11, :161:12, :169:12
  wire sig_115 = sig_75 & sig_107;	// file.cleaned.mlir:129:12, :162:12, :170:12
  assign sig_116 = sig_75 ^ sig_107;	// file.cleaned.mlir:129:12, :162:12, :171:12
  wire sig_117 = sig_80 ^ sig_108;	// file.cleaned.mlir:134:12, :163:12, :172:12
  assign sig_120 = sig_117 ^ sig_115;	// file.cleaned.mlir:170:12, :172:12, :175:12
  wire sig_121 = sig_80 & sig_108 | sig_117 & sig_115;	// file.cleaned.mlir:134:12, :163:12, :170:12, :172:12, :173:12, :174:12, :176:12
  wire sig_122 = sig_85 ^ sig_109;	// file.cleaned.mlir:139:12, :164:12, :177:12
  assign sig_125 = sig_122 ^ sig_121;	// file.cleaned.mlir:176:12, :177:12, :180:12
  wire sig_126 = sig_85 & sig_109 | sig_122 & sig_121;	// file.cleaned.mlir:139:12, :164:12, :176:12, :177:12, :178:12, :179:12, :181:12
  wire sig_127 = sig_90 ^ sig_110;	// file.cleaned.mlir:144:12, :165:12, :182:12
  assign sig_130 = sig_127 ^ sig_126;	// file.cleaned.mlir:181:12, :182:12, :185:12
  wire sig_131 = sig_90 & sig_110 | sig_127 & sig_126;	// file.cleaned.mlir:144:12, :165:12, :181:12, :182:12, :183:12, :184:12, :186:12
  wire sig_132 = sig_95 ^ sig_111;	// file.cleaned.mlir:149:12, :166:12, :187:12
  assign sig_135 = sig_132 ^ sig_131;	// file.cleaned.mlir:186:12, :187:12, :190:12
  wire sig_136 = sig_95 & sig_111 | sig_132 & sig_131;	// file.cleaned.mlir:149:12, :166:12, :186:12, :187:12, :188:12, :189:12, :191:12
  wire sig_137 = sig_100 ^ sig_112;	// file.cleaned.mlir:154:12, :167:12, :192:12
  assign sig_140 = sig_137 ^ sig_136;	// file.cleaned.mlir:191:12, :192:12, :195:12
  wire sig_141 = sig_100 & sig_112 | sig_137 & sig_136;	// file.cleaned.mlir:154:12, :167:12, :191:12, :192:12, :193:12, :194:12, :196:12
  wire sig_142 = sig_105 ^ sig_113;	// file.cleaned.mlir:159:12, :168:12, :197:12
  assign sig_145 = sig_142 ^ sig_141;	// file.cleaned.mlir:196:12, :197:12, :200:12
  wire sig_146 = sig_105 & sig_113 | sig_142 & sig_141;	// file.cleaned.mlir:159:12, :168:12, :196:12, :197:12, :198:12, :199:12, :201:12
  wire sig_147 = sig_106 ^ sig_114;	// file.cleaned.mlir:160:12, :169:12, :202:12
  assign sig_150 = sig_147 ^ sig_146;	// file.cleaned.mlir:201:12, :202:12, :205:12
  assign sig_151 = sig_106 & sig_114 | sig_147 & sig_146;	// file.cleaned.mlir:160:12, :169:12, :201:12, :202:12, :203:12, :204:12, :206:12
  assign O =
    {sig_151, 11'h0}
    | ({1'h0, sig_150, 10'h0}
       | ({2'h0, sig_145, 9'h0}
          | ({3'h0, sig_140, 8'h0}
             | ({4'h0, sig_135, 7'h0}
                | ({5'h0, sig_130, 6'h0}
                   | ({6'h0, sig_125, 5'h0}
                      | ({7'h0, sig_120, 4'h0}
                         | ({8'h0, sig_116, 3'h0}
                            | ({9'h0, sig_71, 2'h0}
                               | ({10'h0, sig_29, 1'h0} | {11'h0, sig_12}) & 12'hFFB)
                            & 12'hFF7) & 12'hFEF) & 12'hFDF) & 12'hFBF) & 12'hF7F)
             & 12'hEFF) & 12'hDFF) & 12'hBFF) & 12'h7FF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:14, :11:15, :12:14, :13:18, :14:19, :15:18, :16:18, :17:18, :18:17, :19:17, :20:17, :21:16, :22:16, :23:15, :24:10, :25:10, :26:10, :27:10, :28:10, :29:10, :30:10, :31:10, :32:10, :33:10, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :59:11, :84:11, :125:12, :171:12, :175:12, :180:12, :185:12, :190:12, :195:12, :200:12, :205:12, :206:12, :207:5
endmodule

