// Generated by CIRCT unknown git version
module mul8x5u_00N(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:29
  input  [4:0]  B,	// file.cleaned.mlir:2:41
  output [12:0] O	// file.cleaned.mlir:2:54
);

  wire sig_197;	// file.cleaned.mlir:250:12
  wire sig_196;	// file.cleaned.mlir:249:12
  wire sig_191;	// file.cleaned.mlir:245:12
  wire sig_186;	// file.cleaned.mlir:240:12
  wire sig_181;	// file.cleaned.mlir:235:12
  wire sig_176;	// file.cleaned.mlir:230:12
  wire sig_171;	// file.cleaned.mlir:225:12
  wire sig_166;	// file.cleaned.mlir:220:12
  wire sig_162;	// file.cleaned.mlir:216:12
  wire sig_117;	// file.cleaned.mlir:171:12
  wire sig_72;	// file.cleaned.mlir:125:12
  wire sig_30;	// file.cleaned.mlir:84:11
  wire sig_14 = A[1] & B[0];	// file.cleaned.mlir:58:11, :59:11, :60:11
  wire sig_15 = A[2] & B[0];	// file.cleaned.mlir:59:11, :61:11, :62:11
  wire sig_16 = A[3] & B[0];	// file.cleaned.mlir:59:11, :63:11, :64:11
  wire sig_17 = A[4] & B[0];	// file.cleaned.mlir:59:11, :65:11, :66:11
  wire sig_18 = A[5] & B[0];	// file.cleaned.mlir:59:11, :67:11, :68:11
  wire sig_19 = A[6] & B[0];	// file.cleaned.mlir:59:11, :69:11, :70:11
  wire sig_20 = A[7] & B[0];	// file.cleaned.mlir:59:11, :71:11, :72:11
  wire sig_21 = A[0] & B[1];	// file.cleaned.mlir:73:11, :74:11, :75:11
  wire sig_22 = A[1] & B[1];	// file.cleaned.mlir:58:11, :74:11, :76:11
  wire sig_23 = A[2] & B[1];	// file.cleaned.mlir:61:11, :74:11, :77:11
  wire sig_24 = A[3] & B[1];	// file.cleaned.mlir:63:11, :74:11, :78:11
  wire sig_25 = A[4] & B[1];	// file.cleaned.mlir:65:11, :74:11, :79:11
  wire sig_26 = A[5] & B[1];	// file.cleaned.mlir:67:11, :74:11, :80:11
  wire sig_27 = A[6] & B[1];	// file.cleaned.mlir:69:11, :74:11, :81:11
  wire sig_28 = A[7] & B[1];	// file.cleaned.mlir:71:11, :74:11, :82:11
  wire sig_33 = sig_14 & sig_21;	// file.cleaned.mlir:60:11, :75:11, :83:11
  assign sig_30 = sig_14 | sig_21;	// file.cleaned.mlir:60:11, :75:11, :84:11
  wire sig_34 = sig_15 ^ sig_22 ^ sig_33;	// file.cleaned.mlir:62:11, :76:11, :83:11, :86:11
  wire sig_35 = sig_15 & sig_22 | sig_33;	// file.cleaned.mlir:62:11, :76:11, :83:11, :85:11, :87:11
  wire sig_36 = sig_16 ^ sig_23;	// file.cleaned.mlir:64:11, :77:11, :88:11
  wire sig_39 = sig_36 ^ sig_35;	// file.cleaned.mlir:87:11, :88:11, :91:11
  wire sig_40 = sig_16 & sig_23 | sig_36 & sig_35;	// file.cleaned.mlir:64:11, :77:11, :87:11, :88:11, :89:11, :90:11, :92:11
  wire sig_41 = sig_17 ^ sig_24;	// file.cleaned.mlir:66:11, :78:11, :93:11
  wire sig_44 = sig_41 ^ sig_40;	// file.cleaned.mlir:92:11, :93:11, :96:11
  wire sig_45 = sig_17 & sig_24 | sig_41 & sig_40;	// file.cleaned.mlir:66:11, :78:11, :92:11, :93:11, :94:11, :95:11, :97:11
  wire sig_46 = sig_18 ^ sig_25;	// file.cleaned.mlir:68:11, :79:11, :98:11
  wire sig_49 = sig_46 ^ sig_45;	// file.cleaned.mlir:97:11, :98:11, :101:11
  wire sig_50 = sig_18 & sig_25 | sig_46 & sig_45;	// file.cleaned.mlir:68:11, :79:11, :97:11, :98:11, :99:11, :100:11, :102:11
  wire sig_51 = sig_19 ^ sig_26;	// file.cleaned.mlir:70:11, :80:11, :103:11
  wire sig_54 = sig_51 ^ sig_50;	// file.cleaned.mlir:102:11, :103:11, :106:11
  wire sig_55 = sig_19 & sig_26 | sig_51 & sig_50;	// file.cleaned.mlir:70:11, :80:11, :102:11, :103:11, :104:11, :105:11, :107:11
  wire sig_56 = sig_20 ^ sig_27;	// file.cleaned.mlir:72:11, :81:11, :108:11
  wire sig_59 = sig_56 ^ sig_55;	// file.cleaned.mlir:107:11, :108:11, :111:11
  wire sig_60 = sig_20 & sig_27 | sig_56 & sig_55;	// file.cleaned.mlir:72:11, :81:11, :107:11, :108:11, :109:11, :110:11, :112:11
  wire sig_61 = sig_60 & sig_28;	// file.cleaned.mlir:82:11, :112:11, :113:11
  wire sig_62 = sig_60 ^ sig_28;	// file.cleaned.mlir:82:11, :112:11, :114:11
  wire sig_63 = A[0] & B[2];	// file.cleaned.mlir:73:11, :115:11, :116:11
  wire sig_64 = A[1] & B[2];	// file.cleaned.mlir:58:11, :115:11, :117:11
  wire sig_65 = A[2] & B[2];	// file.cleaned.mlir:61:11, :115:11, :118:11
  wire sig_66 = A[3] & B[2];	// file.cleaned.mlir:63:11, :115:11, :119:11
  wire sig_67 = A[4] & B[2];	// file.cleaned.mlir:65:11, :115:11, :120:11
  wire sig_68 = A[5] & B[2];	// file.cleaned.mlir:67:11, :115:11, :121:11
  wire sig_69 = A[6] & B[2];	// file.cleaned.mlir:69:11, :115:11, :122:11
  wire sig_71 = sig_34 & sig_63;	// file.cleaned.mlir:86:11, :116:11, :124:11
  assign sig_72 = sig_34 ^ sig_63;	// file.cleaned.mlir:86:11, :116:11, :125:12
  wire sig_73 = sig_39 ^ sig_64;	// file.cleaned.mlir:91:11, :117:11, :126:12
  wire sig_76 = sig_73 ^ sig_71;	// file.cleaned.mlir:124:11, :126:12, :129:12
  wire sig_77 = sig_39 & sig_64 | sig_73 & sig_71;	// file.cleaned.mlir:91:11, :117:11, :124:11, :126:12, :127:12, :128:12, :130:12
  wire sig_78 = sig_44 ^ sig_65;	// file.cleaned.mlir:96:11, :118:11, :131:12
  wire sig_81 = sig_78 ^ sig_77;	// file.cleaned.mlir:130:12, :131:12, :134:12
  wire sig_82 = sig_44 & sig_65 | sig_78 & sig_77;	// file.cleaned.mlir:96:11, :118:11, :130:12, :131:12, :132:12, :133:12, :135:12
  wire sig_83 = sig_49 ^ sig_66;	// file.cleaned.mlir:101:11, :119:11, :136:12
  wire sig_86 = sig_83 ^ sig_82;	// file.cleaned.mlir:135:12, :136:12, :139:12
  wire sig_87 = sig_49 & sig_66 | sig_83 & sig_82;	// file.cleaned.mlir:101:11, :119:11, :135:12, :136:12, :137:12, :138:12, :140:12
  wire sig_88 = sig_54 ^ sig_67;	// file.cleaned.mlir:106:11, :120:11, :141:12
  wire sig_91 = sig_88 ^ sig_87;	// file.cleaned.mlir:140:12, :141:12, :144:12
  wire sig_92 = sig_54 & sig_67 | sig_88 & sig_87;	// file.cleaned.mlir:106:11, :120:11, :140:12, :141:12, :142:12, :143:12, :145:12
  wire sig_93 = sig_59 ^ sig_68;	// file.cleaned.mlir:111:11, :121:11, :146:12
  wire sig_96 = sig_93 ^ sig_92;	// file.cleaned.mlir:145:12, :146:12, :149:12
  wire sig_97 = sig_59 & sig_68 | sig_93 & sig_92;	// file.cleaned.mlir:111:11, :121:11, :145:12, :146:12, :147:12, :148:12, :150:12
  wire sig_98 = sig_62 ^ sig_69;	// file.cleaned.mlir:114:11, :122:11, :151:12
  wire sig_101 = sig_98 ^ sig_97;	// file.cleaned.mlir:150:12, :151:12, :154:12
  wire sig_102 = sig_62 & sig_69 | sig_98 & sig_97;	// file.cleaned.mlir:114:11, :122:11, :150:12, :151:12, :152:12, :153:12, :155:12
  wire sig_103 = sig_61 ^ A[7] & B[2];	// file.cleaned.mlir:71:11, :113:11, :115:11, :123:11, :156:12
  wire sig_106 = sig_103 ^ sig_102;	// file.cleaned.mlir:155:12, :156:12, :159:12
  wire sig_107 = sig_61 & B[2] | sig_103 & sig_102;	// file.cleaned.mlir:113:11, :115:11, :155:12, :156:12, :157:12, :158:12, :160:12
  wire sig_108 = A[0] & B[3];	// file.cleaned.mlir:73:11, :161:12, :162:12
  wire sig_109 = A[1] & B[3];	// file.cleaned.mlir:58:11, :161:12, :163:12
  wire sig_110 = A[2] & B[3];	// file.cleaned.mlir:61:11, :161:12, :164:12
  wire sig_111 = A[3] & B[3];	// file.cleaned.mlir:63:11, :161:12, :165:12
  wire sig_112 = A[4] & B[3];	// file.cleaned.mlir:65:11, :161:12, :166:12
  wire sig_113 = A[5] & B[3];	// file.cleaned.mlir:67:11, :161:12, :167:12
  wire sig_114 = A[6] & B[3];	// file.cleaned.mlir:69:11, :161:12, :168:12
  wire sig_115 = A[7] & B[3];	// file.cleaned.mlir:71:11, :161:12, :169:12
  wire sig_116 = sig_76 & sig_108;	// file.cleaned.mlir:129:12, :162:12, :170:12
  assign sig_117 = sig_76 ^ sig_108;	// file.cleaned.mlir:129:12, :162:12, :171:12
  wire sig_118 = sig_81 ^ sig_109;	// file.cleaned.mlir:134:12, :163:12, :172:12
  wire sig_121 = sig_118 ^ sig_116;	// file.cleaned.mlir:170:12, :172:12, :175:12
  wire sig_122 = sig_81 & sig_109 | sig_118 & sig_116;	// file.cleaned.mlir:134:12, :163:12, :170:12, :172:12, :173:12, :174:12, :176:12
  wire sig_123 = sig_86 ^ sig_110;	// file.cleaned.mlir:139:12, :164:12, :177:12
  wire sig_126 = sig_123 ^ sig_122;	// file.cleaned.mlir:176:12, :177:12, :180:12
  wire sig_127 = sig_86 & sig_110 | sig_123 & sig_122;	// file.cleaned.mlir:139:12, :164:12, :176:12, :177:12, :178:12, :179:12, :181:12
  wire sig_128 = sig_91 ^ sig_111;	// file.cleaned.mlir:144:12, :165:12, :182:12
  wire sig_131 = sig_128 ^ sig_127;	// file.cleaned.mlir:181:12, :182:12, :185:12
  wire sig_132 = sig_91 & sig_111 | sig_128 & sig_127;	// file.cleaned.mlir:144:12, :165:12, :181:12, :182:12, :183:12, :184:12, :186:12
  wire sig_133 = sig_96 ^ sig_112;	// file.cleaned.mlir:149:12, :166:12, :187:12
  wire sig_136 = sig_133 ^ sig_132;	// file.cleaned.mlir:186:12, :187:12, :190:12
  wire sig_137 = sig_96 & sig_112 | sig_133 & sig_132;	// file.cleaned.mlir:149:12, :166:12, :186:12, :187:12, :188:12, :189:12, :191:12
  wire sig_138 = sig_101 ^ sig_113;	// file.cleaned.mlir:154:12, :167:12, :192:12
  wire sig_141 = sig_138 ^ sig_137;	// file.cleaned.mlir:191:12, :192:12, :195:12
  wire sig_142 = sig_101 & sig_113 | sig_138 & sig_137;	// file.cleaned.mlir:154:12, :167:12, :191:12, :192:12, :193:12, :194:12, :196:12
  wire sig_143 = sig_106 ^ sig_114;	// file.cleaned.mlir:159:12, :168:12, :197:12
  wire sig_146 = sig_143 ^ sig_142;	// file.cleaned.mlir:196:12, :197:12, :200:12
  wire sig_147 = sig_106 & sig_114 | sig_143 & sig_142;	// file.cleaned.mlir:159:12, :168:12, :196:12, :197:12, :198:12, :199:12, :201:12
  wire sig_151 = sig_107 ^ sig_115 ^ sig_147;	// file.cleaned.mlir:160:12, :169:12, :201:12, :204:12
  wire sig_152 = sig_107 & sig_115 | A[7] & sig_147;	// file.cleaned.mlir:71:11, :160:12, :169:12, :201:12, :202:12, :203:12, :205:12
  wire sig_153 = A[0] & B[4];	// file.cleaned.mlir:73:11, :206:12, :207:12
  wire sig_154 = A[1] & B[4];	// file.cleaned.mlir:58:11, :206:12, :208:12
  wire sig_155 = A[2] & B[4];	// file.cleaned.mlir:61:11, :206:12, :209:12
  wire sig_156 = A[3] & B[4];	// file.cleaned.mlir:63:11, :206:12, :210:12
  wire sig_157 = A[4] & B[4];	// file.cleaned.mlir:65:11, :206:12, :211:12
  wire sig_158 = A[5] & B[4];	// file.cleaned.mlir:67:11, :206:12, :212:12
  wire sig_159 = A[6] & B[4];	// file.cleaned.mlir:69:11, :206:12, :213:12
  wire sig_160 = A[7] & B[4];	// file.cleaned.mlir:71:11, :206:12, :214:12
  wire sig_161 = sig_121 & sig_153;	// file.cleaned.mlir:175:12, :207:12, :215:12
  assign sig_162 = sig_121 ^ sig_153;	// file.cleaned.mlir:175:12, :207:12, :216:12
  wire sig_163 = sig_126 ^ sig_154;	// file.cleaned.mlir:180:12, :208:12, :217:12
  assign sig_166 = sig_163 ^ sig_161;	// file.cleaned.mlir:215:12, :217:12, :220:12
  wire sig_167 = sig_126 & sig_154 | sig_163 & sig_161;	// file.cleaned.mlir:180:12, :208:12, :215:12, :217:12, :218:12, :219:12, :221:12
  wire sig_168 = sig_131 ^ sig_155;	// file.cleaned.mlir:185:12, :209:12, :222:12
  assign sig_171 = sig_168 ^ sig_167;	// file.cleaned.mlir:221:12, :222:12, :225:12
  wire sig_172 = sig_131 & sig_155 | sig_168 & sig_167;	// file.cleaned.mlir:185:12, :209:12, :221:12, :222:12, :223:12, :224:12, :226:12
  wire sig_173 = sig_136 ^ sig_156;	// file.cleaned.mlir:190:12, :210:12, :227:12
  assign sig_176 = sig_173 ^ sig_172;	// file.cleaned.mlir:226:12, :227:12, :230:12
  wire sig_177 = sig_136 & sig_156 | sig_173 & sig_172;	// file.cleaned.mlir:190:12, :210:12, :226:12, :227:12, :228:12, :229:12, :231:12
  wire sig_178 = sig_141 ^ sig_157;	// file.cleaned.mlir:195:12, :211:12, :232:12
  assign sig_181 = sig_178 ^ sig_177;	// file.cleaned.mlir:231:12, :232:12, :235:12
  wire sig_182 = sig_141 & sig_157 | sig_178 & sig_177;	// file.cleaned.mlir:195:12, :211:12, :231:12, :232:12, :233:12, :234:12, :236:12
  wire sig_183 = sig_146 ^ sig_158;	// file.cleaned.mlir:200:12, :212:12, :237:12
  assign sig_186 = sig_183 ^ sig_182;	// file.cleaned.mlir:236:12, :237:12, :240:12
  wire sig_187 = sig_146 & sig_158 | sig_183 & sig_182;	// file.cleaned.mlir:200:12, :212:12, :236:12, :237:12, :238:12, :239:12, :241:12
  wire sig_188 = sig_151 ^ sig_159;	// file.cleaned.mlir:204:12, :213:12, :242:12
  assign sig_191 = sig_188 ^ sig_187;	// file.cleaned.mlir:241:12, :242:12, :245:12
  wire sig_192 = sig_151 & sig_159 | sig_188 & sig_187;	// file.cleaned.mlir:204:12, :213:12, :241:12, :242:12, :243:12, :244:12, :246:12
  assign sig_196 = sig_152 ^ sig_160 ^ sig_192;	// file.cleaned.mlir:205:12, :214:12, :246:12, :249:12
  assign sig_197 = sig_152 & B[4] | sig_160 & sig_192;	// file.cleaned.mlir:205:12, :206:12, :214:12, :246:12, :247:12, :248:12, :250:12
  assign O =
    {sig_197, 12'h0}
    | ({1'h0, sig_196, 11'h0}
       | ({2'h0, sig_191, 10'h0}
          | ({3'h0, sig_186, 9'h0}
             | ({4'h0, sig_181, 8'h0}
                | ({5'h0, sig_176, 7'h0}
                   | ({6'h0, sig_171, 6'h0}
                      | ({7'h0, sig_166, 5'h0}
                         | ({8'h0, sig_162, 4'h0}
                            | ({9'h0, sig_117, 3'h0}
                               | ({10'h0, sig_72, 2'h0} | {11'h0, sig_30, 1'h0})
                               & 13'h1FF7) & 13'h1FEF) & 13'h1FDF) & 13'h1FBF) & 13'h1F7F)
                & 13'h1EFF) & 13'h1DFF) & 13'h1BFF) & 13'h17FF) & 13'hFFF;	// file.cleaned.mlir:3:15, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:14, :11:15, :12:14, :13:18, :14:19, :15:19, :16:18, :17:18, :18:18, :19:17, :20:17, :21:17, :22:16, :23:15, :24:14, :25:10, :26:10, :27:10, :28:10, :29:10, :30:10, :31:10, :32:10, :33:10, :34:10, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :84:11, :125:12, :171:12, :216:12, :220:12, :225:12, :230:12, :235:12, :240:12, :245:12, :249:12, :250:12, :251:5
endmodule

