// Generated by CIRCT unknown git version
module mul8x6u_0MH(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:29
  input  [5:0]  B,	// file.cleaned.mlir:2:41
  output [13:0] O	// file.cleaned.mlir:2:54
);

  wire sig_243;	// file.cleaned.mlir:71:11
  wire sig_242;	// file.cleaned.mlir:70:11
  wire sig_237;	// file.cleaned.mlir:66:11
  wire sig_232;	// file.cleaned.mlir:61:11
  wire sig_225;	// file.cleaned.mlir:59:11
  wire sig_203;	// file.cleaned.mlir:55:11
  wire sig_71;	// file.cleaned.mlir:41:11
  assign sig_71 = A[5] & B[2];	// file.cleaned.mlir:39:11, :40:11, :41:11
  wire sig_150 = B[3] & A[7];	// file.cleaned.mlir:42:11, :43:11, :44:11
  wire sig_161 = A[7] & B[4];	// file.cleaned.mlir:43:11, :46:11, :48:11
  wire sig_197 = sig_150 ^ sig_161 ^ A[6] & B[4];	// file.cleaned.mlir:44:11, :45:11, :46:11, :47:11, :48:11, :51:11
  wire sig_198 = sig_150 & B[4] | sig_161 & A[6];	// file.cleaned.mlir:44:11, :45:11, :46:11, :48:11, :49:11, :50:11, :52:11
  assign sig_203 = A[4] & B[5];	// file.cleaned.mlir:53:11, :54:11, :55:11
  wire sig_205 = A[6] & B[5];	// file.cleaned.mlir:45:11, :54:11, :57:11
  wire sig_206 = A[7] & B[5];	// file.cleaned.mlir:43:11, :54:11, :58:11
  assign sig_225 = B[5] & sig_71;	// file.cleaned.mlir:41:11, :54:11, :59:11
  assign sig_232 = sig_71 ^ A[5] & B[5] ^ sig_203;	// file.cleaned.mlir:39:11, :41:11, :54:11, :55:11, :56:11, :61:11
  wire sig_233 = sig_225 | A[5] & sig_203;	// file.cleaned.mlir:39:11, :55:11, :59:11, :60:11, :62:11
  wire sig_234 = sig_197 ^ sig_205;	// file.cleaned.mlir:51:11, :57:11, :63:11
  assign sig_237 = sig_234 ^ sig_233;	// file.cleaned.mlir:62:11, :63:11, :66:11
  wire sig_238 = sig_197 & sig_205 | sig_234 & sig_233;	// file.cleaned.mlir:51:11, :57:11, :62:11, :63:11, :64:11, :65:11, :67:11
  assign sig_242 = sig_198 ^ sig_206 ^ sig_238;	// file.cleaned.mlir:52:11, :58:11, :67:11, :70:11
  assign sig_243 = sig_198 & B[5] | sig_206 & sig_238;	// file.cleaned.mlir:52:11, :54:11, :58:11, :67:11, :68:11, :69:11, :71:11
  assign O =
    {sig_243, 13'h0}
    | ({1'h0, sig_242, 12'h0}
       | ({2'h0, sig_237, 11'h0}
          | ({3'h0, sig_232, 10'h0}
             | ({6'h0, sig_71, 7'h0}
                | ({7'h0, sig_237, 6'h0}
                   | ({11'h0, sig_203, 2'h0} | {12'h0, sig_225, 1'h0}) & 14'h3F87)
                & 14'h3F7F) & 14'h38FF) & 14'h37FF) & 14'h2FFF) & 14'h1FFF;	// file.cleaned.mlir:3:15, :4:14, :5:15, :6:19, :7:14, :8:14, :9:18, :10:15, :11:14, :12:18, :13:19, :14:19, :15:18, :16:15, :17:14, :18:10, :19:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :41:11, :55:11, :59:11, :61:11, :66:11, :70:11, :71:11, :72:5
endmodule

