// Generated by CIRCT unknown git version
module mul8x7u_0YY(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:29
  input  [6:0]  B,	// file.cleaned.mlir:2:41
  output [14:0] O	// file.cleaned.mlir:2:54
);

  wire sig_311;	// file.cleaned.mlir:97:11
  wire sig_309;	// file.cleaned.mlir:96:11
  wire sig_301;	// file.cleaned.mlir:92:11
  wire sig_263;	// file.cleaned.mlir:87:11
  wire sig_254;	// file.cleaned.mlir:82:11
  wire sig_132;	// file.cleaned.mlir:70:11
  wire sig_62;	// file.cleaned.mlir:64:11
  wire sig_59;	// file.cleaned.mlir:62:11
  wire sig_46 = A[7] & B[3];	// file.cleaned.mlir:54:11, :55:11, :56:11
  wire sig_53 = A[6] & B[4];	// file.cleaned.mlir:53:11, :57:11, :58:11
  wire sig_54 = A[7] & B[4];	// file.cleaned.mlir:53:11, :54:11, :59:11
  assign sig_59 = A[4] & B[5];	// file.cleaned.mlir:60:11, :61:11, :62:11
  wire sig_61 = A[6] & B[5];	// file.cleaned.mlir:57:11, :61:11, :63:11
  assign sig_62 = A[7] & B[5];	// file.cleaned.mlir:54:11, :61:11, :64:11
  wire sig_68 = A[5] & B[6];	// file.cleaned.mlir:65:11, :66:11, :67:11
  wire sig_69 = A[6] & B[6];	// file.cleaned.mlir:57:11, :66:11, :68:11
  wire sig_70 = A[7] & B[6];	// file.cleaned.mlir:54:11, :66:11, :69:11
  assign sig_132 = sig_46 | sig_53;	// file.cleaned.mlir:56:11, :58:11, :70:11
  wire sig_133 = sig_46 & sig_53;	// file.cleaned.mlir:56:11, :58:11, :71:11
  wire sig_137 = sig_54 & sig_61;	// file.cleaned.mlir:59:11, :63:11, :73:11
  wire sig_138 = sig_54 ^ sig_61;	// file.cleaned.mlir:59:11, :63:11, :74:11
  wire sig_188 = sig_137 ^ sig_69;	// file.cleaned.mlir:68:11, :73:11, :76:11
  wire sig_189 = sig_137 & sig_69;	// file.cleaned.mlir:68:11, :73:11, :77:11
  wire sig_224 = sig_138 & ((sig_133 | sig_68) ^ sig_68);	// file.cleaned.mlir:67:11, :71:11, :72:11, :74:11, :75:11, :78:11
  wire sig_225 = sig_138 | sig_133;	// file.cleaned.mlir:71:11, :74:11, :79:11
  wire sig_226 = sig_62 & sig_188;	// file.cleaned.mlir:64:11, :76:11, :80:11
  wire sig_227 = sig_62 ^ sig_188;	// file.cleaned.mlir:64:11, :76:11, :81:11
  assign sig_254 = sig_225 ^ sig_132;	// file.cleaned.mlir:70:11, :79:11, :82:11
  wire sig_255 = sig_225 & sig_132;	// file.cleaned.mlir:70:11, :79:11, :83:11
  wire sig_262 = sig_227 ^ sig_224 ^ sig_68;	// file.cleaned.mlir:67:11, :78:11, :81:11, :86:11
  assign sig_263 = B[6] & sig_224 | sig_227 & sig_68;	// file.cleaned.mlir:66:11, :67:11, :78:11, :81:11, :84:11, :85:11, :87:11
  wire sig_264 = sig_70 ^ sig_226;	// file.cleaned.mlir:69:11, :80:11, :88:11
  wire sig_267 = sig_264 ^ sig_189;	// file.cleaned.mlir:77:11, :88:11, :91:11
  assign sig_301 = sig_262 ^ sig_255;	// file.cleaned.mlir:83:11, :86:11, :92:11
  wire sig_302 = sig_262 & sig_255;	// file.cleaned.mlir:83:11, :86:11, :93:11
  assign sig_309 = sig_267 ^ sig_263 ^ sig_302;	// file.cleaned.mlir:87:11, :91:11, :93:11, :96:11
  assign sig_311 =
    sig_70 & sig_226 | sig_132 & sig_189 | sig_267 & sig_263 | sig_264 & sig_302;	// file.cleaned.mlir:69:11, :70:11, :77:11, :80:11, :87:11, :88:11, :89:11, :90:11, :91:11, :93:11, :94:11, :95:11, :97:11
  assign O =
    {sig_311, 14'h0}
    | ({1'h0, sig_309, 13'h0}
       | ({2'h0, sig_301, 12'h0}
          | ({3'h0, sig_254, 11'h0}
             | ({4'h0, sig_59, 10'h0}
                | ({5'h0, sig_59, 9'h0}
                   | ({9'h0, sig_263, 5'h0}
                      | ({10'h0, sig_132, 4'h0}
                         | ({12'h0, sig_263, 2'h0}
                            | ({13'h0, sig_62, 1'h0} | {14'h0, sig_59}) & 15'h7FFB)
                         & 15'h7FE7) & 15'h7FDF) & 15'h7C3F) & 15'h7BFF) & 15'h77FF)
          & 15'h6FFF) & 15'h5FFF) & 15'h3FFF;	// file.cleaned.mlir:3:14, :4:15, :5:18, :6:14, :7:14, :8:15, :9:14, :10:17, :11:15, :12:14, :13:15, :14:14, :15:19, :16:19, :17:19, :18:19, :19:19, :20:17, :21:16, :22:15, :23:10, :24:10, :25:10, :26:10, :27:10, :28:10, :29:10, :30:10, :31:10, :32:10, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :62:11, :64:11, :70:11, :82:11, :87:11, :92:11, :96:11, :97:11, :98:5
endmodule

