// Generated by CIRCT unknown git version
module mul8x7u_635(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:29
  input  [6:0]  B,	// file.cleaned.mlir:2:41
  output [14:0] O	// file.cleaned.mlir:2:54
);

  wire sig_289;	// file.cleaned.mlir:234:12
  wire sig_288;	// file.cleaned.mlir:233:12
  wire sig_283;	// file.cleaned.mlir:228:12
  wire sig_278;	// file.cleaned.mlir:223:12
  wire sig_273;	// file.cleaned.mlir:218:12
  wire sig_268;	// file.cleaned.mlir:213:12
  wire sig_263;	// file.cleaned.mlir:208:12
  wire sig_258;	// file.cleaned.mlir:204:12
  wire sig_245;	// file.cleaned.mlir:193:12
  wire sig_199;	// file.cleaned.mlir:157:12
  wire sig_195;	// file.cleaned.mlir:153:12
  wire sig_186;	// file.cleaned.mlir:144:12
  wire sig_160;	// file.cleaned.mlir:133:12
  wire sig_156;	// file.cleaned.mlir:129:11
  wire sig_29 = A[6] & B[1];	// file.cleaned.mlir:72:11, :73:11, :74:11
  wire sig_30 = A[7] & B[1];	// file.cleaned.mlir:69:11, :73:11, :75:11
  wire sig_62 = sig_29 | A[7] & B[0];	// file.cleaned.mlir:69:11, :70:11, :71:11, :74:11, :76:11
  wire sig_63 = sig_62 & sig_30;	// file.cleaned.mlir:75:11, :76:11, :77:11
  wire sig_64 = sig_62 ^ sig_30;	// file.cleaned.mlir:75:11, :76:11, :78:11
  wire sig_70 = A[5] & B[2];	// file.cleaned.mlir:79:11, :80:11, :81:11
  wire sig_71 = A[6] & B[2];	// file.cleaned.mlir:72:11, :80:11, :82:11
  wire sig_72 = A[7] & B[2];	// file.cleaned.mlir:69:11, :80:11, :83:11
  wire sig_96 = B[5] & sig_70;	// file.cleaned.mlir:81:11, :84:11, :86:11
  wire sig_98 = sig_96 ^ (B[5] | sig_29);	// file.cleaned.mlir:74:11, :84:11, :85:11, :86:11, :87:11
  wire sig_99 = sig_96 | sig_70;	// file.cleaned.mlir:81:11, :86:11, :88:11
  wire sig_100 = sig_64 ^ sig_71;	// file.cleaned.mlir:78:11, :82:11, :89:11
  wire sig_103 = sig_100 ^ sig_99;	// file.cleaned.mlir:88:11, :89:11, :92:11
  wire sig_104 = sig_64 & sig_71 | sig_100 & sig_99;	// file.cleaned.mlir:78:11, :82:11, :88:11, :89:11, :90:11, :91:11, :93:11
  wire sig_105 = sig_63 ^ sig_72;	// file.cleaned.mlir:77:11, :83:11, :94:11
  wire sig_108 = sig_105 ^ sig_104;	// file.cleaned.mlir:93:11, :94:11, :97:11
  wire sig_109 = sig_63 & sig_72 | sig_105 & sig_104;	// file.cleaned.mlir:77:11, :83:11, :93:11, :94:11, :95:11, :96:11, :98:11
  wire sig_114 = A[4] & B[3];	// file.cleaned.mlir:99:11, :100:11, :101:11
  wire sig_115 = A[5] & B[3];	// file.cleaned.mlir:79:11, :100:11, :102:11
  wire sig_116 = A[6] & B[3];	// file.cleaned.mlir:72:11, :100:11, :103:11
  wire sig_117 = A[7] & B[3];	// file.cleaned.mlir:69:11, :100:11, :104:11
  wire sig_135 = sig_98 ^ sig_114;	// file.cleaned.mlir:87:11, :101:11, :106:11
  wire _GEN = sig_135 & sig_96;	// file.cleaned.mlir:86:11, :106:11, :109:11
  wire sig_139 = sig_98 & sig_114 | sig_135 & (sig_96 | sig_114);	// file.cleaned.mlir:86:11, :87:11, :101:11, :105:11, :106:11, :107:11, :108:11, :111:11
  wire sig_140 = sig_103 ^ sig_115;	// file.cleaned.mlir:92:11, :102:11, :112:11
  wire sig_143 = sig_140 ^ sig_139;	// file.cleaned.mlir:111:11, :112:11, :115:11
  wire sig_144 = sig_103 & sig_115 | sig_140 & sig_139;	// file.cleaned.mlir:92:11, :102:11, :111:11, :112:11, :113:11, :114:11, :116:11
  wire sig_145 = sig_108 ^ sig_116;	// file.cleaned.mlir:97:11, :103:11, :117:11
  wire sig_148 = sig_145 ^ sig_144;	// file.cleaned.mlir:116:11, :117:11, :120:11
  wire sig_149 = sig_108 & sig_116 | sig_145 & sig_144;	// file.cleaned.mlir:97:11, :103:11, :116:11, :117:11, :118:11, :119:11, :121:11
  wire sig_150 = sig_109 ^ sig_117;	// file.cleaned.mlir:98:11, :104:11, :122:11
  wire sig_153 = sig_150 ^ sig_149;	// file.cleaned.mlir:121:11, :122:11, :125:11
  wire sig_154 = sig_109 & sig_117 | sig_150 & sig_149;	// file.cleaned.mlir:98:11, :104:11, :121:11, :122:11, :123:11, :124:11, :126:11
  assign sig_156 = A[1] & B[4];	// file.cleaned.mlir:127:11, :128:11, :129:11
  wire sig_158 = A[3] & B[4];	// file.cleaned.mlir:128:11, :130:12, :131:12
  wire sig_159 = A[4] & B[4];	// file.cleaned.mlir:99:11, :128:11, :132:12
  assign sig_160 = A[5] & B[4];	// file.cleaned.mlir:79:11, :128:11, :133:12
  wire sig_161 = A[6] & B[4];	// file.cleaned.mlir:72:11, :128:11, :134:12
  wire sig_162 = A[7] & B[4];	// file.cleaned.mlir:69:11, :128:11, :135:12
  wire sig_176 = ~_GEN & sig_158;	// file.cleaned.mlir:109:11, :110:11, :131:12, :137:12
  wire sig_180 = sig_143 ^ sig_159;	// file.cleaned.mlir:115:11, :132:12, :138:12
  wire sig_183 = sig_180 ^ sig_176;	// file.cleaned.mlir:137:12, :138:12, :141:12
  wire sig_184 = sig_143 & sig_159 | sig_180 & sig_176;	// file.cleaned.mlir:115:11, :132:12, :137:12, :138:12, :139:12, :140:12, :142:12
  wire sig_185 = sig_148 ^ sig_160;	// file.cleaned.mlir:120:11, :133:12, :143:12
  assign sig_186 = sig_148 & sig_160;	// file.cleaned.mlir:120:11, :133:12, :144:12
  wire sig_188 = sig_185 ^ sig_184;	// file.cleaned.mlir:142:12, :143:12, :146:12
  wire sig_189 = sig_186 | sig_185 & sig_184;	// file.cleaned.mlir:142:12, :143:12, :144:12, :145:12, :147:12
  wire sig_190 = sig_153 ^ sig_161;	// file.cleaned.mlir:125:11, :134:12, :148:12
  wire sig_193 = sig_190 ^ sig_189;	// file.cleaned.mlir:147:12, :148:12, :151:12
  wire sig_194 = sig_153 & sig_161 | sig_190 & sig_189;	// file.cleaned.mlir:125:11, :134:12, :147:12, :148:12, :149:12, :150:12, :152:12
  assign sig_195 = sig_154 ^ sig_162;	// file.cleaned.mlir:126:11, :135:12, :153:12
  wire sig_198 = sig_195 ^ sig_194;	// file.cleaned.mlir:152:12, :153:12, :156:12
  assign sig_199 = sig_154 & sig_162 | sig_195 & sig_194;	// file.cleaned.mlir:126:11, :135:12, :152:12, :153:12, :154:12, :155:12, :157:12
  wire sig_202 = A[2] & B[5];	// file.cleaned.mlir:84:11, :158:12, :159:12
  wire sig_203 = A[3] & B[5];	// file.cleaned.mlir:84:11, :130:12, :160:12
  wire sig_204 = A[4] & B[5];	// file.cleaned.mlir:84:11, :99:11, :161:12
  wire sig_205 = A[5] & B[5];	// file.cleaned.mlir:79:11, :84:11, :162:12
  wire sig_206 = A[6] & B[5];	// file.cleaned.mlir:72:11, :84:11, :163:12
  wire sig_207 = A[7] & B[5];	// file.cleaned.mlir:69:11, :84:11, :164:12
  wire sig_216 = (~_GEN ^ sig_158) & sig_202;	// file.cleaned.mlir:109:11, :110:11, :131:12, :136:12, :159:12, :165:12
  wire sig_218 = sig_202 & sig_204;	// file.cleaned.mlir:159:12, :161:12, :166:12
  wire sig_220 = sig_183 ^ sig_203;	// file.cleaned.mlir:141:12, :160:12, :167:12
  wire sig_221 = sig_183 & sig_203;	// file.cleaned.mlir:141:12, :160:12, :168:12
  wire sig_223 = sig_220 ^ sig_216;	// file.cleaned.mlir:165:12, :167:12, :170:12
  wire sig_224 = sig_221 | sig_220 & sig_216;	// file.cleaned.mlir:165:12, :167:12, :168:12, :169:12, :171:12
  wire sig_225 = sig_188 ^ sig_204;	// file.cleaned.mlir:146:12, :161:12, :172:12
  wire sig_228 = sig_225 ^ sig_224;	// file.cleaned.mlir:171:12, :172:12, :175:12
  wire sig_229 = sig_188 & sig_204 | sig_225 & sig_224;	// file.cleaned.mlir:146:12, :161:12, :171:12, :172:12, :173:12, :174:12, :176:12
  wire sig_230 = sig_193 ^ sig_205;	// file.cleaned.mlir:151:12, :162:12, :177:12
  wire sig_233 = sig_230 ^ sig_229;	// file.cleaned.mlir:176:12, :177:12, :180:12
  wire sig_234 = sig_193 & sig_205 | sig_230 & sig_229;	// file.cleaned.mlir:151:12, :162:12, :176:12, :177:12, :178:12, :179:12, :181:12
  wire sig_235 = sig_198 ^ sig_206;	// file.cleaned.mlir:156:12, :163:12, :182:12
  wire sig_238 = sig_235 ^ sig_234;	// file.cleaned.mlir:181:12, :182:12, :185:12
  wire sig_239 = sig_198 & sig_206 | sig_235 & sig_234;	// file.cleaned.mlir:156:12, :163:12, :181:12, :182:12, :183:12, :184:12, :186:12
  wire sig_243 = sig_199 ^ sig_207 ^ sig_239;	// file.cleaned.mlir:157:12, :164:12, :186:12, :189:12
  wire sig_244 = sig_199 & sig_207 | A[7] & sig_239;	// file.cleaned.mlir:69:11, :157:12, :164:12, :186:12, :187:12, :188:12, :190:12
  assign sig_245 = A[0] & B[6];	// file.cleaned.mlir:191:12, :192:12, :193:12
  wire sig_246 = A[1] & B[6];	// file.cleaned.mlir:127:11, :192:12, :194:12
  wire sig_247 = A[2] & B[6];	// file.cleaned.mlir:158:12, :192:12, :195:12
  wire sig_248 = A[3] & B[6];	// file.cleaned.mlir:130:12, :192:12, :196:12
  wire sig_249 = A[4] & B[6];	// file.cleaned.mlir:99:11, :192:12, :197:12
  wire sig_250 = A[5] & B[6];	// file.cleaned.mlir:79:11, :192:12, :198:12
  wire sig_251 = A[6] & B[6];	// file.cleaned.mlir:72:11, :192:12, :199:12
  wire sig_252 = A[7] & B[6];	// file.cleaned.mlir:69:11, :192:12, :200:12
  wire sig_256 = sig_218 & sig_246;	// file.cleaned.mlir:166:12, :194:12, :203:12
  assign sig_258 = sig_218 ^ sig_246 | sig_221 & sig_246;	// file.cleaned.mlir:166:12, :168:12, :194:12, :201:12, :202:12, :204:12
  wire sig_260 = sig_223 ^ sig_247;	// file.cleaned.mlir:170:12, :195:12, :205:12
  assign sig_263 = sig_260 ^ sig_256;	// file.cleaned.mlir:203:12, :205:12, :208:12
  wire sig_264 = sig_223 & sig_247 | sig_260 & sig_256;	// file.cleaned.mlir:170:12, :195:12, :203:12, :205:12, :206:12, :207:12, :209:12
  wire sig_265 = sig_228 ^ sig_248;	// file.cleaned.mlir:175:12, :196:12, :210:12
  assign sig_268 = sig_265 ^ sig_264;	// file.cleaned.mlir:209:12, :210:12, :213:12
  wire sig_269 = sig_228 & sig_248 | sig_265 & sig_264;	// file.cleaned.mlir:175:12, :196:12, :209:12, :210:12, :211:12, :212:12, :214:12
  wire sig_270 = sig_233 ^ sig_249;	// file.cleaned.mlir:180:12, :197:12, :215:12
  assign sig_273 = sig_270 ^ sig_269;	// file.cleaned.mlir:214:12, :215:12, :218:12
  wire sig_274 = sig_233 & sig_249 | sig_270 & sig_269;	// file.cleaned.mlir:180:12, :197:12, :214:12, :215:12, :216:12, :217:12, :219:12
  wire sig_275 = sig_238 ^ sig_250;	// file.cleaned.mlir:185:12, :198:12, :220:12
  assign sig_278 = sig_275 ^ sig_274;	// file.cleaned.mlir:219:12, :220:12, :223:12
  wire sig_279 = sig_238 & sig_250 | sig_275 & sig_274;	// file.cleaned.mlir:185:12, :198:12, :219:12, :220:12, :221:12, :222:12, :224:12
  wire sig_280 = sig_243 ^ sig_251;	// file.cleaned.mlir:189:12, :199:12, :225:12
  assign sig_283 = sig_280 ^ sig_279;	// file.cleaned.mlir:224:12, :225:12, :228:12
  wire sig_284 = sig_243 & sig_251 | sig_280 & sig_279;	// file.cleaned.mlir:189:12, :199:12, :224:12, :225:12, :226:12, :227:12, :229:12
  wire sig_285 = sig_244 ^ sig_252;	// file.cleaned.mlir:190:12, :200:12, :230:12
  assign sig_288 = sig_285 ^ sig_284;	// file.cleaned.mlir:229:12, :230:12, :233:12
  assign sig_289 = sig_244 & sig_252 | sig_285 & sig_284;	// file.cleaned.mlir:190:12, :200:12, :229:12, :230:12, :231:12, :232:12, :234:12
  assign O =
    {sig_289, 14'h0}
    | ({1'h0, sig_288, 13'h0}
       | ({2'h0, sig_283, 12'h0}
          | ({3'h0, sig_278, 11'h0}
             | ({4'h0, sig_273, 10'h0}
                | ({5'h0, sig_268, 9'h0}
                   | ({6'h0, sig_263, 8'h0}
                      | ({7'h0, sig_258, 7'h0}
                         | ({8'h0, sig_245, 6'h0}
                            | ({9'h0, sig_156, 5'h0}
                               | ({10'h0, sig_160, 4'h0}
                                  | ({11'h0, sig_195, 3'h0}
                                     | ({13'h0, sig_199, 1'h0} | {14'h0, sig_186})
                                     & 15'h7FF3) & 15'h7FEF) & 15'h7FDF) & 15'h7FBF)
                         & 15'h7F7F) & 15'h7EFF) & 15'h7DFF) & 15'h7BFF) & 15'h77FF)
          & 15'h6FFF) & 15'h5FFF) & 15'h3FFF;	// file.cleaned.mlir:3:14, :4:15, :5:14, :6:14, :7:14, :8:14, :9:14, :10:15, :11:14, :12:15, :13:14, :14:17, :15:15, :16:14, :18:19, :19:19, :20:19, :21:19, :22:19, :23:18, :24:18, :25:18, :26:17, :27:17, :28:17, :29:15, :30:10, :31:10, :32:10, :33:10, :34:10, :35:10, :36:10, :37:10, :38:10, :39:10, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :65:11, :66:11, :67:11, :68:11, :129:11, :133:12, :144:12, :153:12, :157:12, :193:12, :204:12, :208:12, :213:12, :218:12, :223:12, :228:12, :233:12, :234:12, :235:5
endmodule

