// Generated by CIRCT unknown git version
module mul8s_1L2H(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:28
                B,	// file.cleaned.mlir:2:40
  output [15:0] O	// file.cleaned.mlir:2:53
);

  wire _U216_YS;	// file.cleaned.mlir:128:26
  wire _U215_YS;	// file.cleaned.mlir:127:26
  wire _U215_YC;	// file.cleaned.mlir:127:26
  wire _U214_YS;	// file.cleaned.mlir:126:26
  wire _U214_YC;	// file.cleaned.mlir:126:26
  wire _U213_YS;	// file.cleaned.mlir:125:26
  wire _U213_YC;	// file.cleaned.mlir:125:26
  wire _U212_YS;	// file.cleaned.mlir:124:26
  wire _U212_YC;	// file.cleaned.mlir:124:26
  wire _U211_YS;	// file.cleaned.mlir:123:26
  wire _U211_YC;	// file.cleaned.mlir:123:26
  wire _U210_YS;	// file.cleaned.mlir:122:26
  wire _U210_YC;	// file.cleaned.mlir:122:26
  wire _U208_YS;	// file.cleaned.mlir:121:26
  wire _U208_YC;	// file.cleaned.mlir:121:26
  wire _U207_YS;	// file.cleaned.mlir:119:26
  wire _U207_YC;	// file.cleaned.mlir:119:26
  wire _U206_YS;	// file.cleaned.mlir:116:26
  wire _U206_YC;	// file.cleaned.mlir:116:26
  wire _U205_YS;	// file.cleaned.mlir:113:26
  wire _U205_YC;	// file.cleaned.mlir:113:26
  wire _U204_YS;	// file.cleaned.mlir:110:26
  wire _U204_YC;	// file.cleaned.mlir:110:26
  wire _U203_YS;	// file.cleaned.mlir:107:26
  wire _U203_YC;	// file.cleaned.mlir:107:26
  wire _U202_YS;	// file.cleaned.mlir:104:26
  wire _U202_YC;	// file.cleaned.mlir:104:26
  wire _U200_YS;	// file.cleaned.mlir:100:26
  wire _U200_YC;	// file.cleaned.mlir:100:26
  wire _U199_YS;	// file.cleaned.mlir:97:26
  wire _U199_YC;	// file.cleaned.mlir:97:26
  wire _U198_YS;	// file.cleaned.mlir:95:26
  wire _U198_YC;	// file.cleaned.mlir:95:26
  wire _U197_YS;	// file.cleaned.mlir:93:26
  wire _U197_YC;	// file.cleaned.mlir:93:26
  wire _U196_YS;	// file.cleaned.mlir:91:26
  wire _U196_YC;	// file.cleaned.mlir:91:26
  wire _U195_YS;	// file.cleaned.mlir:89:26
  wire _U195_YC;	// file.cleaned.mlir:89:26
  wire _U194_YS;	// file.cleaned.mlir:87:26
  wire _U194_YC;	// file.cleaned.mlir:87:26
  wire _U192_YS;	// file.cleaned.mlir:84:26
  wire _U192_YC;	// file.cleaned.mlir:84:26
  wire _U191_YS;	// file.cleaned.mlir:81:26
  wire _U191_YC;	// file.cleaned.mlir:81:26
  wire _U190_YS;	// file.cleaned.mlir:79:26
  wire _U190_YC;	// file.cleaned.mlir:79:26
  wire _U189_YS;	// file.cleaned.mlir:77:26
  wire _U189_YC;	// file.cleaned.mlir:77:26
  wire _U188_YS;	// file.cleaned.mlir:75:26
  wire _U188_YC;	// file.cleaned.mlir:75:26
  wire _U187_YS;	// file.cleaned.mlir:73:26
  wire _U187_YC;	// file.cleaned.mlir:73:26
  wire _U186_YS;	// file.cleaned.mlir:71:26
  wire _U186_YC;	// file.cleaned.mlir:71:26
  wire _U184_YS;	// file.cleaned.mlir:68:26
  wire _U184_YC;	// file.cleaned.mlir:68:26
  wire _U183_YS;	// file.cleaned.mlir:65:26
  wire _U183_YC;	// file.cleaned.mlir:65:26
  wire _U182_YS;	// file.cleaned.mlir:63:26
  wire _U182_YC;	// file.cleaned.mlir:63:26
  wire _U181_YS;	// file.cleaned.mlir:61:26
  wire _U181_YC;	// file.cleaned.mlir:61:26
  wire _U180_YS;	// file.cleaned.mlir:59:26
  wire _U180_YC;	// file.cleaned.mlir:59:26
  wire _U179_YS;	// file.cleaned.mlir:57:26
  wire _U179_YC;	// file.cleaned.mlir:57:26
  wire _U178_YS;	// file.cleaned.mlir:55:26
  wire _U178_YC;	// file.cleaned.mlir:55:26
  wire _U176_YS;	// file.cleaned.mlir:52:26
  wire _U176_YC;	// file.cleaned.mlir:52:26
  wire _U175_YS;	// file.cleaned.mlir:49:26
  wire _U175_YC;	// file.cleaned.mlir:49:26
  wire _U174_YS;	// file.cleaned.mlir:47:26
  wire _U174_YC;	// file.cleaned.mlir:47:26
  wire _U173_YS;	// file.cleaned.mlir:45:26
  wire _U173_YC;	// file.cleaned.mlir:45:26
  wire _U172_YS;	// file.cleaned.mlir:43:26
  wire _U172_YC;	// file.cleaned.mlir:43:26
  wire _U171_YS;	// file.cleaned.mlir:41:26
  wire _U171_YC;	// file.cleaned.mlir:41:26
  wire _U170_YS;	// file.cleaned.mlir:39:26
  wire _U170_YC;	// file.cleaned.mlir:39:26
  wire _U168_YS;	// file.cleaned.mlir:36:26
  wire _U168_YC;	// file.cleaned.mlir:36:26
  wire _U167_YS;	// file.cleaned.mlir:33:26
  wire _U167_YC;	// file.cleaned.mlir:33:26
  wire _U166_YS;	// file.cleaned.mlir:31:26
  wire _U166_YC;	// file.cleaned.mlir:31:26
  wire _U165_YS;	// file.cleaned.mlir:29:26
  wire _U165_YC;	// file.cleaned.mlir:29:26
  wire _U164_YS;	// file.cleaned.mlir:27:26
  wire _U164_YC;	// file.cleaned.mlir:27:26
  wire _U163_YS;	// file.cleaned.mlir:25:26
  wire _U163_YC;	// file.cleaned.mlir:25:26
  wire _U162_YS;	// file.cleaned.mlir:23:26
  wire _U162_YC;	// file.cleaned.mlir:23:26
  PDKGENHAX1 U162 (	// file.cleaned.mlir:23:26
    .A  (A[1] & B[2]),	// file.cleaned.mlir:5:10, :8:10, :9:10
    .B  (A[2] & B[1]),	// file.cleaned.mlir:6:10, :21:11, :22:11
    .YS (_U162_YS),
    .YC (_U162_YC)
  );	// file.cleaned.mlir:23:26
  PDKGENHAX1 U163 (	// file.cleaned.mlir:25:26
    .A  (A[1] & B[3]),	// file.cleaned.mlir:5:10, :10:10, :11:10
    .B  (A[2] & B[2]),	// file.cleaned.mlir:8:10, :21:11, :24:11
    .YS (_U163_YS),
    .YC (_U163_YC)
  );	// file.cleaned.mlir:25:26
  PDKGENHAX1 U164 (	// file.cleaned.mlir:27:26
    .A  (A[1] & B[4]),	// file.cleaned.mlir:5:10, :12:10, :13:10
    .B  (A[2] & B[3]),	// file.cleaned.mlir:10:10, :21:11, :26:11
    .YS (_U164_YS),
    .YC (_U164_YC)
  );	// file.cleaned.mlir:27:26
  PDKGENHAX1 U165 (	// file.cleaned.mlir:29:26
    .A  (A[1] & B[5]),	// file.cleaned.mlir:5:10, :14:10, :15:11
    .B  (A[2] & B[4]),	// file.cleaned.mlir:12:10, :21:11, :28:11
    .YS (_U165_YS),
    .YC (_U165_YC)
  );	// file.cleaned.mlir:29:26
  PDKGENHAX1 U166 (	// file.cleaned.mlir:31:26
    .A  (A[1] & B[6]),	// file.cleaned.mlir:5:10, :16:11, :17:11
    .B  (A[2] & B[5]),	// file.cleaned.mlir:14:10, :21:11, :30:11
    .YS (_U166_YS),
    .YC (_U166_YC)
  );	// file.cleaned.mlir:31:26
  PDKGENHAX1 U167 (	// file.cleaned.mlir:33:26
    .A  (~(A[1] & B[7])),	// file.cleaned.mlir:5:10, :18:11, :19:11, :20:11
    .B  (A[2] & B[6]),	// file.cleaned.mlir:16:11, :21:11, :32:11
    .YS (_U167_YS),
    .YC (_U167_YC)
  );	// file.cleaned.mlir:33:26
  PDKGENHAX1 U168 (	// file.cleaned.mlir:36:26
    .A  (1'h1),	// file.cleaned.mlir:4:13
    .B  (~(A[2] & B[7])),	// file.cleaned.mlir:18:11, :21:11, :34:11, :35:11
    .YS (_U168_YS),
    .YC (_U168_YC)
  );	// file.cleaned.mlir:36:26
  PDKGENFAX1 U170 (	// file.cleaned.mlir:39:26
    .A  (_U163_YS),	// file.cleaned.mlir:25:26
    .B  (_U162_YC),	// file.cleaned.mlir:23:26
    .C  (A[3] & B[1]),	// file.cleaned.mlir:6:10, :37:11, :38:11
    .YS (_U170_YS),
    .YC (_U170_YC)
  );	// file.cleaned.mlir:39:26
  PDKGENFAX1 U171 (	// file.cleaned.mlir:41:26
    .A  (_U164_YS),	// file.cleaned.mlir:27:26
    .B  (_U163_YC),	// file.cleaned.mlir:25:26
    .C  (A[3] & B[2]),	// file.cleaned.mlir:8:10, :37:11, :40:11
    .YS (_U171_YS),
    .YC (_U171_YC)
  );	// file.cleaned.mlir:41:26
  PDKGENFAX1 U172 (	// file.cleaned.mlir:43:26
    .A  (_U165_YS),	// file.cleaned.mlir:29:26
    .B  (_U164_YC),	// file.cleaned.mlir:27:26
    .C  (A[3] & B[3]),	// file.cleaned.mlir:10:10, :37:11, :42:11
    .YS (_U172_YS),
    .YC (_U172_YC)
  );	// file.cleaned.mlir:43:26
  PDKGENFAX1 U173 (	// file.cleaned.mlir:45:26
    .A  (_U166_YS),	// file.cleaned.mlir:31:26
    .B  (_U165_YC),	// file.cleaned.mlir:29:26
    .C  (A[3] & B[4]),	// file.cleaned.mlir:12:10, :37:11, :44:11
    .YS (_U173_YS),
    .YC (_U173_YC)
  );	// file.cleaned.mlir:45:26
  PDKGENFAX1 U174 (	// file.cleaned.mlir:47:26
    .A  (_U167_YS),	// file.cleaned.mlir:33:26
    .B  (_U166_YC),	// file.cleaned.mlir:31:26
    .C  (A[3] & B[5]),	// file.cleaned.mlir:14:10, :37:11, :46:11
    .YS (_U174_YS),
    .YC (_U174_YC)
  );	// file.cleaned.mlir:47:26
  PDKGENFAX1 U175 (	// file.cleaned.mlir:49:26
    .A  (_U168_YS),	// file.cleaned.mlir:36:26
    .B  (_U167_YC),	// file.cleaned.mlir:33:26
    .C  (A[3] & B[6]),	// file.cleaned.mlir:16:11, :37:11, :48:11
    .YS (_U175_YS),
    .YC (_U175_YC)
  );	// file.cleaned.mlir:49:26
  PDKGENHAX1 U176 (	// file.cleaned.mlir:52:26
    .A  (_U168_YC),	// file.cleaned.mlir:36:26
    .B  (~(A[3] & B[7])),	// file.cleaned.mlir:18:11, :37:11, :50:11, :51:11
    .YS (_U176_YS),
    .YC (_U176_YC)
  );	// file.cleaned.mlir:52:26
  PDKGENFAX1 U178 (	// file.cleaned.mlir:55:26
    .A  (_U171_YS),	// file.cleaned.mlir:41:26
    .B  (_U170_YC),	// file.cleaned.mlir:39:26
    .C  (A[4] & B[1]),	// file.cleaned.mlir:6:10, :53:11, :54:11
    .YS (_U178_YS),
    .YC (_U178_YC)
  );	// file.cleaned.mlir:55:26
  PDKGENFAX1 U179 (	// file.cleaned.mlir:57:26
    .A  (_U172_YS),	// file.cleaned.mlir:43:26
    .B  (_U171_YC),	// file.cleaned.mlir:41:26
    .C  (A[4] & B[2]),	// file.cleaned.mlir:8:10, :53:11, :56:11
    .YS (_U179_YS),
    .YC (_U179_YC)
  );	// file.cleaned.mlir:57:26
  PDKGENFAX1 U180 (	// file.cleaned.mlir:59:26
    .A  (_U173_YS),	// file.cleaned.mlir:45:26
    .B  (_U172_YC),	// file.cleaned.mlir:43:26
    .C  (A[4] & B[3]),	// file.cleaned.mlir:10:10, :53:11, :58:11
    .YS (_U180_YS),
    .YC (_U180_YC)
  );	// file.cleaned.mlir:59:26
  PDKGENFAX1 U181 (	// file.cleaned.mlir:61:26
    .A  (_U174_YS),	// file.cleaned.mlir:47:26
    .B  (_U173_YC),	// file.cleaned.mlir:45:26
    .C  (A[4] & B[4]),	// file.cleaned.mlir:12:10, :53:11, :60:11
    .YS (_U181_YS),
    .YC (_U181_YC)
  );	// file.cleaned.mlir:61:26
  PDKGENFAX1 U182 (	// file.cleaned.mlir:63:26
    .A  (_U175_YS),	// file.cleaned.mlir:49:26
    .B  (_U174_YC),	// file.cleaned.mlir:47:26
    .C  (A[4] & B[5]),	// file.cleaned.mlir:14:10, :53:11, :62:11
    .YS (_U182_YS),
    .YC (_U182_YC)
  );	// file.cleaned.mlir:63:26
  PDKGENFAX1 U183 (	// file.cleaned.mlir:65:26
    .A  (_U176_YS),	// file.cleaned.mlir:52:26
    .B  (_U175_YC),	// file.cleaned.mlir:49:26
    .C  (A[4] & B[6]),	// file.cleaned.mlir:16:11, :53:11, :64:11
    .YS (_U183_YS),
    .YC (_U183_YC)
  );	// file.cleaned.mlir:65:26
  PDKGENHAX1 U184 (	// file.cleaned.mlir:68:26
    .A  (_U176_YC),	// file.cleaned.mlir:52:26
    .B  (~(A[4] & B[7])),	// file.cleaned.mlir:18:11, :53:11, :66:11, :67:11
    .YS (_U184_YS),
    .YC (_U184_YC)
  );	// file.cleaned.mlir:68:26
  PDKGENFAX1 U186 (	// file.cleaned.mlir:71:26
    .A  (_U179_YS),	// file.cleaned.mlir:57:26
    .B  (_U178_YC),	// file.cleaned.mlir:55:26
    .C  (A[5] & B[1]),	// file.cleaned.mlir:6:10, :69:11, :70:11
    .YS (_U186_YS),
    .YC (_U186_YC)
  );	// file.cleaned.mlir:71:26
  PDKGENFAX1 U187 (	// file.cleaned.mlir:73:26
    .A  (_U180_YS),	// file.cleaned.mlir:59:26
    .B  (_U179_YC),	// file.cleaned.mlir:57:26
    .C  (A[5] & B[2]),	// file.cleaned.mlir:8:10, :69:11, :72:11
    .YS (_U187_YS),
    .YC (_U187_YC)
  );	// file.cleaned.mlir:73:26
  PDKGENFAX1 U188 (	// file.cleaned.mlir:75:26
    .A  (_U181_YS),	// file.cleaned.mlir:61:26
    .B  (_U180_YC),	// file.cleaned.mlir:59:26
    .C  (A[5] & B[3]),	// file.cleaned.mlir:10:10, :69:11, :74:11
    .YS (_U188_YS),
    .YC (_U188_YC)
  );	// file.cleaned.mlir:75:26
  PDKGENFAX1 U189 (	// file.cleaned.mlir:77:26
    .A  (_U182_YS),	// file.cleaned.mlir:63:26
    .B  (_U181_YC),	// file.cleaned.mlir:61:26
    .C  (A[5] & B[4]),	// file.cleaned.mlir:12:10, :69:11, :76:11
    .YS (_U189_YS),
    .YC (_U189_YC)
  );	// file.cleaned.mlir:77:26
  PDKGENFAX1 U190 (	// file.cleaned.mlir:79:26
    .A  (_U183_YS),	// file.cleaned.mlir:65:26
    .B  (_U182_YC),	// file.cleaned.mlir:63:26
    .C  (A[5] & B[5]),	// file.cleaned.mlir:14:10, :69:11, :78:11
    .YS (_U190_YS),
    .YC (_U190_YC)
  );	// file.cleaned.mlir:79:26
  PDKGENFAX1 U191 (	// file.cleaned.mlir:81:26
    .A  (_U184_YS),	// file.cleaned.mlir:68:26
    .B  (_U183_YC),	// file.cleaned.mlir:65:26
    .C  (A[5] & B[6]),	// file.cleaned.mlir:16:11, :69:11, :80:11
    .YS (_U191_YS),
    .YC (_U191_YC)
  );	// file.cleaned.mlir:81:26
  PDKGENHAX1 U192 (	// file.cleaned.mlir:84:26
    .A  (_U184_YC),	// file.cleaned.mlir:68:26
    .B  (~(A[5] & B[7])),	// file.cleaned.mlir:18:11, :69:11, :82:11, :83:11
    .YS (_U192_YS),
    .YC (_U192_YC)
  );	// file.cleaned.mlir:84:26
  PDKGENFAX1 U194 (	// file.cleaned.mlir:87:26
    .A  (_U187_YS),	// file.cleaned.mlir:73:26
    .B  (_U186_YC),	// file.cleaned.mlir:71:26
    .C  (A[6] & B[1]),	// file.cleaned.mlir:6:10, :85:11, :86:11
    .YS (_U194_YS),
    .YC (_U194_YC)
  );	// file.cleaned.mlir:87:26
  PDKGENFAX1 U195 (	// file.cleaned.mlir:89:26
    .A  (_U188_YS),	// file.cleaned.mlir:75:26
    .B  (_U187_YC),	// file.cleaned.mlir:73:26
    .C  (A[6] & B[2]),	// file.cleaned.mlir:8:10, :85:11, :88:11
    .YS (_U195_YS),
    .YC (_U195_YC)
  );	// file.cleaned.mlir:89:26
  PDKGENFAX1 U196 (	// file.cleaned.mlir:91:26
    .A  (_U189_YS),	// file.cleaned.mlir:77:26
    .B  (_U188_YC),	// file.cleaned.mlir:75:26
    .C  (A[6] & B[3]),	// file.cleaned.mlir:10:10, :85:11, :90:11
    .YS (_U196_YS),
    .YC (_U196_YC)
  );	// file.cleaned.mlir:91:26
  PDKGENFAX1 U197 (	// file.cleaned.mlir:93:26
    .A  (_U190_YS),	// file.cleaned.mlir:79:26
    .B  (_U189_YC),	// file.cleaned.mlir:77:26
    .C  (A[6] & B[4]),	// file.cleaned.mlir:12:10, :85:11, :92:11
    .YS (_U197_YS),
    .YC (_U197_YC)
  );	// file.cleaned.mlir:93:26
  PDKGENFAX1 U198 (	// file.cleaned.mlir:95:26
    .A  (_U191_YS),	// file.cleaned.mlir:81:26
    .B  (_U190_YC),	// file.cleaned.mlir:79:26
    .C  (A[6] & B[5]),	// file.cleaned.mlir:14:10, :85:11, :94:11
    .YS (_U198_YS),
    .YC (_U198_YC)
  );	// file.cleaned.mlir:95:26
  PDKGENFAX1 U199 (	// file.cleaned.mlir:97:26
    .A  (_U192_YS),	// file.cleaned.mlir:84:26
    .B  (_U191_YC),	// file.cleaned.mlir:81:26
    .C  (A[6] & B[6]),	// file.cleaned.mlir:16:11, :85:11, :96:11
    .YS (_U199_YS),
    .YC (_U199_YC)
  );	// file.cleaned.mlir:97:26
  PDKGENHAX1 U200 (	// file.cleaned.mlir:100:26
    .A  (_U192_YC),	// file.cleaned.mlir:84:26
    .B  (~(A[6] & B[7])),	// file.cleaned.mlir:18:11, :85:11, :98:11, :99:11
    .YS (_U200_YS),
    .YC (_U200_YC)
  );	// file.cleaned.mlir:100:26
  PDKGENFAX1 U202 (	// file.cleaned.mlir:104:26
    .A  (_U195_YS),	// file.cleaned.mlir:89:26
    .B  (_U194_YC),	// file.cleaned.mlir:87:26
    .C  (~(A[7] & B[1])),	// file.cleaned.mlir:6:10, :101:11, :102:11, :103:11
    .YS (_U202_YS),
    .YC (_U202_YC)
  );	// file.cleaned.mlir:104:26
  PDKGENFAX1 U203 (	// file.cleaned.mlir:107:26
    .A  (_U196_YS),	// file.cleaned.mlir:91:26
    .B  (_U195_YC),	// file.cleaned.mlir:89:26
    .C  (~(A[7] & B[2])),	// file.cleaned.mlir:8:10, :101:11, :105:11, :106:11
    .YS (_U203_YS),
    .YC (_U203_YC)
  );	// file.cleaned.mlir:107:26
  PDKGENFAX1 U204 (	// file.cleaned.mlir:110:26
    .A  (_U197_YS),	// file.cleaned.mlir:93:26
    .B  (_U196_YC),	// file.cleaned.mlir:91:26
    .C  (~(A[7] & B[3])),	// file.cleaned.mlir:10:10, :101:11, :108:11, :109:11
    .YS (_U204_YS),
    .YC (_U204_YC)
  );	// file.cleaned.mlir:110:26
  PDKGENFAX1 U205 (	// file.cleaned.mlir:113:26
    .A  (_U198_YS),	// file.cleaned.mlir:95:26
    .B  (_U197_YC),	// file.cleaned.mlir:93:26
    .C  (~(A[7] & B[4])),	// file.cleaned.mlir:12:10, :101:11, :111:11, :112:11
    .YS (_U205_YS),
    .YC (_U205_YC)
  );	// file.cleaned.mlir:113:26
  PDKGENFAX1 U206 (	// file.cleaned.mlir:116:26
    .A  (_U199_YS),	// file.cleaned.mlir:97:26
    .B  (_U198_YC),	// file.cleaned.mlir:95:26
    .C  (~(A[7] & B[5])),	// file.cleaned.mlir:14:10, :101:11, :114:11, :115:11
    .YS (_U206_YS),
    .YC (_U206_YC)
  );	// file.cleaned.mlir:116:26
  PDKGENFAX1 U207 (	// file.cleaned.mlir:119:26
    .A  (_U200_YS),	// file.cleaned.mlir:100:26
    .B  (_U199_YC),	// file.cleaned.mlir:97:26
    .C  (~(A[7] & B[6])),	// file.cleaned.mlir:16:11, :101:11, :117:11, :118:11
    .YS (_U207_YS),
    .YC (_U207_YC)
  );	// file.cleaned.mlir:119:26
  PDKGENHAX1 U208 (	// file.cleaned.mlir:121:26
    .A  (_U200_YC),	// file.cleaned.mlir:100:26
    .B  (A[7] & B[7]),	// file.cleaned.mlir:18:11, :101:11, :120:11
    .YS (_U208_YS),
    .YC (_U208_YC)
  );	// file.cleaned.mlir:121:26
  PDKGENHAX1 U210 (	// file.cleaned.mlir:122:26
    .A  (_U203_YS),	// file.cleaned.mlir:107:26
    .B  (_U202_YC),	// file.cleaned.mlir:104:26
    .YS (_U210_YS),
    .YC (_U210_YC)
  );	// file.cleaned.mlir:122:26
  PDKGENFAX1 U211 (	// file.cleaned.mlir:123:26
    .A  (_U204_YS),	// file.cleaned.mlir:110:26
    .B  (_U210_YC),	// file.cleaned.mlir:122:26
    .C  (_U203_YC),	// file.cleaned.mlir:107:26
    .YS (_U211_YS),
    .YC (_U211_YC)
  );	// file.cleaned.mlir:123:26
  PDKGENFAX1 U212 (	// file.cleaned.mlir:124:26
    .A  (_U205_YS),	// file.cleaned.mlir:113:26
    .B  (_U211_YC),	// file.cleaned.mlir:123:26
    .C  (_U204_YC),	// file.cleaned.mlir:110:26
    .YS (_U212_YS),
    .YC (_U212_YC)
  );	// file.cleaned.mlir:124:26
  PDKGENFAX1 U213 (	// file.cleaned.mlir:125:26
    .A  (_U206_YS),	// file.cleaned.mlir:116:26
    .B  (_U212_YC),	// file.cleaned.mlir:124:26
    .C  (_U205_YC),	// file.cleaned.mlir:113:26
    .YS (_U213_YS),
    .YC (_U213_YC)
  );	// file.cleaned.mlir:125:26
  PDKGENFAX1 U214 (	// file.cleaned.mlir:126:26
    .A  (_U207_YS),	// file.cleaned.mlir:119:26
    .B  (_U213_YC),	// file.cleaned.mlir:125:26
    .C  (_U206_YC),	// file.cleaned.mlir:116:26
    .YS (_U214_YS),
    .YC (_U214_YC)
  );	// file.cleaned.mlir:126:26
  PDKGENFAX1 U215 (	// file.cleaned.mlir:127:26
    .A  (_U208_YS),	// file.cleaned.mlir:121:26
    .B  (_U214_YC),	// file.cleaned.mlir:126:26
    .C  (_U207_YC),	// file.cleaned.mlir:119:26
    .YS (_U215_YS),
    .YC (_U215_YC)
  );	// file.cleaned.mlir:127:26
  PDKGENFAX1 U216 (	// file.cleaned.mlir:128:26
    .A  (1'h1),	// file.cleaned.mlir:4:13
    .B  (_U215_YC),	// file.cleaned.mlir:127:26
    .C  (_U208_YC),	// file.cleaned.mlir:121:26
    .YS (_U216_YS),
    .YC (/* unused */)
  );	// file.cleaned.mlir:128:26
  assign O =
    {_U216_YS,
     _U215_YS,
     _U214_YS,
     _U213_YS,
     _U212_YS,
     _U211_YS,
     _U210_YS,
     _U202_YS,
     _U194_YS,
     _U186_YS,
     _U178_YS,
     _U170_YS,
     _U162_YS,
     A[1] & B[1],
     2'h0};	// file.cleaned.mlir:3:14, :5:10, :6:10, :7:10, :23:26, :39:26, :55:26, :71:26, :87:26, :104:26, :122:26, :123:26, :124:26, :125:26, :126:26, :127:26, :128:26, :129:11, :130:5
endmodule

module PDKGENHAX1(	// file.cleaned.mlir:132:3
  input  A,	// file.cleaned.mlir:132:36
         B,	// file.cleaned.mlir:132:48
  output YS,	// file.cleaned.mlir:132:61
         YC	// file.cleaned.mlir:132:74
);

  assign YS = A ^ B;	// file.cleaned.mlir:133:10, :135:5
  assign YC = A & B;	// file.cleaned.mlir:134:10, :135:5
endmodule

module PDKGENFAX1(	// file.cleaned.mlir:137:3
  input  A,	// file.cleaned.mlir:137:36
         B,	// file.cleaned.mlir:137:48
         C,	// file.cleaned.mlir:137:60
  output YS,	// file.cleaned.mlir:137:73
         YC	// file.cleaned.mlir:137:86
);

  assign YS = A ^ B ^ C;	// file.cleaned.mlir:138:10, :143:5
  assign YC = A & B | B & C | A & C;	// file.cleaned.mlir:139:10, :140:10, :141:10, :142:10, :143:5
endmodule

