// Generated by CIRCT unknown git version
module mul8s_1L2D(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:28
                B,	// file.cleaned.mlir:2:40
  output [15:0] O	// file.cleaned.mlir:2:53
);

  wire _U360_YS;	// file.cleaned.mlir:98:26
  wire _U359_YS;	// file.cleaned.mlir:97:26
  wire _U359_YC;	// file.cleaned.mlir:97:26
  wire _U358_YS;	// file.cleaned.mlir:96:26
  wire _U358_YC;	// file.cleaned.mlir:96:26
  wire _U357_YS;	// file.cleaned.mlir:95:26
  wire _U357_YC;	// file.cleaned.mlir:95:26
  wire _U356_YS;	// file.cleaned.mlir:94:26
  wire _U356_YC;	// file.cleaned.mlir:94:26
  wire _U355_YS;	// file.cleaned.mlir:93:26
  wire _U355_YC;	// file.cleaned.mlir:93:26
  wire _U352_YS;	// file.cleaned.mlir:92:26
  wire _U352_YC;	// file.cleaned.mlir:92:26
  wire _U351_YS;	// file.cleaned.mlir:90:26
  wire _U351_YC;	// file.cleaned.mlir:90:26
  wire _U350_YS;	// file.cleaned.mlir:87:26
  wire _U350_YC;	// file.cleaned.mlir:87:26
  wire _U349_YS;	// file.cleaned.mlir:84:26
  wire _U349_YC;	// file.cleaned.mlir:84:26
  wire _U348_YS;	// file.cleaned.mlir:81:26
  wire _U348_YC;	// file.cleaned.mlir:81:26
  wire _U347_YS;	// file.cleaned.mlir:78:26
  wire _U347_YC;	// file.cleaned.mlir:78:26
  wire _U344_YS;	// file.cleaned.mlir:74:26
  wire _U344_YC;	// file.cleaned.mlir:74:26
  wire _U343_YS;	// file.cleaned.mlir:71:26
  wire _U343_YC;	// file.cleaned.mlir:71:26
  wire _U342_YS;	// file.cleaned.mlir:69:26
  wire _U342_YC;	// file.cleaned.mlir:69:26
  wire _U341_YS;	// file.cleaned.mlir:67:26
  wire _U341_YC;	// file.cleaned.mlir:67:26
  wire _U340_YS;	// file.cleaned.mlir:65:26
  wire _U340_YC;	// file.cleaned.mlir:65:26
  wire _U339_YS;	// file.cleaned.mlir:63:26
  wire _U339_YC;	// file.cleaned.mlir:63:26
  wire _U336_YS;	// file.cleaned.mlir:60:26
  wire _U336_YC;	// file.cleaned.mlir:60:26
  wire _U335_YS;	// file.cleaned.mlir:57:26
  wire _U335_YC;	// file.cleaned.mlir:57:26
  wire _U334_YS;	// file.cleaned.mlir:55:26
  wire _U334_YC;	// file.cleaned.mlir:55:26
  wire _U333_YS;	// file.cleaned.mlir:53:26
  wire _U333_YC;	// file.cleaned.mlir:53:26
  wire _U332_YS;	// file.cleaned.mlir:51:26
  wire _U332_YC;	// file.cleaned.mlir:51:26
  wire _U331_YS;	// file.cleaned.mlir:49:26
  wire _U331_YC;	// file.cleaned.mlir:49:26
  wire _U328_YS;	// file.cleaned.mlir:46:26
  wire _U328_YC;	// file.cleaned.mlir:46:26
  wire _U327_YS;	// file.cleaned.mlir:43:26
  wire _U327_YC;	// file.cleaned.mlir:43:26
  wire _U326_YS;	// file.cleaned.mlir:41:26
  wire _U326_YC;	// file.cleaned.mlir:41:26
  wire _U325_YS;	// file.cleaned.mlir:39:26
  wire _U325_YC;	// file.cleaned.mlir:39:26
  wire _U324_YS;	// file.cleaned.mlir:37:26
  wire _U324_YC;	// file.cleaned.mlir:37:26
  wire _U323_YS;	// file.cleaned.mlir:35:26
  wire _U323_YC;	// file.cleaned.mlir:35:26
  wire _U320_YS;	// file.cleaned.mlir:32:26
  wire _U320_YC;	// file.cleaned.mlir:32:26
  wire _U319_YS;	// file.cleaned.mlir:29:26
  wire _U319_YC;	// file.cleaned.mlir:29:26
  wire _U318_YS;	// file.cleaned.mlir:27:26
  wire _U318_YC;	// file.cleaned.mlir:27:26
  wire _U317_YS;	// file.cleaned.mlir:25:26
  wire _U317_YC;	// file.cleaned.mlir:25:26
  wire _U316_YS;	// file.cleaned.mlir:23:26
  wire _U316_YC;	// file.cleaned.mlir:23:26
  wire _U315_YS;	// file.cleaned.mlir:21:26
  wire _U315_YC;	// file.cleaned.mlir:21:26
  PDKGENHAX1 U315 (	// file.cleaned.mlir:21:26
    .A  (A[2] & B[3]),	// file.cleaned.mlir:5:10, :8:10, :9:10
    .B  (A[3] & B[2]),	// file.cleaned.mlir:6:10, :19:11, :20:11
    .YS (_U315_YS),
    .YC (_U315_YC)
  );	// file.cleaned.mlir:21:26
  PDKGENHAX1 U316 (	// file.cleaned.mlir:23:26
    .A  (A[2] & B[4]),	// file.cleaned.mlir:5:10, :10:10, :11:10
    .B  (A[3] & B[3]),	// file.cleaned.mlir:8:10, :19:11, :22:11
    .YS (_U316_YS),
    .YC (_U316_YC)
  );	// file.cleaned.mlir:23:26
  PDKGENHAX1 U317 (	// file.cleaned.mlir:25:26
    .A  (A[2] & B[5]),	// file.cleaned.mlir:5:10, :12:10, :13:10
    .B  (A[3] & B[4]),	// file.cleaned.mlir:10:10, :19:11, :24:11
    .YS (_U317_YS),
    .YC (_U317_YC)
  );	// file.cleaned.mlir:25:26
  PDKGENHAX1 U318 (	// file.cleaned.mlir:27:26
    .A  (A[2] & B[6]),	// file.cleaned.mlir:5:10, :14:10, :15:11
    .B  (A[3] & B[5]),	// file.cleaned.mlir:12:10, :19:11, :26:11
    .YS (_U318_YS),
    .YC (_U318_YC)
  );	// file.cleaned.mlir:27:26
  PDKGENHAX1 U319 (	// file.cleaned.mlir:29:26
    .A  (~(A[2] & B[7])),	// file.cleaned.mlir:5:10, :16:11, :17:11, :18:11
    .B  (A[3] & B[6]),	// file.cleaned.mlir:14:10, :19:11, :28:11
    .YS (_U319_YS),
    .YC (_U319_YC)
  );	// file.cleaned.mlir:29:26
  PDKGENHAX1 U320 (	// file.cleaned.mlir:32:26
    .A  (1'h1),	// file.cleaned.mlir:4:13
    .B  (~(A[3] & B[7])),	// file.cleaned.mlir:16:11, :19:11, :30:11, :31:11
    .YS (_U320_YS),
    .YC (_U320_YC)
  );	// file.cleaned.mlir:32:26
  PDKGENFAX1 U323 (	// file.cleaned.mlir:35:26
    .A  (_U316_YS),	// file.cleaned.mlir:23:26
    .B  (_U315_YC),	// file.cleaned.mlir:21:26
    .C  (A[4] & B[2]),	// file.cleaned.mlir:6:10, :33:11, :34:11
    .YS (_U323_YS),
    .YC (_U323_YC)
  );	// file.cleaned.mlir:35:26
  PDKGENFAX1 U324 (	// file.cleaned.mlir:37:26
    .A  (_U317_YS),	// file.cleaned.mlir:25:26
    .B  (_U316_YC),	// file.cleaned.mlir:23:26
    .C  (A[4] & B[3]),	// file.cleaned.mlir:8:10, :33:11, :36:11
    .YS (_U324_YS),
    .YC (_U324_YC)
  );	// file.cleaned.mlir:37:26
  PDKGENFAX1 U325 (	// file.cleaned.mlir:39:26
    .A  (_U318_YS),	// file.cleaned.mlir:27:26
    .B  (_U317_YC),	// file.cleaned.mlir:25:26
    .C  (A[4] & B[4]),	// file.cleaned.mlir:10:10, :33:11, :38:11
    .YS (_U325_YS),
    .YC (_U325_YC)
  );	// file.cleaned.mlir:39:26
  PDKGENFAX1 U326 (	// file.cleaned.mlir:41:26
    .A  (_U319_YS),	// file.cleaned.mlir:29:26
    .B  (_U318_YC),	// file.cleaned.mlir:27:26
    .C  (A[4] & B[5]),	// file.cleaned.mlir:12:10, :33:11, :40:11
    .YS (_U326_YS),
    .YC (_U326_YC)
  );	// file.cleaned.mlir:41:26
  PDKGENFAX1 U327 (	// file.cleaned.mlir:43:26
    .A  (_U320_YS),	// file.cleaned.mlir:32:26
    .B  (_U319_YC),	// file.cleaned.mlir:29:26
    .C  (A[4] & B[6]),	// file.cleaned.mlir:14:10, :33:11, :42:11
    .YS (_U327_YS),
    .YC (_U327_YC)
  );	// file.cleaned.mlir:43:26
  PDKGENHAX1 U328 (	// file.cleaned.mlir:46:26
    .A  (_U320_YC),	// file.cleaned.mlir:32:26
    .B  (~(A[4] & B[7])),	// file.cleaned.mlir:16:11, :33:11, :44:11, :45:11
    .YS (_U328_YS),
    .YC (_U328_YC)
  );	// file.cleaned.mlir:46:26
  PDKGENFAX1 U331 (	// file.cleaned.mlir:49:26
    .A  (_U324_YS),	// file.cleaned.mlir:37:26
    .B  (_U323_YC),	// file.cleaned.mlir:35:26
    .C  (A[5] & B[2]),	// file.cleaned.mlir:6:10, :47:11, :48:11
    .YS (_U331_YS),
    .YC (_U331_YC)
  );	// file.cleaned.mlir:49:26
  PDKGENFAX1 U332 (	// file.cleaned.mlir:51:26
    .A  (_U325_YS),	// file.cleaned.mlir:39:26
    .B  (_U324_YC),	// file.cleaned.mlir:37:26
    .C  (A[5] & B[3]),	// file.cleaned.mlir:8:10, :47:11, :50:11
    .YS (_U332_YS),
    .YC (_U332_YC)
  );	// file.cleaned.mlir:51:26
  PDKGENFAX1 U333 (	// file.cleaned.mlir:53:26
    .A  (_U326_YS),	// file.cleaned.mlir:41:26
    .B  (_U325_YC),	// file.cleaned.mlir:39:26
    .C  (A[5] & B[4]),	// file.cleaned.mlir:10:10, :47:11, :52:11
    .YS (_U333_YS),
    .YC (_U333_YC)
  );	// file.cleaned.mlir:53:26
  PDKGENFAX1 U334 (	// file.cleaned.mlir:55:26
    .A  (_U327_YS),	// file.cleaned.mlir:43:26
    .B  (_U326_YC),	// file.cleaned.mlir:41:26
    .C  (A[5] & B[5]),	// file.cleaned.mlir:12:10, :47:11, :54:11
    .YS (_U334_YS),
    .YC (_U334_YC)
  );	// file.cleaned.mlir:55:26
  PDKGENFAX1 U335 (	// file.cleaned.mlir:57:26
    .A  (_U328_YS),	// file.cleaned.mlir:46:26
    .B  (_U327_YC),	// file.cleaned.mlir:43:26
    .C  (A[5] & B[6]),	// file.cleaned.mlir:14:10, :47:11, :56:11
    .YS (_U335_YS),
    .YC (_U335_YC)
  );	// file.cleaned.mlir:57:26
  PDKGENHAX1 U336 (	// file.cleaned.mlir:60:26
    .A  (_U328_YC),	// file.cleaned.mlir:46:26
    .B  (~(A[5] & B[7])),	// file.cleaned.mlir:16:11, :47:11, :58:11, :59:11
    .YS (_U336_YS),
    .YC (_U336_YC)
  );	// file.cleaned.mlir:60:26
  PDKGENFAX1 U339 (	// file.cleaned.mlir:63:26
    .A  (_U332_YS),	// file.cleaned.mlir:51:26
    .B  (_U331_YC),	// file.cleaned.mlir:49:26
    .C  (A[6] & B[2]),	// file.cleaned.mlir:6:10, :61:11, :62:11
    .YS (_U339_YS),
    .YC (_U339_YC)
  );	// file.cleaned.mlir:63:26
  PDKGENFAX1 U340 (	// file.cleaned.mlir:65:26
    .A  (_U333_YS),	// file.cleaned.mlir:53:26
    .B  (_U332_YC),	// file.cleaned.mlir:51:26
    .C  (A[6] & B[3]),	// file.cleaned.mlir:8:10, :61:11, :64:11
    .YS (_U340_YS),
    .YC (_U340_YC)
  );	// file.cleaned.mlir:65:26
  PDKGENFAX1 U341 (	// file.cleaned.mlir:67:26
    .A  (_U334_YS),	// file.cleaned.mlir:55:26
    .B  (_U333_YC),	// file.cleaned.mlir:53:26
    .C  (A[6] & B[4]),	// file.cleaned.mlir:10:10, :61:11, :66:11
    .YS (_U341_YS),
    .YC (_U341_YC)
  );	// file.cleaned.mlir:67:26
  PDKGENFAX1 U342 (	// file.cleaned.mlir:69:26
    .A  (_U335_YS),	// file.cleaned.mlir:57:26
    .B  (_U334_YC),	// file.cleaned.mlir:55:26
    .C  (A[6] & B[5]),	// file.cleaned.mlir:12:10, :61:11, :68:11
    .YS (_U342_YS),
    .YC (_U342_YC)
  );	// file.cleaned.mlir:69:26
  PDKGENFAX1 U343 (	// file.cleaned.mlir:71:26
    .A  (_U336_YS),	// file.cleaned.mlir:60:26
    .B  (_U335_YC),	// file.cleaned.mlir:57:26
    .C  (A[6] & B[6]),	// file.cleaned.mlir:14:10, :61:11, :70:11
    .YS (_U343_YS),
    .YC (_U343_YC)
  );	// file.cleaned.mlir:71:26
  PDKGENHAX1 U344 (	// file.cleaned.mlir:74:26
    .A  (_U336_YC),	// file.cleaned.mlir:60:26
    .B  (~(A[6] & B[7])),	// file.cleaned.mlir:16:11, :61:11, :72:11, :73:11
    .YS (_U344_YS),
    .YC (_U344_YC)
  );	// file.cleaned.mlir:74:26
  PDKGENFAX1 U347 (	// file.cleaned.mlir:78:26
    .A  (_U340_YS),	// file.cleaned.mlir:65:26
    .B  (_U339_YC),	// file.cleaned.mlir:63:26
    .C  (~(A[7] & B[2])),	// file.cleaned.mlir:6:10, :75:11, :76:11, :77:11
    .YS (_U347_YS),
    .YC (_U347_YC)
  );	// file.cleaned.mlir:78:26
  PDKGENFAX1 U348 (	// file.cleaned.mlir:81:26
    .A  (_U341_YS),	// file.cleaned.mlir:67:26
    .B  (_U340_YC),	// file.cleaned.mlir:65:26
    .C  (~(A[7] & B[3])),	// file.cleaned.mlir:8:10, :75:11, :79:11, :80:11
    .YS (_U348_YS),
    .YC (_U348_YC)
  );	// file.cleaned.mlir:81:26
  PDKGENFAX1 U349 (	// file.cleaned.mlir:84:26
    .A  (_U342_YS),	// file.cleaned.mlir:69:26
    .B  (_U341_YC),	// file.cleaned.mlir:67:26
    .C  (~(A[7] & B[4])),	// file.cleaned.mlir:10:10, :75:11, :82:11, :83:11
    .YS (_U349_YS),
    .YC (_U349_YC)
  );	// file.cleaned.mlir:84:26
  PDKGENFAX1 U350 (	// file.cleaned.mlir:87:26
    .A  (_U343_YS),	// file.cleaned.mlir:71:26
    .B  (_U342_YC),	// file.cleaned.mlir:69:26
    .C  (~(A[7] & B[5])),	// file.cleaned.mlir:12:10, :75:11, :85:11, :86:11
    .YS (_U350_YS),
    .YC (_U350_YC)
  );	// file.cleaned.mlir:87:26
  PDKGENFAX1 U351 (	// file.cleaned.mlir:90:26
    .A  (_U344_YS),	// file.cleaned.mlir:74:26
    .B  (_U343_YC),	// file.cleaned.mlir:71:26
    .C  (~(A[7] & B[6])),	// file.cleaned.mlir:14:10, :75:11, :88:11, :89:11
    .YS (_U351_YS),
    .YC (_U351_YC)
  );	// file.cleaned.mlir:90:26
  PDKGENHAX1 U352 (	// file.cleaned.mlir:92:26
    .A  (_U344_YC),	// file.cleaned.mlir:74:26
    .B  (A[7] & B[7]),	// file.cleaned.mlir:16:11, :75:11, :91:11
    .YS (_U352_YS),
    .YC (_U352_YC)
  );	// file.cleaned.mlir:92:26
  PDKGENHAX1 U355 (	// file.cleaned.mlir:93:26
    .A  (_U348_YS),	// file.cleaned.mlir:81:26
    .B  (_U347_YC),	// file.cleaned.mlir:78:26
    .YS (_U355_YS),
    .YC (_U355_YC)
  );	// file.cleaned.mlir:93:26
  PDKGENFAX1 U356 (	// file.cleaned.mlir:94:26
    .A  (_U349_YS),	// file.cleaned.mlir:84:26
    .B  (_U355_YC),	// file.cleaned.mlir:93:26
    .C  (_U348_YC),	// file.cleaned.mlir:81:26
    .YS (_U356_YS),
    .YC (_U356_YC)
  );	// file.cleaned.mlir:94:26
  PDKGENFAX1 U357 (	// file.cleaned.mlir:95:26
    .A  (_U350_YS),	// file.cleaned.mlir:87:26
    .B  (_U356_YC),	// file.cleaned.mlir:94:26
    .C  (_U349_YC),	// file.cleaned.mlir:84:26
    .YS (_U357_YS),
    .YC (_U357_YC)
  );	// file.cleaned.mlir:95:26
  PDKGENFAX1 U358 (	// file.cleaned.mlir:96:26
    .A  (_U351_YS),	// file.cleaned.mlir:90:26
    .B  (_U357_YC),	// file.cleaned.mlir:95:26
    .C  (_U350_YC),	// file.cleaned.mlir:87:26
    .YS (_U358_YS),
    .YC (_U358_YC)
  );	// file.cleaned.mlir:96:26
  PDKGENFAX1 U359 (	// file.cleaned.mlir:97:26
    .A  (_U352_YS),	// file.cleaned.mlir:92:26
    .B  (_U358_YC),	// file.cleaned.mlir:96:26
    .C  (_U351_YC),	// file.cleaned.mlir:90:26
    .YS (_U359_YS),
    .YC (_U359_YC)
  );	// file.cleaned.mlir:97:26
  PDKGENFAX1 U360 (	// file.cleaned.mlir:98:26
    .A  (1'h1),	// file.cleaned.mlir:4:13
    .B  (_U359_YC),	// file.cleaned.mlir:97:26
    .C  (_U352_YC),	// file.cleaned.mlir:92:26
    .YS (_U360_YS),
    .YC (/* unused */)
  );	// file.cleaned.mlir:98:26
  assign O =
    {_U360_YS,
     _U359_YS,
     _U358_YS,
     _U357_YS,
     _U356_YS,
     _U355_YS,
     _U347_YS,
     _U339_YS,
     _U331_YS,
     _U323_YS,
     _U315_YS,
     A[2] & B[2],
     4'h0};	// file.cleaned.mlir:3:14, :5:10, :6:10, :7:10, :21:26, :35:26, :49:26, :63:26, :78:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:26, :99:11, :100:5
endmodule

module PDKGENHAX1(	// file.cleaned.mlir:102:3
  input  A,	// file.cleaned.mlir:102:36
         B,	// file.cleaned.mlir:102:48
  output YS,	// file.cleaned.mlir:102:61
         YC	// file.cleaned.mlir:102:74
);

  assign YS = A ^ B;	// file.cleaned.mlir:103:10, :105:5
  assign YC = A & B;	// file.cleaned.mlir:104:10, :105:5
endmodule

module PDKGENFAX1(	// file.cleaned.mlir:107:3
  input  A,	// file.cleaned.mlir:107:36
         B,	// file.cleaned.mlir:107:48
         C,	// file.cleaned.mlir:107:60
  output YS,	// file.cleaned.mlir:107:73
         YC	// file.cleaned.mlir:107:86
);

  assign YS = A ^ B ^ C;	// file.cleaned.mlir:108:10, :113:5
  assign YC = A & B | B & C | A & C;	// file.cleaned.mlir:109:10, :110:10, :111:10, :112:10, :113:5
endmodule

