// Generated by CIRCT unknown git version
module mul8u_JQQ(	// file.cleaned.mlir:2:3
  input  [7:0]  A,	// file.cleaned.mlir:2:27
                B,	// file.cleaned.mlir:2:39
  output [15:0] O	// file.cleaned.mlir:2:52
);

  wire sig_335;	// file.cleaned.mlir:383:12
  wire sig_334;	// file.cleaned.mlir:382:12
  wire sig_329;	// file.cleaned.mlir:378:12
  wire sig_324;	// file.cleaned.mlir:373:12
  wire sig_319;	// file.cleaned.mlir:368:12
  wire sig_314;	// file.cleaned.mlir:363:12
  wire sig_309;	// file.cleaned.mlir:358:12
  wire sig_304;	// file.cleaned.mlir:353:12
  wire sig_272;	// file.cleaned.mlir:323:12
  wire sig_229;	// file.cleaned.mlir:283:12
  wire sig_186;	// file.cleaned.mlir:242:12
  wire sig_143;	// file.cleaned.mlir:202:12
  wire sig_100;	// file.cleaned.mlir:162:12
  wire sig_57;	// file.cleaned.mlir:128:11
  wire sig_32;	// file.cleaned.mlir:103:11
  wire sig_16;	// file.cleaned.mlir:79:11
  assign sig_16 = B[0] & A[0];	// file.cleaned.mlir:77:11, :78:11, :79:11
  wire sig_17 = B[1] & A[0];	// file.cleaned.mlir:78:11, :80:11, :81:11
  wire sig_18 = B[2] & A[0];	// file.cleaned.mlir:78:11, :82:11, :83:11
  wire sig_19 = B[3] & A[0];	// file.cleaned.mlir:78:11, :84:11, :85:11
  wire sig_20 = B[4] & A[0];	// file.cleaned.mlir:78:11, :86:11, :87:11
  wire sig_21 = B[5] & A[0];	// file.cleaned.mlir:78:11, :88:11, :89:11
  wire sig_22 = B[6] & A[0];	// file.cleaned.mlir:78:11, :90:11, :91:11
  wire sig_24 = B[0] & A[1];	// file.cleaned.mlir:77:11, :94:11, :95:11
  wire sig_25 = B[1] & A[1];	// file.cleaned.mlir:80:11, :94:11, :96:11
  wire sig_26 = B[2] & A[1];	// file.cleaned.mlir:82:11, :94:11, :97:11
  wire sig_27 = B[3] & A[1];	// file.cleaned.mlir:84:11, :94:11, :98:11
  wire sig_28 = B[4] & A[1];	// file.cleaned.mlir:86:11, :94:11, :99:11
  wire sig_29 = B[5] & A[1];	// file.cleaned.mlir:88:11, :94:11, :100:11
  assign sig_32 = sig_17 ^ sig_24;	// file.cleaned.mlir:81:11, :95:11, :103:11
  wire sig_33 = sig_17 & sig_24;	// file.cleaned.mlir:81:11, :95:11, :104:11
  wire sig_34 = sig_18 ^ sig_25;	// file.cleaned.mlir:83:11, :96:11, :105:11
  wire sig_35 = sig_18 & sig_25;	// file.cleaned.mlir:83:11, :96:11, :106:11
  wire sig_36 = sig_19 ^ sig_26;	// file.cleaned.mlir:85:11, :97:11, :107:11
  wire sig_37 = sig_19 & sig_26;	// file.cleaned.mlir:85:11, :97:11, :108:11
  wire sig_38 = sig_20 ^ sig_27;	// file.cleaned.mlir:87:11, :98:11, :109:11
  wire sig_39 = sig_20 & sig_27;	// file.cleaned.mlir:87:11, :98:11, :110:11
  wire sig_40 = sig_21 ^ sig_28;	// file.cleaned.mlir:89:11, :99:11, :111:11
  wire sig_42 = sig_22 ^ sig_29;	// file.cleaned.mlir:91:11, :100:11, :113:11
  wire sig_43 = sig_22 & sig_29;	// file.cleaned.mlir:91:11, :100:11, :114:11
  wire sig_44 = B[7] & A[0] | B[6] & A[1];	// file.cleaned.mlir:78:11, :90:11, :92:11, :93:11, :94:11, :101:11, :115:11
  wire sig_46 = B[0] & A[2];	// file.cleaned.mlir:77:11, :116:11, :117:11
  wire sig_47 = B[1] & A[2];	// file.cleaned.mlir:80:11, :116:11, :118:11
  wire sig_48 = B[2] & A[2];	// file.cleaned.mlir:82:11, :116:11, :119:11
  wire sig_49 = B[3] & A[2];	// file.cleaned.mlir:84:11, :116:11, :120:11
  wire sig_50 = B[4] & A[2];	// file.cleaned.mlir:86:11, :116:11, :121:11
  wire sig_51 = B[5] & A[2];	// file.cleaned.mlir:88:11, :116:11, :122:11
  wire sig_54 = sig_34 ^ sig_46;	// file.cleaned.mlir:105:11, :117:11, :125:11
  assign sig_57 = sig_54 ^ sig_33;	// file.cleaned.mlir:104:11, :125:11, :128:11
  wire sig_58 = sig_34 & sig_46 | sig_54 & sig_33;	// file.cleaned.mlir:104:11, :105:11, :117:11, :125:11, :126:11, :127:11, :129:11
  wire sig_59 = sig_36 ^ sig_47;	// file.cleaned.mlir:107:11, :118:11, :130:11
  wire sig_62 = sig_59 ^ sig_35;	// file.cleaned.mlir:106:11, :130:11, :133:12
  wire sig_63 = sig_36 & sig_47 | sig_59 & sig_35;	// file.cleaned.mlir:106:11, :107:11, :118:11, :130:11, :131:11, :132:12, :134:12
  wire sig_64 = sig_38 ^ sig_48;	// file.cleaned.mlir:109:11, :119:11, :135:12
  wire sig_67 = sig_64 ^ sig_37;	// file.cleaned.mlir:108:11, :135:12, :138:12
  wire sig_68 = sig_38 & sig_48 | sig_64 & sig_37;	// file.cleaned.mlir:108:11, :109:11, :119:11, :135:12, :136:12, :137:12, :139:12
  wire sig_72 = sig_40 ^ sig_49 ^ sig_39;	// file.cleaned.mlir:110:11, :111:11, :120:11, :141:12
  wire sig_73 = sig_40 & sig_49 | sig_39;	// file.cleaned.mlir:110:11, :111:11, :120:11, :140:12, :142:12
  wire sig_75 = sig_42 & sig_50;	// file.cleaned.mlir:113:11, :121:11, :144:12
  wire sig_77 = sig_42 ^ sig_50 | sig_21 & sig_28;	// file.cleaned.mlir:89:11, :99:11, :112:11, :113:11, :121:11, :143:12, :145:12
  wire sig_82 = sig_44 ^ sig_51 ^ sig_43;	// file.cleaned.mlir:114:11, :115:11, :122:11, :147:12
  wire sig_83 = sig_44 & sig_51 | sig_43;	// file.cleaned.mlir:114:11, :115:11, :122:11, :146:12, :148:12
  wire sig_84 = B[7] & A[1] | B[6] & A[2];	// file.cleaned.mlir:90:11, :92:11, :94:11, :102:11, :116:11, :123:11, :149:12
  wire sig_89 = B[0] & A[3];	// file.cleaned.mlir:77:11, :150:12, :151:12
  wire sig_90 = B[1] & A[3];	// file.cleaned.mlir:80:11, :150:12, :152:12
  wire sig_91 = B[2] & A[3];	// file.cleaned.mlir:82:11, :150:12, :153:12
  wire sig_92 = B[3] & A[3];	// file.cleaned.mlir:84:11, :150:12, :154:12
  wire sig_93 = B[4] & A[3];	// file.cleaned.mlir:86:11, :150:12, :155:12
  wire sig_94 = B[5] & A[3];	// file.cleaned.mlir:88:11, :150:12, :156:12
  wire sig_97 = sig_62 ^ sig_89;	// file.cleaned.mlir:133:12, :151:12, :159:12
  assign sig_100 = sig_97 ^ sig_58;	// file.cleaned.mlir:129:11, :159:12, :162:12
  wire sig_101 = sig_62 & sig_89 | sig_97 & sig_58;	// file.cleaned.mlir:129:11, :133:12, :151:12, :159:12, :160:12, :161:12, :163:12
  wire sig_102 = sig_67 ^ sig_90;	// file.cleaned.mlir:138:12, :152:12, :164:12
  wire sig_105 = sig_102 ^ sig_63;	// file.cleaned.mlir:134:12, :164:12, :167:12
  wire sig_106 = sig_67 & sig_90 | sig_102 & sig_63;	// file.cleaned.mlir:134:12, :138:12, :152:12, :164:12, :165:12, :166:12, :168:12
  wire sig_107 = sig_72 ^ sig_91;	// file.cleaned.mlir:141:12, :153:12, :169:12
  wire sig_110 = sig_107 ^ sig_68;	// file.cleaned.mlir:139:12, :169:12, :172:12
  wire sig_111 = sig_72 & sig_91 | sig_107 & sig_68;	// file.cleaned.mlir:139:12, :141:12, :153:12, :169:12, :170:12, :171:12, :173:12
  wire sig_112 = sig_77 ^ sig_92;	// file.cleaned.mlir:145:12, :154:12, :174:12
  wire sig_115 = sig_112 ^ sig_73;	// file.cleaned.mlir:142:12, :174:12, :177:12
  wire sig_116 = sig_77 & sig_92 | sig_112 & sig_73;	// file.cleaned.mlir:142:12, :145:12, :154:12, :174:12, :175:12, :176:12, :178:12
  wire sig_117 = sig_82 ^ sig_93;	// file.cleaned.mlir:147:12, :155:12, :179:12
  wire sig_120 = sig_117 ^ sig_75;	// file.cleaned.mlir:144:12, :179:12, :182:12
  wire sig_121 = sig_82 & sig_93 | sig_117 & sig_75;	// file.cleaned.mlir:144:12, :147:12, :155:12, :179:12, :180:12, :181:12, :183:12
  wire sig_122 = sig_84 ^ sig_94;	// file.cleaned.mlir:149:12, :156:12, :184:12
  wire sig_125 = sig_122 ^ sig_83;	// file.cleaned.mlir:148:12, :184:12, :187:12
  wire sig_126 = sig_84 & sig_94 | sig_122 & sig_83;	// file.cleaned.mlir:148:12, :149:12, :156:12, :184:12, :185:12, :186:12, :188:12
  wire sig_127 = B[7] & A[2] | B[6] & A[3];	// file.cleaned.mlir:90:11, :92:11, :116:11, :124:11, :150:12, :157:12, :189:12
  wire sig_132 = B[0] & A[4];	// file.cleaned.mlir:77:11, :190:12, :191:12
  wire sig_133 = B[1] & A[4];	// file.cleaned.mlir:80:11, :190:12, :192:12
  wire sig_134 = B[2] & A[4];	// file.cleaned.mlir:82:11, :190:12, :193:12
  wire sig_135 = B[3] & A[4];	// file.cleaned.mlir:84:11, :190:12, :194:12
  wire sig_136 = B[4] & A[4];	// file.cleaned.mlir:86:11, :190:12, :195:12
  wire sig_137 = B[5] & A[4];	// file.cleaned.mlir:88:11, :190:12, :196:12
  wire sig_139 = B[7] & A[4];	// file.cleaned.mlir:92:11, :190:12, :198:12
  wire sig_140 = sig_105 ^ sig_132;	// file.cleaned.mlir:167:12, :191:12, :199:12
  assign sig_143 = sig_140 ^ sig_101;	// file.cleaned.mlir:163:12, :199:12, :202:12
  wire sig_144 = sig_105 & sig_132 | sig_140 & sig_101;	// file.cleaned.mlir:163:12, :167:12, :191:12, :199:12, :200:12, :201:12, :203:12
  wire sig_145 = sig_110 ^ sig_133;	// file.cleaned.mlir:172:12, :192:12, :204:12
  wire sig_148 = sig_145 ^ sig_106;	// file.cleaned.mlir:168:12, :204:12, :207:12
  wire sig_149 = sig_110 & sig_133 | sig_145 & sig_106;	// file.cleaned.mlir:168:12, :172:12, :192:12, :204:12, :205:12, :206:12, :208:12
  wire sig_150 = sig_115 ^ sig_134;	// file.cleaned.mlir:177:12, :193:12, :209:12
  wire sig_153 = sig_150 ^ sig_111;	// file.cleaned.mlir:173:12, :209:12, :212:12
  wire sig_154 = sig_115 & sig_134 | sig_150 & sig_111;	// file.cleaned.mlir:173:12, :177:12, :193:12, :209:12, :210:12, :211:12, :213:12
  wire sig_155 = sig_120 ^ sig_135;	// file.cleaned.mlir:182:12, :194:12, :214:12
  wire sig_158 = sig_155 ^ sig_116;	// file.cleaned.mlir:178:12, :214:12, :217:12
  wire sig_159 = sig_120 & sig_135 | sig_155 & sig_116;	// file.cleaned.mlir:178:12, :182:12, :194:12, :214:12, :215:12, :216:12, :218:12
  wire sig_160 = sig_125 ^ sig_136;	// file.cleaned.mlir:187:12, :195:12, :219:12
  wire sig_163 = sig_160 ^ sig_121;	// file.cleaned.mlir:183:12, :219:12, :222:12
  wire sig_164 = sig_125 & sig_136 | sig_160 & sig_121;	// file.cleaned.mlir:183:12, :187:12, :195:12, :219:12, :220:12, :221:12, :223:12
  wire sig_165 = sig_127 ^ sig_137;	// file.cleaned.mlir:189:12, :196:12, :224:12
  wire sig_168 = sig_165 ^ sig_126;	// file.cleaned.mlir:188:12, :224:12, :227:12
  wire sig_169 = sig_127 & sig_137 | sig_165 & sig_126;	// file.cleaned.mlir:188:12, :189:12, :196:12, :224:12, :225:12, :226:12, :228:12
  wire sig_170 = B[7] & A[3] | B[6] & A[4];	// file.cleaned.mlir:90:11, :92:11, :150:12, :158:12, :190:12, :197:12, :229:12
  wire sig_175 = B[0] & A[5];	// file.cleaned.mlir:77:11, :230:12, :231:12
  wire sig_176 = B[1] & A[5];	// file.cleaned.mlir:80:11, :230:12, :232:12
  wire sig_177 = B[2] & A[5];	// file.cleaned.mlir:82:11, :230:12, :233:12
  wire sig_178 = B[3] & A[5];	// file.cleaned.mlir:84:11, :230:12, :234:12
  wire sig_179 = B[4] & A[5];	// file.cleaned.mlir:86:11, :230:12, :235:12
  wire sig_180 = B[5] & A[5];	// file.cleaned.mlir:88:11, :230:12, :236:12
  wire sig_181 = B[6] & A[5];	// file.cleaned.mlir:90:11, :230:12, :237:12
  wire sig_183 = sig_148 ^ sig_175;	// file.cleaned.mlir:207:12, :231:12, :239:12
  assign sig_186 = sig_183 ^ sig_144;	// file.cleaned.mlir:203:12, :239:12, :242:12
  wire sig_187 = sig_148 & sig_175 | sig_183 & sig_144;	// file.cleaned.mlir:203:12, :207:12, :231:12, :239:12, :240:12, :241:12, :243:12
  wire sig_188 = sig_153 ^ sig_176;	// file.cleaned.mlir:212:12, :232:12, :244:12
  wire sig_191 = sig_188 ^ sig_149;	// file.cleaned.mlir:208:12, :244:12, :247:12
  wire sig_192 = sig_153 & sig_176 | sig_188 & sig_149;	// file.cleaned.mlir:208:12, :212:12, :232:12, :244:12, :245:12, :246:12, :248:12
  wire sig_193 = sig_158 ^ sig_177;	// file.cleaned.mlir:217:12, :233:12, :249:12
  wire sig_196 = sig_193 ^ sig_154;	// file.cleaned.mlir:213:12, :249:12, :252:12
  wire sig_197 = sig_158 & sig_177 | sig_193 & sig_154;	// file.cleaned.mlir:213:12, :217:12, :233:12, :249:12, :250:12, :251:12, :253:12
  wire sig_198 = sig_163 ^ sig_178;	// file.cleaned.mlir:222:12, :234:12, :254:12
  wire sig_201 = sig_198 ^ sig_159;	// file.cleaned.mlir:218:12, :254:12, :257:12
  wire sig_202 = sig_163 & sig_178 | sig_198 & sig_159;	// file.cleaned.mlir:218:12, :222:12, :234:12, :254:12, :255:12, :256:12, :258:12
  wire sig_203 = sig_168 ^ sig_179;	// file.cleaned.mlir:227:12, :235:12, :259:12
  wire sig_206 = sig_203 ^ sig_164;	// file.cleaned.mlir:223:12, :259:12, :262:12
  wire sig_207 = sig_168 & sig_179 | sig_203 & sig_164;	// file.cleaned.mlir:223:12, :227:12, :235:12, :259:12, :260:12, :261:12, :263:12
  wire sig_208 = sig_170 ^ sig_180;	// file.cleaned.mlir:229:12, :236:12, :264:12
  wire sig_211 = sig_208 ^ sig_169;	// file.cleaned.mlir:228:12, :264:12, :267:12
  wire sig_212 = sig_170 & sig_180 | sig_208 & sig_169;	// file.cleaned.mlir:228:12, :229:12, :236:12, :264:12, :265:12, :266:12, :268:12
  wire sig_213 = sig_139 ^ sig_181;	// file.cleaned.mlir:198:12, :237:12, :269:12
  wire sig_214 = sig_139 & sig_181;	// file.cleaned.mlir:198:12, :237:12, :270:12
  wire sig_218 = B[0] & A[6];	// file.cleaned.mlir:77:11, :271:12, :272:12
  wire sig_219 = B[1] & A[6];	// file.cleaned.mlir:80:11, :271:12, :273:12
  wire sig_220 = B[2] & A[6];	// file.cleaned.mlir:82:11, :271:12, :274:12
  wire sig_221 = B[3] & A[6];	// file.cleaned.mlir:84:11, :271:12, :275:12
  wire sig_222 = B[4] & A[6];	// file.cleaned.mlir:86:11, :271:12, :276:12
  wire sig_223 = B[5] & A[6];	// file.cleaned.mlir:88:11, :271:12, :277:12
  wire sig_225 = B[7] & A[6];	// file.cleaned.mlir:92:11, :271:12, :279:12
  wire sig_226 = sig_191 ^ sig_218;	// file.cleaned.mlir:247:12, :272:12, :280:12
  assign sig_229 = sig_226 ^ sig_187;	// file.cleaned.mlir:243:12, :280:12, :283:12
  wire sig_230 = sig_191 & sig_218 | sig_226 & sig_187;	// file.cleaned.mlir:243:12, :247:12, :272:12, :280:12, :281:12, :282:12, :284:12
  wire sig_231 = sig_196 ^ sig_219;	// file.cleaned.mlir:252:12, :273:12, :285:12
  wire sig_234 = sig_231 ^ sig_192;	// file.cleaned.mlir:248:12, :285:12, :288:12
  wire sig_235 = sig_196 & sig_219 | sig_231 & sig_192;	// file.cleaned.mlir:248:12, :252:12, :273:12, :285:12, :286:12, :287:12, :289:12
  wire sig_236 = sig_201 ^ sig_220;	// file.cleaned.mlir:257:12, :274:12, :290:12
  wire sig_239 = sig_236 ^ sig_197;	// file.cleaned.mlir:253:12, :290:12, :293:12
  wire sig_240 = sig_201 & sig_220 | sig_236 & sig_197;	// file.cleaned.mlir:253:12, :257:12, :274:12, :290:12, :291:12, :292:12, :294:12
  wire sig_241 = sig_206 ^ sig_221;	// file.cleaned.mlir:262:12, :275:12, :295:12
  wire sig_244 = sig_241 ^ sig_202;	// file.cleaned.mlir:258:12, :295:12, :298:12
  wire sig_245 = sig_206 & sig_221 | sig_241 & sig_202;	// file.cleaned.mlir:258:12, :262:12, :275:12, :295:12, :296:12, :297:12, :299:12
  wire sig_246 = sig_211 ^ sig_222;	// file.cleaned.mlir:267:12, :276:12, :300:12
  wire sig_249 = sig_246 ^ sig_207;	// file.cleaned.mlir:263:12, :300:12, :303:12
  wire sig_250 = sig_211 & sig_222 | sig_246 & sig_207;	// file.cleaned.mlir:263:12, :267:12, :276:12, :300:12, :301:12, :302:12, :304:12
  wire sig_251 = sig_213 ^ sig_223;	// file.cleaned.mlir:269:12, :277:12, :305:12
  wire sig_254 = sig_251 ^ sig_212;	// file.cleaned.mlir:268:12, :305:12, :308:12
  wire sig_255 = sig_213 & sig_223 | sig_251 & sig_212;	// file.cleaned.mlir:268:12, :269:12, :277:12, :305:12, :306:12, :307:12, :309:12
  wire sig_259 = B[7] & A[5] ^ B[6] & A[6] ^ sig_214;	// file.cleaned.mlir:90:11, :92:11, :230:12, :238:12, :270:12, :271:12, :278:12, :310:12
  wire sig_261 = B[0] & A[7];	// file.cleaned.mlir:77:11, :311:12, :312:12
  wire sig_262 = B[1] & A[7];	// file.cleaned.mlir:80:11, :311:12, :313:12
  wire sig_263 = B[2] & A[7];	// file.cleaned.mlir:82:11, :311:12, :314:12
  wire sig_264 = B[3] & A[7];	// file.cleaned.mlir:84:11, :311:12, :315:12
  wire sig_265 = B[4] & A[7];	// file.cleaned.mlir:86:11, :311:12, :316:12
  wire sig_266 = B[5] & A[7];	// file.cleaned.mlir:88:11, :311:12, :317:12
  wire sig_267 = B[6] & A[7];	// file.cleaned.mlir:90:11, :311:12, :318:12
  wire sig_269 = sig_234 ^ sig_261;	// file.cleaned.mlir:288:12, :312:12, :320:12
  assign sig_272 = sig_269 ^ sig_230;	// file.cleaned.mlir:284:12, :320:12, :323:12
  wire sig_273 = sig_234 & sig_261 | sig_269 & sig_230;	// file.cleaned.mlir:284:12, :288:12, :312:12, :320:12, :321:12, :322:12, :324:12
  wire sig_274 = sig_239 ^ sig_262;	// file.cleaned.mlir:293:12, :313:12, :325:12
  wire sig_277 = sig_274 ^ sig_235;	// file.cleaned.mlir:289:12, :325:12, :328:12
  wire sig_278 = sig_239 & sig_262 | sig_274 & sig_235;	// file.cleaned.mlir:289:12, :293:12, :313:12, :325:12, :326:12, :327:12, :329:12
  wire sig_279 = sig_244 ^ sig_263;	// file.cleaned.mlir:298:12, :314:12, :330:12
  wire sig_282 = sig_279 ^ sig_240;	// file.cleaned.mlir:294:12, :330:12, :333:12
  wire sig_283 = sig_244 & sig_263 | sig_279 & sig_240;	// file.cleaned.mlir:294:12, :298:12, :314:12, :330:12, :331:12, :332:12, :334:12
  wire sig_284 = sig_249 ^ sig_264;	// file.cleaned.mlir:303:12, :315:12, :335:12
  wire sig_287 = sig_284 ^ sig_245;	// file.cleaned.mlir:299:12, :335:12, :338:12
  wire sig_288 = sig_249 & sig_264 | sig_284 & sig_245;	// file.cleaned.mlir:299:12, :303:12, :315:12, :335:12, :336:12, :337:12, :339:12
  wire sig_289 = sig_254 ^ sig_265;	// file.cleaned.mlir:308:12, :316:12, :340:12
  wire sig_292 = sig_289 ^ sig_250;	// file.cleaned.mlir:304:12, :340:12, :343:12
  wire sig_293 = sig_254 & sig_265 | sig_289 & sig_250;	// file.cleaned.mlir:304:12, :308:12, :316:12, :340:12, :341:12, :342:12, :344:12
  wire sig_294 = sig_259 ^ sig_266;	// file.cleaned.mlir:310:12, :317:12, :345:12
  wire sig_297 = sig_294 ^ sig_255;	// file.cleaned.mlir:309:12, :345:12, :348:12
  wire sig_298 = sig_259 & sig_266 | sig_294 & sig_255;	// file.cleaned.mlir:309:12, :310:12, :317:12, :345:12, :346:12, :347:12, :349:12
  wire sig_299 = sig_225 | sig_267;	// file.cleaned.mlir:279:12, :318:12, :350:12
  wire sig_300 = sig_225 & sig_267;	// file.cleaned.mlir:279:12, :318:12, :351:12
  assign sig_304 = sig_277 ^ sig_273;	// file.cleaned.mlir:324:12, :328:12, :353:12
  wire sig_305 = sig_277 & sig_273;	// file.cleaned.mlir:324:12, :328:12, :354:12
  wire sig_306 = sig_282 ^ sig_278;	// file.cleaned.mlir:329:12, :333:12, :355:12
  assign sig_309 = sig_306 ^ sig_305;	// file.cleaned.mlir:354:12, :355:12, :358:12
  wire sig_310 = sig_282 & sig_278 | sig_306 & sig_305;	// file.cleaned.mlir:329:12, :333:12, :354:12, :355:12, :356:12, :357:12, :359:12
  wire sig_311 = sig_287 ^ sig_283;	// file.cleaned.mlir:334:12, :338:12, :360:12
  assign sig_314 = sig_311 ^ sig_310;	// file.cleaned.mlir:359:12, :360:12, :363:12
  wire sig_315 = sig_287 & sig_283 | sig_311 & sig_310;	// file.cleaned.mlir:334:12, :338:12, :359:12, :360:12, :361:12, :362:12, :364:12
  wire sig_316 = sig_292 ^ sig_288;	// file.cleaned.mlir:339:12, :343:12, :365:12
  assign sig_319 = sig_316 ^ sig_315;	// file.cleaned.mlir:364:12, :365:12, :368:12
  wire sig_320 = sig_292 & sig_288 | sig_316 & sig_315;	// file.cleaned.mlir:339:12, :343:12, :364:12, :365:12, :366:12, :367:12, :369:12
  wire sig_321 = sig_297 ^ sig_293;	// file.cleaned.mlir:344:12, :348:12, :370:12
  assign sig_324 = sig_321 ^ sig_320;	// file.cleaned.mlir:369:12, :370:12, :373:12
  wire sig_325 = sig_297 & sig_293 | sig_321 & sig_320;	// file.cleaned.mlir:344:12, :348:12, :369:12, :370:12, :371:12, :372:12, :374:12
  wire sig_326 = (sig_299 | sig_214) ^ sig_298;	// file.cleaned.mlir:270:12, :349:12, :350:12, :352:12, :375:12
  assign sig_329 = sig_326 ^ sig_325;	// file.cleaned.mlir:374:12, :375:12, :378:12
  wire sig_330 = sig_299 & sig_298 | sig_326 & sig_325;	// file.cleaned.mlir:349:12, :350:12, :374:12, :375:12, :376:12, :377:12, :379:12
  wire sig_331 = B[7] & A[7] ^ sig_300;	// file.cleaned.mlir:92:11, :311:12, :319:12, :351:12, :380:12
  assign sig_334 = sig_331 ^ sig_330;	// file.cleaned.mlir:379:12, :380:12, :382:12
  assign sig_335 = sig_300 | sig_331 & sig_330;	// file.cleaned.mlir:351:12, :379:12, :380:12, :381:12, :383:12
  assign O =
    {sig_335, 15'h0}
    | ({1'h0, sig_334, 14'h0}
       | ({2'h0, sig_329, 13'h0}
          | ({3'h0, sig_324, 12'h0}
             | ({4'h0, sig_319, 11'h0}
                | ({5'h0, sig_314, 10'h0}
                   | ({6'h0, sig_309, 9'h0}
                      | ({7'h0, sig_304, 8'h0}
                         | ({8'h0, sig_272, 7'h0}
                            | ({9'h0, sig_229, 6'h0}
                               | ({10'h0, sig_186, 5'h0}
                                  | ({11'h0, sig_143, 4'h0}
                                     | ({12'h0, sig_100, 3'h0}
                                        | ({13'h0, sig_57, 2'h0}
                                           | ({14'h0, sig_32, 1'h0} | {15'h0, sig_16})
                                           & 16'hFFFB) & 16'hFFF7) & 16'hFFEF) & 16'hFFDF)
                               & 16'hFFBF) & 16'hFF7F) & 16'hFEFF) & 16'hFDFF) & 16'hFBFF)
                & 16'hF7FF) & 16'hEFFF) & 16'hDFFF) & 16'hBFFF) & 16'h7FFF;	// file.cleaned.mlir:3:14, :4:14, :5:14, :6:14, :7:15, :8:14, :9:15, :10:14, :11:15, :12:14, :13:15, :14:14, :15:15, :16:14, :17:19, :18:20, :19:19, :20:19, :21:19, :22:19, :23:18, :24:18, :25:18, :26:17, :27:17, :28:17, :29:16, :30:16, :31:15, :32:10, :33:10, :34:10, :35:10, :36:10, :37:10, :38:10, :39:10, :40:10, :41:10, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :65:11, :66:11, :67:11, :68:11, :69:11, :70:11, :71:11, :72:11, :73:11, :74:11, :75:11, :76:11, :79:11, :103:11, :128:11, :162:12, :202:12, :242:12, :283:12, :323:12, :353:12, :358:12, :363:12, :368:12, :373:12, :378:12, :382:12, :383:12, :384:5
endmodule

