// Generated by CIRCT unknown git version
module common_clkmux(	// file.cleaned.mlir:2:3
  input  I0,	// file.cleaned.mlir:2:31
         I1,	// file.cleaned.mlir:2:44
         S,	// file.cleaned.mlir:2:57
  output Z	// file.cleaned.mlir:2:70
);

  assign Z = S ? I1 : I0;	// file.cleaned.mlir:3:10, :4:5
endmodule

module common_clkinv(	// file.cleaned.mlir:6:3
  input  I,	// file.cleaned.mlir:6:31
  output ZN	// file.cleaned.mlir:6:44
);

  assign ZN = ~I;	// file.cleaned.mlir:8:10, :9:5
endmodule

