// Generated by CIRCT unknown git version
module sqrt(	// file.cleaned.mlir:2:3
  input  [11:0] x_in,	// file.cleaned.mlir:2:22
  output [11:0] x_out	// file.cleaned.mlir:2:39
);

  wire [11:0] _GEN;	// file.cleaned.mlir:178:12
  wire [12:0] _GEN_0;	// file.cleaned.mlir:170:12
  wire [11:0] _GEN_1;	// file.cleaned.mlir:164:12
  wire [11:0] _GEN_2;	// file.cleaned.mlir:161:12
  wire [12:0] _GEN_3;	// file.cleaned.mlir:153:12
  wire [11:0] _GEN_4;	// file.cleaned.mlir:147:12
  wire [11:0] _GEN_5;	// file.cleaned.mlir:144:12
  wire [12:0] _GEN_6;	// file.cleaned.mlir:136:12
  wire [11:0] _GEN_7;	// file.cleaned.mlir:130:11
  wire [11:0] _GEN_8;	// file.cleaned.mlir:127:11
  wire [12:0] _GEN_9;	// file.cleaned.mlir:119:11
  wire [11:0] _GEN_10;	// file.cleaned.mlir:113:11
  wire [11:0] _GEN_11;	// file.cleaned.mlir:110:11
  wire [12:0] _GEN_12;	// file.cleaned.mlir:102:11
  wire [11:0] _GEN_13;	// file.cleaned.mlir:96:11
  wire [11:0] _GEN_14;	// file.cleaned.mlir:93:11
  wire [12:0] _GEN_15;	// file.cleaned.mlir:85:11
  wire [83:0] _GEN_16 =
    {_GEN, 72'h0}
    | ({12'h0, _GEN_2, 60'h0}
       | ({24'h0, _GEN_5, 48'h0}
          | ({36'h0, _GEN_8, 36'h0} | ({48'h0, _GEN_11, 24'h0} | {60'h0, _GEN_14, 12'h0})
             & 84'hFFFFFFFFF000FFFFFFFFF) & 84'hFFFFFF000FFFFFFFFFFFF)
       & 84'hFFF000FFFFFFFFFFFFFFF) & 84'hFFFFFFFFFFFFFFFFFF;	// file.cleaned.mlir:20:15, :21:15, :22:15, :23:15, :29:36, :30:37, :31:34, :32:30, :33:15, :34:15, :35:10, :36:10, :37:10, :38:10, :39:10, :40:10, :41:10, :42:10, :43:10, :44:10, :45:11, :46:11, :47:11, :48:11, :49:11, :93:11, :110:11, :127:11, :144:12, :161:12, :178:12
  wire [71:0] _GEN_17 =
    {_GEN_1, 60'h0}
    | {12'h0,
       {_GEN_4, 48'h0}
         | {12'h0,
            {_GEN_7, 36'h0}
              | {12'h0, {_GEN_10, 24'h0} | {12'h0, {_GEN_13, 12'h0} | {12'h0, x_in}}}}};	// file.cleaned.mlir:21:15, :22:15, :23:15, :33:15, :34:15, :50:11, :51:11, :52:11, :53:11, :54:11, :55:11, :56:11, :57:11, :58:11, :59:11, :60:11, :61:11, :62:11, :63:11, :64:11, :96:11, :113:11, :130:11, :147:12, :164:12
  wire [77:0] _GEN_18 =
    {_GEN_0, 65'h0}
    | ({13'h0, _GEN_3, 52'h0}
       | ({26'h0, _GEN_6, 39'h0}
          | ({39'h0, _GEN_9, 26'h0} | ({52'h0, _GEN_12, 13'h0} | {65'h0, _GEN_15})
             & 78'h3FFFFFFFFF8003FFFFFF) & 78'h3FFFFFF0007FFFFFFFFF)
       & 78'h3FFE000FFFFFFFFFFFFF) & 78'h1FFFFFFFFFFFFFFFF;	// file.cleaned.mlir:15:15, :16:15, :17:15, :18:15, :19:15, :25:34, :26:35, :27:31, :28:27, :65:11, :66:11, :67:11, :68:11, :69:11, :70:11, :71:11, :72:11, :73:11, :74:11, :75:11, :76:11, :77:11, :78:11, :79:11, :85:11, :102:11, :119:11, :136:12, :153:12, :170:12
  assign _GEN_15 = {1'h0, _GEN_17[11:0]} - ({1'h0, _GEN_16[11:0]} + 13'h400);	// file.cleaned.mlir:13:18, :24:14, :49:11, :64:11, :80:11, :81:11, :82:11, :83:11, :84:11, :85:11
  wire        _GEN_19 = x_in < 12'h400;	// file.cleaned.mlir:14:18, :86:11
  wire [11:0] _GEN_20 = {1'h0, _GEN_16[11:1]};	// file.cleaned.mlir:24:14, :49:11, :88:11, :89:11
  assign _GEN_14 = _GEN_19 ? 12'h0 : _GEN_18[12] ? _GEN_20 : _GEN_20 + 12'h400;	// file.cleaned.mlir:14:18, :34:15, :79:11, :86:11, :87:11, :89:11, :90:11, :92:11, :93:11
  assign _GEN_13 = _GEN_19 ? x_in : _GEN_18[12] ? _GEN_17[11:0] : _GEN_18[11:0];	// file.cleaned.mlir:64:11, :79:11, :80:11, :86:11, :87:11, :94:11, :95:11, :96:11
  assign _GEN_12 = {1'h0, _GEN_17[23:12]} - ({1'h0, _GEN_16[23:12]} + 13'h100);	// file.cleaned.mlir:11:17, :24:14, :49:11, :64:11, :97:11, :98:11, :99:11, :100:11, :101:11, :102:11
  wire        _GEN_21 = x_in < 12'h100;	// file.cleaned.mlir:12:17, :103:11
  wire [11:0] _GEN_22 = {1'h0, _GEN_16[23:13]};	// file.cleaned.mlir:24:14, :49:11, :105:11, :106:11
  assign _GEN_11 = _GEN_21 ? 12'h0 : _GEN_18[25] ? _GEN_22 : _GEN_22 + 12'h100;	// file.cleaned.mlir:12:17, :34:15, :79:11, :103:11, :104:11, :106:11, :107:11, :109:11, :110:11
  assign _GEN_10 = _GEN_21 ? x_in : _GEN_18[25] ? _GEN_17[23:12] : _GEN_18[24:13];	// file.cleaned.mlir:64:11, :79:11, :97:11, :103:11, :104:11, :111:11, :112:11, :113:11
  assign _GEN_9 = {1'h0, _GEN_17[35:24]} - ({1'h0, _GEN_16[35:24]} + 13'h40);	// file.cleaned.mlir:9:16, :24:14, :49:11, :64:11, :114:11, :115:11, :116:11, :117:11, :118:11, :119:11
  wire        _GEN_23 = x_in < 12'h40;	// file.cleaned.mlir:10:16, :120:11
  wire [11:0] _GEN_24 = {1'h0, _GEN_16[35:25]};	// file.cleaned.mlir:24:14, :49:11, :122:11, :123:11
  assign _GEN_8 = _GEN_23 ? 12'h0 : _GEN_18[38] ? _GEN_24 : _GEN_24 + 12'h40;	// file.cleaned.mlir:10:16, :34:15, :79:11, :120:11, :121:11, :123:11, :124:11, :126:11, :127:11
  assign _GEN_7 = _GEN_23 ? x_in : _GEN_18[38] ? _GEN_17[35:24] : _GEN_18[37:26];	// file.cleaned.mlir:64:11, :79:11, :114:11, :120:11, :121:11, :128:11, :129:11, :130:11
  assign _GEN_6 = {1'h0, _GEN_17[47:36]} - ({1'h0, _GEN_16[47:36]} + 13'h10);	// file.cleaned.mlir:7:16, :24:14, :49:11, :64:11, :131:11, :132:11, :133:11, :134:11, :135:12, :136:12
  wire        _GEN_25 = x_in < 12'h10;	// file.cleaned.mlir:8:16, :137:12
  wire [11:0] _GEN_26 = {1'h0, _GEN_16[47:37]};	// file.cleaned.mlir:24:14, :49:11, :139:12, :140:12
  assign _GEN_5 = _GEN_25 ? 12'h0 : _GEN_18[51] ? _GEN_26 : _GEN_26 + 12'h10;	// file.cleaned.mlir:8:16, :34:15, :79:11, :137:12, :138:12, :140:12, :141:12, :143:12, :144:12
  assign _GEN_4 = _GEN_25 ? x_in : _GEN_18[51] ? _GEN_17[47:36] : _GEN_18[50:39];	// file.cleaned.mlir:64:11, :79:11, :131:11, :137:12, :138:12, :145:12, :146:12, :147:12
  assign _GEN_3 = {1'h0, _GEN_17[59:48]} - ({1'h0, _GEN_16[59:48]} + 13'h4);	// file.cleaned.mlir:5:15, :24:14, :49:11, :64:11, :148:12, :149:12, :150:12, :151:12, :152:12, :153:12
  wire        _GEN_27 = x_in < 12'h4;	// file.cleaned.mlir:6:15, :154:12
  wire [11:0] _GEN_28 = {1'h0, _GEN_16[59:49]};	// file.cleaned.mlir:24:14, :49:11, :156:12, :157:12
  assign _GEN_2 = _GEN_27 ? 12'h0 : _GEN_18[64] ? _GEN_28 : _GEN_28 + 12'h4;	// file.cleaned.mlir:6:15, :34:15, :79:11, :154:12, :155:12, :157:12, :158:12, :160:12, :161:12
  assign _GEN_1 = _GEN_27 ? x_in : _GEN_18[64] ? _GEN_17[59:48] : _GEN_18[63:52];	// file.cleaned.mlir:64:11, :79:11, :148:12, :154:12, :155:12, :162:12, :163:12, :164:12
  assign _GEN_0 = {1'h0, _GEN_17[71:60]} - ({1'h0, _GEN_16[71:60]} + 13'h1);	// file.cleaned.mlir:4:15, :24:14, :49:11, :64:11, :165:12, :166:12, :167:12, :168:12, :169:12, :170:12
  wire [11:0] _GEN_29 = {1'h0, _GEN_16[71:61]};	// file.cleaned.mlir:24:14, :49:11, :173:12, :174:12
  assign _GEN = x_in == 12'h0 ? 12'h0 : _GEN_18[77] ? _GEN_29 : _GEN_29 + 12'h1;	// file.cleaned.mlir:3:15, :34:15, :79:11, :171:12, :172:12, :174:12, :175:12, :177:12, :178:12
  assign x_out = _GEN_16[83:72];	// file.cleaned.mlir:49:11, :179:12, :180:5
endmodule

