// Generated by CIRCT unknown git version
module shift(	// file.cleaned.mlir:2:3
  input  [3:0] D,	// file.cleaned.mlir:2:23
               S,	// file.cleaned.mlir:2:35
  output [5:0] SHL,	// file.cleaned.mlir:2:48
               SHR,	// file.cleaned.mlir:2:62
               ASHL,	// file.cleaned.mlir:2:76
               ASHR	// file.cleaned.mlir:2:91
);

  wire [5:0] _GEN = {2'h0, D};	// file.cleaned.mlir:3:14, :4:10
  wire [5:0] _GEN_0 = {2'h0, S};	// file.cleaned.mlir:3:14, :5:10
  wire [5:0] _GEN_1 = {{2{D[3]}}, D};	// file.cleaned.mlir:8:10, :9:10, :10:10
  assign SHL = _GEN << _GEN_0;	// file.cleaned.mlir:4:10, :5:10, :6:10, :13:5
  assign SHR = _GEN >> _GEN_0;	// file.cleaned.mlir:4:10, :5:10, :7:10, :13:5
  assign ASHL = _GEN_1 << _GEN_0;	// file.cleaned.mlir:5:10, :10:10, :11:10, :13:5
  assign ASHR = $signed($signed(_GEN_1) >>> _GEN_0);	// file.cleaned.mlir:5:10, :10:10, :12:10, :13:5
endmodule

