// Generated by CIRCT unknown git version
module ge2(	// file.cleaned.mlir:2:3
  input  [1:0] A,	// file.cleaned.mlir:2:21
               B,	// file.cleaned.mlir:2:33
  output       out	// file.cleaned.mlir:2:46
);

  assign out = A >= B;	// file.cleaned.mlir:3:10, :4:5
endmodule

