// Generated by CIRCT unknown git version
module eqne(	// file.cleaned.mlir:2:3
  input  [7:0] x,	// file.cleaned.mlir:2:22
               y,	// file.cleaned.mlir:2:34
  output       eq1,	// file.cleaned.mlir:2:47
               ne1,	// file.cleaned.mlir:2:61
               eq2,	// file.cleaned.mlir:2:75
               ne2,	// file.cleaned.mlir:2:89
               eq5,	// file.cleaned.mlir:2:103
               ne5	// file.cleaned.mlir:2:117
);

  assign eq1 = x[0] == y[0];	// file.cleaned.mlir:3:10, :4:10, :5:10, :15:5
  assign ne1 = x[0] != y[0];	// file.cleaned.mlir:3:10, :4:10, :6:10, :15:5
  assign eq2 = x[1:0] == y[1:0];	// file.cleaned.mlir:7:10, :8:10, :9:10, :15:5
  assign ne2 = x[1:0] != y[1:0];	// file.cleaned.mlir:7:10, :8:10, :10:10, :15:5
  assign eq5 = x[4:0] == y[4:0];	// file.cleaned.mlir:11:10, :12:10, :13:11, :15:5
  assign ne5 = x[4:0] != y[4:0];	// file.cleaned.mlir:11:10, :12:10, :14:11, :15:5
endmodule

