// Generated by CIRCT unknown git version
module test(	// file.cleaned.mlir:2:3
  input b	// file.cleaned.mlir:2:22
);

  a ua (	// file.cleaned.mlir:3:5
    .BISTEA (b),
    .BISTEB (b)
  );	// file.cleaned.mlir:3:5
endmodule

module a(	// file.cleaned.mlir:6:3
  input BISTEA,	// file.cleaned.mlir:6:27
        BISTEB	// file.cleaned.mlir:6:44
);

endmodule

