// Generated by CIRCT unknown git version
module test();	// file.cleaned.mlir:2:3
  a a_ (	// file.cleaned.mlir:4:5
    .b     (1'h0),	// file.cleaned.mlir:3:14
    .b_buf (1'h0)	// file.cleaned.mlir:3:14
  );	// file.cleaned.mlir:4:5
endmodule

module a(	// file.cleaned.mlir:7:3
  input b,	// file.cleaned.mlir:7:27
        b_buf	// file.cleaned.mlir:7:39
);

endmodule

