// Generated by CIRCT unknown git version
module jelly_texture_blk_addr(	// file.cleaned.mlir:2:3
  input         reset,	// file.cleaned.mlir:2:40
                clk,	// file.cleaned.mlir:2:56
                s_user,	// file.cleaned.mlir:2:70
  input  [11:0] s_addrx,	// file.cleaned.mlir:2:87
                s_addry,	// file.cleaned.mlir:2:106
  input         s_valid,	// file.cleaned.mlir:2:125
                m_ready,	// file.cleaned.mlir:2:143
  output        s_ready,	// file.cleaned.mlir:2:162
                m_user,	// file.cleaned.mlir:2:180
                m_last,	// file.cleaned.mlir:2:197
  output [11:0] m_addrx,	// file.cleaned.mlir:2:214
                m_addry,	// file.cleaned.mlir:2:233
  output        m_valid	// file.cleaned.mlir:2:252
);

  assign s_ready = m_ready;	// file.cleaned.mlir:4:5
  assign m_user = s_user;	// file.cleaned.mlir:4:5
  assign m_last = 1'h1;	// file.cleaned.mlir:3:13, :4:5
  assign m_addrx = s_addrx;	// file.cleaned.mlir:4:5
  assign m_addry = s_addry;	// file.cleaned.mlir:4:5
  assign m_valid = s_valid;	// file.cleaned.mlir:4:5
endmodule

