// Generated by CIRCT unknown git version
module pll_neptuno(	// file.cleaned.mlir:2:3
  input  areset,	// file.cleaned.mlir:2:29
         inclk0,	// file.cleaned.mlir:2:46
  output c0,	// file.cleaned.mlir:2:64
         locked	// file.cleaned.mlir:2:77
);

  assign c0 = 1'h0;	// file.cleaned.mlir:3:14, :4:5
  assign locked = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

