// Generated by CIRCT unknown git version
module la_clkinv(	// file.cleaned.mlir:2:3
  input  a,	// file.cleaned.mlir:2:27
  output z	// file.cleaned.mlir:2:40
);

  assign z = ~a;	// file.cleaned.mlir:4:10, :5:5
endmodule

