// Generated by CIRCT unknown git version
module la_clkxor2(	// file.cleaned.mlir:2:3
  input  a,	// file.cleaned.mlir:2:28
         b,	// file.cleaned.mlir:2:40
  output z	// file.cleaned.mlir:2:53
);

  assign z = a ^ b;	// file.cleaned.mlir:3:10, :4:5
endmodule

