// Generated by CIRCT unknown git version
module circular_barrel_shift(	// file.cleaned.mlir:2:3
  input  [39:0] input_val,	// file.cleaned.mlir:2:39
  input  [5:0]  shift_amt,	// file.cleaned.mlir:2:60
  output [39:0] output_val	// file.cleaned.mlir:2:81
);

  wire [39:0] _GEN =
    shift_amt[0] ? {1'h0, input_val[39:1]} | {input_val[0], 39'h0} : input_val;	// file.cleaned.mlir:11:15, :12:14, :13:10, :14:10, :15:10, :16:10, :17:10, :18:10, :19:10
  wire [39:0] _GEN_0 = shift_amt[1] ? {2'h0, _GEN[39:2]} | {_GEN[1:0], 38'h0} : _GEN;	// file.cleaned.mlir:9:15, :10:14, :19:10, :20:10, :21:10, :22:10, :23:11, :24:11, :25:11, :26:11
  wire [39:0] _GEN_1 =
    shift_amt[2] ? {4'h0, _GEN_0[39:4]} | {_GEN_0[3:0], 36'h0} : _GEN_0;	// file.cleaned.mlir:7:15, :8:14, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11
  wire [39:0] _GEN_2 =
    shift_amt[3] ? {8'h0, _GEN_1[39:8]} | {_GEN_1[7:0], 32'h0} : _GEN_1;	// file.cleaned.mlir:5:15, :6:14, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11
  wire [39:0] _GEN_3 =
    shift_amt[4] ? {16'h0, _GEN_2[39:16]} | {_GEN_2[15:0], 24'h0} : _GEN_2;	// file.cleaned.mlir:3:15, :4:15, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11
  assign output_val =
    shift_amt[5] ? {32'h0, _GEN_3[39:32]} | {_GEN_3[31:0], 8'h0} : _GEN_3;	// file.cleaned.mlir:5:15, :6:14, :47:11, :48:11, :49:11, :50:11, :51:11, :52:11, :53:11, :54:11, :55:5
endmodule

