// Generated by CIRCT unknown git version
module g_p_carry_section(	// file.cleaned.mlir:2:3
  input  input3_out1,	// file.cleaned.mlir:2:35
         input3_out2,	// file.cleaned.mlir:2:57
         input2_out1,	// file.cleaned.mlir:2:79
         input2_out2,	// file.cleaned.mlir:2:101
         input1_out1,	// file.cleaned.mlir:2:123
         input1_out2,	// file.cleaned.mlir:2:145
         input0_out1,	// file.cleaned.mlir:2:167
         input0_out2,	// file.cleaned.mlir:2:189
         ci_bar,	// file.cleaned.mlir:2:211
  output co_bar,	// file.cleaned.mlir:2:229
         x,	// file.cleaned.mlir:2:246
         y	// file.cleaned.mlir:2:258
);

  wire _GEN = input3_out1 & input2_out1;	// file.cleaned.mlir:5:10
  wire _GEN_0 = _GEN & input1_out1;	// file.cleaned.mlir:5:10, :7:10
  wire _GEN_1 =
    input3_out2 | input3_out1 & input2_out2 | _GEN & input1_out2 | _GEN_0 & input0_out2;	// file.cleaned.mlir:4:10, :5:10, :6:10, :7:10, :8:10, :9:10
  wire _GEN_2 = _GEN_0 & input0_out1;	// file.cleaned.mlir:7:10, :11:10
  assign co_bar = _GEN_1 | _GEN_2 & ci_bar;	// file.cleaned.mlir:9:10, :11:10, :12:10, :13:10, :15:5
  assign x = ~_GEN_2;	// file.cleaned.mlir:11:10, :14:11, :15:5
  assign y = ~_GEN_1;	// file.cleaned.mlir:9:10, :10:10, :15:5
endmodule

