// Generated by CIRCT unknown git version
module asic_aoi211(	// file.cleaned.mlir:2:3
  input  a0,	// file.cleaned.mlir:2:29
         a1,	// file.cleaned.mlir:2:42
         b0,	// file.cleaned.mlir:2:55
         c0,	// file.cleaned.mlir:2:68
  output z	// file.cleaned.mlir:2:82
);

  assign z = ~(a0 & a1 | b0 | c0);	// file.cleaned.mlir:4:10, :5:10, :6:10, :7:5
endmodule

