// Generated by CIRCT unknown git version
module asic_xnor2(	// file.cleaned.mlir:2:3
  input  a,	// file.cleaned.mlir:2:28
         b,	// file.cleaned.mlir:2:40
  output z	// file.cleaned.mlir:2:53
);

  assign z = a ^ ~b;	// file.cleaned.mlir:4:10, :5:5
endmodule

