// Generated by CIRCT unknown git version
module oh_mux2(	// file.cleaned.mlir:2:3
  input  sel1,	// file.cleaned.mlir:2:25
         sel0,	// file.cleaned.mlir:2:40
         in1,	// file.cleaned.mlir:2:55
         in0,	// file.cleaned.mlir:2:69
  output out	// file.cleaned.mlir:2:84
);

  assign out = sel0 & in0 | sel1 & in1;	// file.cleaned.mlir:3:10, :4:10, :5:10, :6:5
endmodule

