// Generated by CIRCT unknown git version
module oh_parity(	// file.cleaned.mlir:2:3
  input  [1:0] in,	// file.cleaned.mlir:2:27
  output       out	// file.cleaned.mlir:2:41
);

  assign out = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

