// Generated by CIRCT unknown git version
module oh_or4(	// file.cleaned.mlir:2:3
  input  a,	// file.cleaned.mlir:2:24
         b,	// file.cleaned.mlir:2:36
         c,	// file.cleaned.mlir:2:48
         d,	// file.cleaned.mlir:2:60
  output z	// file.cleaned.mlir:2:73
);

  assign z = a | b | c | d;	// file.cleaned.mlir:3:10, :4:5
endmodule

