// Generated by CIRCT unknown git version
module IBUFDS_IBUFDISABLE(	// file.cleaned.mlir:2:3
  input  I,	// file.cleaned.mlir:2:36
         IB,	// file.cleaned.mlir:2:48
         IBUFDISABLE,	// file.cleaned.mlir:2:61
  output O	// file.cleaned.mlir:2:84
);

  assign O = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

