// Generated by CIRCT unknown git version
module ODELAYE2(	// file.cleaned.mlir:2:3
  input        C,	// file.cleaned.mlir:2:26
               CE,	// file.cleaned.mlir:2:38
               CINVCTRL,	// file.cleaned.mlir:2:51
               CLKIN,	// file.cleaned.mlir:2:70
  input  [4:0] CNTVALUEIN,	// file.cleaned.mlir:2:86
  input        INC,	// file.cleaned.mlir:2:107
               LD,	// file.cleaned.mlir:2:121
               LDPIPEEN,	// file.cleaned.mlir:2:134
               ODATAIN,	// file.cleaned.mlir:2:153
               REGRST,	// file.cleaned.mlir:2:171
  output [4:0] CNTVALUEOUT,	// file.cleaned.mlir:2:189
  output       DATAOUT	// file.cleaned.mlir:2:211
);

  assign CNTVALUEOUT = 5'h0;	// file.cleaned.mlir:3:14, :4:5
  assign DATAOUT = ODATAIN;	// file.cleaned.mlir:4:5
endmodule

