// Generated by CIRCT unknown git version
module echowire2(	// file.cleaned.mlir:2:3
  input  dtr,	// file.cleaned.mlir:2:27
         rts,	// file.cleaned.mlir:2:41
         rx,	// file.cleaned.mlir:2:55
         tx2,	// file.cleaned.mlir:2:68
  output tx,	// file.cleaned.mlir:2:83
         rx2,	// file.cleaned.mlir:2:96
         D1,	// file.cleaned.mlir:2:110
         D2	// file.cleaned.mlir:2:123
);

  assign tx = tx2;	// file.cleaned.mlir:3:5
  assign rx2 = rx;	// file.cleaned.mlir:3:5
  assign D1 = dtr;	// file.cleaned.mlir:3:5
  assign D2 = rts;	// file.cleaned.mlir:3:5
endmodule

