// Generated by CIRCT unknown git version
module aq_cpuio_top(	// file.cleaned.mlir:2:3
  input  [63:0] clint_cpuio_time,	// file.cleaned.mlir:2:30
  input  [1:0]  cp0_biu_lpmd_b,	// file.cleaned.mlir:2:58
  input  [2:0]  pad_biu_coreid,	// file.cleaned.mlir:2:83
  input         sysio_cpuio_me_int,	// file.cleaned.mlir:2:108
                sysio_cpuio_ms_int,	// file.cleaned.mlir:2:137
                sysio_cpuio_mt_int,	// file.cleaned.mlir:2:166
                sysio_cpuio_se_int,	// file.cleaned.mlir:2:195
                sysio_cpuio_ss_int,	// file.cleaned.mlir:2:224
                sysio_cpuio_st_int,	// file.cleaned.mlir:2:253
  input  [39:0] sysio_xx_rvba,	// file.cleaned.mlir:2:282
  output [2:0]  biu_cp0_coreid,	// file.cleaned.mlir:2:308
  output        biu_cp0_me_int,	// file.cleaned.mlir:2:333
                biu_cp0_ms_int,	// file.cleaned.mlir:2:358
                biu_cp0_mt_int,	// file.cleaned.mlir:2:383
  output [39:0] biu_cp0_rvba,	// file.cleaned.mlir:2:408
  output        biu_cp0_se_int,	// file.cleaned.mlir:2:432
                biu_cp0_ss_int,	// file.cleaned.mlir:2:457
                biu_cp0_st_int,	// file.cleaned.mlir:2:482
  output [63:0] biu_hpcp_time,	// file.cleaned.mlir:2:507
  output [1:0]  cpuio_sysio_lpmd_b	// file.cleaned.mlir:2:532
);

  assign biu_cp0_coreid = pad_biu_coreid;	// file.cleaned.mlir:3:5
  assign biu_cp0_me_int = sysio_cpuio_me_int;	// file.cleaned.mlir:3:5
  assign biu_cp0_ms_int = sysio_cpuio_ms_int;	// file.cleaned.mlir:3:5
  assign biu_cp0_mt_int = sysio_cpuio_mt_int;	// file.cleaned.mlir:3:5
  assign biu_cp0_rvba = sysio_xx_rvba;	// file.cleaned.mlir:3:5
  assign biu_cp0_se_int = sysio_cpuio_se_int;	// file.cleaned.mlir:3:5
  assign biu_cp0_ss_int = sysio_cpuio_ss_int;	// file.cleaned.mlir:3:5
  assign biu_cp0_st_int = sysio_cpuio_st_int;	// file.cleaned.mlir:3:5
  assign biu_hpcp_time = clint_cpuio_time;	// file.cleaned.mlir:3:5
  assign cpuio_sysio_lpmd_b = cp0_biu_lpmd_b;	// file.cleaned.mlir:3:5
endmodule

