// Generated by CIRCT unknown git version
module mega_rom(	// file.cleaned.mlir:2:3
  input         clk,	// file.cleaned.mlir:2:26
  input  [13:0] a,	// file.cleaned.mlir:2:40
  input         cs,	// file.cleaned.mlir:2:53
  output [15:0] d	// file.cleaned.mlir:2:67
);

  assign d = 16'h0;	// file.cleaned.mlir:3:15, :4:5
endmodule

