// Generated by CIRCT unknown git version
module axi_rd_wr_combiner(	// file.cleaned.mlir:2:3
  input         clk,	// file.cleaned.mlir:2:36
                m_axi_awready,	// file.cleaned.mlir:2:50
                m_axi_wready,	// file.cleaned.mlir:2:74
                m_axi_bvalid,	// file.cleaned.mlir:2:97
  input  [1:0]  m_axi_bresp,	// file.cleaned.mlir:2:120
  input         m_axi_arready,	// file.cleaned.mlir:2:142
                m_axi_rvalid,	// file.cleaned.mlir:2:166
  input  [1:0]  m_axi_rresp,	// file.cleaned.mlir:2:189
  input  [63:0] m_axi_rdata,	// file.cleaned.mlir:2:211
  input         m_axi_rlast,	// file.cleaned.mlir:2:234
  input  [31:0] s_wr_axi_awaddr,	// file.cleaned.mlir:2:256
  input  [3:0]  s_wr_axi_awlen,	// file.cleaned.mlir:2:283
  input  [2:0]  s_wr_axi_awsize,	// file.cleaned.mlir:2:308
  input  [1:0]  s_wr_axi_awburst,	// file.cleaned.mlir:2:334
  input  [2:0]  s_wr_axi_awprot,	// file.cleaned.mlir:2:361
  input  [3:0]  s_wr_axi_awcache,	// file.cleaned.mlir:2:387
  input         s_wr_axi_awvalid,	// file.cleaned.mlir:2:414
  input  [63:0] s_wr_axi_wdata,	// file.cleaned.mlir:2:441
  input  [7:0]  s_wr_axi_wstrb,	// file.cleaned.mlir:2:467
  input         s_wr_axi_wvalid,	// file.cleaned.mlir:2:492
                s_wr_axi_wlast,	// file.cleaned.mlir:2:518
                s_wr_axi_bready,	// file.cleaned.mlir:2:543
                s_rd_axi_arvalid,	// file.cleaned.mlir:2:569
  input  [31:0] s_rd_axi_araddr,	// file.cleaned.mlir:2:596
  input  [3:0]  s_rd_axi_arlen,	// file.cleaned.mlir:2:623
  input  [2:0]  s_rd_axi_arsize,	// file.cleaned.mlir:2:648
  input  [1:0]  s_rd_axi_arburst,	// file.cleaned.mlir:2:674
  input  [3:0]  s_rd_axi_arcache,	// file.cleaned.mlir:2:701
  input  [2:0]  s_rd_axi_arprot,	// file.cleaned.mlir:2:728
  input         s_rd_axi_rready,	// file.cleaned.mlir:2:754
  output [31:0] m_axi_awaddr,	// file.cleaned.mlir:2:781
  output [3:0]  m_axi_awlen,	// file.cleaned.mlir:2:805
  output [2:0]  m_axi_awsize,	// file.cleaned.mlir:2:827
  output [1:0]  m_axi_awburst,	// file.cleaned.mlir:2:850
  output [2:0]  m_axi_awprot,	// file.cleaned.mlir:2:874
  output [3:0]  m_axi_awcache,	// file.cleaned.mlir:2:897
  output        m_axi_awvalid,	// file.cleaned.mlir:2:921
  output [63:0] m_axi_wdata,	// file.cleaned.mlir:2:945
  output [7:0]  m_axi_wstrb,	// file.cleaned.mlir:2:968
  output        m_axi_wvalid,	// file.cleaned.mlir:2:990
                m_axi_wlast,	// file.cleaned.mlir:2:1013
                m_axi_bready,	// file.cleaned.mlir:2:1035
                m_axi_arvalid,	// file.cleaned.mlir:2:1058
  output [31:0] m_axi_araddr,	// file.cleaned.mlir:2:1082
  output [3:0]  m_axi_arlen,	// file.cleaned.mlir:2:1106
  output [2:0]  m_axi_arsize,	// file.cleaned.mlir:2:1128
  output [1:0]  m_axi_arburst,	// file.cleaned.mlir:2:1151
  output [3:0]  m_axi_arcache,	// file.cleaned.mlir:2:1175
  output [2:0]  m_axi_arprot,	// file.cleaned.mlir:2:1199
  output        m_axi_rready,	// file.cleaned.mlir:2:1222
                s_wr_axi_awready,	// file.cleaned.mlir:2:1245
                s_wr_axi_wready,	// file.cleaned.mlir:2:1272
                s_wr_axi_bvalid,	// file.cleaned.mlir:2:1298
  output [1:0]  s_wr_axi_bresp,	// file.cleaned.mlir:2:1324
  output        s_rd_axi_arready,	// file.cleaned.mlir:2:1349
                s_rd_axi_rvalid,	// file.cleaned.mlir:2:1376
  output [1:0]  s_rd_axi_rresp,	// file.cleaned.mlir:2:1402
  output [63:0] s_rd_axi_rdata,	// file.cleaned.mlir:2:1427
  output        s_rd_axi_rlast	// file.cleaned.mlir:2:1453
);

  assign m_axi_awaddr = s_wr_axi_awaddr;	// file.cleaned.mlir:3:5
  assign m_axi_awlen = s_wr_axi_awlen;	// file.cleaned.mlir:3:5
  assign m_axi_awsize = s_wr_axi_awsize;	// file.cleaned.mlir:3:5
  assign m_axi_awburst = s_wr_axi_awburst;	// file.cleaned.mlir:3:5
  assign m_axi_awprot = s_wr_axi_awprot;	// file.cleaned.mlir:3:5
  assign m_axi_awcache = s_wr_axi_awcache;	// file.cleaned.mlir:3:5
  assign m_axi_awvalid = s_wr_axi_awvalid;	// file.cleaned.mlir:3:5
  assign m_axi_wdata = s_wr_axi_wdata;	// file.cleaned.mlir:3:5
  assign m_axi_wstrb = s_wr_axi_wstrb;	// file.cleaned.mlir:3:5
  assign m_axi_wvalid = s_wr_axi_wvalid;	// file.cleaned.mlir:3:5
  assign m_axi_wlast = s_wr_axi_wlast;	// file.cleaned.mlir:3:5
  assign m_axi_bready = s_wr_axi_bready;	// file.cleaned.mlir:3:5
  assign m_axi_arvalid = s_rd_axi_arvalid;	// file.cleaned.mlir:3:5
  assign m_axi_araddr = s_rd_axi_araddr;	// file.cleaned.mlir:3:5
  assign m_axi_arlen = s_rd_axi_arlen;	// file.cleaned.mlir:3:5
  assign m_axi_arsize = s_rd_axi_arsize;	// file.cleaned.mlir:3:5
  assign m_axi_arburst = s_rd_axi_arburst;	// file.cleaned.mlir:3:5
  assign m_axi_arcache = s_rd_axi_arcache;	// file.cleaned.mlir:3:5
  assign m_axi_arprot = s_rd_axi_arprot;	// file.cleaned.mlir:3:5
  assign m_axi_rready = s_rd_axi_rready;	// file.cleaned.mlir:3:5
  assign s_wr_axi_awready = m_axi_awready;	// file.cleaned.mlir:3:5
  assign s_wr_axi_wready = m_axi_wready;	// file.cleaned.mlir:3:5
  assign s_wr_axi_bvalid = m_axi_bvalid;	// file.cleaned.mlir:3:5
  assign s_wr_axi_bresp = m_axi_bresp;	// file.cleaned.mlir:3:5
  assign s_rd_axi_arready = m_axi_arready;	// file.cleaned.mlir:3:5
  assign s_rd_axi_rvalid = m_axi_rvalid;	// file.cleaned.mlir:3:5
  assign s_rd_axi_rresp = m_axi_rresp;	// file.cleaned.mlir:3:5
  assign s_rd_axi_rdata = m_axi_rdata;	// file.cleaned.mlir:3:5
  assign s_rd_axi_rlast = m_axi_rlast;	// file.cleaned.mlir:3:5
endmodule

