// Generated by CIRCT unknown git version
module LUT1(	// file.cleaned.mlir:2:3
  input  I0,	// file.cleaned.mlir:2:22
  output O	// file.cleaned.mlir:2:36
);

  assign O = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

