// Generated by CIRCT unknown git version
module cordic_int_part_exp_rom_ip(	// file.cleaned.mlir:2:3
  input  [7:0]  address,	// file.cleaned.mlir:2:44
  input         clock,	// file.cleaned.mlir:2:62
  output [31:0] q	// file.cleaned.mlir:2:79
);

  assign q = 32'h0;	// file.cleaned.mlir:3:15, :4:5
endmodule

