// Generated by CIRCT unknown git version
module line_buf_400pts_2lines(	// file.cleaned.mlir:2:3
  input        aclr,	// file.cleaned.mlir:2:40
               clken,	// file.cleaned.mlir:2:55
               clock,	// file.cleaned.mlir:2:71
  input  [8:0] shiftin,	// file.cleaned.mlir:2:87
  output [8:0] shiftout,	// file.cleaned.mlir:2:106
               taps0x,	// file.cleaned.mlir:2:125
               taps1x	// file.cleaned.mlir:2:142
);

  assign shiftout = 9'h0;	// file.cleaned.mlir:3:14, :4:5
  assign taps0x = 9'h0;	// file.cleaned.mlir:3:14, :4:5
  assign taps1x = 9'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

