// Generated by CIRCT unknown git version
module svm_vut_scfifo_1649x128(	// file.cleaned.mlir:2:3
  input           aclr,	// file.cleaned.mlir:2:41
                  clock,	// file.cleaned.mlir:2:56
  input  [1648:0] data,	// file.cleaned.mlir:2:72
  input           rdreq,	// file.cleaned.mlir:2:90
                  sclr,	// file.cleaned.mlir:2:106
                  wrreq,	// file.cleaned.mlir:2:121
  output          empty,	// file.cleaned.mlir:2:138
                  full,	// file.cleaned.mlir:2:154
  output [1648:0] q,	// file.cleaned.mlir:2:169
  output [7:0]    usedw	// file.cleaned.mlir:2:184
);

  assign empty = 1'h0;	// file.cleaned.mlir:3:14, :6:5
  assign full = 1'h0;	// file.cleaned.mlir:3:14, :6:5
  assign q = 1649'h0;	// file.cleaned.mlir:4:17, :6:5
  assign usedw = 8'h0;	// file.cleaned.mlir:5:14, :6:5
endmodule

