// Generated by CIRCT unknown git version
module hazard_unit(	// file.cleaned.mlir:2:3
  input        clk,	// file.cleaned.mlir:2:29
  input  [4:0] IF_ID_RS1,	// file.cleaned.mlir:2:43
               IF_ID_RS2,	// file.cleaned.mlir:2:63
               ID_EX_RD,	// file.cleaned.mlir:2:83
  input        ID_EX_MemRead,	// file.cleaned.mlir:2:102
  output       PCWrite,	// file.cleaned.mlir:2:127
               IF_ID_Write,	// file.cleaned.mlir:2:145
               MuxSignal	// file.cleaned.mlir:2:167
);

  wire _GEN = ID_EX_MemRead & (ID_EX_RD == IF_ID_RS1 | ID_EX_RD == IF_ID_RS2);	// file.cleaned.mlir:4:10, :5:10, :6:10, :7:10
  assign PCWrite = ~_GEN;	// file.cleaned.mlir:7:10, :8:10, :9:5
  assign IF_ID_Write = ~_GEN;	// file.cleaned.mlir:7:10, :8:10, :9:5
  assign MuxSignal = ~_GEN;	// file.cleaned.mlir:7:10, :8:10, :9:5
endmodule

