// Generated by CIRCT unknown git version
module pll(	// file.cleaned.mlir:2:3
  input  clock_in,	// file.cleaned.mlir:2:21
  output clock_out,	// file.cleaned.mlir:2:41
         locked	// file.cleaned.mlir:2:61
);

  assign clock_out = clock_in;	// file.cleaned.mlir:4:5
  assign locked = 1'h1;	// file.cleaned.mlir:3:13, :4:5
endmodule

