// Generated by CIRCT unknown git version
module mux2(	// file.cleaned.mlir:2:3
  input  [7:0] d0,	// file.cleaned.mlir:2:22
               d1,	// file.cleaned.mlir:2:35
  input        s,	// file.cleaned.mlir:2:48
  output [7:0] y	// file.cleaned.mlir:2:61
);

  assign y = s ? d1 : d0;	// file.cleaned.mlir:3:10, :4:5
endmodule

