// Generated by CIRCT unknown git version
module ghrd_10as066n2_hps_m(	// file.cleaned.mlir:2:3
  input         clk_clk,	// file.cleaned.mlir:2:38
                clk_reset_reset,	// file.cleaned.mlir:2:56
  input  [31:0] master_readdata,	// file.cleaned.mlir:2:82
  input         master_waitrequest,	// file.cleaned.mlir:2:109
                master_readdatavalid,	// file.cleaned.mlir:2:138
  output [31:0] master_address,	// file.cleaned.mlir:2:170
  output        master_read,	// file.cleaned.mlir:2:196
                master_write,	// file.cleaned.mlir:2:218
  output [31:0] master_writedata,	// file.cleaned.mlir:2:241
  output [3:0]  master_byteenable,	// file.cleaned.mlir:2:269
  output        master_reset_reset	// file.cleaned.mlir:2:297
);

  assign master_address = 32'h0;	// file.cleaned.mlir:3:15, :6:5
  assign master_read = 1'h0;	// file.cleaned.mlir:4:14, :6:5
  assign master_write = 1'h0;	// file.cleaned.mlir:4:14, :6:5
  assign master_writedata = 32'h0;	// file.cleaned.mlir:3:15, :6:5
  assign master_byteenable = 4'h0;	// file.cleaned.mlir:5:14, :6:5
  assign master_reset_reset = 1'h0;	// file.cleaned.mlir:4:14, :6:5
endmodule

