// Generated by CIRCT unknown git version
module tt_um_matt_divider_test(	// file.cleaned.mlir:2:3
  input        VGND,	// file.cleaned.mlir:2:41
               VPWR,	// file.cleaned.mlir:2:56
               clk,	// file.cleaned.mlir:2:71
               ena,	// file.cleaned.mlir:2:85
               rst_n,	// file.cleaned.mlir:2:99
  input  [7:0] ui_in,	// file.cleaned.mlir:2:115
               uio_in,	// file.cleaned.mlir:2:131
  inout  [7:0] ua,	// file.cleaned.mlir:2:151
  output [7:0] uio_oe,	// file.cleaned.mlir:2:165
               uio_out,	// file.cleaned.mlir:2:182
               uo_out	// file.cleaned.mlir:2:200
);

  assign uio_oe = 8'h0;	// file.cleaned.mlir:3:14, :4:5
  assign uio_out = 8'h0;	// file.cleaned.mlir:3:14, :4:5
  assign uo_out = 8'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

