// Generated by CIRCT unknown git version
module tt_prim_tbuf(	// file.cleaned.mlir:2:3
  input  a,	// file.cleaned.mlir:2:30
         tx,	// file.cleaned.mlir:2:42
  output z	// file.cleaned.mlir:2:56
);

  assign z = tx & a;	// file.cleaned.mlir:3:10, :4:5
endmodule

