// Generated by CIRCT unknown git version
module top_module(	// file.cleaned.mlir:2:3
  input  [5:0] y,	// file.cleaned.mlir:2:28
  input        w,	// file.cleaned.mlir:2:40
  output       Y2,	// file.cleaned.mlir:2:53
               Y4	// file.cleaned.mlir:2:66
);

  assign Y2 = y[0] & ~w;	// file.cleaned.mlir:4:10, :5:10, :6:10, :16:5
  assign Y4 = y[1] & w | y[2] & w | y[4] & w | y[5] & w;	// file.cleaned.mlir:7:10, :8:10, :9:10, :10:10, :11:10, :12:10, :13:10, :14:11, :15:11, :16:5
endmodule

