// Generated by CIRCT unknown git version
module top_module(	// file.cleaned.mlir:2:3
  input        sel,	// file.cleaned.mlir:2:28
  input  [7:0] a,	// file.cleaned.mlir:2:42
               b,	// file.cleaned.mlir:2:54
  output [7:0] out	// file.cleaned.mlir:2:67
);

  assign out = sel ? a : b;	// file.cleaned.mlir:3:10, :4:5
endmodule

