// Generated by CIRCT unknown git version
module MUX2_4B(	// file.cleaned.mlir:2:3
  input  [3:0] A,	// file.cleaned.mlir:2:25
               B,	// file.cleaned.mlir:2:37
  input        S,	// file.cleaned.mlir:2:49
  output [3:0] Y	// file.cleaned.mlir:2:62
);

  assign Y = S ? B : A;	// file.cleaned.mlir:3:10, :4:5
endmodule

