// Generated by CIRCT unknown git version
module ImmExtend(	// file.cleaned.mlir:2:3
  input  [15:0] imm,	// file.cleaned.mlir:2:27
  input         ImmExt,	// file.cleaned.mlir:2:42
  output [31:0] imm_ext	// file.cleaned.mlir:2:60
);

  assign imm_ext = {ImmExt ? {16{imm[15]}} : 16'h0, imm};	// file.cleaned.mlir:3:15, :4:10, :5:10, :6:10, :7:10, :8:5
endmodule

