// Generated by CIRCT unknown git version
module clk_mmcm(	// file.cleaned.mlir:2:3
  input  reset,	// file.cleaned.mlir:2:26
         clk_in1,	// file.cleaned.mlir:2:42
  output clk_200,	// file.cleaned.mlir:2:61
         locked	// file.cleaned.mlir:2:79
);

  assign clk_200 = 1'h0;	// file.cleaned.mlir:3:14, :4:5
  assign locked = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

