// Generated by CIRCT unknown git version
module GTPE2_CHANNEL(	// file.cleaned.mlir:2:3
  input  GTPRXN,	// file.cleaned.mlir:2:31
         GTPRXP,	// file.cleaned.mlir:2:48
  output GTPTXN,	// file.cleaned.mlir:2:66
         GTPTXP	// file.cleaned.mlir:2:83
);

  assign GTPTXN = 1'h0;	// file.cleaned.mlir:3:14, :4:5
  assign GTPTXP = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

