// Generated by CIRCT unknown git version
module decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix(	// file.cleaned.mlir:2:3
  input  [3:0] instruction,	// file.cleaned.mlir:2:59
  input        clk,	// file.cleaned.mlir:2:81
               shifter_flag,	// file.cleaned.mlir:2:95
  output       loadA,	// file.cleaned.mlir:2:119
               loadB,	// file.cleaned.mlir:2:135
               loadO,	// file.cleaned.mlir:2:151
               MUX_0,	// file.cleaned.mlir:2:167
               MUX_1,	// file.cleaned.mlir:2:183
               shift_direction,	// file.cleaned.mlir:2:199
               shifter_en,	// file.cleaned.mlir:2:225
               load_shifter,	// file.cleaned.mlir:2:246
  output [3:0] ALU_Sel,	// file.cleaned.mlir:2:269
  output       ALU_update,	// file.cleaned.mlir:2:287
               update_PC,	// file.cleaned.mlir:2:308
               acc_reset	// file.cleaned.mlir:2:328
);

  assign loadA = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign loadB = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign loadO = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign MUX_0 = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign MUX_1 = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign shift_direction = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign shifter_en = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign load_shifter = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign ALU_Sel = 4'h0;	// file.cleaned.mlir:4:14, :5:5
  assign ALU_update = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign update_PC = 1'h0;	// file.cleaned.mlir:3:14, :5:5
  assign acc_reset = 1'h0;	// file.cleaned.mlir:3:14, :5:5
endmodule

