// Generated by CIRCT unknown git version
module Mat_AddrCal(	// file.cleaned.mlir:2:3
  input  [14:0] refAddr,	// file.cleaned.mlir:2:29
  input  [2:0]  adjNumber,	// file.cleaned.mlir:2:48
  output [14:0] FBAddr	// file.cleaned.mlir:2:69
);

  wire [31:0]      _GEN = {17'h0, refAddr};	// file.cleaned.mlir:10:15, :12:10
  wire [7:0][31:0] _GEN_0 =
    {{_GEN - 32'hB5},
     {_GEN - 32'h1},
     {_GEN + 32'hB3},
     {_GEN + 32'hB4},
     {_GEN + 32'hB5},
     {_GEN + 32'h1},
     {_GEN - 32'hB3},
     {_GEN - 32'hB4}};	// file.cleaned.mlir:5:17, :6:17, :9:17, :11:15, :12:10, :13:10, :14:10, :15:10, :16:10, :17:10, :18:10, :19:10, :20:10, :21:10
  assign FBAddr = _GEN_0[adjNumber][14:0];	// file.cleaned.mlir:21:10, :22:11, :23:11, :24:5
endmodule

