// Generated by CIRCT unknown git version
module DataSplit4(	// file.cleaned.mlir:2:3
  input  [3:0] i,	// file.cleaned.mlir:2:28
  output       o0,	// file.cleaned.mlir:2:41
               o1,	// file.cleaned.mlir:2:54
               o2,	// file.cleaned.mlir:2:67
               o3	// file.cleaned.mlir:2:80
);

  assign o0 = i[0];	// file.cleaned.mlir:3:10, :7:5
  assign o1 = i[1];	// file.cleaned.mlir:4:10, :7:5
  assign o2 = i[2];	// file.cleaned.mlir:5:10, :7:5
  assign o3 = i[3];	// file.cleaned.mlir:6:10, :7:5
endmodule

