// Generated by CIRCT unknown git version
module axi_stream_resizing(	// file.cleaned.mlir:2:3
  input        rstn,	// file.cleaned.mlir:2:37
               clk,	// file.cleaned.mlir:2:52
               i_tvalid,	// file.cleaned.mlir:2:66
  input  [7:0] i_tdata,	// file.cleaned.mlir:2:85
  input        i_tkeep,	// file.cleaned.mlir:2:103
               i_tlast,	// file.cleaned.mlir:2:121
               o_tready,	// file.cleaned.mlir:2:139
  output       i_tready,	// file.cleaned.mlir:2:159
               o_tvalid,	// file.cleaned.mlir:2:178
  output [7:0] o_tdata,	// file.cleaned.mlir:2:197
  output       o_tkeep,	// file.cleaned.mlir:2:215
               o_tlast	// file.cleaned.mlir:2:233
);

  assign i_tready = o_tready;	// file.cleaned.mlir:3:5
  assign o_tvalid = i_tvalid;	// file.cleaned.mlir:3:5
  assign o_tdata = i_tdata;	// file.cleaned.mlir:3:5
  assign o_tkeep = i_tkeep;	// file.cleaned.mlir:3:5
  assign o_tlast = i_tlast;	// file.cleaned.mlir:3:5
endmodule

