// Generated by CIRCT unknown git version
module Zero_Mux(	// file.cleaned.mlir:2:3
  input  [3:0]  NIBBLE,	// file.cleaned.mlir:2:26
  input  [31:0] IN,	// file.cleaned.mlir:2:43
  output [31:0] OUT	// file.cleaned.mlir:2:58
);

  assign OUT = NIBBLE == 4'h0 ? 32'h0 : IN;	// file.cleaned.mlir:3:15, :4:14, :5:10, :6:10, :7:5
endmodule

