// Generated by CIRCT unknown git version
module Sign_Extend(	// file.cleaned.mlir:2:3
  input  [31:0] In,	// file.cleaned.mlir:2:29
  input  [1:0]  ImmSrc,	// file.cleaned.mlir:2:43
  output [31:0] Imm_Ext	// file.cleaned.mlir:2:61
);

  assign Imm_Ext = {{20{In[31]}}, ImmSrc == 2'h0 ? In[31:20] : {In[31:25], In[11:7]}};	// file.cleaned.mlir:3:14, :4:10, :5:10, :6:10, :7:10, :8:10, :9:10, :10:10, :11:10, :12:10, :13:5
endmodule

