// Generated by CIRCT unknown git version
module top_module(	// file.cleaned.mlir:2:3
  input  [7:0] in,	// file.cleaned.mlir:2:28
  output       parity	// file.cleaned.mlir:2:42
);

  assign parity = ^in;	// file.cleaned.mlir:3:10, :4:5
endmodule

