// Generated by CIRCT unknown git version
module top_module(	// file.cleaned.mlir:2:3
  input  [7:0]  in,	// file.cleaned.mlir:2:28
  output [31:0] out	// file.cleaned.mlir:2:42
);

  assign out = {{24{in[7]}}, in};	// file.cleaned.mlir:3:10, :4:10, :5:10, :6:5
endmodule

