// Generated by CIRCT unknown git version
module passthrough(	// file.cleaned.mlir:2:3
  input         clk,	// file.cleaned.mlir:2:29
                rst,	// file.cleaned.mlir:2:43
                op_din_en,	// file.cleaned.mlir:2:57
                op_din_eop,	// file.cleaned.mlir:2:77
  input  [15:0] op_din,	// file.cleaned.mlir:2:98
  output [15:0] op_dout	// file.cleaned.mlir:2:117
);

  assign op_dout = op_din;	// file.cleaned.mlir:3:5
endmodule

