// Generated by CIRCT unknown git version
module SUB(	// file.cleaned.mlir:2:3
  input  [5:0] Funct,	// file.cleaned.mlir:2:21
               Op,	// file.cleaned.mlir:2:37
  output       Y	// file.cleaned.mlir:2:51
);

  wire NOTF3;	// file.cleaned.mlir:26:11
  wire NOTF4;	// file.cleaned.mlir:24:11
  wire NOTOp28;	// file.cleaned.mlir:22:11
  wire NOTOp31;	// file.cleaned.mlir:20:11
  wire NOTOp26;	// file.cleaned.mlir:18:11
  wire NOTOp27;	// file.cleaned.mlir:16:11
  wire NOTOp29;	// file.cleaned.mlir:14:11
  wire NOTOp30;	// file.cleaned.mlir:12:10
  wire NOTF2;	// file.cleaned.mlir:10:10
  wire _Funct_1;	// file.cleaned.mlir:8:10
  wire _Funct_5;	// file.cleaned.mlir:7:10
  wire NOTF0;	// file.cleaned.mlir:6:10
  assign NOTF0 = ~(Funct[0]);	// file.cleaned.mlir:5:10, :6:10
  assign _Funct_5 = Funct[5];	// file.cleaned.mlir:7:10
  assign _Funct_1 = Funct[1];	// file.cleaned.mlir:8:10
  assign NOTF2 = ~(Funct[2]);	// file.cleaned.mlir:9:10, :10:10
  assign NOTOp30 = ~(Op[4]);	// file.cleaned.mlir:11:10, :12:10
  assign NOTOp29 = ~(Op[3]);	// file.cleaned.mlir:13:10, :14:11
  assign NOTOp27 = ~(Op[1]);	// file.cleaned.mlir:15:11, :16:11
  assign NOTOp26 = ~(Op[0]);	// file.cleaned.mlir:17:11, :18:11
  assign NOTOp31 = ~(Op[5]);	// file.cleaned.mlir:19:11, :20:11
  assign NOTOp28 = ~(Op[2]);	// file.cleaned.mlir:21:11, :22:11
  assign NOTF4 = ~(Funct[4]);	// file.cleaned.mlir:23:11, :24:11
  assign NOTF3 = ~(Funct[3]);	// file.cleaned.mlir:25:11, :26:11
  assign Y =
    NOTOp29 & NOTOp31 & NOTOp30 & NOTOp28 & NOTOp27 & NOTOp26 & NOTF3 & _Funct_5 & NOTF4
    & NOTF2 & _Funct_1 & NOTF0;	// file.cleaned.mlir:4:10, :6:10, :7:10, :8:10, :10:10, :12:10, :14:11, :16:11, :18:11, :20:11, :22:11, :24:11, :26:11, :27:5
endmodule

