// Generated by CIRCT unknown git version
module controller_ram_duel_port(	// file.cleaned.mlir:2:3
  input  [13:0] address_a,	// file.cleaned.mlir:2:42
                address_b,	// file.cleaned.mlir:2:63
  input  [3:0]  byteena_a,	// file.cleaned.mlir:2:84
  input         clock_a,	// file.cleaned.mlir:2:104
                clock_b,	// file.cleaned.mlir:2:122
  input  [31:0] data_a,	// file.cleaned.mlir:2:140
                data_b,	// file.cleaned.mlir:2:158
  input         rden_a,	// file.cleaned.mlir:2:176
                rden_b,	// file.cleaned.mlir:2:193
                wren_a,	// file.cleaned.mlir:2:210
                wren_b,	// file.cleaned.mlir:2:227
  output [31:0] q_a,	// file.cleaned.mlir:2:245
                q_b	// file.cleaned.mlir:2:260
);

  assign q_a = 32'h0;	// file.cleaned.mlir:3:15, :4:5
  assign q_b = 32'h0;	// file.cleaned.mlir:3:15, :4:5
endmodule

