// Generated by CIRCT unknown git version
module clkctrl(	// file.cleaned.mlir:2:3
  input  inclk,	// file.cleaned.mlir:2:25
         ena,	// file.cleaned.mlir:2:41
  output outclk	// file.cleaned.mlir:2:56
);

  assign outclk = 1'h0;	// file.cleaned.mlir:3:14, :4:5
endmodule

