// Generated by CIRCT unknown git version
module NV_NVDLA_HLS_shiftrightsatsu(	// file.cleaned.mlir:2:3
  input  [48:0] data_in,	// file.cleaned.mlir:2:46
  input  [5:0]  shift_num,	// file.cleaned.mlir:2:65
  output [31:0] data_out,	// file.cleaned.mlir:2:86
  output        sat_out	// file.cleaned.mlir:2:106
);

  wire [146:0] _GEN = {{49{data_in[48]}}, data_in, 49'h0} >> shift_num;	// file.cleaned.mlir:8:15, :16:10, :17:10, :18:10, :20:10
  wire         point5 = _GEN[48] & (~(data_in[48]) | (|(_GEN[47:0])));	// file.cleaned.mlir:16:10, :20:10, :21:10, :22:10, :23:10, :24:10, :25:10, :26:11
  wire         _GEN_0 =
    data_in[48] & _GEN[96:80] != 17'h1FFFF | ~(data_in[48]) & (|(_GEN[96:80]))
    | ~(data_in[48]) & (&{_GEN[79:49], point5});	// file.cleaned.mlir:12:16, :16:10, :20:10, :23:10, :26:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11
  wire         _GEN_1 = {26'h0, shift_num} > 32'h30;	// file.cleaned.mlir:4:16, :9:15, :41:11, :42:11
  assign data_out =
    _GEN_1
      ? 32'h0
      : _GEN_0
          ? (data_in[48] ? 32'h80000000 : 32'h7FFFFFFF)
          : _GEN[80:49] + {31'h0, point5};	// file.cleaned.mlir:3:15, :5:24, :6:25, :7:15, :16:10, :20:10, :26:11, :27:11, :28:11, :29:11, :39:11, :40:11, :42:11, :43:11, :44:11, :47:5
  assign sat_out = ~_GEN_1 & _GEN_0;	// file.cleaned.mlir:39:11, :42:11, :45:11, :46:11, :47:5
endmodule

